 Alig hogy az evangélium szent szavai elhangzottak és a miséző az isteni szavakat megmagyarázta, felhangzik az ünnepélyes misében a pap éneke: Credo in unum Deum (Hiszek egy Istenben), a nép vagy a kórus pedig folytatja:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Patrem   omnipotentem, factorem coeli et terrae, visibilium omnium et invisibilium. Et   in unum Dominum Jesum Christum, Filium Dei unigenitum. <br><br>
Et   ex Patre natum ante omnia saecula. <br><br>
Deum   de Deo, lumen de lumine,<br><br>
Deum   verum de Deo vero. Genitum, non factum, consubstantialem Patri: per quem   omnia facta sunt.<br><br>
Qui   propter nos homines et propter nostram salutem descendit de coelis. Et   incarnatus est de<br><br>
Spiritu   Sancto ex Maria Virgine:<br><br>
Et   homo factus est. Crucifixus etiam pro nobis: sub Pontio Pilato passus, et   sepultus est. Et resurrexit tertia die secundum Scripturas. Et ascendit in   coelum: sedet ad dexteram Patris.<br><br>
Et   iterum venturus est cum gloria, judicare vivos et mortuos: cujus regni non   erit finis. Et in Spiritum Sanctum, Dominum et vivificantem: qui ex Patre   Filioque procedit. Qui cum Patre et Filio simul adoratur et conglorificatur:   qui locutus est per Prophetas. Et unam sanctam catholicam et apostolicam   Ecclesiam. <br><br>
Confiteor   unum baptisma in remissionem peccatorum. <br><br>
Et   exspecto resurrectionem mortuorum. Et vitam venturi saeculi. Amen.</div>
    <div class="col-lg-4">
Mindenható   Atyában, mennynek és földnek, minden láthatónak és láthatatlannak   teremtőjében. És az egy Úr Jézus Krisztusban, Isten egyszülött Fiában. <br><br>
Ki   az Atyától öröktől fogva született. <br><br>
Isten   az Istentől, világosság a világosságtól, igaz Isten az igaz Istentől. Ki   született, nem alkottatott, egylényegű az Atyával: ki mindeneket alkotott. <br><br>
Ki   értünk, emberekért és a mi üdvösségünkért leszállt a mennyből. És testet   öltött a Szentlélek által Szűz Máriától: <br><br>
és   emberré lett. Pontius Pilátus alatt érettünk szenvedett, keresztre   feszítették és eltemették. És harmadnapra feltámadott az Írások szerint. És   felment az égbe: ott ül az Atyának jobbján. És ismét eljön dicsőséggel, hogy   megítélje az élőket és a holtakat: s országának nem lesz vége. Hiszek a   Szentlélekben, Úrban és életet adóban: ki az Atyától s a Fiútól származik.   Kit az Atyával és a Fiúval együtt imádunk és dicsőítünk: ki a Próféták által   szólt. <br><br>
Hiszek   egy, szent, egyetemes és apostoli Anyaszentegyházat. Vallok egy keresztséget   a bűnök bocsánatára. <br><br>
És   várom a holtak feltámadását. És az eljövendő örökéletet. Amen.</div>
</div>
E szavakkal a pap és a hívek nyilvános, ünnepélyes vallomást tesznek az igaz hitről, vagyis azokról a hittételekről, amelyek a Credo-ban foglaltatnak.<br><br>
A Credo elég későn került bele a miseliturgiába. Eredetileg ugyanis a hitvallások arra szolgáltak, hogy a megkeresztelendők a keresztség szertartásának keretében az igaz hit főbb igazságait megvallják. Így az első keresztény századokban a hitvallás semmiféle vonatkozásban sem volt az Eucharisztiával, vagy a miseliturgiával. Meg kell itt még azt is említenünk, hogy a hitvallásokban nem voltak meg az összes keresztény igazságok, még csak a főbbek sem, hanem a keresztények főleg azokat a hittételeket vették fel a Credo-ba, amelyeket a korukbeli eretnekek kétségbevontak, támadtak. Ami egészen természetes is. Mert hiszen ha az Egyház a keresztelésnél, vagyis egy jelentkezőnek az Egyházba való felvételénél, meg akart bizonyosodni arról, hogy az illető a hit dolgában az igaz keresztényekkel tart-e, úgy főleg azokra az igazságokra vonatkozóan kellett hitvallást követelnie, amelyek körül azokban az időkben harc folyt. Így érthető, hogy pl. az Eucharisztiáról szóló hittételek nincsenek benne a Credo-ban, amennyiben az ősegyházban kifejezetten senki sem vonta kétségbe, hogy Jézus jelen van az eucharisztikus kenyér és bor színe alatt. A régi egyházban többféle, különböző terjedelmű és szövegezésű hitvallás forgott közkézen. Nevezetesebbek a régiek közül az ún. apostoli, a niceai, a konstantinápolyi és a szent Athanáz-féle hitvallás. Az apostoli hitvallást a katekizmusban tanuljuk és a Miatyánk s az Üdvözlégy mellett imádkozni szoktuk. A Szent Athanáz-féle hitvallás („Quicunque”) a papi zsolozsmában, a vasárnapi Primában fordul elő. A szentmisében a niceai-konstantinápolyi hitvallást használjuk. Ezt a hitvallást ti. a niceai egyetemes zsinat (325.) készítette s a konstantinápolyi zsinat (381) kiegészítette.<br><br>
Mikor és hogyan került bele ez a hitvallás a szentmise liturgiájába?<br><br>
A hitvallást először keleten a monofizita eretnekek vették fel a szentmise szertartásai közé. Ezek az eretnekek ugyanis azáltal akartak feltűnő módon tiltakozni a chalcedoni zsinat (451) ellenük kimondott határozatai ellen, hogy a niceai hitvallást, melyet ők is elfogadtak, a szentmise alatt ünnepélyesen elmondták (Duchesne. 87.). A Credo a szentmisében Antiochiában először 471-ben, Konstantinápolyban 511-ben jelenik meg. Ennek ellensúlyozására viszont az igazhitű keresztények a niceai-konstantinápolyi hitvallást szúrták be a szentmisébe. E szokást keletről először Spanyolország vette át, hol a III. toledói zsinaton (589) elrendelték, hogy az összes spanyol egyházakban „a nép hangosan énekelje” a konstantinápolyi hitvallást a Pater noster előtt. A spanyol (mozarab) liturgiában tényleg még ma is az Úrfelmutatás után a Pater noster előtt mondják a Credo-t. A spanyoloktól a németek és a franciák is átvették ezt a szokást a VIII. és a IX. században, amint azt Strabo Walafried (+845) bizonyítja. III. Leó pápa Nagy Károly császár kérésére megerősíti ezt a szertartást (810), bár még ezidőben Rómában a Credo nem tartozott a miseliturgiához (Thalhofer. II. 101.). Rómában 1014-ben vették fel a Credo-t a szentmisébe. Berno, reichenau-i apát ugyanis mint szemtanú beszéli (De quibusd. reb. 2. M. P. L. 142. 1060 sk.), hogy II. Henrik császár (1002-1024.) koronázása alkalmával (1014. febr. 14.) Rómában volt s tanúja volt, amint a császár kifogásolta, hogy a koronázási misében nincs Credo, holott ez Németországban szokás. A rómaiak erre azt felelték, hogy a római egyházat semmiféle eretnekség sem mocskolta be, ennélfogva nincs szükség a Credo imádkozására. Mindazonáltal VIII. Benedek pápa (1012- 1024) teljesítette a császár kérését s elrendelte, hogy azontúl az evangélium után Rómában is énekeljék a hitvallást. Ezt az elbeszélést manapság a tudósok kevés kivétellel általában hiteltérdemlőnek tartják (Thalhofer, Fortescue, Vandeur, Duchesne). Ez a szokás azután a XI. századtól kezdve állandó lett, bár eleinte a Credo-t csak vasárnapokon és főbb ünnepeken énekelték, ami annak a jele, hogy még nem tartották a szentmise fontos részének. A gyertyákat, amelyeket az evangélium- olvasásra meggyújtottak, a Credo éneklése előtt kioltották. A szertartás egyébként a középkorban olyan volt, mint manapság. A pap intonálta: „Credo in unum Deum”, azután a nép (nem a kórus) énekelte a további szöveget, amelyet mindenki kívülről tudott. Megemlítésre érdemes, hogy Milánóban az ambrózián rítus szerint a Credo-t a felajánlás után, míg a keleti liturgiában általánosságban a felajánláskor szokásos békecsók átadása alatt éneklik. A mozarab s a keleti liturgiákban mindennap van Credo, míg a római liturgiában csak vasárnapokon, az Úr, a Bold. Szűz, az angyalok, az apostolok, az evangelisták, az egyházdoktorok ünnepein s más főbb ünnepeken (l. bővebben Mihályfi. Nyilv. istentiszt. 472.).<br><br>
A hitvallás eléneklésével befejezést nyer a katechumenek miséje, vagyis az előkészület a szentáldozatra. A felajánlással kezdődik a hívek miséje. A régi Egyházban a szentmise e két része jobban el volt választva egymástól főleg azáltal, hogy a hívők miséjének megkezdése előtt a katechumeneknek el kellett távozniok. A bizánci liturgiában még ma is van minden praktikus jelentőség nélkül egy ima, mely a katechumenek régente szokásban volt búcsúztatásának a maradványa. A mi liturgiánkban ez a szokás nyomtalanul eltűnt, ma már a hívek egyáltalában nem veszik észre az átmenetet a katechumenek miséjéről a hívők miséjére, a kettő annyira egybeforrott.<br><br>