 Az ún. katechumenek miséje alatt az Egyház a hívek lelkét az imádságok, a zsoltáréneklés, a szent olvasmányok és a szentbeszéd által kellőképpen előkészítette a szentáldozat méltó megünneplésére. Az evangéliumi örök igazságok ereje, az énekek szép melódiája, a miséző szívhez szóló szavai megpuhították a jelenlevők szívét s forró vágyat keltettek a lelkekben az Úr után, aki a „hívek misé”-jében maga az áldozó és az áldozat.<br><br>
Az ún. hívek miséje három részre oszlik. Az első az áldozati anyag előkészítése, vagyis a felajánlás, a második az áldozat létrehozása, vagyis az átlényegülés és a harmadik a részesedés az áldozatban, azaz a szentáldozás.<br><br>
A pap a Credo után Dominus vobiscum-ot, majd Oremus-t („Könyörögjünk”) mond. Ezt a felszólítást azonban tényleg nem követi könyörgés. Itt tehát valami hiányzik a miseszertartásból. A tudósok jórésze (pl. Duchesne, Vandeur) azt tartják, hogy itt imádkozták a hívekért azt a „közös imát”, amelyről fentebb (87. o.) szólottunk.<br><br>
Az Oremus után a pap az oltár felé fordulva összetett kezekkel elmond egy rövid szöveget, amelyet Offertoriumnak szoktunk nevezni. Húsvét vasárnapján pl. ezt olvassa:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Terra   tremuit, et quievit, dum resurgeret in judicio Deus, Alleluja.</div>
    <div class="col-lg-4">
A   föld megrémült s elcsendesedett, midőn felkelt ítélkezni az Isten, Alleluja.</div>
</div>
Ez a rövid zsoltárszöveg manapság már egyáltalában nem sejteti azokat a változatos és évszázadokon keresztül oly nagy bensőséggel végzett szertartásokat, melyeket a régi misében e helyen találunk. Ezek a szertartások önmagukban véve oly lélekemelők s azonfelül oly plasztikusan kifejezik az áldozatról vallott katolikus igazságokat, hogy kissé részletesebben kell róluk szólanunk.<br><br>
Régente ugyanis itt egy zsoltárt énekeltek s a mai offertórium tulajdonképpen nem más, mint annak a zsoltárnak az antifónája. A zsoltáréneklés annak az időnek a kitöltésére szolgált, amelyben a hívek a szentmisére hozott ajándékaikat átadták. Karthágóban Szent Ágoston idejében vezették be ezt a szokást, mely egyébként Rómában is megvolt. Nagy Szent Gergely idejében pl. egy antifónát s néhány zsoltár-verssort énekeltek. Ezeknek az énekszövegeknek a melódiája sokkal változatosabb és gazdagabb volt, mint pl. az introitus-é és a graduale-é, hogy ezáltal is kifejezésre jusson az áldozat bemutatásának s ezáltal Krisztus eljövetelének a közelsége. Még a XII. században bizonyítékunk van arra, hogy Rómában felajánláskor zsoltárokat énekeltek. Később, ahogy a hívek részéről az önkéntes adományok felajánlása mindig ritkább lett, ez a zsoltáréneklés is megszűnt. A XIII. században legtöbb helyütt már csak az antifónát énekelték. Ma már csak a gyászmise offertóriumában találunk az antifóna mellett néhány zsoltár-verssort is.<br><br>
Az áldozatos szellemnek igazán nagyszerű megnyilatkozása volt az őskeresztény egyházban az, hogy a hívek maguk adták össze a szentmise bemutatásához és a jelenlevők megáldoztatásához szükséges kenyeret és bort. Ezt a szolgáltatást nem csak kedves kötelességnek, hanem egyúttal kitüntetésnek s jognak is tekintették, amelyből a méltatlanokat kizárták. E felajánlásokról a régi római írások is gyakran megemlékeznek. A hívek ajándékainak átvétele a pápai misében járt különösen ünnepélyes szertartásokkal (Ord. Rom. I. 13, 14.). A pápa teljes kíséretével a templom hajójába vonult s az előkelő rómaiaktól sajátkezűleg vette át a felajánlott áldozati tárgyakat. A felajánlott bor összegyűjtésére nagy kelyhet használtak (scyphus). Ebből öntöttek azután egy kisebb kehelybe, mely a szentmise bemutatására szolgált (calix sanctus) és egy nagyobb kehelybe (calix ministerialis), amelyből a jelenlevőket megáldoztatták. Ami a nem konzekrált kenyérből és borból megmaradt, azt a szegényeknek osztották ki. Egyes helyeken ebből a megszentelt, de nem konzekrált kenyérből kisebb darabokat a távollevő keresztényeknek küldöttek el. Ez a megáldott kenyér (eulogia) volt a keresztény közösségnek a kifejezője. Franciaországban, Olaszországban és keleten még ma is szokás, hogy felajánláskor kis kenyérdarabokat osztanak ki a hívek között, akik azt áldozáskor magukhoz veszik, így mintegy ezzel pótolják a valóságos szentáldozást s kifejezik az áldozatot bemutató pappal való közösségüket. A keresztények évszázadokon keresztül a legnagyobb örömmel ajánlották fel adományaikat a szentmise céljaira. Mikor Nagy Szent Gergely pápa egy alkalommal misét mondott s egy asszonyt megáldoztatott, ez áldozás közben elmosolyodott, mert megismerte, hogy ugyanazzal a kenyérrel áldoztatták meg, amelyet felajánlott (Vita S. Greg. P. L. 75. 52.).<br><br>
A régi Egyházban valóságban kenyeret s bort ajánlottak fel a hívek, a XII. századtól kezdve azonban már legtöbbnyire csak pénzfelajánlásról olvasunk. A későbbi századokban a pénzfelajánlások is mindig ritkábbak és ritkábbak lettek. A XV. és XVI. század zsinatain gyakran felhangzott a panasz, hogy a régi Egyház szép felajánlási szokása mindjobban feledésbe megy. A zsinatok (így pl. a konstanci 1567-ben) intették is a híveket, hogy legalább a 4 főünnepen járuljanak hozzá a szentáldozat bemutatásához. Luther tagadta a szentmise áldozati jellegét s azért erősen küzdött a felajánlások ellen s így szembehelyezkedett az ősegyház tanításával és gyakorlatával. A régi szokásnak bizonyos maradványa Milanóban az a szertartás, amely szerint még manapság is 10- 10 aggastyán és éltes matróna régi nemzeti viseletben kenyeret (ostyát) és bort hoz az oltárhoz s azokat az asszonyok a szentély korlátjánál, a férfiak pedig a szentélyben átadják a miséző papnak. Ugyancsak a régi szokásra vezethető vissza az a szertartás is, mely szerint a papszentelésnél a felszenteltek felajánláskor egy égő gyertyát adnak át a szentelő püspöknek. A püspökszentelésnél az újonnan felszentelt püspök két nagy égő gyertyát, két kenyeret és két hordócska bort ajánl fel a konzekráló püspöknek. Külföldön (pl. Tirolban) még ma is szokás az, hogy a hívek -- különösen gyászmisék alkalmával -- felajánláskor körüljárják az oltárt („Opfergehen”) s az oltár mellett elhelyezett perselybe dobják adományaikat. A nálunk szokásos perselyezés is ezeknek a régi ajándékozásoknak a maradványa. A szentmisét hallgató híveknek tehát tudniok kell, hogy amikor a szentmise alatt körülhordozott perselybe pénzt tesznek, akkor tulajdonképpen a szentáldozat bemutatásához járulnak hozzá és nagyobb mértékben részesednek annak kegyelmeiből.<br><br>
Már az első keresztény évezredben megvolt, de csak a XII. századtól bizonyítható az a szokás, hogy egyesek, akik különösebb mértékben akartak részesülni a szentmise gyümölcseiben, a misézőnek nagyobb pénzösszeget adtak. Ezek az összegek tehát az adományozók szándéka szerint nemcsak a szentáldozat bemutatására, hanem a papság eltartására is szolgáltak. Ezeket az adományokat stipendiumoknak nevezték, mint ahogy általában a papság megélhetésére adott mindenféle adománynak ez volt a neve. E névhasználat a római császári hadseregből eredt, hol e szó azt az összeget jelentette, amelyet a tényleges szolgálatban álló katonák a rendes zsoldon felül megélhetésük biztosítására kaptak (Thalhofer. II. 123.).<br><br>
Meg kell itt említenünk egy elég feltűnő eltérést a római liturgia és a többi keresztény liturgiák között. Az összes keleti liturgiákban ugyanis az áldozati tárgyak előkészítése, megszentelése és felajánlása nem a katechumenek miséje után, hanem az előtt történik. Mikor a pap a leckét, az evangéliumot olvassa, akkor már a felajánlás megtörtént. Ebből következik, hogy a görög misében nincs introitus, mert hiszen a pap a miseliturgia megkezdése előtt már a templomban van s ott elkészítette az áldozati tárgyakat (proszkomidia). Ezért a hívek miséje elején nincs felajánlás, hanem csak processzió, vagyis a mise előtt már felajánlott kenyérnek és bornak az oltárhoz való ünnepélyes elvitele. Bővebben nem térhetünk ki e szertartások ismertetésére. Azt azonban meg kell állapítanunk, hogy a római liturgia e pontban jobban követi az őskeresztény szokást, mely pl. a Szent Jusztin által leírt liturgiában ismeretes. A keleti liturgiák mai sorrendje valószínűleg a IV-V. században keletkezett, amikor Szent Vazul s Aranyszájú Szent János mindent elkövettek a túlságosan hosszúra nyúlt liturgia megrövidítésére. Valószínűleg ennek a törekvésnek volt a következménye az, hogy az áldozati tárgyak előkészítése és felajánlása egészen a mise elejére került s az ezen való részvétel a híveknek nem volt kötelező.<br><br>
A latin egyház kovásztalan, a keleti egyházak pedig az örmény és a maronita keresztényeket kivéve, kovászos kenyeret használnak a szentmiséhez. Ez az eltérő gyakorlat még manapság is sok vitára ad alkalmat. Mi itt természetesen helyszűke miatt, mélyebben e kérdésbe bele nem hatolhatunk. Mindössze csak arra szorítkozhatunk, hogy ennek a lényegében tudományos, történeti kérdésnek mai állásáról tájékoztatást nyújtsunk. A kérdés annak az eldöntésénél kezdődik, hogy Krisztus az utolsó vacsorán az Eucharisztia rendelésénél kovászos, vagy kovásztalan kenyeret használt-e? Ezt a kérdést egész tudományos bizonyossággal maradék nélkül megoldani nem lehet. Mindazonáltal a legnagyobb valószínűség amellett szól, hogy Krisztus kovásztalan kenyeret használt az utolsó vacsorán. Hiszen a három első evangelista kifejezetten mondja, hogy „a kovásztalan kenyerek első napján” történt az Oltáriszentség alapítása. Krisztus tanítványaival megünnepelte a húsvétot, rituális húsvéti vacsorát evett velük. A húsvéti vacsoránál pedig nemcsak, hogy nem volt szabad kovászos kenyeret enni, de ilyen kenyeret még a házban sem volt szabad tartani. Egészen más kérdés azonban, hogy az őskeresztény egyház milyen kenyeret használt a szentmiséhez. Itt viszont meg kell állapítanunk, hogy úgy a keleti, mint a nyugati egyházban, sőt Rómában is inkább a kovászos kenyér mellett szólnak az adatok. A régi írók ugyanis az eucharisztikus kenyérről úgy beszélnek, mint közönséges, vagyis kovászos kenyérről. A 693-iki toledói-zsinat egészen aprólékosan leírja, milyen legyen a szentmiséhez használandó kenyér és semmi említést sem tesz arról, hogy az kovásztalan legyen (XVI. c. 6. Hefele. K. G. III.2 351.). Említettük továbbá, hogy régente a hívek hozták a szent áldozáshoz a kenyeret. Ha ennek kovásztalannak kellett volna lennie, vagyis azt külön kellett volna készíteni, akkor ezt bizonyára feljegyezték volna az akkori írók. Az első, aki a nyugati egyházban a kovásztalan kenyér használatáról ír, Szent Béda (+735)ˇ Ugyanezt bizonyítja a IX. századból Hraban Maurus (+856). A XI. században nyugaton már olyan általános a kovásztalan kenyér használata, hogy a Cerularius Mihállyal folytatott vitában a latinok már egészen elfelejtették a kovászos kenyér használatát és a kovásztalan kenyér használatának védelmezésében az apostoli hagyományra hivatkoztak. A mai gyakorlat szerint a nyugati egyház előírja halálos bűn terhe alatt, hogy a pap kovásztalan kenyeret használjon a szentmisében, bár a kovászos kenyér konzekrációját -- még ha vétkes engedetlenségből latin pap által történik is -- érvényesnek veszi. A szakadár görög egyház ellenben a kovásztalan kenyér konzekrációját egyenesen érvénytelennek tartja.<br><br>
A kenyér, illetve az ostya mai kerek alakja a XII. századból származik. A borra vonatkozólag megjegyezhetjük, hogy régente a hívek a bort kis palackokban (amulae) hozták a templomba, ahol a bor összegyűjtésére szolgáló nagyobb edénybe (scyphus) beleöntötték. Fehér bort csak a XIV. századtól kezdve használnak, a vörös bor ugyanis jobban jelképezte az Úr Jézus vérét.<br><br>
Az Oltáriszentség iránti tisztelet sugallta a középkorban azokat a zsinati határozatokat, amelyek szerint az ostyát a papoknak kellett készíteniök. A XI. században a hirschaui kolostor szabályai szerint (Thalhofer. I. 112.) a nagy gonddal kiválasztott búzaszemeket albába öltözött szerzetesnek kellett megőrölnie, a lisztet gondosan kitisztított szitán megszitálnia. Az ostyasütéshez négy szerzetes kellett, akik közül háromnak papnak, vagy diákonusnak kellett lennie. Az éjjeli nocturnus elvégzése után fogtak munkához, szintén albába s humeraléba öltözve. Ostyasütés közben legszigorúbb szentcsendet kellett tartaniok. Más kolostorokban ostyakészítés közben zsoltárokat énekeltek. Mihályfi említi (Nyilv. istentiszt. 410.), hogy egy észak- amerikai apácakolostornak van e célra külön búzaföldje és szőlője, az apácák szántják a földet, vetik, aratják, cséplik, őrlik a búzát, amelyből a szentostya készül. Az oltár használatára szükséges bort is ők szüretelik és sajtolják.<br><br>
* * *<br><br>
 A felajánlásnak azok az imádságai, amelyeket a mai miseliturgiában találunk, általában nem régi keletűek. Mindazonáltal az áldozati tárgyak megszentelése s felajánlása már a legrégibb időkben szokásban volt. Krisztus urunk is, midőn kezébe vette az utolsó vacsorán a kenyeret, előbb megáldotta (Mt 26,26) s csak azután változtatta át Szent Testévé. Ezt a megszentelést és felajánlást a római egyház egészen a középkorig, az ún. secretá-val végezte el. Ez volt az egyetlen felajánlási imádság, amelyet a pap közvetlenül a praefatio előtt mondott s amely még a kánonhoz tartozott. A ma szokásos felajánlási imádságok csak a középkorban jöttek szokásba s ezeket az imákat akkor „kisebb kánon”-nak (canon minor) nevezték. Minthogy ez tehát a secretá-nak, vagyis a „csöndes imádság”-nak a kibővítése, azért a pap ezt is halkan imádkozza.<br><br>
A pap kezébe veszi az aranyos paténát, feltekint az oltár keresztjére, majd szeme a szentostyán nyugszik meg, mely a szem magasságában tartott paténán fekszik s a mennyei Atyához a következő imádságot mondja:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Suscipe,   sancte Pater, omnipotens aeterne Deus, hanc immaculatam hostiam, quam ego   indignus famulus tuus offero tibi Deo meo vivo et vero, pro innumerabilibus   peccatis, et offensionibus, et negligentiis meis, et pro omnibus   circumstantibus, sed et pro omnibus fidelibus christianis vivis atque   defunctis: ut mihi et illis proficiat ad salutem in vitam aeternam. Amen.<br><br>
</div>
    <div class="col-lg-4">
Fogadd   el, szentséges Atyánk, mindenható örök Isten, ezt a szeplőtelen ostyát,   melyet én, méltatlan szolgád, neked, élő és igaz Istennek fölajánlok,   megszámlálhatatlan bűneimért, megbántásaimért és hanyagságaimért. Fölajánlom   az itt jelenlevőkért, úgyszintén minden keresztény hívőért, élőkért és   holtakért: hogy nekem és nekik üdvösségükre legyen az örök életben. Amen.</div>
</div>
Ez az ima már egy IX. századbeli imakönyvben (Charles-le-Chauve Liber precationum című könyvében) előfordul. Hogy nem római eredetű, azt abból is következtethetjük, hogy a pap egyes számban, mintegy csak a maga nevében imádkozza. Az a kijelentés, hogy ez a „szeplőtelen ostya... üdvösségünkre legyen az örök életben”, természetesen előlegezi ennek az ostyának Jézus Szent Testévé való konzekrálását, mert csak mint eucharisztikus kenyér szerez nekünk örök boldogságot. A liturgiában ilyen „drámai áthelyezések” („déplacement dramatique”, Fortescue. 403.) gyakran előfordulnak. A pap ennek az imának az elvégzése után a patenával keresztet rajzol a levegőben s mintegy erre a keresztre helyezi az áldozati bárányt, a Krisztus Testévé átváltoztatandó ostyát.<br><br>
Ezután a leckeoldalon bort tölt a kehelybe. Majd megáldja a vizet és a vizes ámpolnából néhány cseppet beleönt a kehelybe, miközben a következő imádságot mondja:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Deus,   qui humanae substantiae dignitatem mirabiliter condidisti, et mirabilius   reformasti: da nobis per hujus aquae et vini mysterium, ejus divinitatis esse   consortes, qui humanitatis nostrae fieri dignatus est particeps, Jesus   Christus, Filius tuus, Dominus noster: Qui tecum vivit et regnat in unitate   Spiritus Sancti Deus: per omnia saeeula saeculorum. Amen.</div>
    <div class="col-lg-4">
Isten,   ki az emberi természet méltóságát csodálatosan alkottad és még   csodálatosabban helyreállítottad: add, hogy e víz és bor titka által, annak   istenségében részesülhessünk, ki emberségünknek részesévé lenni méltóztatott:   Jézus Krisztus a te Fiad, a mi Urunk. Ki veled él és uralkodik a   Szentlélekkel együtt, Isten, mindörökkön örökké. Amen.</div>
</div>
A víznek a borhoz való vegyítése egészen az őskereszténységbe visszanyúló szokás. Egész bizonyossággal feltehető hogy az Úr az utolsó vacsorán a zsidók rituális szokását követve, a borba egy kevés vizet vegyített, bár a Szentírás erről semmiféle említést sem tesz. Az első keresztény századok írói (Szent Jusztin, Szent Irenaeus, Szent Ciprián), továbbá már a karthágói (397) és trullo-i (698) zsinatok is bizonyságot tesznek erről a szokásról. Valószínű tehát, hogy ez a szokás még a zsidó liturgiának a maradványa. Később azután ennek a vegyítésnek különböző magyarázatokat adtak. Így egynéhány nyugati liturgia, mint pl. a milánóiak, vagy a karthauziak liturgiája, a víznek a kehelybe való beöntésénél és megáldásánál e szavakat mondatja a pappal: „Jézus Krisztus oldalából vér és víz folyt ki; az Atyának és Fiúnak és Szentléleknek nevében”. Ez a szertartás is mély gondolatot fejez ki. De mi a bor és víz összevegyítésének legjobb indokolását s magyarázatát mégis abban a fent közölt imádságban látjuk, melyet a római egyház mondat a pappal e szertartás végzése közben. E szerint a bor az isteni természetet, a víz pedig az emberi természetet jelenti, a kettőnek az egyesítése tehát jelképezi az Isten megtestesülésének a titkát. Ez az imádság nagyon régi, már a legrégibb Sacramentarium-okban is megtalálható, még pedig mint karácsonyi miseimádság. A „per hujus aquae et vini mysterium” szavakat csak a középkor adta hozzá akkor, mikor ebből a karácsonyi collectá-ból mindennapi felajánlási ima lett. A középkorban a pap keresztalakban öntötte be a vizet a kehelybe. A XIV. századtól kezdve az ünnepélyes misében a víznek a kehelybe való öntése az alszerpap szerepe, a pap pedig a keresztalakban való öntést pótlandó, áldást ad szintén keresztalakban a vízre. A borra nem ad áldást, mert az az isteni természetet jelképezi s így az áldásnak nem lehetne értelmet adni.<br><br>
Az így elkészített kelyhet a pap felemeli s tekintetét az oltárkeresztre szegezve mondja:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Offerimus   tibi, Domine, calicem salutaris, tuam deprecantes clementiam: ut in conspectu   divinae majestatis tuae, pro nostra et totius mundi salute, cum odore   suavitatis ascendat. Amen.</div>
    <div class="col-lg-4">
Fölajánljuk   neked, Urunk, az üdvösség kelyhét és kérjük kegyelmedet: hogy isteni fölséged   színe elébe, a mi üdvösségünkért és az egész világ üdvösségéért kellemes   illatként fölszálljon. Amen.</div>
</div>
 Ez az ima a „Suscipe Sancte Pater” imának a párja s a XI. századból származik. A szerpap is együtt mondja a pappal, miközben ő is tartja a kelyhet. Régente ugyanis a kehely igen nagy és nehéz volt. Egyik-másik 30-50 fontot is nyomott. (Vandeur. 148.) Nagynak is kellett lennie, mert hiszen a szent vérből nemcsak a pap, de a klérus és a nép is áldozott. A szerpap kötelessége volt a híveknek a szent vérrel való megáldoztatása (S. Laurentius diac.: „cui commisisti Dominici Sanguinis dispensationem”, Brev.) s ezért része volt a felajánlásban is. Innen van, hogy a pap ezt az imát többes számban imádkozza („Offerimus...”), vagyis a szerpappal együtt ajánlja fel a kelyhet. Ezalatt az alszerpap a válláról lelógó velum két végével betakarja a paténát s azt maga előtt magasra emelve, az oltár közepén állva, tartja egész a Pater noster-ig. Ez a szép szertartás régi eredetű. Mikor ugyanis már nem a paténán, hanem a corporalén pihentették az áldozati tárgyakat, akkor a paténa feleslegessé vált az oltárnál, viszont az alszerpapnak nincs a kánon alatt szerepe, így reá bízták a paténa tartását. Magasra kell emelnie a paténát, hogy jelezze a szentáldozás idejének a közeledtét (in signum instantis communionis), amint azt egy párizsi misekönyv megjegyzi.<br><br>
Ezután a pap meghajol, összetett kezeit az oltárra helyezi s alázattal kéri imájának a meghallgatását:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
In   spiritu humilitatis et in animo contrito suscipiamur a te, Domine: et sic   fiat sacrificium nostrum in conspectu tuo hodie, ut placeat tibi, Domine   Deus.</div>
    <div class="col-lg-4">
Alázatos   lélekkel és törődött szívvel fogadj el minket, Urunk, és áldozatunk úgy   szálljon színed elé a mai napon, hogy tessék neked, Úristen.</div>
</div>
 Ez szintén a XI. századból származó imádság. A tüzes kemencében szenvedő, de istenbizalmában meg nem rendülő Dániel próféta (3,39-40) lelkével esedezik a pap az áldozat kegyes elfogadásáért. Majd kiterjeszti s felemeli kezeit e szavakkal:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Veni,   sanctificator, omnipotens aeterne Deus: et benedic hoc sacrificium tuo sancto   nomini praeparatum.</div>
    <div class="col-lg-4">
Jöjj,   megszentelő, mindenható, örök Isten és áldd meg ezen áldozatajándékot, melyet   szent nevednek készítettünk.</div>
</div>
Ez az ima a gallikán liturgiából ered s nagyon régi. Sőt régente nagyobb jelentősége is volt, mert pl. a Stowe-misekönyv szerint (Írország, VII-VIII. sz.) háromszor kellett énekelni. A mozarab liturgiában e helyen a pap kifejezetten a Szentlélek Úristent hívja segítségül az áldozat bemutatására. Gihr (i. m. 473.) ebben az imában a nyugati egyház epiklézisét látja, véleményét azonban nem tudja elfogadhatóvá tenni.<br><br>