A felajánlási imák elvégzése után az ünnepélyes misében a pap tömjénnel megfüstöli a felajánlott tárgyakat és az oltárt. Ez az oltárfüstölés is az újabb keletű szertartások közül való. A régi római szertartáskönyvek csak két tömjénezést írnak elő: a katechumenek miséje előtt az oltárt és evangéliumolvasáskor pedig az evangéliumos könyvet kellett megfüstölni. A VIII. században készült I. római Ordo még semmit sem említ a felajánláskor végzendő oltárfüstölésről. A Micrologus, amelynek a keletkezése a XI. századra tehető, a második oltárfüstölés keletkezéséről így ír: „A római Ordo előírja, hogy füstölőt vigyenek az evangéliumos könyv előtt, valahányszor az oltárhoz, vagy az ambon-ra viszik, de nem engedi meg, hogy a felajánlott tárgyakat az oltáron megincenzálják... jóllehet ezt manapság nagyon sokan megteszik, sőt mondhatnánk, majdnem mindenki” (Micr. 9. P. L. 151. 983.). Ez a szöveg mutatja, hogy a XI. században Rómában még nincs megengedve felajánláskor az oltárfüstölés, de a gyakorlatban mégis csak megtörténik. Nemsokára a római liturgiába is beleolvad ez a szertartás, melyet legelőször a gallikán liturgia hozott szokásba. Tényleg a második Ordo Romanus szerint, amelyen a gallikán liturgia hatása már erősen meglátszik, „a felajánlás után a füstölőt az oltárra kell tenni” (II. 9. P. L. 78. 972.). És ha már az áldozati tárgyakat megfüstölték, könnyen szokásba jött az oltár újabb megfüstölése is. Ami egészen természetes is. Ahogy a katechumenek miséje is oltárfüstöléssel kezdődött, úgy nagyon helyénvalónak látszott az oltár megfüstölése a hívők miséje előtt is. Később még egy lépéssel továbbmentek és megfüstölték a misézőt, a segédkezőket, sőt a népet is.<br><br>
Ennek a füstölésnek a szertartása a mai liturgiában sokkal ünnepélyesebb, mint a többi füstöléseké és már a XIV. században (a XIV. Ordo Romanus-ban, P. L. 78. 1164.) majdnem ugyanabban az alakban megvolt, ahogy azt most végezzük. A pap, miután tömjént tett a füstölőbe, megáldja azt a következő szavakkal:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Per   intercessionem beati Michaelis Archangeli, stantis a dextris altaris incensi,   et omnium electorum suorum incensum istud dignetur Dominus benedicere, et in   odorem suavitatis accipere. Per Christum, Dominum nostrum. Amen.</div>
    <div class="col-lg-4">
Szent   Mihály arkangyal könyörgésére, aki az áldozati oltár jobbján áll és minden   kiválasztottak könyörgésére áldja meg az Úr e tömjént, hogy édes illatával   tetszésre találjon. A mi Urunk Jézus Krisztus által. Amen.<br><br>
</div>
</div>
Ez az ima évszázadok óta sok vitára adott alkalmat. Meg kell jegyeznünk, hogy a szöveget egy a VIII. századra visszavezethető Ordo- ból vette az Egyház (Flaccus Illyricus, vö. Fortescue. 214.). Névszerint megemlítjük benne Szent Mihály arkangyalt, „aki az áldozati oltár jobbján áll.” Viszont Szent Lukács Szent Gábor arkangyalról használja ugyanezeket a szavakat: „stantis a dextris altaris incensi” (Lk 1,11). Igaz, hogy a Látomások könyve szerint (8,3) Szent János látott az égben az oltár mellett egy angyalt, aki arany füstölőt tartott a kezében és ennek az angyalnak a nevét nem említi. Lehet, hogy ez az ima a Látomások könyvében említett angyal közbenjárását kéri s ez az angyal, minthogy a Szentírásban névtelen, lehet Szent Mihály is. Minthogy azonban az üdvösség történetében inkább Szent Gábor arkangyal szerepel s az említett Lukács-szöveg szóról-szóra megegyezik ennek az imának megfelelő kifejezéseivel, azért sokan arra gondolnak, hogy ebben az imában a név tévedésből fel van cserélve. Hogy ki követte el ezt a tévedést, azt természetesen ma már nem tudjuk megállapítani. Bossuet a felügyelete alatt kiadott misekönyvbe a Szent Gábor arkangyal nevét helyettesítette be, viszont egy párizsi misekönyv a nehézség elkerülése végett e kifejezést így közli: „a te szent arkangyalod közbenjárására...” (Vandeur 155.). A szertartások Kongregációjától kérték is, hogy a két nevet fel lehessen cserélni, de eredménytelenül (S. R. C. 1705. szept. 25.). Ennek a kérdésnek különben csak történeti jelentősége van, mert hiszen imádságaink meghallgatásánál épp úgy számíthatunk Szent Gábor arkangyal, mint Szent Mihály arkangyal közbenjárására.<br><br>
A tömjénfüst a mi imádságainkat jelképezi. Ahogy a tömjénfüst felfelé száll és kellemes illatot terjeszt, úgy szeretnénk, ha a mi imádságunk is felemelkednék az égbe, az Atya trónusához s az ő tetszésével találkoznék. Ezért a pap az eddig csak imádságos szóval felajánlott áldozati tárgyakat most körültömjénezi, hogy ezáltal még kedvesebbé tegye azokat a mindenható Isten előtt. Háromszor keresztalakban felülről megfüstöli a kenyeret és a bort, azután háromszor körülviszi a füstölőt a kehely körül, miközben ezeket a szavakat mondja:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Incensum   istud a te benedictum ascendat ad te Domine: et descendat super nos   misericordia tua.</div>
    <div class="col-lg-4">
Ezen   tömjénillat, melyet megáldasz, szálljon föl hozzád, ó Urunk: mireánk pedig   szálljon le a te irgalmasságod.</div>
</div>
Azután háromszor megfüstöli az oltárkeresztet majd az oltárt s közben hangosan imádkozza a 140-ik zsoltár eme szavait:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Dirigatur,   Domine, oratio mea, sicut incensum, in conspectu tuo: elevatio manuum <br><br>
mearum   sacrificium vespertinum. Pone, Domine, custodiam ori meo, et ostium   circumstantiae labiis meis: Ut non declinet cor meum in verba malitiae, ad   excusandas excusationes in peccatis.</div>
    <div class="col-lg-4">
Legyen   előtted imádságom mint jóillatú áldozat, -- Fölemelt kezem esti áldozatként   jószívvel elfogadd! Állíts, Uram, őrséget szám előtt -- És ajkaimnak ajtajába   őrt. Ne engedd szívem vásottságra térni, -- Gonoszokkal gonoszra vetemedni.</div>
</div>
Végül átadja a szerpapnak a füstölőt e szavakkal:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Accendat   in nobis Dominus ignem sui amoris, et flammam aeternae caritatis. Amen</div>
    <div class="col-lg-4">
Gyújtsa   föl bennünk az Úr szerelmének tüzét és az örök szeretet lángját. Amen.</div>
</div>
 Ezután a szerpap megfüstöli elsősorban a miséző papot, aki az örök Főpap, Jézus Krisztus helyettese az oltárnál. Ez a gondolat magyarázza meg azt, hogy régente Párizsban a szerpap térdenállva incenzálta meg a papot. Ezután az asszisztálók és a nép megincenzálása következik. A tömjén illatos füstje betölti az Isten házát, ünnepélyes hangulat ömlik el a lelkeken, minden arra mutat, hogy a nagy esemény, Krisztus áldozatának a megújítása immár közel van. Még az utolsó előkészületek vannak hátra.<br><br>
Először is a kézmosás. Volt idő, mikor a felajánlás előtt s a felajánlás után is volt kézmosás, ahogy még most is történik a püspöki misében. A felajánlás előtti kézmosás azért volt szükséges, mert abban az időben a pap vagy a püspök a katechumenek miséjének a végén a távozni készülő katechumenek s a nyilvános vezeklők fejére feltette a kezét s ezáltal a keze bepiszkolódhatott. Ez a felajánlás előtti kézmosás az egész középkoron keresztül általános szokás volt.<br><br>
A felajánlás utáni kézmosás szintén szükségszerű volt, mert a pap a hívek által felajánlott áldozati ajándékok átvételénél, vagy a füstölő kezelésénél könnyen bepiszkolhatta a kezét. Hogy tehát az Úr Szent Testét érinthesse, kezét meg kellett mosnia. Ez a szertartás egyébként emlékeztette a papot arra is, hogy nemcsak a kezének kell tisztának, szeplőtelennek lennie, hanem még inkább a szívének.<br><br>
Az őskereszténységben nemcsak a pap, de a hívek is megmosták a kezüket a szentmise előtt. Erre a célra a templom bejáratánál kút, vagy forrás szolgált. Egyes kolostortemplomok előcsarnokában még ma is látni forrást, amelyet a szerzetesek a szent szertartások előtti kézmosásra használnak. Ennek a maradványa az a szokás, hogy a hívek a templom bejáratánál szenteltvízzel meghintik magukat.<br><br>
Manapság a pap már nem az egész kezét, hanem csak a 4, ún. konzekrációs vagy kanonikus ujját mossa meg. Ez az ujjmosás az ambrozián misében közvetlenül a konzekráció előtt (tehát a Pridie quam pateretur előtt) történik. Nyilvánvalóan emlékezteti tehát a papot az Úr Szent Testének nagy méltóságára, mely tiszta kezet és ártatlan szívet követel. Kézmosás közben a XI. századtól kezdve a 25. zsoltárnak utolsó verssorait (6-12.) imádkozza a pap:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Lavabo   inter innocentes manus meas: et circumdabo altare tuum, Domine.<br><br>
Ut   audiam vocem laudis et enarrem universa mirabilia tua. <br><br>
Domine,   dilexi decorem domus tuae et locum habitationis gloriae tuae. Ne perdas cum   impiis, Deus, animam meam, et cum viris sanguinum vitam meam: In quorum   manibus iniquitates sunt: dextera eorum repleta est muneribus. Ego autem in   innocentia mea ingressus sum: redime me et miserere mei. Pes meus steinit in   directo: in ecclesiis benedicam te, Domine.<br><br>
Gloria   Patri et Filio et Spiritui Sancto. <br><br>
Sicut   erat in principio, et nunc, et semper: et in saecula saeculorum. Amen.</div>
    <div class="col-lg-4">
Ártatlanságban   mosom a kezem, S oltárodat, Uram, körülveszem. Hogy hallhassam a hála   szózatát -- És elbeszéljem minden te-csodád.<br><br>
Szeretem,   Uram, házad sátorát, És Fölséged trónjának hajlokát. A bűnösökkel lelkem ne   veszejtsd el, -- Életemet a véres emberekkel, Kiknek gonosztól tapad a keze,   Ragadománnyal jobbkezük tele. <br><br>
Én   pedig utam ártatlanul járom, Irgalmazz nekem, légy szabadulásom. Egyenes úton   állok rendületlen. Áldalak Uram, gyülekezetedben. Dicsőség az Atyának és   Fiúnak és Szentléleknek.<br><br>
Miképpen   kezdetben vala, most és mindig és mindörökké. Amen.</div>
</div>
E zsoltár valószínűleg csak az első szavak miatt („Lavabo inter innocentes manus meas”) lett a kézmosás szertartásának kísérő szövege. A további verssorokat csak azért imádkoztatja az Egyház, hogy a papot a kézmosás ideje alatt jámbor gondolatokkal foglalkoztassa. Mindazonáltal ez a zsoltár, mint az ártatlan ember segélykiáltása az ellenségtől való szorongattatás idején, nagyon jól beleilleszkedik a legfőbb áldozati ténykedésre való előkészületbe. A pap is tiszta lélekkel „ártatlanságban” áll az oltárnál, hogy hallhassa a kórus „hálaszózatát” s maga is a Glóriá-ban, a Credó-ban s a praefatió-ban „elbeszélje az Úr csodáit”. Bármennyire is szereti „az Úr fenséges házát”, mégis fél a bűntől s kéri az Urat, hogy „a bűnösökkel lelkét ne veszítse el”. „Ártatlan lélekkel jött” az Úr házába s amint „egyenes úton” járt mindig, úgy „áldani akarja az Urat a gyülekezetben”. A zsoltár végén a pap lelkes örömének kifejezésére Gloria Patri-t mond, mely azonban a gyászmisében elmarad.<br><br>
Ezután a pap az oltár közepére megy, összetett kezeit az oltárra helyezi s kissé meghajolva, így imádkozik:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Suscipe,   sancta Trinitas, hanc oblationem, quam tibi offerimus ob memoriam passionis,   resurrectionis et ascensionis Jesu Christi, Domini nostri: et in honorem   beatae Mariae semper Virginis, et beati Joannis Baptistae, et sanctorum<br><br>
Apostolorum   Petri et Pauli, et istorum et omnium Sanctorum: ut illis proficiat ad   honorem, nobis autem ad salutem: et illi pro nobis intercedere dignentur in   caelis, quorum memoriam agimus in terris. Per eundem Christum, Dominum   nostrum. Amen.<br><br>
<br><br>
</div>
    <div class="col-lg-4">
Fogadd   el, Szentháromság, ezt a felajánlott áldozatot, melyet neked bemutatunk a mi   Urunk, Jézus Krisztus szenvedésének, feltámadásának és mennybemenetelének   emlékére: a Boldogságos és Mindenkor Szűz Máriának, Keresztelő Szent   Jánosnak, Szent Péter és Pál Apostolaidnak és azoknak a Szenteknek, akiknek   ereklyéi itt vannak, és minden szenteidnek tiszteletére; hogy nekik   tiszteletükre, nekünk pedig üdvösségünkre legyen és hogy ők érettünk   közbenjárjanak a mennyben, akiknek emlékét ünnepeljük a földön. Ugyanazon a   mi Urunk, Krisztus által. Amen.</div>
</div>
 Ez mintegy összefoglalása a felajánlási imádságoknak. Kifejezi, hogy kinek mutatják be az áldozatot, milyen fenséges annak a lényege, milyen részt vesz benne az ég s milyen segítséget remél tőle az Egyház. Ez az ima a középkor elején magánimádság volt. Egyes helyeken akkor imádkozták, mikor a pap átvette a hívektől a felajánlott áldozati anyagot. A XI. században még csak „vallásos szokásból, de nem előírás alapján” imádkozták és csak a főbb ünnepeken (Micrologus, XI., P. L. 151., 984.). A domonkosrendiek liturgiájában különösen fontos ez az ima, mert az összes felajánlási imák elhagyásával ezzel ajánlják fel a kenyeret és a bort. De csak az Úr szenvedéséről emlékeznek meg, míg mi az Úr feltámadását s mennybemenetelét is említjük. A lyoni rítusban pedig még az Úr megtestesüléséről és születéséről is említés történik. Egyes helyeken nemcsak Szűz Máriáról, Keresztelő Szent Jánosról s az apostolfejedelmekről emlékeztek meg ebben az imában, hanem tetszés szerint más szentek nevét is beleszúrták, amire a szövegben alkalmazott N. N. mintegy bíztatást adott. A latin szövegben az „istorum” szó alatt értenünk kell azokat a szenteket, akiknek az ereklyéi az oltáron vannak.<br><br>
