Ez a kettős ima, mely a IV. századból származó De sacramentis c. iratban még csak egy ima volt, közvetlen előkészület és bevezetés a konzekrációhoz. A pap kiterjeszti kezeit a kehely fölé és így imádkozik:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Hanc   igitur oblationem servitutis nostrae, sed et cunctae familiae tuae,   quaesumus, Domine, ut placatus accipias: diesque nostros in tua pace   disponas, atque ab aeterna damnatione nos eripi et in electorum tuorum jubeas   grege numeravi. Per Christum, Dominum nostrum. Amen.</div>
    <div class="col-lg-4">
Ugyanezért   az áldozatajándékot szolgáidtól, valamint egész családodtól is, kérünk Urunk,   vedd kegyesen: és napjainkat intézd a te békédben és az örök kárhozatból   bennünket kiragadni és választottaid seregébe sorozni méltóztassál. Krisztus,   a mi Urunk által. Amen.</div>
</div>
Majd a kezeit összeteszi s így folytatja:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Quam   oblationem, tu Deus, in omnibus, quaesumus, benedictam, adscriptam, ratam,   rationabilem, acceptabilemque facere digneris: ut nobis Corpus et Sanguis,   fiat dilectissimi Filii tui, Domini nostri Jesu Christi.</div>
    <div class="col-lg-4">
Kérünk   téged, Istenünk, hogy a felajánlott áldozatajándékot méltóztassál mindenben   áldottá, megfelelővé, érvényessé, értelmes voltunkhoz méltóvá és előtted   kedvessé tenni, hogy az nekünk Testévé és Vérévé változzék a te szeretett   Fiadnak, a mi Urunk Jézus Krisztusnak.</div>
</div>
 A Hanc igitur ima utolsó szavait: „diesque nostros...” Nagy Szent Gergely pápa adta hozzá. Ezekben a szavakban a pap békességért, az örök kárhozat elkerüléséért s az örök boldogság elnyeréséért imádkozik. A békéért való imádságra Nagy Szent Gergely idejében talán a longobardok Itáliába való betörése s Róma városának veszélyeztetése adott alkalmat (Schuster, I. 46.).<br><br>
Mint a Communicantes imánál, úgy a Hanc igitur-nál is, nagyobb ünnepek alkalmával betoldásokat kell alkalmaznunk. Ilyen betoldás csak három van. Nagycsütörtökön a betoldott rész az Oltáriszentség alapítására vonatkozik, Húsvétkor és Pünkösdkor pedig az újonnan kereszteltekről szól. A régi egyházban ugyanis a felnőtteket csak Húsvét és Pünkösd vigíliáján keresztelték, azért van ma is még e két napon keresztkútszentelés. A megkereszteltek a keresztelés napján s egész Húsvét, illetve Pünkösd hetében -- bár mindennap áldozhattak -- áldozati ajándékokat azonban még nem tehettek az oltárra. Ezek helyett ezt a kötelességet a keresztszülők, illetve a szülők teljesítették. Ezért imádkozza a pap ezeken a napokon a következő szöveget: fogadd kegyesen az áldozatot, „melyet neked felajánlunk azok nevében is, akiket a vízből és a Szentlélekből újjáteremteni kegyeskedtél”. A régi időben számos ilyen betoldás volt a Hanc igitur-ban: így pl. a nagyböjt harmadik vasárnapján, amikor a keresztszülők bemutatták a keresztelendőt az Egyháznak, továbbá a papszentelés, vagy házasságkötés évfordulóján, a halottakért bemutatott szentmisében stb. Így a Gelasianum-ban 38 Hanc igitur van, amelyek nem annyira valamelyik ünnep hangulatát fejezik ki, mint inkább egyes évfordulók alkalmából kéréseket tartalmaznak.<br><br>
A pap a Hanc igitur imádkozása közben kezét kiterjeszti a kehely fölé. Ez a nagyon szép szertartás nem régibb a XVI. századnál. Annak előtte a pap mélyen meghajolt, úgyhogy a feje majdnem az oltárt érintette s így végezte ezt az imát. Ez a szokás még ma is megvan a domonkosrendieknél és a kármelitáknál.<br><br>
Mit jelent a római liturgiában ez a kézfeltétel? A legkézenfekvőbb magyarázat az, hogy a pap az Úr előtt rá akar mutatni az áldozati tárgyakra („hanc... oblationem”) s mintegy fel akarja azokra hívni az Úr figyelmét, mielőtt az átváltoztatás megtörténnék. Mások (pl. Thalhofer II. 172. és Vandeur 202.) az ószövetségi liturgiából magyarázzák ezt a szokást. Az ószövetségben ugyanis a pap rátette a kezét az áldozati állatra s ezzel kifejezte azt, hogy a feláldozandó állatra átviszi az emberek bűneit. Már most minden bűnös embernek magának kellene meghalnia a bűneiért. De a pap a kézfeltétel által jelzi, hogy az emberek bűneit ráhelyezi erre az áldozati bárányra, vagyis Jézusra, aki önként vállalkozott, hogy meghal az emberek bűneiért. Hogy milyen szempontok vezették V. Pius pápát, mikor a misekönyvreform kapcsán (1570) ezt a szertartást behozta, ma már nem tudjuk megállapítani. Annyi azonban bizonyos, hogy ez a kézfeltétel, ha nem is nagyon régi szertartás, mert hiszen több mint ezer évvel később keletkezett, mint a Hanc igitur szövege, mégis nagyon kedves s igen mélyértelmű szokása a miseliturgiának.<br><br>
A Quam oblationem kezdetű ima egyik legrégibb része a kánonnak. Oly szorosan kapcsolódik az átváltoztatás szövegéhez, hogy egyes szerzők (Bishop) a konzekrálás rítusához számítják. Szerintök ez a szöveg volt a nyugati liturgia epiklézise, vagyis a Szentlélek segítségül hívása, hogy hajtsa végre az átlényegülést. Ez az ima egészen a legújabb időkig (vö. Jahrb. f. Lit. Wiss. II. 98. sk. és Zeitschr. f. k. Theol. 1925. 474. sk.) élénk vitára adott alkalmat. A liturgikus szerzők ugyanis egy ilyen ősrégi imánál minden szót fontosnak tartanak s megmagyarázására minden lehetőt megtesznek. Így mindjárt felkelti az érdeklődést a szent áldozatra vonatkozó jelzőknek eme sorozata: „benedictam, adscriptam, ratam, rationabilem, acceptabilemque”. Mit jelent ez az öt jelző? Mi ebbe a részletkérdésbe itt mélyebbre bele nem hatolhatunk, mindazonáltal megjegyezzük, hogy ezek a jelzők egyrészről általánosságban ugyanazt fejezik ki, hogy ti. az Úr tegye kedvessé színe előtt ezt az áldozatot, másrészről nem lehet ezt a szöveget puszta szószaporításnak (tautologia) nevezni, mert mindegyik szó valamilyen árnyalati különbséget tartalmaz. Véleményünk szerint a leghelyesebb fordítás ez: „méltóztassál ezt az áldozatot, áldottá, megfelelővé, érvényessé, értelmes voltunkhoz méltóvá s előtted kedvessé tenni”. Ez alatt a pap ötször keresztet vet az áldozati tárgyakra, hogy azokat tőle telhetőleg megszentelje. Egyesek szerint ez az öt keresztvetés a kereszten függő isteni Üdvözítő öt szent sebére emlékeztet.<br><br>
A pap kifejezi legfőbb vágyát, hogy ez az áldozat „Testévé és Vérévé változzék a te szeretett Fiadnak, a mi Urunk Jézus Krisztusnak”. Az Úr szentséges nevének említésére fejét mélyen meghajtja, kezét tisztelettel összezárja s most megnyílik előtte a szentek szentje. <br><br>