 Az Úrfelmutatást követő három ima (Unde et memores, Supra quae, Supplices) tulajdonképpen egy ima, mely közös klauzulával (Per eundem Christum stb.) végződik. Ebben az imában a pap az Úr Jézus szent testét és vérét ajánlja fel kedves áldozatul a mennyei Atyának. Valójában maga az Úr az, aki önmagát áldozatul bemutatja, aki „az emberek között nem talált olyan tiszta áldozatot, amelyet felajánlhatott volna az emberekért, ezért maga magát adta oda tiszta áldozatul. Ó boldogságos áldozat, ó valóságos áldozat, ó szeplőtelen áldozat” (Szent Ágoston, Enarr. in. ps. 149. 6.).<br><br>
Az első ima így hangzik:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Unde   et memores, Domine, nos servi tui, sed et plebs tua sancta, ejusdem Christi   Filii tui, Domini nostri, tam beatae passionis, nec non et ab inferis   resurrectionis, sed et in coelos gloriosae ascensionis: offerimus praeclarae   majestati tuae de tuis donis ac datis, hostiam puram, hostiam sanctam,   hostiam immaculatam, Panem sanctum vitae aeternae et Calicem salutis   perpetuae.</div>
    <div class="col-lg-4">
Azért   megemlékezvén Urunk, mi, a te szolgáid és a te szent néped is, ugyanazon   Krisztusnak, a te Fiadnak, a mi Urunknak áldott szenvedéséről, mint   halottaiból való föltámadásáról, valamint dicsőséges mennybemeneteléről is:   bemutatjuk szent Fölségednek a te ajándékaidból és adományaidból ezt a tiszta   áldozatot, szent áldozatot, szeplőtelen áldozatot, az örök élet szent Kenyerét   és az örök üdvösség Kelyhét.</div>
</div>
A pap a konzekrálás szertartását azzal végezte be, hogy megismételte az Úr kívánságát: „Ezt cselekedjétek az én emlékezetemre”. Természetes tehát, hogy a konzekrálás után így kezdi az imát: „Azért megemlékezvén... a mi Urunk áldott szenvedéséről”. Így ennek az imának liturgikus neve görögül anamnezis (memoria), vagyis megemlékezés. A Liber Pontificalis szerint ezt az imát I. Sándor pápa (kb. 105-115) szúrta be a kánonba (Fortescue. 178.). Sőt még ennél is régebbinek tarthatjuk. Már a legrégibb liturgiákban találunk hasonló imát. Nagyon valószínű tehát, hogy az ősliturgiában is volt hasonló megemlékezés az Úr szenvedéséről. A IV. században a De sacramentis c. iratban található anamnézis majdnem ugyanazon szövegű, mint a mi mostani imánk.<br><br>
A XII. században szokásba jött, hogy a pap a konzekrálás után karjait kereszt alakban kiterjesztette s ezáltal is emlékeztette magát és a híveket az Úr kereszthalálára. Erről a szokásról s annak jelentőségéről kifejezetten tanúskodik Aquinói Szent Tamás: „A pap karjainak kiterjesztése a konzekrálás után azt fejezi ki, hogy az Úr is kiterjesztette karjait a kereszten” (III. 83. 5. 5.). Ennek a szokásnak bizonyos maradványa még ma is megvan egyes szerzetesrendek liturgiájában így pl. a karthauziaknál és a karmelitáknál. A domonkosoknál e helyen ez a megjegyzés olvasható: „A pap terjessze ki a karjait a szokottnál jobban, de azért ne egészen”. A ferencrendiek új szertartáskönyve (Caeremoniale Romanoseraphicum Ordinis Fratrum Minorum, 1908.) a ministráns teendőiről az Úrfelmutatás után így szól: „A ministráns visszatér a helyére s ott térdelve s a karjait kiterjesztve marad egész Pater noster-ig s ezen idő alatt halkan elimádkozik 6 Miatyánkot, Üdvözlégyet és Dicsőséget” (Vandeur. 224, 2.). A római egyházban a karok kiterjesztésének a szokása -- úgy látszik -- sohasem dívott, ott a pap -- mint ma is -- csak melle előtt felfelé tartott kezekkel mondta ezt az imádságot.<br><br>
A mai római liturgia szerint nemcsak az Úr szenvedéséről emlékezünk meg ebben az imában, hanem feltámadásáról s mennybemeneteléről is. Az V. században még az Úr születéséről is megemlékeztek. Ezt a római egyházban később elhagyták, de a kisebb egyházakban még sokáig szokásban maradt. A görög egyház még arról is megemlékezik, hogy Jézus az Atya jobbján ül a mennyben és hogy dicsőséggel fog eljönni a világot megítélni.<br><br>
A szentmise tehát az Úr szenvedésének a megújítása. Az Egyház mai liturgiája ugyanazt mondja általában az Oltáriszentségről, mikor így imádkozik: „Isten, ki nekünk a csodálatos Oltáriszentségben szenvedésed emlékezetét hagytad stb.”.<br><br>
E megemlékezések után a pap bemutatja a tiszta, szent és szeplőtelen áldozatot a mennyei Atyának, de egyúttal alázatosan elismeri e szavakkal „a te ajándékaidból és adományaidból”, hogy mi nem tudunk semmiféle ajándékot adni az Istennek, ami nem volna az övé. Jézus Krisztust is ő adta nekünk s most visszaadjuk őt neki. Az alázatosságnak e kifejezései nagyon régiek és megtalálhatók az alexandriai és bizánci liturgiákban is (Renaudot. II. 32., 236.). Az örmény liturgia pedig még világosabb kifejezést használ: „Felajánljuk neked azt, ami a tied, abból, ami a tied stb.” (Fortescue. 457.).<br><br>
A pap ezután öt keresztet vet a kehely és a szent ostya felé. Ezek a keresztvetések, valamint a későbbi „Per quem haec omnia” kezdetű ima keresztvetései a középkor liturgikus szerzői előtt szinte megfejthetetlenek voltak. Nem tudták sehogy sem megmagyarázni, hogyan lehet a szent ostyát és a bort megáldani, ha az már át van változtatva az Úr szent testévé és vérévé. E kérdésnek legelfogadottabb megoldása az volt, hogy ezek a keresztvetések tulajdonképpen nem is áldások, hanem csak Jézus öt sebének, vagy a Szentháromságnak a szimbólumai. Mások pedig arra gondoltak, hogy e keresztvetésekkel akarjuk az Urat megengesztelni azokért a hibákért, amelyeket a szentáldozat bemutatásánál elkövettünk. Ezek bizony erőszakolt magyarázatok. Helyesebben azt mondjuk, hogy ezek a keresztvetések valóban áldások, csakhogy ezeket nem szabad a konzekrációtól elszakítani, azzal időbelileg szembehelyezni. Ellenkezően a konzekrációs kánon összes imádságával tulajdonképpen csak egy ima, melynek az a célja, hogy a kenyeret és a bort Jézus testévé és vérévé változtassa. Isten ezt az átváltoztatást egy pillanat alatt eszközli, mi azonban az átváltoztatásra vonatkozó kérésünket nem tudjuk egy pillanat alatt elmondani. Így természetesen az átváltoztatás pillanata után is folytatjuk az átváltoztatásra vonatkozó érzelmeink kifejezéseit. Erről részletesebben az ún. epiklézis-kérdésnél fogunk szólani. <br><br>