Az újszövetség nagyszerű áldozatának fenségét mutatja az is, hogy az Úr már az ószövetségi áldozatok között előképeket állított, amelyek reá vonatkoznak. Egészen megfelelő dolog tehát, hogy a pap ezekre az ószövetségi áldozatokra való hivatkozással is kérje a Mindenhatót a szentmiseáldozat kegyes elfogadására. A pap így könyörög:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Supra   quae propitio ac sereno vultu respicere digneris: et accepta habere, sicuti   accepta habere dignatus es munera pueri&nbsp;   tui justi Abel, et sacrificium Patriarchae nostri Abrahae: et quod   tibi obtulit summus sacerdos tuus Melchisedech, sanctum sacrificium,   immaculatam hostiam.</div>
    <div class="col-lg-4">
Melyre   kiengesztelten, derült arccal tekinteni méltóztassál: és fogadd el kegyesen,   amint kegyesen elfogadtad igaz gyermekednek, Ábelnek ajándékait és   ősatyánknak, Ábrahámnak áldozatát: és melyet neked bemutatott a te főpapod,   Melchizedek, a szent áldozatot, a szeplőtelen ajándékot.</div>
</div>
Három ószövetségi áldozatról van itt szó, amelyek, mint Krisztus Urunk áldozatának előképei, emelik a szentmise fényét. Ábel, aki nyájának legjavát áldozta fel Istennek (Ter 4,4) s akit Káin megölt, előképe Krisztusnak, az „elsőszülöttnek a sok testvér között” (Róm 8,29), akit a zsidók keresztre feszítettek. Ábrahám kész volt feláldozni egyetlen fiát, Izsákot (Ter 22) s így áldozata emlékeztet Isten egyszülött Fiának áldozatára a Kálvárián. Ábrahámot „a mi pátriarkánknak” nevezi a liturgia („partiarchae nostri”), mivel erős hite és bizodalma Istenben atyjává tette őt mindazoknak, akik hisznek. Szent Pál is ily értelemben írja a galatákhoz: „Értsétek meg tehát, hogy akik e hitből vannak, azok fiai Ábrahámnak” (3,6). Azután a pap Melchizedek áldozatára hivatkozik, aki kenyeret és bort ajánlott fel Istennek. Személyéről a szentírás azt mondja, hogy „Sálem királya” és „a fölséges Isten papja” volt (Ter 14,18), továbbá, hogy „atya nélkül, anya nélkül, nemzetségtábla nélkül való; mivel sem napjainak kezdete, sem életének vége nincs, hasonlóvá tétetett Isten Fiához és pap marad mindörökké” (Zsid 7,3). E szavak szerint a szentírás azért nem említi Melchizedek származási adatait s csak papi mivoltját domborítja ki, hogy ezáltal is kimutassa hasonlóságát Krisztussal, akinek az isteni természete szerint anyja nem volt s mint embernek atyja nem volt, de mint Isten örökkévaló. Melchizedek a szentírás szerint pap volt, de nem volt főpap, mert Áron nemzetségének főpapi tiszte későbbi keletű. A liturgia „summus sacerdos” kifejezése tehát inkább „kiváló papot”, mint „főpapot” jelent.<br><br>
Ennek az imának az utolsó szavai: „sanctum sacrificium, immaculatam hostiam” vonatkozhatnak Melchizedek áldozatára is, mely bizonyára szent és szeplőtelen volt. Helyesebb azonban, ha e szavakat a jelen miseáldozatra vonatkoztatjuk (Vandeur. 231.). Ez lehetett a régiek véleménye is, mert e szavak kiejtésénél a szent ostyára és a kehelyre keresztet vetettek. Grammatikailag ezek a szavak az „accepta habere” szavaktól függnek, vagyis az összefüggés ez: „fogadd el kegyesen... a szent áldozatot, a szeplőtelen ajándékot”. A közbeeső rész „sicuti”- tól egész „Melchisedech”-ig tehát beszúrás. Egyébként ezeket az utolsó szavakat a Liber Pontificalis szerint I. Leó pápa (440-461) adta hozzá a kánonhoz. (Ed. Duchesne. I. 239.) Duchesne-nek az a véleménye, hogy a pápa a manicheusok ellen irányította ezeket a szavakat, akik az anyagok szent voltát tagadták s így minden anyagi tárgyból álló áldozatot elvetettek.<br><br>
Megemlítésre érdemes, hogy az alexandriai liturgiának van egy igen hasonló szertartása. Ott ugyanis a pap a tömjén megáldásánál a következő szavakat mondja: „Amint kegyesen fogadtad az igaz Ábel ajándékát, a mi atyánknak, Ábrahámnak az áldozatát, Zachariás tömjénfüstjét, Cornelius alamizsnáit és az özvegyasszony két fillérét”. Ez alapon Buchwald azt tartja (Fortescue. 460.), hogy a mi imánk az alexandriai liturgiából származik, csakhogy az átvételnél Zachariás tömjénfüstjét, Cornelius alamizsnáit, a szegény asszony két fillérét elhagyták, minthogy ezeket nehezebben vonatkoztathatták a szentmisére, azért helyettük Melchizedek áldozatát szúrták be. Érdekes, hogy ez az ima több keleti liturgiában a tömjén megáldásánál fordul elő s nem a szentmiseáldozatra vonatkozik.<br><br>