Már az apostolok idejében szokás volt, hogy a szentmisékben a holtakról is megemlékeztek. Aranyszájú Szent János (Ep. Phil. h. III. 4. P. G. 62. 204.) és Szent Ágoston (serm. 32. de v. Ap. P. L. 38. 936.) kifejezetten az apostolokig visszamenő hagyományra hivatkoznak, mikor a szentmisében a holtakért való imádkozást ajánlják a híveknek. A legrégibb liturgiákban is találunk valamelyes formában megemlékezést a holtakról. Ezt annál is inkább természetesnek tarthatjuk, mert hiszen már az ószövetségben is megvolt a holtak tisztelete s az érettük felajánlott kegyeletes könyörgés (2Mak 12,32 sk.). Az újszövetségi áldozat bemutatásánál mindenképpen indokolt tehát, hogy a hívek a tisztítótűzben szenvedő testvéreikért könyörögjenek. Nem is lehet az Egyháznak hatásosabb imája a mennyei Atyához az örökkévalóságba átköltözött tagjaiért, mintha az oltáron misztikus módon feláldozott Üdvözítőt ajánlja fel váltságul a megholtak földi gyarlóságaiért. Ennek az imának eredetileg nem ez volt a helye, hanem régente közvetlenül az élőkről való megemlékezés után a konzekráció előtt állt, ahogy azt még ma is sok keleti liturgiában találjuk. Mindazonáltal ez a hely is nagyon megfelelő, mert hiszen az előző imában (Supplices) feltekintettünk a mennyei oltárra s kértük a földi oltár áldozatának az örökkévalóság oltárán való folytatását s így érthető, hogy ráterelődik figyelmünk azokra a lelkekre, akik az örökkévalóság ölén égi megdicsőülésüket várják.<br><br>
A régi egyház a megholtak neveit, éppúgy mint előbb az élők neveit kis táblácskákról, az ún. diptichákról olvastatta fel. Ma már a pap csak lélekben gondol azokra a megholtakra, akikért a szentmisét bemutatja.<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Memento   etiam, Domine, famulorum famularumque tuarum N. et N., qui nos praecesserunt   cum signo fidei, et dormiunt in somno pacis. Ipsis, Domine, et omnibus in   Christo quiescentibus locum refrigerii, lucis et pacis ut indulgeas,   deprecamur. Per eundem<br><br>
Christum   Dominum nostrum. Amen.</div>
    <div class="col-lg-4">
Emlékezzél   meg, Urunk, N. N. szolgáidról és szolgálóidról, kik minket megelőzve   költöztek el a hit jelével és a béke álmát alusszák.<br><br>
Kérünk,   Urunk, hogy nekik és Krisztusban minden elhunytnak a megenyhülés, a világosság   és a béke hazáját megadjad. Ugyanazon Krisztus, a mi Urunk által. Amen.</div>
</div>
A Memento mai szövege újabb keletű. Legalább is ezer évvel később keletkezett, mint a holtakról való megemlékezés szokása. Sem a Gelasius pápa, sem a Gergely pápa sacramentarium-ában nem találjuk meg, ezekben a Supplices ima után mindjárt a Nobis quoque következik. Valószínű, hogy a mai szöveg a XII. századból származik, bár egyes kifejezései, különösen az elköltözöttek örök boldogságára vonatkozóak a régi egyházban is használatosak voltak, amint arról a fennmaradt sírfeliratok tanúskodnak (Gihr. 587.). Így pl. gyakran előfordul régi sírfeliratokban „meghaltak” helyett „megelőztek minket”. Nagyon sokszor nevezik a megholtakat „alvóknak” („dormientes”) amint ez már szent Pál idejében is szokásban volt (1Tesz 4,13-15). Ezért régente a sírokat Caemeteriá-nak, vagyis alvóhelynek nevezték. Ez a kifejezés tulajdonképpen a feltámadás hitének a megvallása, vagyis hirdetése ama meggyőződésüknek, hogy a megholtak csak alszanak s ebből az alvásból, álomból az örökéletre fognak felébredni. Egy dél-olaszországi régi sírfelirat így hangzik: „Itt nyugszik Successa a hit jelével a béke álmában” (cum signo fidei in somno pacis). Mint látjuk, szóról-szóra a mi Mementó-nk szavai, mintha csak az Egyház ezekről a II. századig visszamenő sírfeliratokról kölcsönözte volna ennek az imádságnak költői szépségű kifejezéseit. A „hitnek a jelén” („signum fidei”) itt bizonyára a keresztségben nyert eltörölhetetlen jelet kell értenünk, mivel a keresztséget szokták a „hit szentségének” nevezni s másrészről a keresztség adja meg a jogcímet az örök boldogság elnyerésére. Lényegében „a hit jelén” szent Ciprián írására támaszkodva a keresztény hitvallást értjük. Mindenképpen azt akarták e szóval a régi keresztények kifejezni, hogy csak annak a boldog örökkévalóságában bíznak, aki mint buzgó keresztény halt meg. Ezek -- bár még büntetéseik letörlesztése végett imádságainkra rászorulnak -- másrészről már „Krisztusban pihennek” („in Christo quiescentibus”) s nyugodtan várják a bebocsátást a mennyországba, amelyet ez az ima oly gyönyörű kifejezéssel „a megenyhülés, a világosság és a béke hazájának” („locum refrigerii lucis et pacis”) nevez. Nagy vigasztalására szolgálhat minden keresztény hívőnek, hogy az Egyház nemcsak azokért a lelkekért imádkozik, akikért éppen azt a szentmiseáldozatot bemutatják, hanem minden egyes szentmisében „minden Krisztusban elhunytért” („omnibus in Christo quiescentibus”).<br><br>
Ezt az imát is „Krisztus, a mi Urunk által” terjeszti az Egyház a mennyei Atya elé és a pap a Krisztus szó kiejtésénél fejet hajt. Ez az egyetlen eset a szentmisében, amikor a pap Krisztus szóra fejet hajt, egyébként csak Jézus szóra kell az előírt mély fejhajtást végeznie. XIV. Benedek pápa a szentmiséről írt gyönyörű könyvében (De sacr. Miss. II. 17. 4.) arra inti a papot, hogy e fejhajtásnál Krisztus halálára gondoljon, aki a kereszten „lehajtván fejét, kiadá lelkét” amint azt a szeretet apostola, aki a kereszt alatt állott, feljegyezte (Jn 19,30). <br><br>