 Ez az ima szorosan kapcsolódik az előzőhöz, amelynek végén azért nincs is Amen, tulajdonképpen még pontot sem kellene tennünk, mert hiszen a „Krisztus, a mi Urunk” szavak után közvetlenül folytathatjuk „ki által mindenezen jókat stb”.<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Per   quem haec omnia, Domine, semper bona creas, sanctificas, vivificas, benedicis   et praestas nobis.</div>
    <div class="col-lg-4">
Ki   által mindezen jókat, Urunk, mindig teremted, megszenteled, élteted, megáldod   és nekünk adod.</div>
</div>
 Ennek az imának a megértéséhez tudnunk kell, hogy régente ezen a helyen a szentmisében különböző terményeket, gabonát, bort, olajat áldottak meg. Ezekre a terményekre vonatkozik tehát a „mindezen jókat” „haec omnia bona” kifejezés (Duchesne, 193.). A régi keresztények ugyanis abból a hitből kiindulva, hogy minden áldás az Oltáriszentségből, illetve a szentmiséből származik, szerették a megszentelésre szánt dolgaikat a szentmise alatt megáldatni. Már a régi sacramentarium-ok is utasítást adnak a szentmise e helyén a termények megáldására (Leon. Gelas. Greg.). Így a Gelasianum szerint az Úr mennybemenetelének a napján meg kellett áldani a friss hüvelyes veteményeket („Benedic, Domine, et has fruges novas fabae etc.”). A Leonianum előírja, hogy pünkösd ünnepén az első misében történjék a katechumenek számára hozott víz, méz és tej megáldása. Szent Xystus pápa napján (aug. 5.) a Gregorianum szerint szőlőt áldottak meg e szavakkal: „Áldd meg Uram, ezt az új szőlőtermést is, melyet égi harmattal, bőséges esővel, derült és nyugodt idővel nekünk megérlelni méltóztattál s amelyet azért adtál nekünk, hogy hálaadással fordítsuk azt hasznunkra a mi Urunk Jézus Krisztus nevében, ki által mindezen jókat mindig teremted stb”. A XVI. század végén még szokásban volt (Sacerdotale romanum, 1580), hogy Szent Balázs napján mise közben áldották meg a kenyeret és bort, a gyümölcsöket és magvakat, Szent Ágota napján a kenyeret, húsvét előtt a húsvéti bárányt. A pap a nép felé fordulva mondta az áldást. A gnesen-posen-i egyházmegyében még ma is szokás Szent Ágota napján az ún. Ágota-víznek és Ágota-kenyérnek a megáldása (Thalhofer, II. 191.). Ennek a régi szokásnak a maradványa a nagycsütörtöki misében a betegek olajának a megszentelése. A püspök ugyanis közvetlenül a Per quem haec omnia előtt félbeszakítja a szentmisét s egy külön e célra felállított asztalhoz, vagy oltárhoz vonul s ott megszenteli a betegek olaját, majd visszatér az oltárhoz és folytatja a szentmisét. Szentmise alatt más áldások és szentelések is történnek, bár nem a szentmise e részénél: így a papszentelés, püspökszentelés, az apátok megáldása, a szerzetesi és szerzetesnői fogadalom, házasságkötés (nászmise), a krizma és a katechumenek olajának a megáldása.<br><br>
A pap, míg ezeket a szavakat mondja „megszenteled, élteted, megáldod”, háromszor keresztet vet a kehely és a szent ostya felett. Ezeket a keresztvetéseket a pap régente bizonyára a közép, azután jobb- és balfelé végezte, ti. arrafelé, ahol a megáldásra szánt termények voltak. A mai liturgiában ez az ima régi jelentőségét jóformán teljesen elvesztette, mert csak arra szolgál, hogy a kánon ünnepélyességét emelje. <br><br>
