A pap kezébe veszi a Szentostyát s vele a kehely felett kereszteket vetve mondja:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Per   ipsum, et cum ipso, et in ipso est tibi Deo Patri omnipotenti, in unitate   Spiritus Sancti, omnis honor et gloria. --Per omnia saecula saeculorum. Amen.</div>
    <div class="col-lg-4">
Őáltala,   ővele, és őbenne, neked, mindenható Atyaistennek, a Szentlélek egységében   minden tisztelet és dicsőség. -- Mindörökkön örökké. Amen.</div>
</div>
E szavakat az Egyház valószínűen szent Pálnak a rómaiakhoz írt leveléből vette, hol az apostol egy fejezet végén így ír: „Mert minden belőle, általa és érte van (ťex ipso et per ipsum et in ipsoŤ). Dicsőség neki örökre” (11,36). Más szóval semmi által sem dicsőül meg annyira a Szentháromság, mint az Úr Jézus s az ő működése által.<br><br>
A „minden tisztelet és dicsőség” szavaknál a pap a Szentostyával együtt kissé felemeli a kelyhet. Egész a XII. századig e helyen, vagyis a konzekrációs kánon végén történt az úrfelmutatás. Az első római Ordo (VIII. század) így írja le (n. 16.) ezt a felemelést. Az archidiákonus feláll és egy vászonkendővel megfogja a kehely fogóit s mikor a főpap „Per ipsum et cum ipso” szavakat mondja, a kelyhet magasba emeli. Így tartja, míg a főpap fel nem emeli a Szentostyát s oldalról meg nem érinti vele a kelyhet. Mikor már a Per omnia saecula saeculorum után az Amen is elhangzott, a főpap és az archidiákonus visszahelyezik a Szentostyát, illetve a kelyhet a helyére. Ezzel végződik a kánon. Ez tehát a régi liturgiában az úrfelmutatás.<br><br>
Egyes egyházmegyékben (Köln) a pap e felemelések alkalmával a nép felé fordult. Belgiumban még ma is szokás, hogy e helyen csengetnek s így felhívják a nép figyelmét erre a szertartásra, az ún. „kis felemelésre.”<br><br>
A görög katolikusok, valamint a keletiek liturgiájában is megvan ez a második felemelés, még pedig a szentáldozás előtt. Előtte a diákonus felkiált: „Figyelmezzünk!” Azután a pap felemeli a szent Testet s felkiált: „Szentség a szenteknek” (Rusznák, 224.). Ez a felkiáltás nagyon régi, nyugaton a gallikán s a mozarab-liturgiában is megtalálható, a római egyház azonban sohasem használta. Tulajdonképpen azt a gondolatot fejezi ki, hogy a szentáldozáshoz csak egészen tiszta lélekkel lehet járulni.<br><br>
Az első római Ordo szerint tehát a főpap a Szentostyával megérintette a kelyhet, amelyet az archidiákonus felemelt. Ennek a megérintésnek bizonyára az a jelentősége, hogy a szent Test és Vér együtt alkotják a szentáldozatot. Eleinte csak egy helyütt érintette a Szentostyával a kelyhet, utóbb három helyen. Később ez az érintés a kehely mind a négy oldalán történt s a pap mintegy keresztalakot írt le a Szentostyával, mikor azt a kehely egyik szélétől a másikhoz vitte. Lehetséges, hogy így jött szokásba, hogy a pap a Szentostyával keresztet vet a kehely felett (Vandeur, 246). Ezután a Szentostyával két keresztjelet tesz a kehely előtt, miközben a mindenható Atyát és a Szentlelket említi. Ezeknél az utóbbi kereszteknél egyes középkori misekönyvekben azt az utasítást találjuk, hogy az Atya-Isten említésénél a keresztet „in alto”, vagyis a kehelytől kissé magasabban fekvő vonalban, a Szentlélek említésénél „versus pedem” vagyis a kehely lábának magasságában kell végezni. Így fejezték ki a Szentháromság személyeinek a származását: a legmagasabban van az Atya, középen a titokzatos kehelyben a Fiú és alól a Szentlélek (Vandeur, 246.).<br><br>
A keresztvetések és a kehely felemelése után a pap hangosan mondja, vagy énekli: Per omnia saecula saeculorum s a nép, illetve a segédkezők ráfelelik: Amen. Ezeket a szavakat a mai liturgiában úgy szoktuk venni, mint a Pater noster-t előkészítő szöveget, pedig ez tulajdonképpen az előző „Per ipsum et cum ipso” imához tartozik, mint annak a befejezése. Ennek az Amen-nek a mai szertartásban semmi különös jelentősége sincs, a régi miseliturgiának azonban egyik legünnepélyesebb része volt, Az ősegyházban ugyanis hangosan mondta a pap a kánont, a nép által hallható hangon mondta a konzekrálás szavait is. Azután a konzekrált kenyeret és bort az archidiákonussal együtt felemelte s megmutatta a népnek, miközben kifejezte azt a kérését, hogy ez az áldozat szolgáljon a Szentháromság dicsőségére mindörökkön örökké. Erre a nép hangosan kiáltotta az Amen-t s ebben a kiáltásban fejezte ki hitét az Úr eucharisztikus jelenlétében, közvetlen résztvételét a szentmisében s forró óhajtását, hogy a keresztfa áldozatának megújítása az oltáron valóban a háromszemélyű Isten dicsőségére szolgáljon. Már a II. században Szent Jusztin tanúságot tesz erről. A III. században Szent Dénes, később pedig Szent Ambrus és Szent Ágoston nagy magasztalással írtak a nép által lelkes hangon kiáltott, a kánont bevégző Amen-ről.<br><br>