A lépcsőima és az oltárfüstölés után a pap hozzáfog a szentmise tulajdonképpeni szövegéhez. Keresztet vet magára és megkezdi az ún. introitus-t. Ez a kezdőima egyik legérdekesebb, legváltozatosabb része a szentmisének. Legelsősorban bemutatunk egy mintát. Karácsony ünnepén az első mise introitusa így hangzik:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Ps.   2. -- Dominus dixit ad me: Filius meus es tu, ego hodie genui te.</div>
    <div class="col-lg-4">
2.   zs. Az Úr mondotta ezt nekem: „Az én fiam vagy, én ma szültelek.”</div>
</div>
<div class="row two_column">
    <div class="col-lg-4">
Ps.   ibid. Quare fremuerunt gentes: et populi meditati sunt inania?</div>
    <div class="col-lg-4">
P.   Miért hogy a nemzetek háborognak? Hiúságokon a népek miért hogy agyarognak?</div>
</div>
<div class="row two_column">
    <div class="col-lg-4">
V.   Gloria Patri et Filio et Spiritui Sancto.<br><br>
</div>
    <div class="col-lg-4">
V.   Dicsőség az Atyának, és Fiúnak, és Szentlélek Istennek.</div>
</div>
<div class="row two_column">
    <div class="col-lg-4">
R.   Sicut erat in principio et nunc et semper et in saecula saeculorum. Amen.</div>
    <div class="col-lg-4">
R.   Miképpen kezdetben vala, most és mindig és mindörökké. Amen.</div>
</div>
<div class="row two_column">
    <div class="col-lg-4">
Dominus   dixit ad me: Filius meus es tu, ego hodie genui te.</div>
    <div class="col-lg-4">
Az   Úr mondotta ezt nekem: „Az én fiam vagy, én ma szültelek”.</div>
</div>
A mai introitus tehát áll egy antifónából, vagyis a zsoltáréneklést előkészítő előversből (Dominus), azután egy zsoltárrészletből (Quare), melyet a zsoltár recitálás után szokásos Gloria Patri követ, majd azután a végén az antifónát megismételjük.<br><br>
Az introitus-nak, magyarul: bevonulásnak igen messzire nyúló története van. Abból az ünnepélyes körmenetből származik, amellyel a régi egyházban a püspök a szentmiseáldozat bemutatására a templomba bevonult. A püspök ugyanis a templom bejáratánál fekvő sekrestyében (secretarium) liturgikus ruhákat öltött magára, azután méltóságteljes menetben, teljes asszisztenciával az oltárhoz vonult. A körmenet alatt zsoltárt énekeltek. A legrégibb időben nem is volt más énekük a keresztényeknek, mint a zsoltár. A zsoltár verseit felváltva énekelték. A dallam megadására és a zsoltár alapgondolatának a kifejezésére szolgált az antifóna, melyet a zsoltár előtt az énekkar (scola cantorum) énekelt el. Az antifóna rendesen magából a zsoltárból vett szövegrész volt. A zsoltárt menetközben egészen elénekelték, vagy legalább is addig, míg a püspök az oltárhoz ért. A püspök az oltárnál először is mély imádással üdvözölte azt a konzekrált szent ostyát, amelyet az előző szentmisében tettek el és amelyet most adorálás céljából egy segédkező pap a püspöknek felmutatott. Majd békecsókot adott a jelenlevő papságnak és leborult az oltár előtt, hogy megkezdje a szentmisét. A zsoltáréneklést a bevonulási körmenetnél a Liber Pontificalis megjegyzése szerint I. Celesztin pápa (422-432) hozta be. Középkori szerzők gyakran megismétlik ezt az adatot s hozzáfűzik, hogy viszont az antifóna-éneklést Nagy Szent Gergely pápa rendelte el. Szent Ágoston „Vallomásai”-ban említi, hogy Milánóban Szent Ambrus hozta be a zsoltáréneklést. Így ír: „Ebben az időben kezdtek az Egyház keleti részeinek példája szerint himnuszokat és zsoltárokat énekeltetni a néppel, nehogy gyászába belefáradjon és belefásuljon” (IX. 7. 1.). Ebben az időben még az antifónát a zsoltár minden egyes versszaka után megismételték. Lassankint azonban ezt a módot igen hosszúnak találták s ezért csak a zsoltár elején és végén énekelték el az antifónát. Sőt a zsoltárból is mindig kevesebbet énekeltek, úgy hogy a tizedik Ordo Romanus idejében (XI. sz. körül) már csak a zsoltár első versszaka maradt meg. Az új római Graduale (Rubr. 1.) megengedi, hogy a kórus az introitus éneklését megkezdje, mielőtt a pap az oltárhoz érne. Ez helyes is mert így a kórus zsoltáréneklése kíséri a pap kivonulását az oltárhoz.<br><br>
Régente a pap természetesen nem recitálta az introitus-t, hanem azt csak a kórus és a nép énekelte. Rómában egész a XIV. századig ez volt a szokás. Később az ének művésziessége érdekében a szöveg egyes részeit a kórus elhagyta, vagy megváltoztatta s azért a papnak kellett az oltárnál pótolni az elhagyott részeket. Mikor azután szokásba jött a kismise végzése -- a régi egyházban tudvalevőleg csak énekes misét ismertek --, a kórus hiányában már állandóan a pap végezte az introitus- t. Ha már most a misekönyvben található introitus-okat összevetjük a Nagy Szent Gergely Liber Antiphonarius c. könyvében közölt introitusokkal, akkor azt látjuk, hogy azok legnagyobb részben szószerint megegyeznek (M. P. L. 78. 641. sk.). Igaz, hogy ez az Antiphonarius, ahogy az a mi kezünkben van, már javított kiadás, mégis a zöme kétségtelenül Nagy Szent Gergelyre vezethető vissza. Ez a tény mutatja a mi introitusaink ősiségét és növeli előttünk azok értékét.<br><br>
A görög liturgiában a szövegrészek ilyen változatossága nincs meg. A keleti liturgiák általában minden napra ugyanazon szöveget adják, kivéve természetesen az egyes olvasmányokat és a nagy ünnepekre szánt egyes énekszövegeket. A nyugati egyház viszont alkalmazkodik a kalendáriumhoz, így majdnem minden nap más a mise szövege. Ennek a változásnak a behozatalát egyesek szent Damasus pápának tulajdonítják.<br><br>
Ami az introitus tartalmát illeti, megfigyelhetjük, hogy az antifóna rendesen egy zsoltárvers, mégpedig többnyire ugyanabból a zsoltárból, melynek egy verssora az introitus gerince. Máskor az antifónát nem a zsoltárkönyvből, hanem a Szentírás valamelyik másik könyvéből veszi az egyház. Így a karácsony második és harmadik miséjében, pünkösdkor stb. Egyes misékben az antifónát maga az Egyház szövegezi meg, így általában a szentek ünnepeinél, pl. Mindenszentek napján. Ugyanez áll a gyászmise introitus-ára is. A „Salve sancta parens” kezdetű introitus-t Caelius Sedulius, V. századbeli költőnek egyik himnuszából kölcsönözte az Egyház. A Vízkereszt utáni 3., 4., 5., 6. vasárnapok introitus-ai (Adorate) s egyéb énekrészei szövegileg teljesen egyformák. Érdekes, hogy a pünkösd utáni vasárnapokon egész a 17. vasárnapig az introitus- ok zsoltárszámai mindig emelkedőben vannak. Szinte látjuk azt a valakit, aki az egyes vasárnapok introitus-zsoltárait kijelölte, amint lapozott a zsoltárkönyvben s a napi evangéliumnak megfelelő bevonulási zsoltárt kiválasztotta.<br><br>
A gyász kifejezésére a gyászmisében és a Passio-időszak miséiben az introitusnál nincs Gloria. Nagyszombaton és pünkösd vigíliáján meg egyáltalán nincs introitus, minthogy itt nincs bevonulás. Az introitus első szava az egész miseszöveg megjelölésére szokott szolgálni. Így ismerünk Requiem-et, Roraté-t, Cogitationes-misét (az új Jézus-Szíve mise) stb. Az introitus latin szövege többször eltér a hivatalos Vulgata-szövegtől. Ennek az a magyarázata, hogy egyik-másik introitus már megvolt a Vulgata-fordítás elterjedése (VII. sz.) előtt is. Ezekben a szövegekben tehát a régi népies Itala-fordítás szövegét találjuk. Ismeretes dolog, hogy a Vulgata-fordítás elterjedésének egyik nagy akadálya az volt, hogy a nép már hozzászokott a misénél az Itala- szöveghez.<br><br>
Az introitus elején a pap keresztet vet magára. Már a régi keresztények kereszttel jelölték meg magukat, ha valami imához hozzáfogtak. Egyes egyházmegyékben a keresztvetéssel együtt mondták: „Adjutorium nostrum in nomine Domini -- az Úr nevében van a mi oltalmunk”, máshol meg a szokásos „In nomine Patris” szavakat használták. E szövegeket később elhagyták, de a keresztvetés megmaradt. A gyászmisében a pap a könyv felé ad áldást, ami által jelzi, hogy a szentmise gyümölcseit a tisztítótűzben szenvedő lelkek javára szenteli.<br><br>
Nagyobb ünnepeken, azután adventi s nagyböjti napokon a mise introitus-a előtt ilyen felírásokat találunk: „Statio ad Mariam majorem”, „Statio ad S. Crucem in Jerusalem” stb. Mit jelentenek ezek a felírások? Ezek a szavak azt akarják kifejezni, hogy a régi időben a római keresztények a római Maria Maggiore, vagy a S. Croce in Gerusalemme templomba vonultak s ott mutatták be az ünnepi szentmisét. Grisar szerint (Das Missale im Lichte röm. Stadtgesch. 4.) a stációk eredete a jeruzsálemi anyaegyházra vezetendő vissza. Az ottani keresztények gyakran felkeresték azokat a helyeket, amelyeket az Úr szenvedése által megszentelt. Az Úr életének egyes emléknapjait a megfelelő helyen ülték meg. Már most, ha figyelembe vesszük, hogy milyen szoros összeköttetés volt a jeruzsálemi és a római keresztény egyházak között, könnyen érthető, hogy Rómában is szokásba jött a stáció, annál is inkább, mert hiszen a római egyháznak is voltak kegyeletes helyei, az egyes mártírok sírjai, mint pl. Szent Péter, Szent Pál, Szent Lőrinc templomai. A stációjárás abban állott, hogy a nép egy templomban, mely a stációtemplomhoz közel volt, összegyülekezett (collecta) s onnan körmenetileg vonult -- elől a stációs-kereszttel -- zsoltárokat és Kyrie eleison-t énekelve a stációstemplomba. A nagyböjti időszak hétköznapi miséinek végén található imádság: oratio super populum (imádság a nép felett) jelentette a stációra összegyűlt népnek az elbocsátását. A stációskörmenetek a pápák avignoni fogságának idejében szűntek meg. A pápák később nagy búcsúkat engedélyeztek a stációstemplomok meglátogatóinak. Jelenleg a stációk megtartása Rómában erős fellendülésben van. Az utóbbi években még a stációs körmeneteket is megtartották, amelyek 1870 óta szüneteltek. (Tausch O. S. B. Bibel und Liturgie. III. évf. 10. sz.)<br><br>
Az introitus „az egész misének a kulcsa” (Wiseman). Olyan, mint egy „színpompás ouverture” (Gihr), mely az egész ünnep alaptónusát, hangulatát mutatja be nekünk. <br><br>