Mint említettük, a Pater noster a konzekrációs kánonon kívül esik s vele kezdődik az ún. áldozási kánon (canon communionis). Az Úr imádságának elmondása előtt a pap egy kis bevezetést mond:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Oremus.   Praeceptis salutaribus moniti et divina institutione formati audemus dicere:</div>
    <div class="col-lg-4">
Könyörögjünk.   Üdvös parancsok által megintve és isteni tanítás által oktatva merjük   mondani:</div>
</div>
<div class="row two_column">
    <div class="col-lg-4">
Pater   noster, qui es in caelis: Sanctificetur nomen tuum: Adveniat regnum tuum: <br><br>
fiat   voluntas tua, sicut in caelo et&nbsp; in   terra: Panem nostrum cotidianum da nobis hodie: et dimitte nobis debita   nostra, sicut et nos dimittimus debitoribus nostris: <br><br>
Et   ne nos inducas in tentationem.<br><br>
Sed   libera nos a malo. <br><br>
Amen.</div>
    <div class="col-lg-4">
Miatyánk,   ki vagy a mennyekben: Szenteltessék meg a te neved: Jöjjön el a te országod:<br><br>
Legyen   meg a te akaratod, miképpen mennyben, azonképpen itt a földön is. Mindennapi   kenyerünket add meg nekünk ma: És bocsásd meg a mi vétkeinket, miképpen mi is   megbocsátunk az ellenünk vétkezőknek. És ne vigy minket a kísértésbe. De   szabadíts meg a gonosztól.<br><br>
Amen.</div>
</div>
A bevezetésnek az a célja, hogy az Úr imádságának az elmondását ünnepélyesebbé tegye. Ezért hivatkozik a pap arra, hogy az Úr sok üdvös parancsot adott az imádságra („praeceptis salutaribus moniti”) és hogy ő maga tanította az apostolokat a Miatyánkra („divina institutione formati”). Ez az isteni tanítás és rendelet felhatalmaz minket arra, hogy ilyen bizalmasan merjük („audemus”) megszólítani az Istent: „mi Atyánk”. Az Egyház minden alkalmat felhasznál arra, hogy a liturgiában is kimutassa az Úrtól tanult imádság iránti nagyrabecsülését és szeretetét. Már maga ez a bevezetés is kiemeli a Miatyánkot a többi kánonima közül. A III. században Szent Ciprián püspök tanúskodik arról (De or. dom. I. P. L. 4, 537.), hogy a Miatyánk imádkozását néhány soros imával előkészítették. Szent Ágoston és Szent Jeromos pedig már ugyanazt a szöveget mondják a Miatyánk előtt, amelyet mi is használunk. Ennek a bevezetésnek az ősiségét mutatja az is, hogy valamelyes formában minden liturgiában megtalálható. A latin liturgiában mindennap egyforma, az ambrózián-liturgiában csak kétszer változik: nagycsütörtökön és húsvétkor. A gallikán és mozarab- liturgiában mindennap más. A régi gallikán liturgiában karácsony napján pl. így hangzik: „Szent Atyánk, nem a mi érdemeinkkel kérkedve, hanem a te Fiad, a mi Urunk Jézus Krisztus parancsának engedelmeskedve merjük mondani: Mi Atyánk...” (Mabillon. De Lit. Gall. 192.). Egyes alkalmakkor (pl. Szent István vértanú ünnepén) ebben a bevezetésben külön szándékot is említenek, amelyre azon a napon ezt a nagyhatású imádságot végzik.<br><br>
A Miatyánk használata már az őskeresztény egyházban igen általános volt. A katechumeneknek ezt az imát, amelyet nekik előzőleg nagy gonddal megmagyaráztak, kívülről meg kellett tanulniok s a kereszteléskor felmondaniok. De csak a megkeresztelt hívőnek volt szabad azt hangosan imádkoznia, mert csak az volt teljes értelemben Isten gyermeke s csak ő mondhatta igazában az Istennek: Atyánk. Miért is a Miatyánkot régente a hívők imádságának nevezték (Cabrol. Le livre. 133.). A szentmisében is már a legrégibb idők óta előfordul a Miatyánk. Hiszen már eleve is feltételezhetjük, hogy az apostolok a szentáldozat bemutatása alkalmával imádkoztak is s bizonyára nem volt ismertebb és kedvesebb imádságuk a Miatyánknál. Szent Jeromos szerint maga az Úr rendelte el, hogy a szentmisénél a Miatyánkot imádkozzák. Annyi kétségtelen, hogy az összes liturgiákban megvan a Miatyánk. Csak az ún. apostoli konstitúciók miserendjében (8. könyv) nem találjuk meg, de ez a miserend ezen a ponton hiányos.<br><br>
Rómában Nagy Szent Gergely pápa (590-604) tette a Miatyánkot a mai helyére, vagyis közvetlenül a kánon után („mox post Precem”), mégpedig azért, mert hiszen illő dolog, hogy az Úr imádsága közel kerüljön a kánonhoz, vagyis a kánon után mindjárt az első imádság legyen (Schuster. I. 44.). Továbbá a Miatyánk azzal a kéréssel „és bocsásd meg a mi vétkeinket, miképpen mi is megbocsátunk az ellenünk vétőknek” nagyon jó előkészület volt a békecsókra, mely Nagy Szent Gergely liturgiájában mindjárt a Miatyánk után következett. Nagy Szent Gergely ezen intézkedéséről a János szirakuszi püspökhöz intézett leveléből értesülünk. Érdemes itt röviden megemlítenünk, mily sok vitára adott alkalmat a nagy pápa egy helytelen kifejezése. Szent Gergely ugyanis olyasféle véleményt nyilvánít, mintha szerinte az apostolok a Miatyánk szövegével s nem az utolsó vacsora szavaival végezték volna a kenyérnek és bornak az Úr testévé és vérévé való átváltoztatását („quia mos apostolorum fuit, ut ad ipsam solummodo orationem oblationis hostiam consecrarent”). Ez természetesen történeti tévedés, melyet manapság már senki se fogad el. A múlt században még Schell (+1906) próbált e vélemény mellett hangulatot kelteni (Kath. Dogm. 1893. III. 543.), de sikertelenül. Manapság már általánosan elfogadott vélemény, hogy a Pater noster sohasem volt az átváltoztatás formulája. Szent Gergely levelében tehát az „oratio”-n nem az Úr imádságát, vagyis a Miatyánkot, hanem a kánont kell értenünk (Probst. Lit. der drei erst. Jh. 356.).<br><br>
Nagy Szent Gergely fentemlített levelében tiltakozik azon beállítás ellen, hogy ő a szentmisére vonatkozó reformjaiban a konstantinápolyi görög liturgiát utánozza. Cáfolatul a pápa felsorolja a két liturgia közötti eltéréseket s e felsorolásból megtudjuk, hogy a keleti egyházban a latin egyháztól eltérően már a VI. században a nép együtt mondta, vagy énekelte a Miatyánkot a pappal. Régente Franciaországban és Spanyolországban is ez volt a szokás. Tours-i Szent Gergely beszéli, hogy egy néma zarándokasszony Szent Márton sírjánál éppen akkor nyerte vissza beszélőképességét, mikor a nép a szentmise alatt a Miatyánkot énekelte. A meggyógyult asszony is együtt énekelte a hívekkel a Pater noster-t. (Mirac. S. Mart. 2. 30. P. L. 71. 954.) Ez a szokás még ma is változatlanul megvan az összes keleti liturgiákban. A latin egyház azonban Nagy Szent Gergely óta kitart azon szokás mellett, hogy csak a pap mondja, vagy énekli a Miatyánkot. A nép csak az utolsó kérést fűzi hozzá: De szabadíts meg a gonosztól. A mozarab miseliturgia szerint, mely a spanyolországi Toledó-ban még manapság is használatos, a nép a Miatyánk minden egyes kérésére Amen-t felel, csak a negyedik kérésnél, mely a mindennapi kenyérért esdekel, mondja: „Mert Isten vagy” („Quia Deus es”).<br><br>
A Miatyánk imádkozásával a hívek egyúttal előkészültek a szentáldozásra. A negyedik kérést ugyanis: „add meg nekünk mindennapi kenyerünket” már a legrégibb keresztény írók is, ha nem is kizárólagosan, de mégis elsősorban az eucharisztikus kenyérre értették, így Tertullián (De orat. c. 6.), Origenes (De orat. c. 27.) és Szent Ciprián (De orat. c. 18.). „A szentatyák írásai alapján joggal feltételezhetjük, hogy a Miatyánk a liturgiában azért került a szentáldozás közvetlen közelébe, mert a negyedik kérést az Eucharisztiára vonatkoztatták”, írja Thalhofer (II. 200.). Tényleg, régente a nép a Miatyánk imádkozása alatt készülődött a szentáldozásra. Sőt egyes helyeken szokás volt, hogy az áldozók már a Miatyánk alatt az oltárhoz járultak. Néhol az alszerpap felmutatta a paténát, hogy jelezze a szentáldozás idejének közeledtét. Lyonban régente a pap „miképpen a mennyben” szavaknál felemelte a Szentostyát, „azonképpen itt a földön is” szavaknál pedig visszahelyezte az oltárra s ezáltal kifejezte, hogy ez a szent Kenyér az égből származik s a földön élő hívek lelki táplálására szolgál. (Vandeur. 253.) Szent Ágoston idejében (Serm. 351. 6. P. L. 39. 1541.) e szavaknál „és bocsásd meg a mi vétkeinket” a hívek a mellükre vertek, hogy bűnbánatukat kifejezzék.<br><br>