A Miatyánkot a pap Amen-nel fejezi be. Azután a pap a kehelykendővel gondosan megtörli a paténát, miközben ezt az imádságot mondja:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Libera   nos, quaesumus, Domine, ab omnibus malis, praeteritis, praesentibus et   futuris: et intercedente beata et gloriosa semper Virgine Dei Genitrice   Maria, cum beatis Apostolis tuis&nbsp; Petro   et Paulo, atque Andrea et omnibus Sanctis, da propitius pacem in diebus   nostris: ut ope misericordiae tuae adjuti et a peccato simus semper liberi et   ab omni perturbatione securi.</div>
    <div class="col-lg-4">
Szabadíts   meg minket, kérünk, Urunk, minden múlt, jelen és jövő gonosztól: és a   boldogságos és dicsőséges mindenkor Szűz, Istenanya Mária és boldog   Apostolaid, Péter és Pál, meg András és minden Szenteid közbenjárására, adj   kegyesen békét napjainkban: hogy irgalmad segítségével a bűntől mindig   szabadok és minden lelki nyugtalanságtól mentesek legyünk.</div>
</div>
Ez az ima tulajdonképpen nem más, mint bővebb kifejtése a Miatyánk utolsó kérésének: „Szabadíts meg a gonosztól”. Ezért a liturgikus szerzők ezt az imát embolismus-nak, vagyis beszúrásnak, kibővítésnek nevezik. Ahogy a Miatyánk imádkozása előtt egy kis bevezetés („Praeceptis salutaribus...”) előkészített minket ennek a gyönyörű imádságnak méltó elmondására, úgy most a Miatyánk elmondása után nem tudunk mindjárt ettől a gondolatkörtől megválni s a Miatyánk utolsó akkordja mintegy tovább cseng a fülünkben, mikor részletezzük, hogy mi minden gonosztól szabadítson meg minket az Úr.<br><br>
Ha ennek az imának a keletkezési idejét akarjuk megállapítani, nagyon messzire kell visszamennünk. Valószínűleg még az őskereszténységben keletkezett. A Szent Gelasius és Szent Gergely-féle sacramentariumokban már majdnem azonos a szövege a maival. Feltűnő, hogy csak három apostolról történik említés. Péterről, Pálról és Andrásról. Főleg Szent András említése szorul magyarázatra, mert hiszen máshol az apostolfejedelmek mellett nem szokás az ő nevét említeni. Grisar (Zeitschr. f. k. Th. 1885. 582.) rámutatott arra, hogy a Gelasius-féle sacramentariumokban még nem igen fordul elő Szent András neve. Valószínű tehát, hogy ennek az apostolnak a nevét Nagy Szent Gergely szúrta be ebbe az imába. Ezt a feltevést megerősíti az a tény is, hogy Szent Gergely pápa nagy tisztelője volt Szent András apostolnak, sőt a Mons Coelius-on Szent András tiszteletére benedekrendi kolostort is építtetett, amelyben mint szerzetes ő maga is hosszabb ideig tartózkodott. A középkorban ennek az imának a szövegében más szentek neveivel is találkozunk. Sőt a negyedik római Ordo (IV. P. L. 78. 984.) egyenesen felhatalmazza a papot, hogy más szentek neveit is megemlítheti. Különösen Szent Mihály arkangyalnak, Keresztelő Szent Jánosnak, Szent Istvánnak, továbbá az egyházmegye vagy a szerzetesrend védőszentjének a nevét szerették megemlíteni.<br><br>
Nagyon mélyértelmű szertartás az, mikor a pap e szavaknál: „adj kegyelmesen békét napjainkban” az arany áldozati tányérkával, a paténával keresztet vet magára és megcsókolja azt. Ha ennek a keresztvetésnek a magyarázatát keressük, önkéntelenül is felvetődik a kapcsolat a békeima és a kereszt között, hiszen minden békesség a szent keresztről származik. Mások szerint ez a keresztvetés eredetileg az ima végén a Per eundem Dominum szavaknál volt. De mivel később a per eundem Dominum szavaknál történt a Szentostya megtörése, azért a keresztvetést kissé előbbre tették. Sőt régi misekönyvek, így pl. az 1556-ban kiadott meaux-i misekönyv, három keresztvetést írnak elő, ti. az adjuti, liberi és securi szavaknál. A paténa megcsókolása is igen szép szokás. Ezzel a liturgikus csókkal a pap a legnagyobb megtiszteltetésben akarja részesíteni a paténát, amelyre közvetlenül a csók után reá helyezi az Úr szentséges Testét. Régente egyes vidékeken szokás volt, hogy a pap, mielőtt megcsókolta volna a paténát, hozzáérintette azt a Szentostyához s így mintegy az Úr Jézustól magától vette át a békecsókot.<br><br>
Bona kardinális (i. m. 1. II. c. XVI. § 1.) nagyon érdekes adatokat közöl arra vonatkozólag, hogy régente a püspök a Libera nos ima elvégzése után ünnepélyes áldást adott. Ez az áldás három-négy ima elmondásából állott, melyek mindegyikére Amen-nel feleltek. Ez a szokás Franciaországban, Spanyolországban, Németországban elég széles körben dívott és Bona kardinális szerint egyes francia egyházmegyékben még a XVII. században is megvolt. Egy vatikáni kéziratos misekönyv e szertartást a következőképpen írja le: „Mikor a Libera nos ima után az Amen elhangzott, a főpap a Szentostya részecskéjét a paténára teszi. Ekkor a diákonus a nép felé fordulva, kezében a pásztorbottal, hangos szóval így kiált: Hajoljatok meg az áldásra. A kórus válaszol: Amen. Erre a szerpap a püspök felé hangosan énekli: Egyházunk fejedelme, nyájunk pásztora, kegyeskedjél minket megáldani. Erre ismét a nép felé fordulva így szól: Szelídséggel és szeretettel hajoljatok meg az áldásra. A kórus válaszol: Alázatos lélekkel kiáltsunk és adjunk hálát mindig Istennek. Erre a főpap az oltár közepén a nép felé fordulva olvassa az ünnepnek megfelelő áldást. Áldásadás után így szól: Az ő békéje legyen mindenkor veletek. Erre a Szentostya részecskéjét beleejti a kehelyben. Ez az áldás eleinte csak a püspökök joga volt. Később egyes helyeken egyszerű papok is átvették. Úgy látszik, hogy a mai misekönyvben található nászmise (Missa pro sponso et sponsa) ennek a szokásnak a maradványát őrzi. A pap ugyanis a nászmisében a Pater noster után kifordul s a leckeoldalon az oltár lépcsőjén térdeplő jegyesek felett két imát mond, amelyekben Istentől áldást s hosszú életet kíván nekik.<br><br>
A nagypénteki csonkamisében, amely tulajdonképpen nem is mise, csak áldozási szertartás, a pap Oremus-szal kezdi a Libera nos imát és az egész imát hangosan mondja. Milánóban az ambrózián-liturgia szerint mindennap hangosan kell mondani ezt az imát. <br><br>