A Libera nos ima után a pap térdet hajt s a „kenyértörés” szertartása alatt tulajdonképpen folytatja az előző imát (ezért: „ugyanazon”, „eundem”):<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Per   eundem Dominum nostrum Jesum Christum, Filium tuum, qui tecum vivit et regnat   in unitate<br><br>
Spiritus   Sancti Deus. Per omnia saecula saeculorum. -- Amen.<br><br>
--   Pax Domini sit semper vobiscum.<br><br>
--   Et cum spiritu tuo.</div>
    <div class="col-lg-4">
Ugyanazon   a mi Urunk, Jézus Krisztus, a te Fiad által, ki veled él és uralkodik a   Szentlélek Istennel egyetemben. Mindörökkön örökké. <br><br>
--   Amen.<br><br>
--   Az Úr békéje legyen mindig veletek. <br><br>
--   És a te lelkeddel.</div>
</div>
A zsidók nem vágták a kenyeret, hanem törték. Ehhez a szokáshoz alkalmazkodva, az Úr az utolsó vacsorán a konzekrált kenyeret széttörte s úgy osztotta ki apostolai között. Azután megparancsolta, hogy ezt cselekedjék az ő emlékezetére. A szentírás szerint az apostolok tényleg kenyértörésre gyűjtötték össze vasárnaponként a keresztényeket. Ez később az ősegyházban mintegy liturgikus szokássá vált, úgyhogy kenyértörésen általában eucharisztikus áldozatot értettek. Lukács pl. így ír: „A hét első napján pedig (azaz vasárnap), mikor egybegyűltünk a kenyértörésre, Pál beszédbe ereszkedett velök stb”. (ApCsel 20,7) Az első század végén a Didaché is a kenyeret „megtört dolog”-nak (IX. 3.) nevezi. Az Úr az utolsó vacsorán a kenyeret szent Testévé változtatta, azután mindjárt megtörte s apostolai között kiosztotta. A szentmisében ezek az események, vagyis az átváltoztatás s a kenyértörés nem közvetlenül egymásután következnek. A liturgia fejlődése, a rítus gazdagodása ezeket a szertartásokat elszakította egymástól, a Szentostya megtörése a szentmisében bizony elég messze esik az átváltoztatástól.<br><br>
De miért kell a szentmisében a Szentostyát eltörni? A pap a szertartás végzésénél elsősorban kétségtelenül Krisztus Urunk példáját követi. Az Úr pedig azért törte meg a szent kenyeret, hogy apostolai között kioszthassa. Ugyancsak az apostolok a konzekrált kenyeret azért törték darabokra, hogy a keresztényeket a szentáldozásban részesíthessék. A régi időben ugyanis nem konzekráltak külön kenyeret a papnak és külön kenyeret a híveknek, hanem egy közös kenyérből vették valamennyien magukhoz az Úr szent Testét, ahogy még ma is a pápai misében a miséző pápa ostyájából áldozik a szerpap és az alszerpap, a püspökszentelési misében pedig az újonnan felszentelt püspök. Később, mikor a hívek megáldoztatására külön kenyerek, illetve ostyák szolgáltak, kenyértörésre az áldoztatás céljából már nem volt szükség. A kenyértörést azonban mégis minden liturgia megtartotta, de már csak mint az Úr által végzett kenyértörés emlékét. A misztikus magyarázat szerint a megtört Szentostya jelképezi Jézusnak a szenvedések által megtört, meggyötört testét. A görög liturgiában négy felé, a mozarab liturgiában kilenc felé törik szét a szent kenyeret. A mozarab liturgia a kilenc résszel az Úr életének kilenc misztériumát jelöli: a megtestesülést, a születést, a körülmetéltetést, a színeváltozást, a szenvedést, a halált, a feltámadást, a mennybemenetelt és a mennyei uralkodást.<br><br>
A kenyértöréssel kapcsolatban három régi, szép szokásról kell megemlékeznünk, amelyek ma már nem ismeretesek, de amelyek a régi időben nagyszerűen kifejezték a keresztények ama kedves hitét, hogy az Eucharisztia a keresztények lelki közösségének egyik legszebb kifejezése, leghatásosabb eszközlője. Ezt a gondolatot domborítja ki az ősegyház egyik legmarkánsabb írója, a hős antiochiai püspök, Szent Ignác is, mikor a philadelphiai hívekhez küldött búcsúlevelében ezt írja: „Gondotok legyen rá, hogy csak egy Eucharisztiában részesüljetek: mert a mi Urunknak, Jézus Krisztusnak csak egy teste van, az ő vérének csak egy kelyhe a mi egyesülésünkre, csak egy oltár, mint ahogy csak egy püspök a presbyterekkel, szerpapokkal és segédkezőkkel” (IV.).<br><br>
A VIII. századból származó első római Ordo szerint (8. P. L. 78. 941.) a miséző püspök a konzekrált kenyérből egy kis partikulát eltesz a következő szentmisére. Mikor azután a következő alkalommal a püspök bevonul a kíséretével a templomba, hogy a szentmisét bemutassa, a segédkezők felnyitják előtte a kis szentségtartót, hogy a püspök a kis partikulát láthassa és fejhajtással üdvözölhesse („inclinato capite salutat Sancta”). Ezt a kis partikulát azután a Pater noster után beleejtették a konzekrált kehelybe. Viszont a püspök ismét letört egy kis darabot az aznapi Szentostyából s az oltáron hagyta („ut dum missarum solemnia peraguntur, altare sine sacrificio non sint”, uo. 19.). Így keletkezett tehát az a szokás, hogy a pap a Szentostyából egy részecskét letör s beleejti a kehelybe. A különbség csak az, hogy most az aznapi Szentostyából törjük le a kehelybe ejtendő partikulát, míg régente az előző szentmiséből vették azt. A régi szokás a szent áldozat egységét akarta kifejezni, hogy ti. minden szentmise csak folytatása az előzőnek s végeredményképpen a szent kereszt áldozatának.<br><br>
Egy másik szép szokásról is tanúskodnak a régi írások. A IV. századtól kezdve egész a X. századig gyakran olvassuk, hogy a pápa, vagy valamelyik püspök az ünnepélyes miséből kis konzekrált partikulákat küldött más templomokba, ahol az ott miséző papok azokat a mise közben a kehelybe ejtették. Egy IX. századbeli író (Anastasius Bibliothecarius) szerint már Miltiades pápa (311-314) elrendelte, hogy a püspökök konzekrált partikulákat, ún. fermentum-okat küldjenek az egyes templomokba. Ugyancsak I. Ince pápa (401-417) Decentius püspökhöz írt levelében említi, hogy ő minden vasárnap Róma minden tituláris templomába szokott konzekrált partikulákat küldeni. E küldés célja az volt, hogy azok a papok, akik nem misézhettek együtt a pápával („concelebrare”) s nem áldozhattak a pápa oltáránál, „tudják meg, hogy nincsenek elszakítva a mi közösségünktől” („ut se a nostra communione non judicent separatos”). A pápa nem kívánja, hogy a partikulákat vidéki plébániákra („per paroecias”), vagy a temetőben levő szentélyekbe is elvigyék, mert „nem volna helyes a szent misztériumokat oly nagy távolságra elvinni” (P. L. 20. 556-557.). Már a II. század végén megvolt ez a szép szokás, mert I. Viktor pápáról (190-202) olvassuk, hogy ő is küldött Eucharisztiát a püspököknek (Eus. H. E. V. 24.). Mily gyönyörű kifejezése volt ez az eucharisztia-küldés a pápa és a püspökök, illetve a püspök és a papok lelki egységének, legteljesebb szent közösségének. A római egyház roppant fontosnak tartotta, hogy a szentáldozás szertartásában minél jobban kidomborodjék az Egyház egysége Krisztusban.<br><br>
Ugyanez volt a célja még egy harmadik szokásnak is, amely a híveknek a papsággal ápolt lelki közösségét fejezte ki. Mikor ugyanis a hívek még legtöbbször két szín alatt áldoztak, a püspök kelyhéből néhány csepp konzekrált bort átöntöttek egy másik nagyobb kehelybe, mely a hívek áldoztatásához szükséges konzekrált bort tartalmazta. Így akarták kifejezni, hogy nemcsak egy közös kenyeret törnek meg mindnyájuk számára, hanem közös a lelki italuk is. Az Egyház, mikor a hívek lelki egységéért imádkozik, manapság is gyakran hivatkozik a közös, eucharisztikus kenyérre („ut, quos uno pane coelesti satiasti, tua facias pietate concordes”, Or. divers. 9.). <br><br>