Miután a pap a nagy ostyából letört partikulával háromszor keresztet vetett a kehely felett, a partikulát a kehelybe ejti, miközben ezt az imát mondja:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Haec   commixtio, et consecratio Corporis et Sanguinis Domini nostri Jesu Christi   fiat accipientibus nobis in vitam aeternam. Amen.<br><br>
</div>
    <div class="col-lg-4">
A   mi Urunk Jézus Krisztus Testének és Vérének ezen egyesülése és megszentelése   legyen nekünk, kik azt magunkhoz vesszük, az örök életre. Amen.</div>
</div>
 A szent Testnek és a szent Vérnek ilyen egyesítése nagyon régi liturgikus szokás. Eredetét pontosan megjelölni nem tudjuk. Lehet, hogy még a régi zsidók ama szokásából származott, hogy étkezések alkalmával a kenyérdarabokat a borba mártogatták. Az Úr az utolsó vacsorán egy „bemártott falatot” nyújtott Júdásnak (Jn 13,26). Hogy az Úr a konzekrált kenyeret a kehelybe, esetleg már a konzekrált kehelybe bemártotta-e, mielőtt apostolainak nyújtotta volna, a szent írók nem említik. De nem valószínű, mert hiszen akkor az Úr először a bort konzekrálta volna, vagy legalább is a kenyeret csak a bor konzekrálása után adta volna tanítványainak. Annyi azonban kétségtelen, hogy a Szentostya és a szent Vér vegyítése az összes keleti és nyugati liturgiákban megvan. Sőt a keleti liturgiák általános szokása, hogy két szín alatt egyszerre szolgáltatják ki a szentáldozást, vagyis az áldoztatásnál a Szentostyát bemártják a szent Vérbe.<br><br>
A nyugati egyházban régente két vegyítés is volt a szentmisében. Az első akkor történt, mikor -- mint előbb (196. o.) említettük -- a pápa az előző szentmiséből félretett partikulát a Pater noster után a kehelybe ejtette, vagy amikor a püspökök és a papok ugyanezt tették azzal a partikulával, amelyet a pápa, vagy a püspök küldött nekik (197. o.). Ez a vegyítés a IX. vagy a X. században megszűnt. A második vegyítés pedig az aznapi Szentostya partikulájának a szent Vérrel való egyesítéséből állott. Ezt a vegyítést, vagyis általában azt, miért ejtik be a partikulát a konzekrált kehelybe, mostanában a következőképpen szokták magyarázni (Vandeur. 263.). Régente két szín alatt áldoztak a keresztények. Ha azonban a hívek oly tömegesen jöttek a szentáldozáshoz, hogy a konzekrált szent Vér nem volt már elegendő, akkor nem-konzekrált bort öntöttek a kehelybe s azzal áldoztattak. Hogy ezt a bort mégis valamiképpen megszenteljék, a kehelybe egy kis konzekrált kenyérdarabot tettek, amely benne is maradt egész az áldozás befejezéséig. Azután a szerpapnak vagy az alszerpapnak a dolga volt, hogy az áldoztatás után a megmaradt bort s a bennelevő partikulát magához vegye. Ennek a régi szokásnak bizonyos maradványa az, hogy a nagypénteki csonkamisében, amelyben konzekrálás nincs, hanem csak az előző napon konzekrált Szentostyát veszi magához a pap, ebből az ostyából egy kis partikulát a kehelybe kell ejteni, melyben nem- konzekrált bor van. És jóllehet ebben a csonkamisében nincs konzekrált bor, mégis úgy Franciaországban, mint Rómában régente nagypénteken is két szín alatt áldoztak a hívek, amint azt a Szent Gergely-féle sacramentárium tanúsítja. E napon tehát nem konzekrált, hanem csak a partikula által megszentelt bort vettek magukhoz. Később a két szín alatti áldozás megszűnt, de a partikulának a kehelybe való ejtése mégis megmaradt, csakhogy persze most már nem a diákonus, hanem a pap veszi azt magához. Ezért mondja a szentmise rubrikája: a pap „tisztelettel magához veszi az egész Vért a kehelybe ejtett partikulával együtt” (tit. X. n. 5.).<br><br>
Az az ima, melyet a partikulának a konzekrált kehelybe való ejtésénél mondunk, főleg az a kifejezés: „commixtio et consecratio” („egyesítés és megszentelés”) sok vitára adott alkalmat (Gihr. 632.). Mit kell itt a „consecratio” szón értenünk? Egyes tudósok szerint itt a mise közepén már megtörtént konzekrálásról van szó. Egy régi milánói misekönyvben tényleg ezt a szöveget így olvassuk: „Az Úr konzekrált Testének és Vérének a vegyítése...” („commixtio consecrati Corporis et Sanguinis...”). Ez a vélemény azonban nem helyes, mert a legtöbb misekönyvben mégis csak így olvassuk: „commixtio et consecratio”. Továbbá ha itt a már megtörtént átváltoztatásra kellene gondolnunk, akkor előbb kellene mondanunk a „consecratio” szót és csak azután a „commixtio” szót, mert hiszen mindig előbb van az átlényegülés s csak azután a szent Test és Vér összekeverése. Itt tehát olyan konzekrációról van szó, amely a szent Test és Vér egyesítése után, vagy legalább is azzal egyidejűleg történik. Hogyan értjük ezt a konzekrációt?<br><br>
A régi liturgikus szerzők erre a kérdésre a következő magyarázatot adták. Szerintük az Úr szent Testének és Vérének liturgikus egyesítése a szentmisében az Úr dicsőséges feltámadásának a szimbóluma.<br><br>
A trienti zsinat ugyanis azt tanítja (sess. XIII. c. 3., XXI. c. 3.), hogy az átlényegüléskor a kenyér felett elmondott szentségi szavak ereje által („vi verborum”) csak az Úr Teste jelenik meg, a bor felett elmondott szavak által pedig csak a Vére. Mindazonáltal a szent Testnek és a Vérnek ez a szétválasztása csak misztikus és nem valóságos különválás, mert az Úr emberi természetének természetes egysége folytán („per concomitantiam”) az Úr Teste nem lehet a Vére nélkül, sem a Vére a Teste nélkül. Ez a külön konzekrálás mégis azért történik, mert ez fejezi ki az Úr misztikus halálát, amennyiben itt megújul a keresztáldozat, hol az Úr vére kifolyt s így el volt választva a testétől. De mivel később az Úr teste a feltámadás által megdicsőült, a vér a testtel örökre egyesült, illő dolog, hogy a szentmisében ez az egyesülés illetve a dicsőséges feltámadás is szimbolizálva legyen. S ez történik a test és vér egyesítése által, amelyet itt méltán konzekrációnak nevezhetünk, mert amint az átváltoztatással a szentmisében megújul a keresztáldozat, vagyis a mi megváltásunk ténye, úgy az Úr testének és vérének egyesítése alkalmával megújul az Úr feltámadásának a ténye s abban a mi feltámadásunk reménye és biztosítéka. Ezért mondjuk a fenti imában, hogy ez az egyesülés és megszentelés „szolgáljon nekünk, kik azt magunkhoz vesszük, az örök életre”.<br><br>
Történeti teljesség kedvéért említsünk meg itt még röviden egy régi szokást, amelynek a mai liturgiában már semmiféle nyoma sincs. A régi misekönyvek tanúsága szerint ugyanis egyes egyházakban a Miatyánk és az Agnus Dei között zsoltárokat is énekeltek. Egy salzburgi misekönyv pl. 1555-ben a nagyböjti hétköznapokra előírja, hogy e helyen három zsoltárt kell elimádkozni a megfelelő antifónákkal és imádságokkal, mégpedig az elsőt a Szentföld visszafoglalásáért, a másodikat a pápáért, a harmadikat a királyért.<br><br>