Ezután megható jelenet következik a szentmisében. A pap térdet hajt, azután kezeit összeteszi, majd háromszor mellére ver, miközben kissé meghajolva e szép szavakat mondja:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Agnus   Dei, qui tollis peccata mundi: miserere nobis.<br><br>
Agnus   Dei, qui tollis peccata mundi: miserere nobis.<br><br>
Agnus   Dei, qui tollis peccata mundi: dona nobis pacem.</div>
    <div class="col-lg-4">
Isten   Báránya, ki elveszed a világ bűneit: irgalmazz nekünk.<br><br>
Isten   Báránya, ki elveszed a világ bűneit: irgalmazz nekünk.<br><br>
Isten   Báránya, ki elveszed a világ bűneit: adj nekünk békességet.</div>
</div>
E szavakat a Szentírásból vette az Egyház. Keresztelő Szent János ugyanis, mikor a Jordán mellett keresztelt, látta közeledni az isteni Üdvözítőt s az Úrra rámutatva, a hallgatósághoz így szólt: „Íme, az Isten Báránya, íme, aki elveszi a világ bűneit!” (Jn 1,29). A pap is közeledni látja azt a pillanatot, amikor az Úr őt a szentáldozásban meglátogatja, azért mély áhítatának jeléül összeteszi a kezét, majd bűnösségének tudatában a mellét veri s úgy üdvözli a Bárányt, aki megszabadítja az embereket a bűneiktől. Már Izaiás próféta bárányhoz hasonlította az isteni Üdvözítőt (53,7) s Keresztelő Szent János bizonyára erre a jóslatra célzott, mikor ezt a mélyértelmű kijelentést tette, mely most nap-nap mellett minden litánia végén elhangzik a papság és a hívek ajkán.<br><br>
Az Agnus Dei éneklését a szentmisében I. Sergius pápa (687-701) rendelte el (Lib. Pont. Ed. Duch. I. 376.). E rendelet szerint a papságnak és a népnek kellett azt énekelnie, mégpedig a szentostya megtörése idejében. Minthogy népének volt, nagyon egyszerű dallamra énekelték. A régi római Ordó-k nem említik, hogy hányszor kellett énekelni, de valószínű, hogy a régiek addig énekelték, míg a kenyértörésnek vége nem volt. Ez olykor elég hosszú ideig is tarthatott, mert abban az időben még nem ostyákkal áldoztattak s így elég hosszú időt vehetett igénybe, míg a közös kenyérből a hívek áldoztatásához szükséges partikulákat letördelték. A XI. századtól kezdve azonban már csak háromszor énekelték. A miséző pap ebben az időben még nem recitálta az Agnus Dei-t, hanem csak meghallgatta a nép és a segédkező papság énekét. Általában meg kell jegyeznünk, hogy régente azokat a szövegeket, amelyeket a kórus, vagy az asszistencia énekelt, a pap nem recitálta, hanem vagy hallgatta az éneket, vagy azalatt valami liturgikus cselekményt végzett. Az énekszövegeknek a pap által való recitálása csak akkor jött szokásba, mikor az énekes- és közösmise helyett csendes- és magánmisét kezdtek mondani, amelynél már nem mindig volt jelen a nép s így sokszor nem volt, aki énekeljen.<br><br>
Egész a XI. századig mind a három Agnus Dei-re az volt a válasz: Miserere nobis, Irgalmazz nekünk. Rómában a lateráni főszékesegyházban még ma is így mondják. Ma a harmadik Agnus Dei után a békéért könyörgünk. Ez a szokás már a XII. században megvolt. III. Ince pápa megjegyzése szerint (De altar. myst. 6. 4.) az Egyház nagy üldöztetés idején hozta azt be. Másrészről ez a kérés: „adj nekünk békességet” nagyon jó előkészület a békecsókra, mely közvetlenül ezután következik a szentmisében. Nagycsütörtökön régente a harmadik Agnus Dei után is Miserere nobis-t mondtak, mert e napon Júdás áruló csókja iránti utálat kifejezésére a szentmiséből elmaradt a békecsók. A békeköszöntés a nagycsütörtöki misében ma is elmarad, de a rendes Agnus Dei-t mondjuk. A nagyszombati szentmisében nincs Agnus Dei, még pedig valószínűleg azért nincs, mert ez a szentmise nagyon régi keletű, még abból az időből származik, amikor a szentmisében még nem volt Agnus Dei. Hogy később nem szúrták be, az Durandus szerint (Ration. 6. 85.) azért történt, hogy emlékeztessék a keresztényeket a Krisztus szenvedése idején szétszaladt apostolok gyönge hitére.<br><br>
A gyászmisében nincs békeköszöntés. Itt az Agnus Dei-t nem magunkra vonatkoztatjuk, hanem a megholtakra s azért az Agnus Dei után kérjük az Urat, hogy adjon nekik örök nyugodalmat. Az ambrozián-liturgiában csak a gyászmisében van Agnus Dei s ott a harmadik ismétlésnél hozzáfűzik: „és a könyörület helyét a te szenteiddel a dicsőségben”. <br><br>