A békéért mondott ima, illetve az ünnepélyes misében a békeadás után a misekánonban két szentáldozási ima következik. A pap ezeket az oltárra tett kezekkel kissé meghajolva imádkozza, miközben tekintetét a szentostyára függeszti s így mintegy az oltáron jelenlevő Jézust szólítja meg:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Domine   Jesu Christe, Fili Dei vivi, qui ex voluntate Patris, cooperante Spiritu   Sancto, per<br><br>
mortem   tuam mundum vivificasti: libera me per hoc sacrosanctum e Corpus et Sanguinem   tuum ab omnibus iniquitatibus meis et universis malis: et fac me tuis semper   inhaerere mandatis, et a<br><br>
te   nunquam separari permittas: Qui cum eodem Deo Patre et Spiritu Sancto vivis   et regnas Deus in saecula saeculorum. Amen.<br><br>
Perceptio   Corporis tui, Domine Jesu Christe, quod ego indignus sumere praesumo, non   mihi<br><br>
proveniat   in judicium et condemnationem: sed pro tua pietate prosit mihi ad tutamentum   mentis et corporis et ad medelam percipiendam. Qui vivis et regnas cum Deo   Patre in unitate Spiritus Sancti Deus, per omnia saecula saeculorum. Amen.</div>
    <div class="col-lg-4">
Uram   Jézus Krisztus, élő Isten Fia, ki az Atya akaratából, a Szentlélek   közreműködésével halálod által a világnak életet adtál: szabadíts meg engem   szentséges Tested és Véred által minden bűnömtől és minden rossztól: add,   hogy parancsaidhoz mindig ragaszkodjam és ne engedd, hogy tőled valaha   elszakadjak. Ki ugyanazon Atyaistennel és Szentlélekkel élsz és uralkodol,   Isten, mindörökkön örökké. Amen.<br><br>
Testednek   vétele, Uram Jézus Krisztus, melyet én méltatlan magamhoz venni bátorkodom,   ne legyen ítéletemre és kárhozatomra: hanem kegyességed szerint váljék az   nekem testem és lelkem oltalmára és lelkem gyógyulására. Ki élsz és uralkodol   az Atyával a Szentlélekkel egyetemben, Isten, mindörökkön örökké. Amen.</div>
</div>
Mindjárt feltűnik ezekben az imákban, hogy a pap csak egyes számban, vagyis csak magáért imádkozik („libera me”, „fac me”). A kánon többi imái általában a keresztény közösség imái s ezért a pap legtöbbnyire többes számban beszél, vagyis imájába a híveket, vagy legalább a segédkezőket is belefoglalja. Ebből is láthatjuk, hogy ez a két szentáldozási ima nem olyan régi, mint a kánon többi imádsága. A régi Egyház ugyanis a nyilvános istentiszteleteknél magánimákat nem ismert, hanem minden imát a keresztény egyházközség nevében, vagyis többes számban intézett az Úrhoz. Egy XI. századbeli író (Micrologus. 18. P. L. 151. 989.) megemlíti, hogy a régi Egyház csak a közös imákat szerette s hivatkozik szent Ince pápára, aki „a püspökökhöz írt levelében kifejti, hogy sokkal többet érünk el Istennél a közös és nyilvános, mint a magánimák által”.<br><br>
Tényleg ez a két szentáldozási ima a régi római Ordókban nem található. Régente ugyanis a békeadás után mindjárt a szentáldozás következett. Lassankint azután szokásba jött, hogy míg a békeadás és az Agnus Dei éneklése tartott, a pap az oltárnál magánimákat mondott előkészületül a szentáldozásra. Ezek az imák eleinte nagyon különbözők voltak. Később egy-egy szebb imát egyes püspökök egyházmegyéjük területére el is rendeltek, sőt a használatosabb imák itt-ott a misekönyvekbe is bekerültek. Bár a mi két áldozási imánk már a X. és XI. században is ismeretes, de kötelező nem volt, vagy legalább is szabad volt még más imákat is tetszés szerint hozzájuk csatolni. Még a XVI. század elején is azt írja egy szerző (Clichtovens, +1543), miután a mi misekönyvünk három szentáldozási imáját leközölte: „a miséző pap tetszése és buzgósága, vagy egyházának a szokása szerint más imákat is mondhat”. V. Pius pápa ezeket az imákat az 1570-ben kiadott s az egész Egyházra kötelezőleg előírt misekönyvbe felvette, azóta úgy a helyük, mint a szövegük változatlan.<br><br>
Ami a két imának a tartalmát illeti, megállapíthatjuk, hogy azok szentáldozás utáni imának is megfelelnek. Tényleg, egyes régi misekönyvekben ezek az imák, vagy legalább is hol az egyik, hol a másik a szentáldozás után, vagy a két áldozás között foglalnak helyet. A nagypénteki csonkamisében csak a Perceptio-ima található meg, valószínűleg azért, mert régibb keletű, mint a másik. Mind a két imát azonban már évszázadok áhítatos buzgalma megszentelte s nemcsak a miséző papnak, de a jámbor híveknek is kedves áldozási imájává tette. <br><br>