A hívek áldoztatása a mai római liturgia szerint a bűnvallomással, a Confiteor-nak az elimádkozásával kezdődik. Ez nem nagyon régi keletű szokás és valószínűleg a betegáldoztatás szertartásából került át a miseliturgiába. A betegek ugyanis nem a szentmise alatt áldoztak, így ők nem vettek részt a szentmise elején végzett bűnbánati imákban. Ezért előzte meg a betegek áldoztatását a Confiteor. Később azután, főleg a XIII. századtól kezdve, minden szentáldozás előtt mondották a Confiteor- t, még akkor is, ha az a szentmise alatt történt. Ez tulajdonképpen megismétlése a szentmise elején mondott Confiteor-nak.<br><br>
A bűnvallomás után a pap a következő szertartást és imákat végzi a hívek áldoztatása előtt:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Misereatur   vestri omnipotens Deus, et, dimissis peccatis vestris, perducat vos ad vitam   aeternam. Amen.<br><br>
Indulgentiam,   absolutionem et remissionem peccatorum vestrorum tribuat vobis omnipotens et   misericors Dominus. Amen.<br><br>
Ecce   Agnus Dei, ecce, qui tollit peccata mundi.<br><br>
Domine   non sum dignus, ut intres sub tectum meum, sed tantum dic verbo et sanabitur   anima mea.<br><br>
Corpus   Domini nostri Jesu Christi custodiat animam tuam in vitam aeternam. Amen.</div>
    <div class="col-lg-4">
Irgalmazzon   nektek a mindenható Isten, bocsássa meg vétkeiteket és vezessen titeket az   örök életre. Amen.<br><br>
Vétkeitek   elengedését, föloldozását és bocsánatát adja meg nektek a mindenható és   irgalmas Úr. Amen. <br><br>
Íme   az Isten Báránya, íme ki elveszi a világ bűneit. Uram, nem vagyok méltó, hogy   hajlékomba jöjj, hanem csak szóval mondd és meggyógyul az én lelkem.<br><br>
A   mi Urunk Jézus Krisztus Teste őrizze meg lelkedet az örök életre. Amen.</div>
</div>
A hívek áldoztatási módjáról meglehetősen sok adatunk van a régi időkből. Így a III-V. században az áldoztatópap, mikor a szent kenyeret és bort nyújtotta az áldozó hívőnek, e szavakat mondta: „Krisztus teste”, „Krisztus vére”. Erre a hívő hitének és hálájának a kifejezésére Amen-nel felelt (Eus. H. E. 6. 43.; Tert. De spect. 25.; Aug. c. Faust. 12. 10.). Ezt az Amen-t a hívek különös nyomatékkal ejtették ki s nagy jelentőséget tulajdonítottak neki. Tertullián, mikor megbotránkozásának ad kifejezést, hogy a keresztények a pogány színjátékokon résztvesznek, így ír: „Mit mondjak arról, aki az Isten társaságából az ördög társaságába megy?... Ha ugyanazzal a szájjal, amellyel a Legszentebb felé Amen-t kiáltott, a gladiátort üdvözli?” A VI. században, Nagy Szent Gergely idejében már ezt a szöveget használták: „A mi Urunk Jézus Krisztus teste őrizze meg a lelkedet” („conservet animam tuamn, Jo. Diac. Vita. S. Gr. 2. 41.). A hívek ma már nem felelnek Amen-t a szentáldozásnál. A régi szokásnak már csak egy maradványa van, tudniillik a papszentelésnél, mikor a nagyobb rendeket felvevő szentelendők még most is Amen-t felelnek az áldoztató püspöknek.<br><br>
A VIII. századból származó első római Ordo részletesen leírja az áldoztatás akkori szokását a pápa által végzett ünnepélyes misék alkalmával (c. 19. 20. P. L. 78. 945-47.). E szertartás lényege az, hogy a pápa két szín alatt megáldoztatta a vele együtt miséző papokat, azután a szentostyát nyújtotta a szerpapoknak. Ezre a segédkező papok megáldoztatták a szent Vérrel is a diákonusokat, majd a miséző és a többi pap nyújtották a népnek a szent kenyeret, míg a szent bor kiosztása a szerpapok kötelessége volt.<br><br>
A hívek régente általánosságban állva áldoztak. A régi görög Atyák (Jeruzsálemi Szent Cirill, Aranyszájú Szent János) kifejezetten állítják, hogy a hívek állva s lehajtott fejjel vették magukhoz a szent kenyeret és a bort. A keleti liturgiákban még most is állva áldoznak a hívek. De a nyugati egyházban is valószínűleg állva áldoztak, legalábbis bizonyos napokon. Vasárnapokon és a húsvéti időszakban ugyanis nem volt szabad térdelve imádkozni. Bona kardinális nagyon régi szokásnak tartja azt, hogy a pápai miséken a szerpap állva áldozik (i. m. II. 17. 8.). Nagyon valószínű azonban, hogy régente a böjti napokon, mikor térdelve szoktak imádkozni, a szentáldozásnál is térdeltek. Manapság már csak a miséző pap áldozik állva, más mindenki térdelve, még a papság is, ha nem misézik, hanem csak áldozik. Egyes helyeken a hívek mezítláb járultak a szentáldozáshoz (Vandeur. 283.). A régi írók gyakran említik (Tert. De idol. 7., Cypr. De laps. 26., Aug. c. ep. Parm. II. 7. 13.), hogy a pap az áldozó hívőnek nem a nyelvére, hanem a tenyerére tette az eucharisztikus kenyeret. A nőknek a szentáldozásnál fehér vászonkendővel kellett a kezüket betakarniok. Ezt a kendőt „dominicale”-nak hívták. Az 585 körül tartott auxerre-i zsinat elrendeli: „a nőnek tilos letakaratlan kézzel a szentáldozáshoz járulni” (Hefele. Conc.-Gesch. III. 46.). Valószínű azonban, hogy már Nagy Szent Gergely (+604) idejében fennállott a mai gyakorlat, vagyis hogy a hívek nyelvére tették a szentostyát (S. Greg. Dial. III. 3.). Mind a két szentáldozási mód használatban maradt évszázadokon keresztül. Szent Béda (+735) még említi, hogy a VIII. században a hívők tenyerébe adják a szentostyát, viszont a IX. századbeli V. római Ordó (P. L. 78. 994.) már a mostani áldoztatási módot közli.<br><br>
A mostani liturgia előírása szerint az áldozónak meg kell csókolnia a püspök kezét, illetve a gyűrűjét. Az ünnepélyes pápai misében a diákonus a szentáldozás után megcsókolja a pápa arcát. Általában a régi liturgiában a szeretetnek ilyenféle megnyilatkozása a szentáldozással kapcsolatban gyakran előfordul. A püspök kezének a megcsókolása a szentáldozás előtt vagy után nagyon régi szokás. Mikor Szent Melánia 439. dec. 31-én Rómában a szentáldozáshoz járult, megcsókolta a főpap kezét (Rampolla: St. Melania. 68. 39.).<br><br>
Meg kell még említenünk azt a régi szokást, hogy régente a szentáldozás után az áldozóknak bort, vagy vizet nyújtottak s egy kendőcskét, hogy az ajkukat megtöröljék (Vandeur. 284.). E szokásnak az volt a célja, hogy az áldozók a szent kenyeret (akkor még nem ostya volt) könnyebben le tudják nyelni és hogy a szent Vér minden részecskéje (akkor még két szín alatt áldoztak) lejusson a gyomorba. Ez a szokás -- mondhatni -- általános volt a latin egyházban egész a XV. századig. Ebben az időben szűnik meg ugyanis véglegesen a két szín alatt való áldozás a nyugati egyházban. Egyes helyeken, főleg a nagyobb ünnepeken, még a XVI. században is fennállott ez a szokás. Manapság már csak a papszentelési misében, a szerzetesek ünnepélyes fogadalmánál, a kartauziak és a domonkosok liturgiájában van hasonló szokás.<br><br>