A pap a csendes misében az oltár közepén az ünnepélyes misében pedig a leckeoldalon a segédkezőkkel felváltva imádkozza görög nyelven:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Kyrie   eleison. Kyrie eleison. Kyrie eleison.</div>
    <div class="col-lg-4">
Uram,   irgalmazz. Uram, irgalmazz. Uram, irgalmazz.</div>
</div>
<div class="row two_column">
    <div class="col-lg-4">
Christe   eleison. Christe eleison. Christe eleison.</div>
    <div class="col-lg-4">
Krisztus,   kegyelmezz. Krisztus, kegyelmezz. Krisztus, kegyelmezz.</div>
</div>
<div class="row two_column">
    <div class="col-lg-4">
Kyrie   eleison. Kyrie eleison. Kyrie eleison.</div>
    <div class="col-lg-4">
Uram,   irgalmazz. Uram, irgalmazz. Uram, irgalmazz.</div>
</div>
Legelsősorban az a feltűnő, hogy a pap ezeket a röpimákat görögül imádkozza. Görög nyelvű szöveg -- kivéve még a nagypénteki ún. improperiákat (Agios o Theos) nem is fordul elő többször a misekönyvben. A latintól eltérő nyelvű szöveg még a miseliturgiában a héber Amen, Alleluja, Sabaoth, Hosanna. Így az a három nyelv, melyen Krisztus keresztfájának a felirata (Jn 19,19) készült, a szentmisében is előfordul. A Kyrie eleison-t a görög tulajdonképpen Kyrie eleęson- nak ejti ki. A régi latinok azonban a görög é-t i-nek olvasták (pl. Paraclitus). Érdekes dolgot említ Martčne (I. 132.), hogy Alcuin szerint egy időben a görögök viszont latinul imádkozták a Kyrie eleison-t az egyébként görög szövegű misében.<br><br>
Tudvalevő dolog, hogy Rómában az őskeresztények görögül beszéltek. A katakombák legrégibb feliratai görög nyelvűek. Római Szent Kelemen az I. század végén görögül írt. Minthogy ezidőben még nem volt külön liturgikus nyelv, az istentiszteleteket is görög nyelven tartották. A latin nyelv liturgikus használata a II. században kezdődik Afrikában. Az ősegyház liturgiájának s a görög nyelvnek e szoros kapcsolatát ismerve egészen természetesnek kellene tartanunk azt a véleményt, mely szerint a mai miseszöveg görög részei az ősliturgiának maradványai. Ez a következtetés azonban a történeti adatok fényében helytelennek bizonyul. A Kyrie használatára ugyanis a nyugati egyházban a VI. század előtt semmiféle biztos adatot sem találunk. Bár ez a kérés: „Uram, irgalmazz” gyakran előfordul a Szentírásban (Mt 9,27; 15,22; 20,30; -- Mk 10,47; stb.), e formula liturgikus használatáról azonban sem az apostoli atyák, sem a II. századbeli apologéták, sem a IV. századbeli latin szentatyák nem tesznek említést. A Kyrie eleison valószínűleg Antiochiából származott (Fortescue. 306.). Itt ugyanis a mise előtt litániaszerű imát végeztek, amely a Kyrie eleison-nal végződött. Ezt a nézetet megerősíti az a körülmény is, hogy a Kyrie eleison liturgikus alkalmazásáról először az antiochiai származású Aranyszájú Szent János tesz említést. Ugyancsak az antiochiai egyház gyakorlatáról szól a Constitutiones apostolorum szerzője, mikor említi (VIII. 6.), hogy a diákonus könyörgésére a nép többször Kyrie eleisonnal felelt (Diction. d'archéol. VIII. 909.). Később a litánia elmaradt, csak a vége, a Kyrie eleison maradt meg a misében.<br><br>
Róma kétségtelenül keletről vette át a Kyrie eleison szokását. Valószínűleg itt is követték az antiochiai, illetve a konstantinápolyi szokást, hogy ti. a mise előtt -- legalább is bizonyos napokon -- litániát is énekeltek, amelynek vége a Kyrie eleison volt. Ezért a papszentelési misében nem mondott a pap a mise elején Kyrié-t, mert a graduale után a mindenszentek litániájával kapcsolatban úgyis kellett azt mondania (Duchesne. 174.). Erre a szokásra emlékeztet még a mai liturgiában is a nagyszombati szertartás, amikor is a mise előtt a kórus énekli a litániát s a végén a Kyrié-t és így a pap a mise elején nem mond Kyrie eleison-t.<br><br>
A nyugati egyháznak legrégibb adata a Kyrie eleison imádkozására vonatkozólag az 529-ben tartott második vaisoni zsinat (Hefele i. m. II.2 741.), mely a 3-ik kánonban elrendeli, hogy úgy a misében, valamint a Matutinumban és a vecsernyében többször mondják a Kyrié-t. Indokolásul felhozza a zsinat a római szentszék, valamint a keleti és az itáliai egyházak szokását. Ez a határozat mutatja, hogy a nyugati egyházak Rómától vették át ezt a szokást, továbbá, hogy abban az időben a Kyrie még Rómában is csak újabb keletű ima volt.<br><br>
A VI. sz. végén Nagy Szent Gergely pápa (590-604) tesz említést a Kyrie-ről. Szirakuzai Jánoshoz írt levelében (P. L. LXXVII. 956.) ugyanis tiltakozik azon vád ellen, mintha Róma utánozná a konstantinápolyi liturgiát. Rámutat arra, hogy a Kyrié-t a görögöknél közösen énekli a papság a néppel, míg Rómában a klérus énekli s a nép csak válaszol. Továbbá Rómában Christe eleison-t is énekelnek, míg ez a görögöknél nincs meg. Nagy Szent Gergely életrajzírója, Joannes Diaconus, e nagy pápának tulajdonítja a Kyrie Rómába való bevezetését. Ez azonban tévedés, mert hiszen -- mint láttuk -- a vaison-i zsinat szerint már a VI. század elején ismerték Rómában a Kyrié-t. Szent Gergely leveléből továbbá kitűnik hogy a mise előtti litániát a hétköznapi misében lassankint mindjobban elhagyták s a litániából csak a Kyrié-t hagyták meg. Később már a nagy ünnepeken is csak a Kyrié-t énekelték, úgy hogy nem sokkal azután általánossá vált az a ma is fennálló szokás, hogy a litániát csak nagyszombaton és pünkösd előtt levő szombaton, valamint a papszentelési misében imádkozzák.<br><br>
Az ambrozián liturgiában a Christe eleison nem szokásos, viszont a Kyrie eleison háromszor fordul elő a misében, mégpedig a Gloria, az evangélium és az ablutio után, minden egyes alkalommal három Kyrie. Nagy Szent Gergely idejében nem volt megállapítva, hogy hányszor kell a Kyrie-t énekelni. Addig énekelte a klérus, míg csak a püspök jelt nem adott, hogy abbahagyhatják. Avaison-i zsinat csak annyit mond, hogy a Kyrié-t „többször” kell énekelni. A IX. században a Kyrie-t már kilencszer éneklik, illetve három Kyrié-t mondanak az Atyaisten, három Christé-t a Fiú Isten és három Kyrié-t a Szentlélek Isten tiszteletére. Duchesne (i. m. 475-478.) a IX. századba teszi a Szent Amand által leírt Ordo Romanus szöveget, mely a Kyrié-re vonatkozólag ezt az utasítást adja: „Mikor az énekkar (scola) befejezte az antifóna éneklését, a püspök int, hogy mondják a Kyrie eleison-t. Erre a scola énekli a Kyrié-t, amelyet azután a szószék alatt álló regionáriusok (egyházi felügyelők) megismételnek. Mikor harmadszor is megismételték, a püspök int, hogy énekeljék a Christe eleison-t. És mikor már ezt is háromszor mondották, a püspök ismét jelt ad, hogy mondják a Kyrie eleison-t. A kilencedik ismétlés után a püspök int, hogy az éneklést abbahagyhatják”.<br><br>
Történeti szempontból érdekesek az ún. kitöltött Kyrie-k. A Kyrie eleison-t ugyanis már Nagy Szent Gergely idejében úgy énekelték, hogy minden egyes szótagra sok hangjegy esett, ami az éneket nagyon elnyújtotta. Ezt a középkorban igen hosszadalmasnak és fáradságosnak találták s azért a hangjegyeknek megfelelőleg szöveget iktattak a Kyrie és az eleison közé. Egy XVI. századbeli misekönyv megjegyzése szerint ez a beszúrás „a papok buzgóságának a kielégítésére” („ob nonnullorum Sacerdotum pascendam devotionem”, Bona III. 76.) történt. Az ünnepnapokra írt Kyrie-nek első három verssora pl. úgy hangzott (Bona III. 76.):<br><br>
 Kyrie, fons bonitatis, a quo cuncta procedunt, eleisont.<br><br>
Kyrie, qui pati natum mundi pro crimine, ipsum ut salvaret, misisti, eleison.<br><br>
Kyrie, qui septiformis das dona Pneumatis, a quo coelum et terra replentur, eleison. Stb.<br><br>
 Ezek a kitöltött Kyrié-k az V. Pius-féle misekönyvreformban (1570) teljesen megszűntek. Emléküket azonban a legújabban kiadott római Graduale is megőrzi, mikor az egyes Kyrie-knek ilyen címeket ad: Kyrie fons bonitatis, vagy Kyrie Deus sempiterne stb.<br><br>
Németországban a középkorban a Kyrie népének volt. Szent Bernát csodáinak a láttára a rajnavidéki német nép „Kyrie eleison, Christ uns genade” éneket énekelt. A német népénekek refrénjében gyakran fordul elő a Kyrie eleison s azért ezeket „Leisen”-nek, vagy „Kyrie- leisen”-nek nevezték. (Bäumer O. S. B. Kirchenlex. s. v. „Kyrie”.) <br><br>
