 A pap áldozása, illetve a hívek megáldoztatása után bort öntet a kehelybe, miközben így imádkozik:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Quod   ore sumpsimus, Domine, pura mente capiamus: et de munere temporali fiat nobis   remedium sempiternum.</div>
    <div class="col-lg-4">
Mit   ajkunkkal magunkhoz vettünk, add Uram, hogy tiszta szívbe fogadjuk és a földi   adományból legyen nekünk mennyei orvosságunk.</div>
</div>
Ezután a kehelyből a bort magához veszi. Majd a leckeoldalra megy, ott a kelyhet az oltár felett, mutató- és hüvelykujjait pedig a kehely felett tartva, azokra bort és vizet öntet e szavak kíséretében:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Corpus   tuum, Domine, quod sumpsi, et Sanguis, quem potavi, adhaereat visceribus   meis: et praesta; ut in me non remaneat scelecum macula, quem pura et sancta   refecerunt sacramenta: Qui vivis et regnas in saecula saeculorum. Amen.</div>
    <div class="col-lg-4">
Tested,   Uram, melyet magamhoz vettem és Véred, amelyet ittam, hassa át bensőmet és   add, hogy ne maradjon a bűnök szennye bennem, kit tiszta és szent Szentségek   megújítottak. Ki élsz és uralkodol örökkön örökké. Amen.</div>
</div>
Erre az oltár közepére visszatérve kezeit megtörli és a kehely tartalmát magához veszi.<br><br>
Ez a szertartás egyrészről a kehelynek, azután a pap ajkának és ujjainak a leöblítése, másrészről pedig hálaadás. Amíg ugyanis a pap az áldozat bemutatása után a használt szereket, a kelyhet és a paténát kiöblíti, illetve megtisztogatja, azalatt az Úr Jézus szentségi látogatásáért mond köszönetet.<br><br>
A kehely kiöblítéséről és az ujjak lemosásáról már a középkor elején olvasunk, így nevezetesen Bonitus, clermont-i püspök (+709) életrajzában, mely még a VIII. századból származik (Franz. 106.). Ebben az időben ez még nem lehetett általános szokás, mert az első római Ordó- k nem említik. A XI. századtól kezdve ez a kiöblítés, illetve lemosás nagyon elterjed, csak a módozatokban van különbség. Így Németországban bort, Franciaországban és Itáliában inkább vizet használtak. A VIII. Bonifác idejében (1294-1303) készült római Ordo (XIV. c. 53. P. L. 78, 1168.) szerint a pápa először a kehely fölött bort öntet az ujjaira, azután egy tál fölött vizet, amelyet azután nem a kehelybe, hanem a sacrarium-ba öntöttek. Ennek a szokásnak a maradványa az a kézmosás, amelyet a püspök a két ablutio után végez. Régente az egész kezet megmosták, ma már csak azokat az ujjakat, amelyekkel a pap a szentostyát érintette.<br><br>
Franz (105. sk.) nagyon érdekes adatokat hoz fel arra vonatkozóan, mily nagy tiszteletben részesítették az ablutio-vizet a középkorban. Az Oltáriszentség iránti mélységes hit ugyanis már a régi Atyák idejében is arra vezette a keresztényeket, hogy az Oltáriszentség érintésének gyógyító erőt tulajdonítsanak. Ahogy Jézus földi életében megérintette a betegeket s azok meggyógyultak, úgy az eucharisztikus Jézus érintésétől is ilyen eredményeket vártak. Alexandriai Szent Kelemen (Paedag. 2, 12.) és Jeruzsálemi Szent Cirill (Cat. m. 5, 21.) említik, hogy az ő korukban, tehát a III-IV. században az Eucharisztiával megérintették a szemeket, vagy az Oltáriszentség vétele után az ujjaikat az ajkukon megnedvesítették s azzal érintették szemüket, fülüket. Ugyanez a hit volt az alapjuk azoknak a középkori szokásoknak is, hogy a keresztények az ablutio-vizet megszerezték maguknak s azt a betegekkel megitatták, vagy azzal azok beteg testrészeit bekenték. A középkori szentek élettörténetében gyakran olvasunk olyan csodákról, amelyek az ablutio-vízzel való megérintés, vagy annak a megivása útján történtek. Így Szent Pius Sulpicius, Szent Eduárd angol király és Szent Odilo életében olvasunk ilyen csodálatos gyógyulásokról. Ezeket a gyógyulásokat az Oltáriszentségnek tulajdonították, mert hiszen az ablutio-vizet is csak azért tisztelték, mivel a pap azon ujjainak lemosásából származott, amelyekkel közvetlenül előtte az Oltáriszentséget érintette. Szent Bonitus püspökhöz nagy tömegben zarándokoltak a betegek, hogy az ablutio-vízből részesüljenek. Különösen sokan gyógyultak meg a XI. század közepén János, monte- cassinoi papnak a szentmiséjéből származó ablutio-víztől. Maga Lucca Anselm, a későbbi II. Sándor pápa is hozatott magának ebből a vízből s tapasztalta jó hatását. Németországban is általánosan hittek az ablutio- víz gyógyító erejében. Egy látomás által felbuzdulva egy vak asszony résztvett Szent Heribert, kölni érsek szentmiséjén és azzal a borral, amellyel a szent főpap az ujjait a szentáldozás után lemosta, megnedvesítette a szemét és visszanyerte látását. Franz nagyon sok hasonló esetet közöl a források megjelölésével (Die Messe, 109. sk.).<br><br>
A mai szentmisében a kehely kiöblítése idejében mondott ima, a Quod ore sumpsimus, egyik legrégibb ima a misekönyvben. Már az első mise- imagyűjteményben, a Leonianum-ban is megtaláljuk. Érdemes megfigyelnünk, hogy a tíz áldozási ima közül, amelyeket a mai misekánonban olvasunk, csak ezt az egyet mondja a pap többes számban („sumpsimus”). Már ez is mutatja ennek az imának régi eredetét. Régente közvetlenül a nép áldozása után mondták ezt az imát s „a földi adomány” („de munere temporali”) kifejezés az Oltáriszentségre mint ebben az életben legfőbb lelki táplálékunkra vonatkozott.<br><br>
Az ujjak leöblítése közben mondott Corpus tuum kezdetű ima már újabb keletű. A XI. században Rómában még nem ismerték. Későbbi eredetét mutatja az is, hogy az Úr Jézushoz intézzük, míg a régi római egyház inkább az Atyához imádkozott Jézus által. Eleinte ez is a nép áldozása után mondott hálaadó ima volt, csak később lett belőle ablutio-ima.<br><br>
Az említetteken kívül még más szép imákat is találunk egyes középkori misekönyvekben. Így egy XI. századbeli kéziratos misekönyvben e helyen ez a röpimaszerű szöveg áll, melyet háromszor kellett mondani: „Az ige testté lőn és mibennünk lakozék” (Ebner. 302.). Egy másik misekönyv szerint a pap a szentáldozás után így imádkozott: „Láttam az Urat szemtől-szembe s üdvözült a lelkem”. Máshol bizonyára az ablutiós víz csodás hatására gondolva, a pap az evangéliumi vak ember (Jn 9,11) szavait ismétli: „Sarat csinált az Úr nyálból, megkente szemeimet és elmentem és megmostam és láttam és hittem az Istennek”. A XI. században a pap e helyen még tetszésszerinti magánimákat is végezhetett (Microl. 18.). <br><br>