Már az Egyház első évszázadaiban szokás volt, hogy a híveknek nem volt szabad addig az istentiszteletről eltávozniok, míg erre a szertartást végző pap, vagy a diákonus fel nem szólította őket. Ez a szokás különben már a régi, pogány rómaiaknál is megvolt. Gyűléseken „Populis missio”, vagy „Discedite Quirites” szavakkal adtak jelt a távozásra. A temetési szertartásoknál „Ilicet” szóval („Ire licet”, „Eltávozhattok”) búcsúztatták el a jelenlevőket (Bona II. XX. 3.). A keresztény istentiszteleteken már a III. században, Tertullián és Szent Ciprián idejében szokás volt a szentmise végeztével a hívek liturgikus elbocsátása. A római egyházban már a legrégibb idő óta a következő formula volt használatban:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Ite,   missa est.<br><br>
Deo   gratias.</div>
    <div class="col-lg-4">
Menjetek,   itt az elbocsátás.<br><br>
Istennek   legyen hála.</div>
</div>
A többi egyházakban, úgy keleten, mint nyugaton, más formulák voltak szokásban. A görögöknél a diákonus így énekelt a nép felé: In pace procedamus (Távozzunk békével) s a nép ráfelelte: In nomine Domini (Az Úr nevében). Máshol a szerpap ezt énekelte: Ite in pace (Menjetek békével; Const. Ap., vö. Bona. i. h.). A gallikán liturgiában ezt a formulát találjuk: „Missa acta est”, a válasz „In pace” („A mise bevégződött” „Békével”, Duchesne. 240.). A VIII-IX. századból származó római Ordó-k már csak az „Ite, missa est” formulát közlik, mely ettől az időtől kezdve általános lett a nyugati egyházban.<br><br>
Az Ite missa est-nek már a régi időtől fogva igen gazdag, változatos s ünnepi dallama volt. Ezt a formulát énekelték minden szentmisénél, a böjti napokon éppúgy, mint a vasár- és ünnepnapokon. Később az ite missa est, talán éppen szép melódiája révén, vagy pedig a mise Glóriá- jával való kapcsolata miatt az örömnek, az ünnepélyességnek a kifejezésére szolgált. Így azután a XI. században már az adventben és a nagyböjtben s általában azokon a napokon, mikor nem volt Glória, nem mondták, hanem helyette Benedicamus Domino-t („Áldjuk az Urat”) énekeltek (Microl. 46.). Még egy másik ok is volt, ami a böjti napokon az Ite missa est elhagyását kívánta. Ezeken a napokon ugyanis a papság a mise után még zsolozsmát is imádkozott s az Egyház óhajtotta, hogy ez alatt az imádság alatt is jelen legyenek a hívek. Ezért a diákonus nem énekelte az elbocsátás formuláját („Ite”, „Menjetek”), hanem ellenkezőleg a Benedicamus-szal felszólította a jelenlevőket a továbbimádkozásra. Ugyanezen oknál fogva a gyászmisében sem mondtak Ite missa est-et, hanem „Requiescant in pacé”-t („Nyugodjanak békében”), mert a gyászmise után következett az absolutio, vagyis a megholt beszentelése. Sőt a középkorban még karácsony éjszakáján sem volt Ite missa est, hanem Benedicamus Domino, mert az éjféli mise után mindjárt a Laudest imádkozták.<br><br>
A VIII. században a pápai misében (Ordo R. I. 21. P. L. 78. 948.) a pápa kiválasztott egyet a segédkező diákonusok közül s annak be kellett várnia, míg a pápa intett, hogy az Ite missa est-et elkezdheti. Verdunben igen megható szertartás volt szokásban (Vandeur. 294.). A diákonus térdre ereszkedve a pap előtt, megkapta az Ite missa est-et, megcsókolta a miseruhát és Deo gratias-t válaszolt. Ezután felállt és a nép felé fordulva elénekelte az Ite missa est-et. Még ma is megvan az a szokás, hogy a pap is a nép felé fordul, mikor a diakónus az Ite missa est-et énekli. Ezáltal a pap azt fejezi ki, hogy a diákonus az ő nevében mondja a híveknek a búcsúszót. A pap halk hangon nem is mondja az Ite missa est-et, míg a Benedicamus Dominó-t és a Requiescant in pacé-t a papnak is kell mondania (C. R. 1816. szept. 7.), mert ez utóbbiak imádságok, míg az Ite missa est tulajdonképpen csak utasítás. A „missa” szón nem misét kell érteni, hanem „missió”-t, vagyis elküldést, elbocsátást. Már a IX. században lyoni Florus is így magyarázza (Fortescue. 517.). Ezért tehát az Ite missa est-et nem szabad így fordítani: „Menjetek, a misének vége van”, hanem úgy, ahogy azt mi fentebb fordítottuk. <br><br>