Úgy az ünnepélyes, mint a csendes szentmise az utolsó evangélium elmondásával végződik. A legtöbb szentmisében szent János evangéliumának első oldala (1,1-14) az utolsó evangélium, mely így hangzik:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
In   principio erat Verbum et Verbum erat apud Deum, et Deus erat Verbum. Hoc erat   in principio apud Deum. Omnia per ipsum facta sunt: et sine ipso factum est   nihil, quod factum est: in ipso vita erat, et vita erat lux hominum: et lux   in tenebris lucet et tenebrae eam non comprehenderunt. Fuit homo missus a   Deo, cui nomen erat Joannes. Hic venit in testimonium, ut testimonium perhiberet   de lumine, ut omnes crederent per illum. Non erat ille lux, sed ut   testimonium perhiberet de lumine. Erat lux vera, quae illuminat omnem hominem   venientem in hunc mundum. In mundo erat, et mundus per<br><br>
ipsum   factus est, et mundus eum non cognovit. In propria venit, et sui eum non   receperunt. Quotquot autem receperunt fieri, his, qui credunt in nomine ejus:   qui non ex sanguinibus, &nbsp;neque ex   voluntate carnis, neque ex voluntate viri, sed ex Deo nati sunt. Et verbum   caro factum eum, dedit eis potestatem filios Dei est et habitavit in nobis:   et vidimus gloriam ejus, gloriam quasi Unigeniti a Patre, plenum gratiae et   veritatis.</div>
    <div class="col-lg-4">
Kezdetben   volt az Ige és az Ige Istennél volt és Isten volt az Ige. Ez volt kezdetben   az Istennél. Mindenek ő általa lettek és nála nélkül semmi sem lett, ami   lett. őbenne élet volt és az élet volt az emberek világossága. És a   világosság a sötétségben világít, de a sötétség azt föl nem fogta. Volt egy   Istentől küldött ember, kinek neve volt János. Ez bizonyságul jött, hogy   bizonyságot tegyen a világosságról, hogy mindnyájan higyjenek általa. Nem   volt ő a világosság, hanem hogy bizonyságot tegyen a világosságról. Igaz   világosság volt, mely megvilágosít minden e világra jövő embert. E világon volt   és a világ ő általa lett és a világ őt meg nem ismerte. Tulajdonába jött, de   övéi nem fogadták be őt. Mindazoknak pedig, kik befogadták őt, hatalmat   adott, hogy Isten fiaivá legyenek, azoknak, kik az ő nevében hisznek, kik nem   vérből, sem a test ösztönéből, sem nem a férfiú akaratából, hanem az Istentől   születtek. És az Ige testté lőn és mibennünk lakozék. És láttuk az ő   dicsőségét, mint az Atya egyetlenegy Szülöttének dicsőségét, telve malaszttal   és igazsággal.</div>
</div>
Szent János, a szeretet apostola, ebben a gyönyörű szövegben az Úr Jézus istenségéről szól. A második isteni személy, az Ige öröktől fogva létezik, egylényegű az Atyával, aki az Ige által teremtett mindent, ami van. Az Ige, aki maga az élet és a világosság, az idők teljében testté lőn és miköztünk lakozék, hogy bennünket Isten fiaivá tegyen.<br><br>
Ez a szentírási részlet már a régi Egyházban a keresztények előtt nagy becsben állott. Már Szent Ágoston idejében (De civ. Dei. 10. 29.) egy platonikus bölcselő azt a kijelentést tette, hogy Szent János e mélyértelmű szavait arany betűkkel kellene felírni minden templom falára. A középkorból sok adat bizonyítja, hogy a keresztények igen nagy, szinte babonaságig menő tisztelettel viseltettek e szöveg iránt. Pergament lapokra leírták s nyakukban hordozták, vagy a betegek fejét megérintették vele. Máshol a gonosz lélek támadásai ellen védőpajzsul szolgált. Elemi csapások, vihar elhárításáért végzett szertartásokban előfordult ez a szöveg. Egész a XII. századig visszavihető az a szokás, hogy -- mint manapság is a búzaszentelési szertartásnál -- a termények megáldásánál énekeljük Szent János e sorait.<br><br>
A keleti liturgiákban még ma sincs utolsó evangélium. A római liturgiában is csak a XIII. századtól kezdve jön szokásba. A pap eleinte ezt az evangéliumi szakaszt a sekrestyében a szent ruhák levetése közben, vagy pedig útközben az oltártól a sekrestyéig mondotta. A jámbor hívek kívánságára a pap olykor még az oltárnál is imádkozta azt, sőt egyes misealapítványok ezt kifejezetten ki is kötötték. E szokás azután nagyon gyorsan elterjedt, mert hiszen a pap és a hívek semmit sem imádkozhattak volna alkalmasabban a szentáldozás után, mint az Úr Jézus istenségéről és kegyelemteljes megtestesüléséről írt e gyönyörű sorokat. V. Pius pápa a reformált misekönyv kiadásánál már csak az általános szokást rögzítette meg, mikor e Szent János- szöveget a szentmise előírt szövegéhez csatolta.<br><br>
A ministráns az utolsó evangélium végén Deo gratias-t mond s ezzel kifejezést ad a hívő lelkek hálájának az isteni Gondviselés iránt, hogy az újszövetség fenséges áldozatában részesülhettek. A pap a csendes misék után még előimádkozza a XIII. Leó és X. Pius pápák által elrendelt imákat (3 Üdvözlégy, Salve Regina és a könyörgések), ezek azonban már nem tartoznak a szorosan vett szentmise szertartásához. <br><br>