A pap méltóságteljes mozdulattal az ég felé emeli kezeit s ajkán felcsendül az egyház évezredes dicsőítő imája, a Gloria. Ez az ima négy részből áll. Az első rész a Krisztus születésénél megjelent angyalok dicsőítő éneke (Lk 2,14), a következő három rész pedig az Atya, Fiú és Szentlélek Isten dicsőségét zengi.<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Gloria   in excelsis Deo. Et in terra pax hominibus bonae voluntatis.<br><br>
Laudamus   te. Benedicimus te. Adoramus te. Glorificamus te.<br><br>
Gratias   agimus tibi propter magnam gloriam tuam. Domine Deus, Rex caelestis, Deus   Pater omnipotens.<br><br>
Domine   Fili unigenite, Jesu Christe. Domine Deus, Agnus Dei, Filius Patris. Qui   tollis peccata mundi, miserere nobis. Qui tollis peccata mundi suscipe   deprecationem nostram. Qui sedes ad dexteram Patris, miserere nobis. Quoniam   tu solus Sanctus. <br><br>
Tu   solus Dominus. Tu solus Altissimus, Jesu Christe.<br><br>
Cum   Sancto Spiritu in gloria Dei Patris. Amen.<br><br>
</div>
    <div class="col-lg-4">
Dicsőség   a magasságban Istennek. És békesség a földön a jóakaratú embereknek.<br><br>
Dicsérünk   téged. Áldunk téged. Imádunk téged. Dicsőítünk téged. <br><br>
Hálát   adunk neked nagy dicsőségedért. Úr Isten, mennyei király, mindenható   Atyaisten. <br><br>
Úr   Jézus Krisztus, egyszülött Fiú, Úr Isten, Istennek Báránya, az Atyának Fia.   Ki elveszed a világ bűneit, irgalmazz nekünk. Ki elveszed a világ bűneit,   fogadd el könyörgésünket. Ki az Atya jobbján ülsz, irgalmazz nekünk. <br><br>
Mert   egyedül te vagy Szent. Egyedül te vagy Úr. Egyedül te vagy végtelen Fölség,   Jézus Krisztus.<br><br>
A   Szentlélekkel együtt az Atyaisten dicsőségében. Amen.</div>
</div>
Ennek a gyönyörű himnusznak a keletkezése, sajnos, homályba vész. Annyi kétségtelen hogy a keleti egyház a hazája s hogy eleinte görögül imádkozták. Az ősegyház ugyanis csak zsoltárokat énekelt. De már a II. században feltűnnek egyes magánzsoltárok, vagy magánhimnuszok, amelyek a zsoltárok mintájára a keresztény igazságokat foglalták egybe s énekeltették a néppel. Ezek a kezdet kezdetén csak rögtönzött imák, énekek voltak, később mindinkább állandósultak, lassankint már meghatározott szöveggel bírtak. Ezek között az imák között a legszebb és leghasználatosabb a Gloria volt.<br><br>
A Gloria ősrégi, patinás szöveg. A benne előforduló kérésekkel gyakran találkozunk a legrégibb prefációkban, miseimákban, himnuszokban. Ez a szöveg bennünket a liturgikus nyelv forrásához vezet el. „Nincs benne egy formula sem, amely elütne a legrégibb szerzők stílusától, egy kifejezés sem, amelyet ne írhattak volna az első vagy a második században”. (Cabrol. Le livre etc. 153.)<br><br>
Amint a Te Deum, úgy a Gloria is valószínűleg több imának az összeolvasztásából keletkezett. Bizonyára az első részt, az angyalok szavait kezdték el legelőször az Isten dicsőítésére használni. Hiszen ha Istent dicsérő éneket kerestek, az angyalok karácsonyéji éneke e célra legalkalmasabb volt. A keleti liturgiák még ma is csak az angyali éneket mondják a Gloriában a Szentháromságot magasztaló további három rész nélkül. Így pl. szent Jakab liturgiájában ez a rövid Gloria háromszor fordul elő. A Gloria többi része -- természetesen sokkal rövidebb alakban -- a legrégibb görög egyház dicsőítő éneke volt. Keletkezését még a II. század első felébe tehetjük. (Cl. Blume. St. a. Maria-Laach. LXXIII. 58.) Ez a dicsőítő ének akkor még csak általánosságban az Istenről szólt. A III-IV. század hitvitái idejében a Gloria-szöveget kissé átalakították, hogy a hívek hitéletének előterébe került keresztény igazságok, főleg Krisztus istensége, benne kifejezést találjanak. A Szentlélekről aránylag csak rövid szöveg szól a Gloria- ban. Ez is mutatja, hogy a Gloria olyan idők terméke, amelyekben csak az Atya Isten és az ő egyszülött Fia, a világ megváltója fordultak elő gyakran a keresztények imádságában. Csak a IV. század eretnekségei által hívta fel a Gondviselés a keresztények figyelmét a Szentlélek Istenre.<br><br>
Nincs rá bizonyítékunk, hogy régente keleten a Gloria a miseliturgia része lett volna. Szent Athanáz (+373) egyik művében, melynek eredetiségét újabban mindig szélesebb körben kezdik elismerni (De virg. c. 20.) megparancsolja, hogy a szüzek pirkadatkor énekeljék a Gloriá-t: „Az Úr összes teremtményei dicsérjétek az Urat. Dicsőség a magasságban Istennek és békesség a földön, megelégedés az embereknek. Dicsérünk téged, áldunk téged, imádunk téged stb.” Ez a „stb.” mutatja, hogy Szent Athanáz nem tartotta szükségesnek a Gloria szövegét egészen leírni, mert feltételezte, hogy a keresztények kívülről tudják. Másrészről, mi nagyon sajnáljuk a szövegnek ezt a megszakítását, mert hiszen ez a szöveg lenne a ránk maradt legrégibb adat a Gloria görög szövegéről.<br><br>
Hogyan származott át a Gloria a nyugati egyházba? Alcuin, tours-i apát (+804) szerint a Gloria szerzője Szent Hilarius poitiers-i püspök (+366 vagy 367). Ugyanezt állítják auxerre-i Remigius (+908 körül), autun-i Honorius (+1130 körül) és mások. Ezek azonban mind franciaországi írók, akik ebben a kérdésben elfogultaknak látszanak. Tours és Poitiers szomszédos egyházmegyék, így nem csoda, ha Alcuin s a kétségkívül reája támaszkodó többi szerzők örömmel látják szent Hilariusban ennek a nagyszerű himnusznak a szerzőjét (Blume i. m. 45.), pedig már csak azért sem tarthatjuk a Gloriá-t szent Hilarius művének, mert akkor sokkal élesebben ki volna benne domborítva a Fiú Isten egylényegűsége az Atyával. Szent Hilarius, aki annyit küzdött az arianizmus ellen, bizonyára nem mulasztotta volna el ezt az alkalmat a Fiú istenségének a megvallására. A tudós cisztercita kardinális, Bona János, (+1674) nagyrészt helytálló érvekkel kimutatta, hogy Szent Hilarius csak fordítója lehetett a Gloria-nak, mert ennek keleten van a hazája. Szent Hilarius száműzetésben volt keleten, honnan 360-ban tért vissza Galliába. Valószínű, hogy ő hozta magával a Gloriá-t Európába s hogy ő fordította azt le latinra. Így a Gloria elterjesztése a nyugati egyházban az ő nevéhez fűződött. Innen származott Alcuin tévedése a szerzőséget illetőleg.<br><br>
A Gloria keletkezésére vonatkozólag egy másik hagyomány is van a nyugati egyházban, mely azonban kétségtelenül helytelen nyomokon jár. III. Ince pápa (+1216) ugyanis ezt állítja: „Telesphor, Szent Péter után a kilencedik pápa (kb. 125-136) meghagyta, hogy ezt a himnuszt az Úr születésének ünnepén az ő általa elrendelt éjféli misén énekeljék. Az angyal szavaihoz ő fűzte hozzá a további szavakat. Egyesek ugyan azt állítják, hogy azokat Szent Hilarius a poitiers-i püspök fűzte hozzá”. (De s. alt. myst. 2. 20. M. P. L. CCXVII. 810.). Ez a hagyomány azonban téves. A Telesphor pápa rendeletének a régi Sacramentarium-okban semmi nyoma sincs. Ez a téves vélemény, hogy Telesphor pápa lenne a Gloria szerzője, csak a IX. században tűnik fel (Blume i. c. 46.). Durandus (Rationale, IV. 13.) úgy próbálta a Gloria keletkezéséről szóló kétféle hagyományt egyesíteni, hogy Telesphor pápa rendelte volna el az angyalok szavainak a recitálását, míg a Gloria többi része (Laudamus te szavaktól kezdve) Szent Hilariustól származnék. Nézetének a támogatására azonban nem tud elfogadható történeti érveket felhozni.<br><br>
A Gloria szövege a további századokban nem ment át nagyobb változásokon. Annál változatosabb azonban a Gloria beillesztése az egyes ünnepek liturgiájába. A Liber Pontificalis szerint Symmachus pápa (498-514) „elrendeli, hogy a Gloria in excelsis himnuszt énekeljék minden vasárnap és a vértanúk ünnepnapjain”, mégpedig a Kyrie után, de csak a püspök által bemutatott misében (Ed. Duchesne 1. 263.). A VIII. századbeli Ordo Romanus I. ismeri a Gloriát, de feltételezi, hogy nem gyakran éneklik. A pápa olyankor intonálja, „ha van még idő”. (M. P. L. LXXVIII. 942. nota h.) Eleinte tehát csak a püspökök mondták a Gloriá-t. A papok ugyanazon Ordo szerint csak húsvét ünnepén mondhatták. Szent Amandus Ordo-ja szerint mondhatták még húsvét vigíliáján és pappá való szentelésük napján is (Duchesne. Origines. 497.). Ez a szokás fennáll még a XI. században is, amikor is reichenau- i Berno panaszkodik e megszorítás miatt s kérdezi, miért nem szabad pl. karácsonykor Gloriá-t mondani, hiszen ezen az ünnepen e himnusz igazán helyénvaló lenne? (P. L. CXLII. 1059.; Fortescue i. m. 321.) Viszont a Micrologus, amely szintén a XI. században keletkezett, így ír: „Minden ünnepen, melynek teljes officiuma van, kivéve az adventi és nagyböjti (hetvenedvasárnap utáni) időszakot s az aprószentek ünnepét, úgy a papok, mint a püspökök, Gloria in excelsis-t mondanak”. (M. P. L. CLI. 979.) A XII. században már az adventben is mondták a Gloria-t. (Ordo R. XI. 4. P. L. LXXVIII. 1027.) Ekkor ugyanis az adventnek még nem volt bűnbánati jellege.<br><br>
A mostani misekönyvben (pl. a Pustet-féle 1908-ban megjelent misekönyvben) a Gloria szövege után ezt az utasítást találjuk: „Így kell mondani a Gloria in excelsis Deo-t a Szűz Máriáról szóló misékben is, valahányszor csak mondani kell”. Ennek az utasításnak történeti háttere van. Régente ugyanis nemcsak „kitöltött” Kyrié-k, hanem „kitöltött Gloriá-k is voltak. Így különösen a boldogságos Szűzről szóló Gloria igen sokfelé használatos volt. Ilyen pl.: „Filius Patris, primogenitus Mariae virginis”; „Suscipe deprecationem nostram, ad Mariae gloriam”; „Quoniam tu solus Sanctus, Mariam sanctificans; tu solus altissimus, Mariam coronans”. Ezek a betoldások a többszöri tiltó rendeletek ellenére is szokásban maradtak egészen az V. Pius misekönyvreformjáig, 1570-ig. Így került bele a reformált misekönyvekbe a fenti rubrika, amelynek manapság már semmiféle gyakorlati célja nincs. Az utóbbi években megjelent misekönyvekben ezt a rubrikát már nem találjuk.<br><br>
A Gloriát a VIII. században a nép felé fordulva intonálta a pap. Az Ordo Romanus I. így szól: „A Kyrie eleison elvégzése után a főpap a nép felé fordul s elkezdi a Gloriá-t, majd rögtön visszafordul kelet felé (vagyis az oltár felé), míg csak a Gloria véget nem ér”. (n. 9. M. P. L. LXXVIII. 942.) A pap a Gloria intonálásánál bizonyára azért fordult a nép felé, hogy ezáltal is felhívja őket az Istent dicsőítő énekben való részvételre. A IX. században már az oltár felé fordulva énekli a pap a Gloriá-t, még pedig a lecke-oldalon, mint azt Amalarius (+857 körül) megjegyzi. (Vö. De eccl. offic. 1. 3. c. 8.) Ez a szokás valószínűleg abból eredhetett, hogy a Gloriá-t -- mint ahogy a Kyrié-t is -- a misét előkészítő körmenethez és litániához tartozandónak vették s így nem tartozott a szorosan vett miseliturgiához. A mai szokás, hogy az oltár keresztje előtt énekli, illetve recitálja a pap a Gloriá-t, e himnusz rendeltetésének sokkal jobban megfelel.<br><br>
A Gloria történeténél miért ne említenénk meg, hogy Róma városának kedvelt szentje, Néri Szt. Fülöp halála napján (1595. máj. 26.), mely éppen Úrnap-ja volt, utolsó szentmiséjének Gloriá-jánál elragadtatásba esett s valami mennyei boldogsággal énekelte az angyali himnuszt (Gihr. i. m. 354.). Az Egyház is lelkesedésének és művészetének minden varázsával törekedett a szentmise Gloriá-ját a teremtmények Isten előtti imádságos hódolatának középpontjává tenni. <br><br>