1. Graduale.<br><br>
A lecke és az evangélium között a miseszöveg néhány zsoltárverssort tartalmaz, amelyek látszólag csak átmenetek az egyik szentírási részlet olvasásától a másikig. A történeti kutatás azonban megállapította, hogy ezek a zsoltárénekek már a legrégibb időben is nagyon fontos részei voltak a szentmise liturgiájának. Ez a szokás, ti. a zsoltáréneklés a szentírásolvasás után, Duchesne szerint (Origines. 179.) „egyenes vonalban származik le hozzánk a zsidó zsinagóga vallási gyakorlataiból”. Míg a többi miseénekek: a Kyrie, offertorium, communio, csak az időközöket töltötték ki s egyes hosszabb szertartások, körmenetek alatt a nép figyelmét tartották ébren, addig a graduale-t önmagáért énekelték. Miért is a graduale alatt a klérus semmiféle szertartást nem végzett, hanem csak figyelt az énekre.<br><br>
Mielőtt a graduale változatos és érdekes történetének elmondásába kezdenénk, röviden szólnunk kell az egyházi ének jelentőségéről az ősegyházban. Máté evangélista (26,30) tanúskodik arról, hogy már az Úr és az apostolok is énekeltek szent énekeket. Így egészen természetes, hogy Szent Pál apostol így buzdítja az efezusi híveket: „Magatok között zsoltárokat, szent dalokat és lelki énekeket mondjatok, énekeljetek”. (5,19) A régi keresztények tényleg nagyon szerettek énekelni. Úgy a nyugati (Ambros. Praef. in Ps. n. 9.) mint a keleti egyházban (Chrys. In. Ps. 41.) a hívek áhítata gyakran szállt lélekemelő zsoltáréneklésben az ég felé. Mily szép lehetett a keresztények éneke, ha Szent Ágoston öreg korában „Vallomásai”-ban így írhat: „Mennyi könnyem elfolyt akkor himnuszok és zsoltárok éneklése közben! Mélyen meghatottak a templomban édesen csengő énekek. Beözönlöttek a hangok füleimbe, szívemre rászállt az igazság harmata, kigyulladtak bennem a jámbor érzések, megeredtek könnyeim -- s a könnyek igen jól estek nekem”. (9. 6.) A zsoltárokat a régi egyházban különböző módon énekelték. Szent Vazul (+379) szerint olykor két részre oszlott a nép és a két csoport felváltva énekelte a zsoltárverseket. Más alkalommal pedig választott előénekesek után énekelték a hívők vagy az előénekelt szöveget, vagy csupán egyes refréneket. Ez utóbbi éneklési mód, úgy látszik, a zsidóknál is szokásban volt, mert a 135-ik zsoltár folyton megismétlődő refrénje („mert örökkévaló az ő irgalmassága”) erre enged következtetni.<br><br>
A lecke és az Evangélium között az Egyház két éneket énekeltet, ti. a graduale-t és az Alleluja-t, ez utóbbit néha felváltja a tractus. Nézzünk egy példát. Advent első vasárnapján a lecke után ezt olvassuk:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Graduale.   Ps. 24. Universi, qui te exspectant, non confundentur, Domine.</div>
    <div class="col-lg-4">
Átmenetre   való ének 24. zs. Mert aki benned bízik, nem vall gyalázatot.</div>
</div>
<div class="row two_column">
    <div class="col-lg-4">
V.   Vias tuas, Domine, notas, fac mihi: et semitas tuas edoce me.<br><br>
Alleluja,   alleluja.</div>
    <div class="col-lg-4">
V.   Utaidra taníts meg, Uram, oktass meg engem ösvényeidben. <br><br>
Alleluja,   alleluja.</div>
</div>
<div class="row two_column">
    <div class="col-lg-4">
V.   Ps. 84. Ostende nobis, Domine, misericordiam tuam: et salutare tuum de nobis.   Alleluja.</div>
    <div class="col-lg-4">
V.   84. zs. Engedd, Uram irgalmad látnunk és hozd el már szabadulásunk. Alleluja.</div>
</div>
Ez a szöveg tulajdonképpen két énekrészből áll. Az első rész a két zsoltárversből álló graduale, a másik rész az ún. Alleluja, vagyis a három Alleluja közé zárt zsoltárvers. Ennek a kettős éneknek az az eredete, hogy a régebbi időben két lecke volt. Az első a prófétákból s ez után énekelték a graduale-t, a második az újszövetségi szentírásból s ezt követte mint előkészület az evangéliumra az Alleluja-ének. Az ambrozián-misében még ma is ezt a szokást találjuk. Sőt a római misekönyvben is, mikor két lecke van, pl. a kántorböjtök szerdáin akkor az egyik lecke után van a graduale, a másik lecke után pedig az Alleluja-éneket helyettesítő tractus. Mikor a római liturgiában később az egyik lecke elmaradt, a két éneket egybekapcsolták.<br><br>
Már a zsinagógában szokás volt, hogy a szentírásolvasás után az imádságos hangulat fokozására és az egyhangúság kiküszöbölésére zsoltárokat énekeltek. Ezt a szokást bizonyára a keresztények is átvették, mert már Tertullián (De anima. 9.) említi, hogy a leckék között zsoltárokat szoktak énekelni. Szent Ágoston szerint a lecke után egy egész zsoltárt elénekeltek (Sermo 176. 1.), legalább is ha a zsoltár rövid volt. Szent Ágoston egy alkalommal mentegeti magát a nép előtt, mikor a lector egy hosszú zsoltárt végigénekelt (Exp. 138. Ps. Schuster. I. 92.). A VI. században Rómában a szerpapok vezették a zsoltáréneklést. A római katakombákban talált síremlékeken itt-ott mint a diákonusok életének egyik legjellegzetesebb ténykedése szerepel az előéneklés a zsoltározásnál. Deusdedit diákonus sírfelirata (V. sz.) pl. így szól:<br><br>
 Hic levitarum primus in ordine vivens Davitici cantor carminis ipse fuit. (De Rossi. Roma sott. III. 242; Duchesne. 180.)<br><br>
 A szerpapok zsoltáréneklését Nagy Szent Gergely szüntette meg az 595- iki zsinaton. Ettől kezdve már csak az evangéliumot éneklik a szentmisében. A zsoltár azonban ezután is csak szólóének marad, melyet a kórus, vagy a nép csak kísér.<br><br>
A lecke utáni zsoltárt régente az ambon legalsó lépcsőjéről énekelte a diákonus, innen a gradale vagy graduale név (lépcsőének), mely már a Sacramentarium Gregorianum-ban is előfordul, bár még a IX. században is használták a régi „responsorium” nevet (Batiffol. Leçons. 131.). Később nagyon különböző szabályok voltak a graduale éneklésének a helyét illetőleg. Beleth János szerint a hétköznapokon az oltár legalsó lépcsőjén, ünnepnapokon pedig a legfelső lépcsőn énekelték (Div. off. exp. 38. P. L. CCII. 46.).<br><br>
Eleinte az egész zsoltárt végigénekelték. Még Nagy Szent Leó pápa (440-461) így ír: „Dávid zsoltárát elénekeltük egyhangon” (Sermo III. in anniv. assumpt. P. L. LIV. 145.). Később az istentiszteletek igen hosszúra nyúltak s ezért a pápák a hívek érdekében törekedtek azokat a lehetőség szerint egyszerűsíteni és rövidíteni. Így Nagy Szent Gergely pápa Antiphonarium-a (P. L. LXXVIII. 641.) már csak két verssort énekeltet a zsoltárból a lecke után, ahogy az manapság is szokásos. A mai misekönyvben nem is mindig zsoltárverset találunk a gradualeban. Így a Szeplőtelen-fogantatás ünnepén Judit könyvéből, többször pedig (pl. Szűz Mária látogatásának az ünnepén, júl. 2-án) nem is a Szentírásból, hanem máshonnan vett szöveget olvastat, illetve énekeltet az anyaszentegyház.<br><br>
2. Alleluja.<br><br>
Az Alleluja zsidó szó, mely annyit jelent, hogy „dicsérjétek az Istent”. Használata az ószövetségi zsidóknál is elég gyakori volt. A zsoltárokban is sokszor előfordul, mint a diadalmas öröm kifejezése, így a 104., 105., 106., 134-ik zsoltárban. Különösen helyénvaló a használata az ún. hallel-zsoltárokban (113-118.). A keresztények lefordítás nélkül vették át az Alleluját, amellyel szintén az Isten dicséretét s az Istent szerető lélek boldogságát akarták kifejezni. Szent János apostol a mennyország diadalmas Allelujá-ját így írja le: „És mint egy nagy sereg szózatát hallám, és mint sok vizek zúgását, és mint nagy mennydörgések hangját, amint így énekeltek: Alleluja!” (19,6) A régi keresztényeknél nagyon használatos volt nemcsak az istentiszteleteknél, hanem a munka végzése közben is. Kint a mezőn a nehéz földmunkánál, vagy a hajón a keresztény matrózok ajkán gyakran felcsendült az örömteli Alleluja, melyet a partok visszhangoztak (Respondentibus ripis, Sidon. Apollin. l. 2. ep. 10.). 429-ben a bretonok Alleluja-kiáltással mentek a harcba. (Uo.). Az V. században a vandalok betörtek Afrikában egy templomba s nyíllal átlőtték a lector nyakát épp abban a pillanatban, mikor az ünnepi Allelujá-t énekelte (Cabrol. 63.).<br><br>
Az Alleluja használata keleten a régi időben is sokkal gyakoribb volt, mint nyugaton. A görögök ma is még a nagyböjtben és a gyászmisében is éneklik az Alleluja-t. A keresztény koptok Egyiptomban néha egy negyedóráig is éneklik. Az Allelujának az evangélium előtt való éneklése római szokás. Eleinte csak húsvét ünnepén énekelték, de már Nagy Szent Gergely előtt az Alleluja éneklését az egész húsvéti időszakra kiterjesztették. Szent Gergely azután megengedte, hogy a húsvéti ünnepkörön kívül is énekeljék s a szirakuzai Jánoshoz írt levelében (Ep. IX. 11. P. L. LXXVIII. 955-958.) hangsúlyozta, hogy ez a szokás nem Konstantinápolyból eredt. Szerinte az Alleluját Damasus pápa idejében Szent Jeromos (+419) hozta Jeruzsálemből Rómába, ahol azonban az Alleluja használatát már korlátozták, mert nem énekelték a böjti napokon és a gyászmisékben.<br><br>
A liturgikus éneklésnél már a régi időkben is az Alleluja utolsó „a” betűjére hosszú dallamokat énekeltek, amelyeket „jubilus”-nak (jubilatio, cantilena) hívtak. Ez az ének a középkori írók szerint nagy jelentőségű s a legnagyobb érdeklődéssel tárgyalták a jubilus különböző misztikus magyarázatait. Minden valószínűség szerint annak a zsoltárversnek, mely a három Alleluja között található (l. a fenti példában: Ostende nobis stb.), tulajdonképpen csak az volt a célja, hogy a hosszú jubilus-éneklés alatt a papnak legyen valami elfoglaltsága. Ugyanaz az eset, mint amit az ún. „kitöltött Gloriá”- nál láttunk (54. old.). Ezt az allelujás zsoltárverset (versus allelujaticus) egyes esetekben valamelyik más szentírási könyvből vett szöveg helyettesíti. Szent Lőrinc napján (aug. 10.) pedig nem is szentírási szöveget találunk. „Levita Laurentius bonum opus operatus est, qui per signum crucis caecos illuminavit”, „Lőrinc levita jót cselekedett, mikor a kereszt jelével a vakokat látókká tette”.<br><br>
A húsvéti időszakban másféle Allelujá-t énekelünk, ti. az ún. nagy Allelujá-t. Ez négy Allelujá-ból áll, mint pl. a fehérvasárnapi szöveg mutatja:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Alleluja.   Alleluja.<br><br>
V.   Matth. 28. In die resurrectionis meae, dicit Dominus, praecedam vos in   Galileam. Alleluja.<br><br>
V.   Joann. 20. Post dies octo, januis clausis, stetit Jesus in medio discipulorum   suorum, et dixit: Pax vobis. Alleluja.</div>
    <div class="col-lg-4">
Alleluja,   alleluja. <br><br>
V.   Mt. 28. Feltámadásom napján, úgymond az Úr, előttetek megyek Galileába.   Alleluja. <br><br>
V.   Ján. 20. Nyolc nap múlva Jézus zárt ajtókon át tanítványai között megjelent   és mondá: Békesség nektek. Alleluja.</div>
</div>
A második, harmadik és negyedik Alleluja végén éneklik a jubilus- dallamot. A két szentírási szöveget már a régiek sem egyforma dallamra énekelték, ami mutatja, hogy itt tulajdonképpen két összeolvasztott ének van, melyek közül az első a gradualé-nak felel meg. Érdekes, hogy húsvét nyolcada alatt egészen péntekig bezárólag még nem mondjuk az ún. nagy-Alleluját, hanem csak a gradualé-t. Ennek az az oka, hogy a húsvét hetének szövegrészei nagyon régiek, már a Szent Gergely pápa Liber Antiphonariusában szóról-szóra megtalálhatók s ezért az Egyház ezeket mint tiszteletreméltó örökséget őrzi és nem változtat rajta, bár bizonyos értelemben a szabálytól eltérnek.<br><br>
3. Tractus.<br><br>
A tractus elnevezés onnan származik, hogy ezeket a szövegeket az előénekesek egyfolytában (uno tractu) énekelték, nem úgy tehát, mint a graduale zsoltárverseit, amelyeket a nép az egyes válaszversek éneklésével megszakított. Ezért van az, hogy a tractus minden verssora előtt egy „V” betűt (versiculus) találunk s sehol sincs „R” betű (responsorium). Már a VIII. században az első Ordo Romanus említi, hogy a tractus-t olyankor éneklik, amikor nincs Alleluja, vagyis adventben és nagyböjtben, továbbá a vigíliákon, kántorböjti napokon és a gyászmisében. E szabály alól ma is csak a húsvét és a pünkösd sajátos vigíliái a kivételek, amelyeknél Alleluja is van és tractus is. A tractus meghatározatlan számú zsoltárversből áll. A nagyböjt hétfőin, szerdáin és péntekjein (a nagypénteket kivéve) egyforma a tractus. A tractus tartalmilag jobban alkalmazkodik a misében felolvasott szentírási szakaszhoz, mint a graduale. A nagyböjt első vasárnapján pl. az Úr megkísértetésének a történetét olvassuk a szentmise evangéliumában. A kísértő idézi a 90-ik zsoltár szavait: „angyalainak parancsolt felőled stb”. Ennek megfelelően a tractus-ban a 90-ik zsoltárt olvassuk, még pedig egy-két verssor kivételével az egész zsoltárt. Ez egyedülálló példa a misekönyvben. A zsoltár liturgikus szövege nem vág teljesen egybe a Szent Jeromos-féle Vulgata-szöveggel, ez a fordítás ugyanis régibb a Vulgatánál is. A tractus eredetére vonatkozólag Schuster kard. (I. 97.) tiltakozik azon feltevés ellen, mintha ez a szokás is keletről származnék, „mintha a latin szellem teljesen képtelen volna méltó módon felemelkedni Teremtőjéhez”.<br><br>
4. Sequentia.<br><br>
A középkorban az Alleluja után még egy ének jött szokásba, ti. a sequentia. Az V. Pius pápa által 1570-ben kiadott s máig is használt misekönyvben már csak öt seguentia van. A középkorban többezer ilyen éneket ismertek. A sequentia-éneklés szokása tulajdonképpen az Allelujá- ból keletkezett. Mint említettük, az Alleluja végső „a” betűjére hosszú dallamokat énekeltek, úgy mint manapság pl. az Ite missa est „e” betűjére. Ezeket a dallamokat azonban nehéz volt úgy megjegyezni, hogy szöveg nem volt hozzá. Ezért azután Notker Balbulus, szentgalleni apát (+912) olyan énekeket írt, amelyeknek minden egyes szótagja a dallam egy-egy hangjegyének felelt meg. Így a szöveg révén könnyebb volt a dallamot is emlékezetben tartani. Ezeket az énekeket, melyek lassankint nagyon elszaporodtak, azért nevezték sequentiá-knak, mert a graduale Allelujá-ját „követték”. Nevezetesebb sequentia-írók voltak Szent-viktori Ádám (+1192), Szent-galleni Eckehart (+973), limburgi Gottschalk (+1098), Celano Tamás (+1250 körül). Később nemcsak latin, de a nép nyelvén készült sequentiák is készültek, sőt különböző nyelvűek is (Fortescue i. m. 364.), mint pl.:<br><br>
Ein verbum bonum ac suave<br><br>
Sand dir Gott, der heisset Ave stb.<br><br>
 Voltak sequentiá-k a borra és a sörre. Nass János Luther Mártonról írt sequentiá-t: „Invicti Martini laudes intonent Christiani”. Ez a szokásos versírás lassanként annyira elfajult, hogy egyformán ártott a jóízlésnek és a vallásosságnak. A trienti zsinat atyái sokat foglalkoztak ezzel a kérdéssel. A megállapodás az lett, hogy a Victimae paschali, a Veni Sancte Spiritus, a Lauda Sion és a Dies irae sequentiá- k kivételével a többit mind törölték a megreformált misekönyvből. Így azután a kezdeményezőnek, Notkernak is az összes himnuszai kiestek. Kétségtelen, hogy a megmaradottak az összesek között a legszebbek és legtartalmasabbak. Az 1509-ben kiadott egri Ordinarius szerint a székesegyházban a fentieken kívül még a következő sequentiák is használatosak voltak: Dilectus Deo, Exultant, Gaudeat Ecclesia, Grates nunc, Salve porta, Verbum Dei Deo stb. (Kandra. XIX.)<br><br>
 a) A húsvéti gyönyörű sequentiá-t, a Victimae paschali-t, Wipo (+1048 körül), II. Konrád udvari papja írta. Valószínűleg a fenséges dallam is tőle származik. A második részben kedves párbeszédet találunk, amelynek révén ez a himnusz a középkorban szokásos vallásos drámákban is igen gyakran szerepelt. Az 1570-iki reform elhagyta a hatodik verssort, mely így hangzott: „Credendum est magis soli, Mariae veraci, quam Iudaeorum turbae fallaci”.<br><br>
 b) A pünkösdi himnuszt, a Veni Sancte Spiritus-t Langton István canterbury érsek írta, amiről egy egykorú szerzetes írása tanúskodik (Fortescue i. m. 367.). Régente Róbert francia királynak, vagy III. Ince pápának is tulajdonították.<br><br>
 c) Amint a pünkösdi himnusz a Szentlélek Úristenről szóló tant adja elő segítségülhívás alakjában, úgy a legméltóságosabb Oltáriszentségről szóló tanítást az Úrnap himnuszában, a Lauda Sion-ban találjuk meg. Ez a himnusz, valamint az egész úrnapi zsolozsma Aquinói Szent Tamás nagyszerű alkotása, mely „inkább égi visszhanghoz hasonlít, mint földi költészethez” (Faber). Ez a mélyértelmű sequentia, melyet Szent Tamás IV. Orbán pápa felszólítására készített, ugyanazon szellem műve, mely a középkori dómokat alkotta (Baumgartner).<br><br>
 d) A máig megmaradt sequentiá-k között talán a legszebb a Dies irae. Ez az ének a legnagyobb valószínűség szerint Celano Tamás, ferences szerzetestől (+1250 körül) származik, aki Szent Ferenc kortársa s első életrajzírója volt. Nem is sequentiá-nak készült, hiszen a gyászmisében nem lévén Alleluja, nem is volt szükség sequentiá-ra. A szerző csak magánájtatosság céljából írta ezt az éneket, de már a XIII. századtól kezdve használták sequentiá-nak is. A két utolsó strófa későbbi hozzátoldás, mely nem is felel meg az előző strófák gondolatmenetének.<br><br>
Ebben az énekben ugyanis az utolsó ítélet nagyszerű rajzát találjuk, az utolsó két strófa pedig a megholtakra tereli a figyelmet, akikről az előzőkben egyáltalán említés sem történt. A Dies irae páratlan művészettel megalkotott mestermű, melyről a híres irodalomtörténész, Baumgartner S. J. így ír: „Ez a monumentális költemény, mely még most is minden egyes ünnepélyes gyászmisében felharsan és a legnagyobb zeneszerzőket foglalkoztatta, egy Goethe-t képes volt megrázni; ennek az emléke a ’Faust’-ban bejárta a modern, a kereszténységtől többé- kevésbé eltávolodott világot s még ma is figyelmezteti azt, hogy a középkor költői erejének nem kell félnie a későbbi idők költészetével való összehasonlítástól, sőt hogy ez utóbbi még nagy mértékben az előbbi örökségéből él” (Weltlitteratur. IV. 3-4. 463 sk.).<br><br>
 e) Az ötödik sequentia az V. Pius pápa által kiadott misekönyvben még nem volt meg. A Stabat Mater-t XIII. Benedek 1727-ben vette fel a misekönyvbe. Szerzőjének Jacopone de Todi (Jacobus de Benedictis) nevű ferencrendi szerzetest (+1306) tartják. Újabban egyesek (Blume S. J.) kétségbevonják ezt és a Stabat Mater-t Szent Bonaventurának tulajdonítják (Stimmen d. Zeit. 1915. 592-598.). „A legünnepeltebb zeneszerzők versenyeztek, hogy ennek a felülmúlhatatlan szövegnek méltó zenei kifejezést adjanak. Az egyháztól távolállók ezrei épültek rajta. Walter Scott halálos ágyán vigasztalást talált benne. Semmiféle márvány Pieta nem képes az Istenanya részvételét a Világmegváltó keresztútjában megrázóbban megjeleníteni, mint ez a csodálatos ének” (Baumgartner i. m. 463.). Ez a himnusz sem sequentiának készült, csak később került a misekönyvbe. Jelenleg a Szűz Mária hét fájdalmának két ünnepén imádkozzuk. A régi sequentiá-k közül egynéhány a szentmisén kívül még ma is használatban van. Így a Salve Regina is régente sequentia volt, legalább is Durandus azt állítja (Rationale. IV. 22.).<br><br>
A seguentia csak a római liturgiában szokásos. Sem a mozarab, sem az ambrozián liturgia nem ismer ilyesmit, annál kevésbé a keleti liturgiák. De azért minden liturgiában van valami ének a leckeolvasás után. Az Antiochiából származó liturgiák a lecke előtt néhány rövid verssort mondanak, a lecke után pedig az Alleluját. A nesztoriánusok a leckék között hosszú zsoltárokat énekelnek, míg a koptok a Trisagiont mondják. Milánóban két lecke van, az első után kis zsoltárt (Psalmellus- t) mondanak, a második után pedig az Alleluját.<br><br>
A régi egyházban a katechumeknek, vagyis tanítás alatt álló s megkeresztelésre váró embereknek csak a szentmise elején volt szabad résztvenni. Egyes helyeken az evangélium, vagy a szentbeszéd után, Rómában valószínűleg már a leckeolvasás után elküldték őket. Ezért azután a keresztséget megelőző vizsgálatuknál ünnepélyes szertartással adták át nekik az evangéliumot („traditio Evangelii”) annak a jeléül, hogy ezentúl már az evangélium éneklésénél is jelen lehetnek a templomban. <br><br>