
 Az evangélium olvasása, illetve az ünnepélyes misében az evangélium éneklése egyik legjellegzetesebb s legmegkapóbb része a szentmise szertartásának. Míg a leckében a próféták és az apostolok szólottak a hívekhez, addig az evangéliumban maga az Úr Jézus, az örök Igazság ad tanítást. Ennek megfelelően az Egyház hite a századok folyamán az evangélium olvasását oly páratlanul szép, az egyszerű nép által is könnyen megérthető szertartásokkal ruházta fel, hogy a jelenlevő hívek szinte a jeruzsálemi templomban, vagy a Genezáret-tó partján tanító Jézust látják a fényes ruhába öltözött ünnepi diákonusban s a legnagyobb alázattal hallgatják az evangélium fenséges igéit.<br><br>
Már magát az evangéliumos könyvet is a keresztények mindenkor nagy tiszteletben tartották, mert benne látták Jézus szimbólumát. S méltán, mert hiszen az evangélium, vagyis Jézus szavai sokkal jobban elénk varázsolják az isteni Üdvözítőt, mint pl. egy kép vagy egy szobor. Éppen azért már régi időben is szokás volt, hogy az evangéliumos könyvet értékes kötésbe foglalták, a kötést festményekkel, arany vagy ezüst veretekkel, drágakövekkel, olykor még ereklyékkel is díszítették. Nagy ünnepeken az evangéliumos könyv egész nap az oltáron feküdt, vagy pedig szerzetesek körmenettel vitték körül s útközben folyton tömjénnel füstölték. Ha egy pápai követ vagy püspök a székesegyházba, vagy a kolostorba jött, a fogadásnál megcsókolásra nyújtották neki. Alexandriai Szent Cirill beszéli, hogy a harmadik egyetemes zsinaton az evangéliumos könyvnek külön trónust készítettek (Migne. P. G. 49, 96.). Ezt a szokást a trienti és a vatikáni zsinat is követte (Vandeur, 115.). Eskütételnél az Egyház még ma is ezt a könyvet csókoltatja meg. Régente még az is szokás volt, hogy a hívek az evangélium egyes szövegeinek a másolatát a nyakukba akasztották, vagy a mellükön hordozták. A görögök az evangéliummal együtt temették el papjaikat. Ez az egyetlen könyv, amelyet a liturgiában megcsókolnak, megfüstölnek, a kereszt jelével megjelölnek.<br><br>
Ma a csendes misében a pap olvassa, az ünnepélyes misében pedig a szerpap énekli az evangéliumot. Az első századokban az istentiszteleteken nem egyes kiragadott részleteket olvastak az evangéliumból, hanem folytatólagosan olvasták azt. S a felolvasást egy külön e célra kirendelt felolvasó (lector) végezte. Így pl. Szent Ciprián egy bizonyos Aureliust kijelöl lector-nak, hogy „olvassa az evangéliumot, mely képzi a vértanúkat” (Ep. 33. P. L. 4., 328.). Később az evangélium iránti nagy tisztelet arra indította az Egyházat, hogy magasabb rangú egyházi személlyel olvastassa az Úr szavait. Sozomenus szerint Konstantinápolyban húsvét ünnepén maga a püspök töltötte be ezt a szerepet, Alexandriában az archidiákonus, „más helyeken a szerpapok olvasták az evangéliumot, elég sok egyházban pedig maga a pap” (H. E. 7., 19. P. Gr. 67., 1477.)ˇ Az V. századtól kezdve mindjobban állandósul az a szokás, hogy a szerpap, vagyis a miséző pap után a legmagasabb rangú segédkező tölti be ezt a szerepet. Kivétel mindössze talán az az évszázadokon keresztül tartó szokás volt, hogy karácsony szent éjszakáján maga a császár -- karingben és stolá-val -- énekelte az ünnepi evangéliumot, mely így kezdődik: „Történt pedig ama napokban, rendelet ment ki Augusztus császártól stb.” (Mabillon, M. I. 1,256.) Hasonló kiváltság alapján énekelte Zsigmond király és császár a konstanci zsinaton (1414) XXIII. János pápa jelenlétében az evangéliumot (Vandeur, 116.).<br><br>
Nézzük az ünnepélyes misében az evangélium éneklésének szertartását és figyeljük meg, mily szépen tud az Egyház szertartásokkal reánevelni minket az evangélium nagyrabecsülésére.<br><br>
Előre kell bocsátanunk, hogy a középkor előtt az ünnepélyes misében a pap nem olvasta el az evangélium szövegét, mint az manapság történik, hanem csak meghallgatta a szerpap által énekelt szöveget. Akkor még a misekönyv (sacramentarium) nem is tartalmazta az evangéliumi szövegeket, hanem csak a miseimákat, míg az evangéliumi szakaszokat a szerpap külön könyvből énekelte (liber epistolasius, evangeliarius). Csak a IX. század körül -- a csendes mise szokásának behozatalával egyidőben -- egyesítik a kétféle könyvet (missale plenarium) s ez időtől kezdve az evangélium éneklése előtt a pap elolvassa az evangéliumot.<br><br>
Az evangélium-éneklés szertartása azzal kezdődik, hogy a szerpap az evangéliumos könyvet az oltárra helyezi. Nem azért teszi ezt, mintha hirtelenében nem tudná hová tenni, hanem ennek a ténykedésnek mély jelentősége van. Régente már a szentmise kezdetétől kezdve az oltáron volt az evangéliumos könyv (Ord. Rom. II. 5.). Az oltár ti. már a régi Egyházban is Krisztust jelképezte. Az evangéliumos könyvnek az oltárra való helyezése tehát azt fejezte ki, hogy az evangéliumos ige az örök Ige, vagyis az élő Krisztus ajkáról folyik.<br><br>
Ezután a pap tömjént tesz a füstölőbe, majd a diákonus az oltár lépcsőjén elmondja a következő imát:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Munda   cor meum ac labia mea, omnipotens Deus, qui labia Isaiae Prophetae calculo   mundasti ignito: ita me tua grata miseratione dignare mundare, ut sanctum   Evangelium tuum digne valeam muntiare. Per Christum Dominum nostrum. Amen.</div>
    <div class="col-lg-4">
Tisztítsd   meg szívemet és ajkamat, mindenható Isten, ki Izaiás Próféta ajkát tüzes   zsarátnokkal tisztítottad meg: úgy méltóztassál engem kegyes irgalmaddal   megtisztítani, hogy szent Evangéliumodat méltóan hirdethessem. A mi Urunk   Jézus Krisztus által. Amen.<br><br>
</div>
</div>
Ez az ima már a XI. században ismeretes, bár még a XV. században is van olyan misekönyv, amelyből hiányzik. A szerpap kéri az Úr áldását, hogy méltóképpen hirdethesse a szent igéket. ő is remeg, mint Izaiás próféta a nagy feladat előtt. De amint az Úr angyala a mennyei oltárról hozott tüzes szénnel megtisztította Izaiás ajkait s erőt adott a prófétának a kemény igazságok bátor hirdetésére (Iz 6,5. sk.), úgy a szerpap is az Úrtól várja bűnös ajkának és szívének a megtisztítását. ő is, mint a próféta az isteni üzenet hirdetéséhez küldetést vár s azért oda térdel a pap elé e szavakkal: Jube, domne, benedicere (méltóztassál, Uram, megáldani). A pap megáldja a szerpapot:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Dominus   sit in corde tuo et in labiis tuis: ut digne et competenterannunties   Evangelium suum. Amen.</div>
    <div class="col-lg-4">
Az   Úr legyen szívedben és ajkadon, hogy méltóan és megfelelően hirdethessed   Evangéliumát. Amen.</div>
</div>
Ez az áldás már a VIII. században megvan (Ord. Rom. I. P. L. 78, 942.). Ugyanott olvassuk, hogy a szerpap az áldás után megcsókolja a püspök lábát. Ez a lábcsók a pápai misében most is megtörténik s kifejezi a szerpap alázatosságát e kitüntető megbízatás teljesítése előtt s a miséző főpap lelki hatalmát, aki Krisztus nevében ad meghatalmazást az evangélium kihirdetésére. E hatalom átruházásának a kifejezésére a miséző ráteszi a kezét az evangéliumos könyvre, a szerpap pedig hálából a püspöki misében megcsókolja a püspök kezét. A régi egyházban a szerpap a templom közepén álló emelvényről, az ún. ambon-ról olvasta fel az evangéliumot. Az ambon-hoz ünnepélyes körmenetben vonult a diákonus. Előtte mentek a gyertyavivők (acolytusok) égő gyertyákkal, melyek az evangéliumban megnyilatkozó Krisztust, a világ világosságát jelképezték. Utánuk jöttek a füstölővel a thuriferek, majd az alszerpap és végül a szerpap az evangéliumos könyvvel. Durandus idejében keresztet is vittek az evangélium olvasáshoz az ambon-ra, hogy a nép szemlélhesse a Keresztrefeszített alakját, mikor hallja tanítását (Ration. 4, 24, 16.). Egy VI. századbeli francia író, Párizsi Szent Germanus, a feltámadt Krisztus diadalmas mennyei bevonulásához hasonlítja ezt a körmenetet. Az ő idejében hét kandelábert vittek az akolitusok a körmenetben s a kórus a körmenet alatt Sanctus-t énekelt (Duchesne. Origines. 208.).<br><br>
Mikor a szerpap az utolsó előkészületet végzi nagy funkciójának megkezdése, vagyis Krisztus valóságos szavainak megismétlése előtt, Krisztus mintegy titokzatosan jelen van a diákonus szerepében s ezért a főpap levéteti fejéről a püspöksüveget, ha egyszerű pap végzi a szentmisét, akkor az kifordul az oltártól a diákonus felé, a nép pedig feláll. Ez a felállás ősrégi szokás, már az apostoli konstitúciók (2,57.) is említik. A középkorban a hívek letették a kezükből még a botot is, amelyre a szentmise alatt támaszkodni szoktak. Keleten a püspökök levetették a palliumot. A francia királyok és császárok letették koronáikat. A lengyel hercegek kivonták kardjukat annak a kifejezésére, hogy készek az evangéliumot, illetve a Krisztus tanítását valló híveket akár fegyverrel is megvédelmezni a támadások ellenében. Szintén régi szokás volt s nyugaton csak a VII. vagy VIII. században szűnt meg az, hogy a híveket az evangélium felolvasása előtt így figyelmeztették: „Álljatok csendben és hallgassatok figyelmesen!” („State cum silentio audientes attente”. Fortescue, 373.). Ez a szokás még ma is megvan a bizánci liturgiában.<br><br>
A szerpap „észak felé” fordulva énekli az evangéliumot. A különböző égtájak felé való igazodás a liturgiában a keleti egyházban már az V. században, a nyugati egyházban pedig a VI. században keletkezik. (Batiffol. Leçons. 78.) Ekkor kezdik megkívánni, hogy a templom apsisa a keleti oldalon legyen, vagyis hogy a hívek, ha az oltár felé néznek, kelet felé fordulva legyenek. A VIII. században a pap is, aki eddig a néppel szembefordulva misézett, a népnek hátat fordított, hogy a szentmise bemutatásánál arccal kelet felé legyen („stat versus ad orientem” Ord. Rom. I. 8. P. L. 78. 942.). A XI. században először a csendes misében jött szokásba az, hogy a pap az evangélium olvasásánál egy kissé a nép felé, vagyis a kelet felé fekvő oltártól kissé észak felé fordult. Ezt azután átvitték az ünnepélyes misébe, ahol a diákonus már nem egyenesen a nép felé, hanem kissé oldalt fordulva énekli az evangéliumot. Ez a szokás még ma is megvan úgy a csendes, mint az ünnepélyes misében. (Caerem. ep.: versus ipsam partem dexteram, quae pro Aquilone figuratur.) Ennek a szokásnak a középkorban misztikus magyarázatot is adtak. Az észak ti. a sötétséget, a Sátán birodalmát jelenti s így a diákonus azért fordul észak felé, hogy az evangéliumi világosság a Sátán birodalmának sötétségét eloszlassa.<br><br>
Erre a szerpap ünnepélyesen üdvözli a jelenlevőket Dominus vobiscum szavakkal. Az Úr valóban a hívek lelkében van s ott megkezdi tanítását. A szerpap ezt a mélyértelmű köszöntést a pap, vagy a püspök jelenlétében máskor nem használja, csak itt az evangélium hirdetésénél és még a nagyszombati Exsultet-nél. Ez is mutatja, mily nagy megbízatásban jár el, mikor az Egyház nevében az Úr igéit hirdeti. Azután mintegy a maga igazolására, hogy tényleg szentírási részletet olvas, tudomására hozza a híveknek, hogy melyik evangelistának a könyvéből olvas s hogy az elején kezdi-e meg az evangéliumot, vagy pedig valahonnan folytatást vesz. (Initium, vagy Sequentia S. evangelii secundum N.) Ugyanekkor megjelöli a szent szöveg kezdetét a kereszt jelével majd ugyancsak a kereszt jelével érinti homlokát, ajkait és mellét. E szokás nagyjából már a XI. században megvolt s jelentése kézenfekvő. A szöveg kereszttel való megjelölése kifejezése annak, hogy ez a tanítás a „kereszt evangéliuma” (evangelium crucis. 1Kor 1,18), míg a homlok, az ajkak és a mell megérintése, amit a diákonussal együtt a hívek is végeznek, azt fejezi ki, hogy az Úr tanítását törekszünk értelmünkkel felfogni, ajkainkkal megvallani és szívünkbe befogadni. A nép lelkes felkiáltása „Dicsőség neked, Uram!” („Gloria tibi, Domine”) a gallikán rítusból eredő szokás, melyet már a VI. században megtalálunk. A mai gyakorlattól a régi szokás csak annyiban tér el, hogy régente e felkiáltás alatt a diákonus a néppel együtt az oltár felé meghajtotta magát. Ezután a szerpap tömjénnel megfüstöli a könyvet, hogy ezáltal is kifejezésre juttassa szívének mély hódolatát az Úr üdvösségre vezető, szentséges tanítása iránt. Erről a füstölésről cremoni Sicardus (+1215) tesz először említést. Egyes helyeken, így pl. Párizsban is, régente harangoztak vagy csengettek is az evangélium- éneklés alatt, hogy felhívják a fontos ténykedésre a nép figyelmét. Ha a felolvasandó szöveg nem valamely evangélium kezdő sorait adja (Initium), akkor a régi szokás szerint az evangélium az időpont meghatározásával kezdődik. Némelyik evangéliumban maga a szentírási szöveg ad ilyen útbaigazítást („Heródes király napjaiban”, „Tiberius császár tizenötödik évében”), ha azonban ez hiányzik, akkor az evangélium „In illo tempore” („abban az időben”) szavakkal kezdődik, amelyen azt a nagyjelentőségű időt értjük, mikor az Üdvözítő a földön járt és a megváltásunk nagy művét végrehajtotta.<br><br>
Az evangélium elhangzása után ma „Laus tibi, Christe”-t („Dicséret neked, Krisztus!”) mondunk. Régente inkább „Deo gratias” (,Istennek hála!”), vagy még gyakrabban az Amen volt szokásban. Ezután az alszerpap odaviszi a könyvet a misézőhöz, aki megcsókolja a felolvasott evangéliumi szöveg kezdetét. Ez a legnagyobb tiszteletnek és szeretetnek a jele, mely Krisztusnak szól, aki kinyilatkoztatta magát az evangéliumban. Nagyon kedves szokás volt régente, hogy a néppel is megcsókoltatták az evangéliumot. Az alszerpap a thuriferrel először a klérus tagjaihoz vitte oda a könyvet s csókoltatta meg velük a szent szöveget. Azután becsukta a könyvet s sorra odanyújtotta a híveknek, akik a szent könyvet kívülről tisztelettel megcsókolták. Ez a szokás III. Honorius pápa (1216-1227) idejében szűnt meg.<br><br>
A könyvcsókolásnál a pap e szavakat mondja:<br><br>
<div class="row two_column">
    <div class="col-lg-4">
Per   evangelica dicta deleantur nostra delicta.</div>
    <div class="col-lg-4">
Az   evangélium szavai töröljék el vétkeinket.</div>
</div>
Ilyenféle imát már a XII. században mondottak, ennek az imának a szövege azonban csak a XVI. században keletkezett. Igen mély értelmű gondolatot fejez ki ez a szöveg, azt ti., hogy az evangélium hallgatása még bűneink megbocsátását is eredményezi, amennyiben ugyanis minket bánatra s hibáink jóvátételére indít.<br><br>
A keleti egyházban az evangélium-éneklés szertartása még változatosabb, mint a mi liturgiánkban. Náluk az ambon-hoz az evangéliumos könyvvel végzett körmenet az ún. „kis bemenetel” a katechumenek liturgiájának legkiemelkedőbb szertartása. De a mi liturgiánk is e ponton oly fenséges és gazdag, figyelmünket érdeklődésünket oly nagyszerűen irányítja az Úr igéjét tartalmazó evangéliumra, hogy e szertartások láttán mi is fellelkesülünk az Úr tanítása iránt s a lelkesedés rajongásával szinte kiáltani szeretnénk az Úr felé az evangéliumi asszonnyal: „Boldog e méh, mely téged hordozott” s hallani az Úr szavát: „sőt inkább boldogok, akik az Isten igéjét hallgatják és megőrzik azt” (Lk 11,27-28). <br><br>