<div class="row">
    <nav role="navigation" class="table-of-contents">
        <h3 id="top">Tartalomjegyzék:</h3>
        <ol type="I">
            <li><a href="#eloszo">Előszó</a></li>
            <li><a href="#attekintes">Áttekintés a szentmise történetéről</a></li>
            <li><a href="#szentmise_reszei">A szentmise egyes részeinek története</a></li>
            <ol class="multicolumn_list">
                <li><a href="#1">Lépcsőima</a></li>
                <li><a href="#2">Oltárfüstölés</a></li>
                <li><a href="#3">Introitus</a></li>
                <li><a href="#4">Kyrie eleison</a></li>
                <li><a href="#5">Gloria</a></li>
                <li><a href="#6">Oratio</a></li>
                <li><a href="#7">A szent lecke</a></li>
                <li><a href="#8">Karversek a szent lecke után</a></li>
                <li><a href="#9">Evangélium</a></li>
                <li><a href="#10">Szentbeszéd</a></li>
                <li><a href="#11">Hiszekegy</a></li>
                <li><a href="#12">Felajánlás</a></li>
                <li><a href="#13">A második oltárfüstölés és a kézmosás</a></li>
                <li><a href="#14">Secreta</a></li>
                <li><a href="#15">Praefatio</a></li>
                <li><a href="#16">Sanctus</a></li>
                <li><a href="#17">Kánon</a></li>
                <li><a href="#18">Te igitur</a></li>
                <li><a href="#19">Megemlékezés az élőkről</a></li>
                <li><a href="#20">Communicantes</a></li>
                <li><a href="#21">Hanc igitur és Quam oblationem</a></li>
                <li><a href="#22">Átváltoztatás</a></li>
                <li><a href="#23">Megemlékezés az Úr haláláról</a></li>
                <li><a href="#24">Supra quae</a></li>
                <li><a href="#25">Supplices te rogamus</a></li>
                <li><a href="#26">Megemlékezés a holtakról</a></li>
                <li><a href="#27">Nobis quoque</a></li>
                <li><a href="#28">Per quem haec omnia</a></li>
                <li><a href="#29">Per ipsum</a></li>
                <li><a href="#30">Miatyánk</a></li>
                <li><a href="#31">Libera nos</a></li>
                <li><a href="#32">A Szentostya eltörése</a></li>
                <li><a href="#33">A szent Test és Vér egyesítése</a></li>
                <li><a href="#34">Agnus Dei</a></li>
                <li><a href="#35">Békeköszöntés</a></li>
                <li><a href="#36">Előkészület a szentáldozásra</a></li>
                <li><a href="#37">Szentáldozás</a></li>
                <li><a href="#38">A hívek áldoztatása</a></li>
                <li><a href="#39">Az egy szín alatt való áldozás</a></li>
                <li><a href="#40">A kehely kiöblítése</a></li>
                <li><a href="#41">Zsoltáréneklés az áldozás alatt</a></li>
                <li><a href="#42">Postcommunio</a></li>
                <li><a href="#43">A liturgikus elbocsátás</a></li>
                <li><a href="#44">Placeat</a></li>
                <li><a href="#45">Áldás</a></li>
                <li><a href="#46">Az utolsó evangélium</a></li>
            </ol>
            <li><a href="#utoszo">Utószó</a></li>
            <li><a href="#irodalomjegyzek">Felhasznált irodalom</a></li>
        </ol>
    </nav>
</div>