<h1>Plébániánk és templomunk története</h1>
<br>
<h4>Az előzmények:</h4>
<p>József nádor igen fiatalon meghalt leánya,   Hermina főhercegnő emlékére 1856. szeptember 8-án   szentelték fel a Hermina kápolnát, a Kassai téri   templom jogelődjét. A kápolna adta a városrész   nevét.</p>
<h4>A fontosabb események évenként felsorolva:</h4>
<p><strong>1919.</strong><em><br />Április 21-én</em>, húsvéthétfőn   a Hermina kápolna főoltára előtt <em>dr. Mészáros   János</em> érseki helytartó jelenlétében <em>dr.   Zsámboki Pál </em>titkár okiratot olvasott fel, melynek értelmében   Budapest-<strong>Herminamezőt</strong> az esztergomi érsek önálló <strong>plébániává</strong><strong> </strong><strong>emelte</strong> és   vezetését <em>Mihalovics   Zsigmond</em> áldozópapra bízta, és a Hermina   kápolnát plébániatemplommá tette.Ezt követően   a plébánia híveinek száma gyorsan növekedett,   ezért rövid idő alatt a Hermina kápolna befogadóképessége   elégtelenné vált.<br />A kápolna búcsúját a hívek   nagy száma miatt az udvaron tartották. Ezért <em>Mihalovics   Zsigmond</em> atya tervbe vette egy nagy befogadó képességű központi   fekvésű templom építését.<br />Az egyházközség vallási élete   nagyon hamar intenzívvé vált. A leányok a <strong>Mária   Kongregációban</strong> tevékenykedtek. Ez volt az egyházközség   első egyesülete. Ugyanebben az évben megalakult az <strong>Oltáregylet</strong> és   a <strong>Rózsafüzér Társulat</strong> is.</p>
<p><strong>1923.</strong><br />Megalakul a Herminamezői Egyházközség <strong>135.     számú Turul Cserkészcsapata</strong>.</p>
<p><strong>1924.</strong><em><br />Mihalovics Zsigmond </em>atyát plébánossá nevezik   ki. Beiktatását a Hermina kápolna kertjében tartották   meg. Megkezdte a gyűjtést a felépítendő új   plébániaépületre és -templomra.</p>
<p><strong>1925.</strong><br />A   plébánián rövid idő alatt élénk   kulturális élet alakult ki. Vasárnap délutánonként   társas összejöveteleket tartottak, színdarabokat adtak   elő. (egy kép 1936. március   15-éről)<em> Január 13-án</em> már az 50. jubiláris   színielőadást tartották, ezen az eseményen <em>Lukács   György</em> is részt vett, és méltatta a színielőadást.</p>
<p><strong>1926.</strong><em><br />Március 14.</em> <em>Mécs László</em> is   fellépett az egyik kulturális összejövetelen. A kulturális   események támogatására esetenként a <em>filmgyár</em> segítségét   is sikerült megnyerni.</p>
<p><strong>1927.</strong><br />A Gyermekvédelmi szakosztály - többek között   - megalapította az iskolából kimaradt és munkába   járó leányok szövetségét.</p>
<p><strong>1928.</strong><br />A munkásifjak megalapították a <strong>Szent     György Egyesületet</strong>. Megalakult a <strong>Katolikus Iparos és     Munkás Ifjak Egyesülete</strong>, később ezek a <strong>Kakolikus     Legényegylet</strong>hez csatlakoztak. <br />A munkás leányok a <strong>Szent Margit Körben</strong> tevékenykedtek.<em><br />Petrovácz Gyula </em>építész   mérnök tanár, az egyházközség világi   elnöke díjtalanul elkészítette az építendő templom   terveit. Áldozatos munkájával az építési   költségeket 8%-al csökkentette, így ő volt a templom   legnagyobb mecénása.</p>
<p><strong>1930.</strong><br />Megalakult a férfi <strong>CREDO Egyesület</strong>.</p>
<p><strong>1932.</strong><em><br />Serédi Jusztinián</em> esztergomi érsek,   hercegprímás kijelölte az egyházközség új   határait.<br />Szeptemberben az építendő új Kassai   téri templom alapkövének megáldása.</p>
<p><strong>1935.</strong><em><br />Március 31-én</em> körmenetben vittek   egy hatalmas tőlgyfa-keresztet a Kassai téren építendő templom   telkére, amelyet a leendő torony helyén állítottak   fel. Ez a kereszt jelenleg a templom előcsarnokában látható Missziós   kereszttel azonos.</p>
<p><strong>1936.</strong><em><br />Augusztus     23-án</em> <em>Medveczky Zoltán</em> MÁV tisztviselő elkészítette     az épülő templom kicsinyített  mását,     amelyet a Hermina kápolna teraszán állítottak     ki. A makett ma is megvan és     megtekinthető.<em><br />Augusztus 29</em>-én a templomépítési   vegyes bizottság <em>Wihart Ferencet</em>, a képviselőtestület   tagját bízta meg a templomépítéssel.<em><br />Szeptember 6.</em> Első, ünnepélyes kapavágás.<em><br />Szeptember 20.</em> <em>Serédi Jusztinián</em> jelenlétében   elhelyezték a templom alapkövét, és abban a díszes   miniatűrökkel ékesített pergament alapító okmányt.<em><br />December 12.</em> Bokréta-ünnepély   megtartása, majd a fedélszék felrakása.</p>
<p><strong>1937. A Herminamezői Szentlélek templom szentelésének éve</strong><br />Januárban elkészült a huszártorony.<em><br />Május 2.</em> A plébániaépület   alapkőletételi ünnepsége, az alapító okirat ünnepélyes   elhelyezése.<em><br />Június 13.</em> A toronykereszt megáldási és   feltételi ünnepsége.<em><br />Szeptember 19</em>. A három új harang: 810   kg-s Szent István, 345 kg-s Szent Imre, 180 kg-s Szent László bemutatása   az Öszi Lakberendezési Vásáron, ezt követően   szentelésük.<em><br />November 13.</em> A hívek égő gyertyát   tartó sorfala köszöntötte a szentelésre érkező,   Szent Kelemen és Szent Tamás ereklyét hozó <em>Serédi   Jusztinián</em> atyát. Este 6 órakor megszólaltak   az új harangok, és negyed órán át zúgva-bongva   hírdették a szentelés eseményének közelgő beköszöntét.<em><br />November 14.</em> A templom szentelését <em>Serédi     Jusztinián</em> esztergomi érsek végezte szentmise keretében.     Az első ünnepélyes litániát aznap délután     5 órakor tartották meg.</p>
<p><strong>1938. A hazánkban megtartott 34. Eucharisztikus Világkongresszus éve</strong><em><br />Március 4</em>. Az <em>Orbán Antal</em> szobrászművész által   készített és <em>Hoffmann Ferenc</em> által ajándékozott   stációképek megáldása.<em><br />Április 2-9.</em> Az Eucharisztikus Kongresszus   előkészítő hete templomunkban.<em><br />Május 23-29.</em> Az Eucharisztikus Kongresszus ünnepi   eseményei; a nők szentórája templomunkban.<br />Az olasz zarándokok képviselője átadta   a <strong>Mamertini feszület</strong> mását, amelyet a Hercegprímás úr   templomunkbanhelyezett el. Ugyanekkor köszönetet mondott <em>Mihalovics   Zsigmond</em> plébános atyának a másfél éves   sikeres, a Kongresszust előkészítő munkájáért.</p>
<p><strong>1939.</strong><em><br />Március 29-30</em>. Az 50 éves <em>Mihalovics     Zsigmond</em>, ezüstmisés plébános köszöntése.</p>
<p><strong>1944.</strong><em><br />Április 15.</em> <em>XII. Piusz</em> pápa   esztergomi kanonokká nevezi ki <em>Mihalovics Zsigmond</em> plébánost.<em><br />Július 2</em>8. <em>Seres       Ferencet</em> plébánossá nevezik ki.<em><br />Szeptember 18</em>. <em>Seres Ferenc </em>az új   herminamezői plébános Esztergomban letette az esküt <em>dr.   Drahos János</em> általános érseki helytartó előtt.   Beiktatása szeptember 24-én volt.<br />A II. világháború idején - feltehetőleg   a Budapest-Rákosrendező vasúti pályaudvar közelsége   miatt - a légitámadások, bombázások súlyos   következményekkel jártak: a templom tornyai megsérültek   - a csúcsíves torony eredeti alakjában történő helyreállítása   sohasem történt meg, csúcsíves torony helyére   végül a templom neoromán stílusához jobban   illő közel lapos tetejű román stílusú torony   került -, minden üvegezés tönkrement, a belső és   kölső ajtók megrongálódtak és a tető is   több helyen megsérült.</p>
<p><strong>1947.</strong><em><br />Május 27.</em> <em>Mindszenty József</em> bíboros   hercegprímás 468 hívőnek szolgáltatta ki a   bérmálás szentségét.</p>
<p><strong>1948.</strong><em><br />Augusztus 20</em>. a háború idején   elvitt harangok pótlására a hívek 200 kg-os harangot öntettek,   amelyet Szent Margit tiszteletére szenteltek fel.</p>
<p><strong>1949.</strong><em><br />Június 5</em>. A templom búcsújára   elkészült a főoltár, csodálatos kenyérszaporítás és   a víz borrá változtatásának szobrászati   alkotásai, amelyeket <em>Csiszér János</em> szobrászművész   alkotott és <em>Fischer Ferenc</em> és <em>Fischer Ágota</em> szobrászművészek   faragtak ki.</p>
<p><strong>1957.</strong><em><br />Július 14.</em> <em>Kontuly Béla</em> festőművész és<em> Beszédes     László</em> megkezdték a szentély festését.<em><br />Augusztus     4.</em> <em>Kopp Ferenc</em> iparművész a szentélybe 6     színes ablakot készített. A szentély baldachinjának     lebontását<em>Endrey     Gyula</em> püspök úr     engedélyezése után <em>Beszédes László</em> iparművész     végezte el.</p>
<p><strong>1958.</strong><em><br />Június 24.</em> <em>Kontuly Béla</em> elkészítette   a templom Szentlélek eljövetelét ábrázoló 26   személyt magába foglaló 45 négyzetméteres   címfreskóját.<em><br />Július 29.</em> <em>Seres Ferenc</em> plébános   bemutatta ezüstmiséjét.</p>
<p><strong>1959.</strong><em><br />Augusztus 28.</em> <em>Mihalovics Zsigmond</em> pápai   prelátus hosszas, súlyos betegség után életének   70., papságának 47. évében elhonyt USA Chicago államában.   (a "Mindszenty per" elől menekült nyugatra 47-ben)<em><br />December 15.</em> <em>Beszédes László</em> iparművész   elkészítette a főhajó első szakaszának   festését, a 6 homlokíves keresztboltozatnak mezőibe   a Szentlélek vonatkozásait ábrázoló képeket és   a szemléltető képsorozatokat, a freskókat <em>Kontuly   Béla</em> festőművész festette.<em><br />December 19</em>. <em>Szabó Imre</em> püspök   atya az államhatalom hozzájárulása nélkül   titokban, zárt templomban pappá szentelte: <em>Rubin Ferencet</em>, <em>Székely   Tibort</em> és <em>Krichenbaum József</em>et.</p>
<p><strong>1960.</strong><em><br />Május 9.</em> <em>Kontuly Béla</em> megfestette   a főhajó első szakaszának további 4 freskóját.<em><br />Július 25. Zadravecz István</em> püspök   atya az állam hatalom nélkül pappá szentelte <em>Bohán   Bélát</em>.</p>
<p><strong>1962.</strong><em><br />Beszédes László</em> tovább   folytatta a főhajó 3. szakaszának ornamentális festését.</p>
<p><strong>1963.</strong><br />Megkezdődött a templom külső tatarozása.   A főhajó 4. szakaszának és a kórusnak ornamentális   festését <em>Beszédes László</em> iparművész   végezte. A templom belső terének festése <em>Kontuly   B</em>éla új freskóival gazdagodott.<em><br />Szeptember 30</em>. <em>Seres Ferenc</em> plébános   atyának a titkos papszentelések következményeként,   büntetésül a plébániát át kellett   adni <em>dr. Hóka Imre</em> érseki tanácsosnak, az új   plébánosnak.</p>
<p><strong>1963-73.</strong><em><br />Dr. Hóka Imre</em> 10 éves plébánosi   tevékenysége nagyrészt a plébánia és   a templom (bele értve a Jáki kápolnát is) fenntartásáért   folytatott küzdelmekből állt. Többször volt betörés,   a Jáki kápolnát a BNV miatt nehéz volt megközelíteni,   sorozatosak voltak az ablakbetörések, el kellett viselni a hatóság   zaklatását stb.</p>
<p><strong>1973.</strong><em><br />Május 1.</em> meghalt <em>dr. Hóka Imre</em> plébános.<em><br />Július</em> <em>Tarnai Béla</em> tiszteletbeli   kanonokat kinevezték plébánosnak.</p>
<p><strong>1974.</strong><em><br />Október 1.</em> Megkezdődött a templomi   hitoktatás.<em><br />December</em> A hívek karácsonyi meglepetésére   országosan egyedülálló, nagyméretű népi   jellegű betlehemet készíttetett <em>Tarnai Béla</em>,   amelynek szobrait <em>Kovács Anna</em> szobrászművész   készítette.</p>
<p><strong>1975.</strong><em><br />Június</em> Elkezdődött a templom átfogó,   teljes renoválása a baloldali kistorony helyreállításával.</p>
<p><strong>1976.</strong><em><br />Április 27.</em> A háborúban csonkává,   majd román stílusúvá alakított toronyra   felkerült az új rázborítású kereszt.<em><br />Április 29. Takács István</em> mezőkövesdi   festőművész folytatta a freskósor festését.</p>
<p><strong>1976-86.</strong><br />Folyamatosan tartott a templom renoválása, karbantartása és   szépítése. Ez idő alatt a Kassai téri templomba   járó hívek száma többszörösére   emelkedett. Nagymértékben megnövekedett a hittanra járók és   az elsőáldozók száma.</p>
<p><strong>1987. A Herminamezői templom felszentelésének 50. évfordulója</strong><em><br />November     22.</em> <em>Dr. Paskai László</em> esztergomi érsek     prímás hálaadó szentmisén megáldotta     a <em>Tarnai Bél</em>a atya évek hosszú során     folytatott kitartó szervező munkájának, a herminamezői     hívek és a német támogatók áldozatkészségének     köszönhetően megvalósult új, országosan     is a legjobb orgonák közé tartozó orgonát.</p>
<p><strong>1988. Az 1938. Budapesti Eucharisztikus Világkongresszus 50. évfordulója</strong><em><br />Május 19.</em> A Világkongresszus 50. évfordulójáról   a herminamezői egyházközség május 19 - május   21- ig tartó ünnepségsorozattal emlékezett meg. A '38-as ünnepélyes hajófelvonulás   emlékére a herminamezői hívek hajókirándulást   tartottak, amelyet azóta is minden évben megismételnek.</p>
<p><strong>1989.</strong><em><br />Szeptember</em> A templomi hitoktatás mellett megkezdődött   az iskolai hitoktatás.</p>
<p><strong>1990.</strong><em><br />Június Tarnai Béla</em> plébános   aranymiséje.</p>
<p><strong>1991-97.</strong><br />Elkészült   a szembemiséző oltár,   megújult a szentély. Befejeződött a templom alagsorában   az igen szép kivitelű urnatemető létrehozása.</p>