@extends('index')

@section('content')
<p class="cikk">
    <q>
        A szöveg eredete a <a href="http://www.ppek.hu/k127.htm">Pázmány Péter Elektronikus Könyvtár</a> a magyarnyelvű keresztény irodalom tárháza.
        Felhasználhatóság: csak lelkipásztori munkára, nyomtatása nem engedélyezett. - Szerzői jog tulajdonosa: Ósz István
    </q>

    <h1>Romzsa Teodor élete és munkássága</h1>
    <h3>Bevezetés</h3>
    Mivel közeledni érzem földi életem befejezését, kötelességemnek tartom, hogy leírjam elhunyt görögkatolikus püspök atyánk, Romzsa Teodor őexcellenciája, 
    halálának történetét, aki nemes lelkét 1947. november 1-én adta vissza Teremtőjének a munkácsi (Ukrajna Kárpátalja részén) kórházban.
    <br><br>
    Drága vértanúnk halála után legendaszerűen terjedtek el különböző téves verziók a történtekről a kétségbeesett és elkeseredett árva kárpátaljai nép körében. 
    Halálának igazi okát alig ismerte valaki. Azok a kevesek, akik tudták, nem szólhattak róla. Elégtételül a kemény és hosszú hallgatásunkért, negyven nehéz év elmúlta után határoztam el, hogy mindazt aminek szemtanúja voltam, aprólékosan leírom.<br><br>
    Annak tudatában, hogy minden itt papírra vetett szavamért az Úr Isten előtt, a szent, katolikus, apostoli Anyaszentegyház előtt és saját lelkiismeretem előtt is felelek. Kérem a Szentlélek Úristen segítségét a tragikus események hű és pontos felidézéséhez.<br><br>
    Az Atyának és Fiúnak és Szentlélek Istennek nevében. Amen.<br><br>
    Mennyei Király, vigasztaló, igazságnak Lelke, ki mindenütt jelen vagy és mindeneket betöltesz, minden jónak kútfeje, az élet adója! Jöjj el, lakozzál bennünk és tisztíts meg minden szennytől. Lelkünket, jóságos, üdvözítsd.<br><br>
    Őexcellenciája, Főtisztelendő Romzsa Teodor munkácsi görögkatolikus püspök atya halálának története
    1947. november 1-én moszkvai időszámítás szerint fél egy órakor, rózsafüzérrel a kezeiben, mosollyal az ajkán, drága vértanúnk visszaadta tiszta lelkét Teremtőnknek.<br><br>
    1947. október 27-én hétfőn 12 óra 30 perckor (m.i.sz.) szállították be Teodor püspököt súlyos állapotban a munkácsi kórházba. Vele együtt hozták be Bacsinszky Dániel lelkipásztort súlyos sérülésekkel és Bereznay Andrást könnyebb sérüléssel. Két teológus, Bugir Mihály és Maszlej Mihály kisebb sérüléseket szenvedtek. (őket később titokban szentelték pappá.) Ugyanakkor szállították be a kórházba azt a falusi fuvaros bácsit, aki a püspök atyát és kísérőit vitte Lohovó faluból az Ivánovci autóbusz állomásra, ahol fel kellett volna szállniuk az ungvári járatra.<br><br>
    A történtek, melyek püspökünket kínhalálba sodorták, a következők.<br><br>
    Az említett Lohovó a munkácsi járás egyik községe. Parókiájának Lovki nevű filiáléjában, ahol is a hívők befejezték a templomuk tatarozását, templomszentelésre készültek. Ennek időpontját vasárnapra, 1947. október 26-ra, Krisztus Király ünnepére tűzték ki.<br><br>
    őexcellenciája nem engedte, hogy a veszélyeztető körülmények megfélemlítsék. Még Kapitula anya óvó intése sem tudta elhatározását megváltoztatni. Püspök atyánk, mint valaha szent Jozefát, elhatározta, hogy személyesen fogja a templomot felszentelni.<br><br>
    Ungvárról a papság autóbusszal indult célja felé. Püspök atyánk az egész úton Ivanovci falu megállójáig a rózsafüzért imádkozta. Ott már várta őket Vaszkó Péter atya, a lohovói parokus, lovas kocsija.<br><br>
    A szentelés ünnepi szertartását zavartalanul fejezték be. A vendégek részére a lohovói plébánián rendezett ebéden a hűséges falusiak elmondták, hogy már napok óta áll a falu határában egy katonai teherautó, ismeretlen egyenruhába öltözött emberekkel, akik figyelik a települést, különösen a parókia épületét. Péter atya és felesége, Margaret, aki Bacsinszky Dániel atyának volt édestestvére, kérlelték a drága vendégeket, maradjanak náluk éjszakára Lohovón. Mivel esteledett, püspök atyánk beleegyezett, hogy ott maradjon.<br><br>
    Másnap, október 27-én reggel Teodor püspök a lohovói templomban asszisztenseivel celebrálta a Szent Liturgiát.<br><br>
    A hírek a katonai teherautó ottlétéről nem változtak, sőt nem messze tőle megjelent egy dzsip is, amelyet előző nap az emberek, a templomszentelés ideje alatt többször láttak a lovki templom környékén. Mindezen hírek ellenére püspök atyánk reggeli után határozottan kijelentette: "Indulunk."<br><br>
    Amikor lovas kocsival elindultak, a teherautó lassan követte őket. Ivanovo előtt, amikor egy kisebb dombról ereszkedtek le, a dombtetőn megjelent az ismeretlen teherautó, és nagy sebességgel rohant le a lejtőn. Az autó vezetője kiugrott a kocsiból, az autó pedig teljes sebességgel belerohant a lovas kocsiba. A teherautó nyomában jött a dzsip a gyilkosokkal, akik figyelték a balesetet. A kép szörnyűséges volt! A teherautó roncsolt mindenkit, aki és ami utjában volt, amíg bele nem rohant egy árokba. Teodor püspök a jármű két első kereke közé szorult. Bacsinszky Dániel atya és Homa, a fuvaros, a lovas kocsi alá kerültek és súlyos sérüléseket szenvedtek. A lovak, halál előtti agóniában félelmetesen nyerítettek és rövid idő múlva kimúltak. Bereznay András atya és a két teológus, Bugir és Maszlej, az összeütközéskor a hirtelen ütéstől kirepültek a a rétre. Még sokkos állapotban azt látták, hogy a gyilkosok Teodor püspököt, Bacsinszky atyát és a fuvarost vasrudakkal verik. A három fiatalember felállt és ordítva Ivanovci felé iramodott. "Emberek, segítsetek!" - - kiáltozták. A gyilkosok kénytelenek voltak otthagyni áldozataikat, hogy utolérjék a kiáltozókat. Ez sikerült is nekik. Ott ütötték a szerencsétlen védtelen embereket vasrudaikkal, ahol érték. Szerencsére nem tudták elvégezni feladatukat, mert egy postaautó tűnt fel az úton Munkács felől. Sietve beszálltak a dzsipbe és gyorsan elhajtottak. A mi vérben úszó megkínzottainkat a jóérzésű postai dolgozók autójukon a munkácsi kórházba szállították.<br><br>
    Abban az időpontban, amikor ezek a tragikus események történtek, az országúton egyetlen átutazó sem volt. Ez ideális lehetőséget nyújtott a gonosztettre. Szerintem ebben is a jóságos Isten beleegyezését kell látnunk. Lehet, hogy a Mindenható ezt az áldozatot azért fogadta el, hogy szerény szülőföldünk vértanúink vérével való megpecsételése megszentelje és megerősítse Egyházát az elkövetkezendő megpróbáltatásokra és az azt követő dicsőségre.<br><br>
    A munkácsi kórházban azonnal elsősegélyben részesítették megkínzottjainkat. A sebészeti osztály vezetője abban az időben a nagytudású Fedinec Sándor doktor volt. Sebész kollégáival együtt mindent lelkiismeretesen megtett, hogy a szenvedők életét megmentse. Fáradtságot nem ismerve késő éjjelig műtött a mi jólelkű, a mindenkor mindenkinek segíteni kész Fedinec doktorunk és sebész társa, Dr. Vitenberger Miklós. Legjobb tudásuk szerint mindent megtettek.<br><br>
    Teodor püspök atyánknak leginkább a feje sérült meg. Alsó állkapcsán kétszeres törést szenvedett, és szájüregében csupán hét foga maradt meg egészségesen. A többi részben kitört, részben meglazult. Az egyik lábszárán hosszanti sebek voltak, az ütlegelések kék foltjai egész testét beborították.<br><br>
    A megboldogult Bacsinszky Dánielnél koponyaalapi repedést, jobb lapocka repedést, négy vagy öt borda törést és a jobb lábszár mindkét csontján zárt spirális-szilánkos törést állapítottak meg. Lábát gipsz pólyába helyezték. Később a gipszkötés alatt tályog képződött, mely jelentősen nehezítette a beteg állapotát. Dániel atya az első három hét alatt eszméletlen volt, csak amikor magas láza kissé alábbhagyott, nyerte vissza időnként eszméletét. Hőmérséklete általában 39 fok volt.<br><br>
    A szegény fuvaros megmentése teljesen reménytelennek látszott. Arca a felismerhetetlenségig szét volt roncsolva, mély koponya sebéből velő szivárgott. Hiábavaló volt rendkívüli tehetségű és híres sebészünk, Dr. Fedinec Sándor minden igyekezete. Háromhetes kórházi kezelés után, a család kérésére Homát hazaszállították, ahol egy hét múlva meghalt.<br><br>
    Bereznay András atya, Bugir Mihály és Maszej Mihály teológusok megúszták sebészeti varratokkal a fejükön.<br><br>
    A műtét utáni éjszaka mind a betegek, mind az egészségügyi dolgozók részére csendesen és nyugodtan telt el.<br><br>
    Október 28-án kedden reggel a főorvos, Dr. Bergman, bejelentette, hogy arra az időre, amíg ártatlan püspökünk és kísérete nálunk tartózkodik, felvett segítségnek egy fiatal lánykát "szanitarka"[1] beosztásban. Neve Odárka vagy Odotia volt. (Pontosan nem emlékszem.) Ezt az emberséges lépést azzal indokolta, hogy a területi ügyészségtől, sőt Kievből és lehet, Moszkvából is hivatalos személyek érkeznek majd, akiknek a lehető legnagyobb rendben kell találniuk pacienseink szobáit. Dr. Bergman utasításait azzal fejezte be, hogy határozott kívánsága, hogy betegeink ételeit a konyháról ez a kedves leányka vigye be személyesen.<br><br>
    Megjegyzem, mindez a sebészet főnővére és az adminisztrációs főnővér (akinek feladatait én láttam el) tudta és megkérdezése nélkül történt. Üresedés a sebészeten "szanitarka" részére nem volt, ezért a főorvos úr döntése gyanúsnak tűnt.<br><br>
    Kételyeinket erősítette Dr. Bergman azon parancsa, miszerint ennek a szegény lánynak a sebészet gyógyszerraktárában kell fekhelyet biztosítanunk, amíg lakást nem talál magának. Bárhogy is próbáltunk jólelkűsége ellen érveket felhozni, igyekezetünk hasztalan volt. Így maradt a lány a sebészet dolgozója.<br><br>
    Nem tudván hová is soroljam, megkértem a gazdasági nővért, adjon neki kellékeket, hogy a folyosó ablakait megtisztítsa. Ez nem felelt meg Odárka kívánalmainak. Kényszeredetten törölgette az ablakokat. Közben erősen figyelt mindenre, ami az osztályon történt. A főorvos úr is dühös volt, mert a lányt nem az ő utasításai szerint foglalkoztatjuk, nem a püspök atya és társa szobájában jelölünk ki számára feladatokat. Ők ketten feküdtek egy kis kórteremben, a többiek a szomszédos nagyobban. Dr. Bergman fáradhatatlanul látogatta betegeinket. Este alvás előtt már vagy negyedszer szaladt be megnézni őket. Püspök atyánkhoz fordult és megnyugtatta: "A második éjszaka nyugodtabb lesz, mint az első." Bacsinszky atya felett elnevette magát, mert az csodás baritonján felkiáltott: "Áldj meg, Uram!". Püspök atyánk szintén elmosolyodott, s akkor még nagy nehezen suttogta: "Megáldalak Danika." -- és kereszt alakú mozdulattal valóban megáldotta. A főorvos ezután Dániel atya feleségéhez fordult és suttogva kérte, hogy az éjszakákat ne töltse a férje mellett. Azzal nyugtatta, hogy a mi súlyos állapotú betegeink úgyis személyes felügyelet alatt vannak. Vagyis, legyen szíves vegye tudomásul, ezentúl férjét csakis nappal látogathatja. Szegény asszony, Bacsinszky Mária, keservesen elsírta magát. Én rögvest nyugtatni kezdtem, nem megyek el Dániel mellől addig, amíg ő reggel vissza nem tér. Dr. Bergman kihívott a folyosóra és kérdőre vont, hogy mi szükség van arra, hogy én is ott maradjak éjszakára, amikor a két ügyeletes nővéren és az éjjeli szanitarkán kívül még itt van az új lányka is, akit kizárólag a betegek mellé vett fel. Én hirtelen, más magyarázatot nem találva, ezt feleltem: "ő az unokabátyám. (Bacsinszky atyához valóban rokoni kapcsolat is fűzött.) A főorvos úr és Dániel atya feleségének távozása után visszatértem a betegszobába. Pár perc múlva csendesen kinyílt az ajtó, Odárka nézett be.<br><br>
    "Szüksége van valamire Odárka? Miért nem alszik?" -- kérdeztem felé fordulva.<br><br>
    "Szeretnék őszintén beszélni a nővérkével." -- felelte.<br><br>
    "Arra holnap is lesz idő." -- mondtam én.<br><br>
    "Nem ilyen nyugodtan, mint most, nappal nem beszélhetünk! Nagyon kérem hallgasson meg!" -- mondta követelően.<br><br>
    Éreztem, nem szabadulhatok meg tőle egykönnyen. Más kiutat nem látván elküldtem az egyik ügyeletes Bazil rendű nővér után, hogy távollétemkor is legyen valaki súlyos betegeink ágyánál. Ezután szobájuk közelében a folyosón ültem le Odárkával, aki a következőket mesélte: "Lembergben születtem. Öt éves voltam, amikor a bolsevikok letartóztatták drága szüleimet. A jó emberek, vagyis személyesen Septickij metropolita atya megfogta a kezemet és a Bazil rendű nővérekhez vezetett. Rájuk bízta taníttatásomat és neveltetésemet. Gyerekkoromban sokat sírtam, de később egyre közelebb kerültem hozzájuk. Főleg Mária Viter anyát szerettem meg nagyon, aki anyám helyett anyám volt. Tizenhárom éves múltam amikor a bolsevikok feloszlatták a zárdákat Lembergben és Ukrajnában. A főnővéreket letartóztatták, a nővéreket szélnek eresztették. Az én Mária anyám is börtönbe került. Egy csoport merész leánnyal és fiúval az erdőbe menekültünk, hogy ne kerüljünk bolsevik gyermekotthonba, és hogy megbosszuljuk szüleink és Ukrajna elvesztését... Lassan barátnőim mind meghaltak és én nem maradhattam egyedül a fiúk között. Átkeltem a Kárpátokon. Így kerültem Munkácsra. Hallottam a munkácsi kórház Bazil rendű nővéreiről, akik egészségügyi nővérként dolgoznak itt, s elhatároztam, hogy idejövök. Igazán nagyon jó a maguk főorvosa. Meghallgatta kérésemet és maguk közé helyezett engem. Ismét otthon vagyok. Igazán mégis akkor leszek csak boldog, ha ön úgy fog szeretni, mint ahogy Mária anya szeretett. Biztos vagyok abban, hogy akkor ugyanúgy, mint ő, ön sem tagad meg tőlem semmit."<br><br>
    Igyekeztem nem kimutatni, hogy reszketek a meséitől. Nem tudtam megakadályozni beszédét. Odárka gyorsan és szünet nélkül folytatta. "Anyám, mennyivel könnyebb lenne nekem, ha el tudnám felejteni erdei jó barátaimat. Szegény fiúk! Nem egyszer véresek, nincs már kötszerük, vattájuk, orvosságuk, amelyek a mindennapi életben szükségesek, különösen az erdőben. Nagyon kérem, adjon nekem gyógyszereket, kötszert a megsegítésükre!"<br><br>
    Elgondolkoztam és megpróbáltam nagyon komolyan feltenni Odárkának a kérdést:<br><br>
    "A Bazil rendi nővérek nem tanították meg Isten tíz parancsolatára?"<br><br>
    "Dehogynem." Kezdte azonnal sorolni.<br><br>
    "Hogyan kívánhatja, hogy bármit is kihozzak a kórház gyógyszertárából magának?" -- állítottam meg, amikor a hetedikhez ért.<br><br>
    "Nagyon egyszerűen. A mi nővéreink úgy értelmezték, Istennek tetsző dolgot cselekszenek, amikor bennünket segítettek."<br><br>
    "Odárka, én nem vagyok kompetens tetteikért ítélkezni felettük. Én azonban nem azért léptem be fiatalon a Szent Bazil Rendbe, hogy most befeketítsem tiszta lelkületemet Isten tíz parancsolatának ilyen súlyos megsértésével. Életemben soha semmit el nem loptam és nem is fogok."<br><br>
    Odárka igyekezett meggyőzni igazáról, de én határozottan felálltam és a kórterem felé sietve azt ajánlottam neki, menjen aludni.<br><br>
    Közülünk senki sem aludt reggelig. Őexcellenciája csendesen szenvedve a rózsafüzért morzsolgatta. Dániel atya többnyire a Szent Liturgia szövegéből idézett egy-egy mondatot önkívületben. Én pedig gondolataimmal kínlódtam, mit is tegyek holnap? Tanácstalanul, a Jóisten akaratának ajánlva a következő napot, püspök atyánk példáját követve a rózsafüzér imádkozásában kerestem megnyugvást. Égi Anyánk oltalmába ajánlottam pácienseimet és a velük kapcsolatos összes problémáinkat.<br><br>
    A főorvos éjszaka még egyszer meglátogatott helyettesével együtt, aki a 2-es számú sebészeti osztály vezetője volt. (A nevére már nem emlékszem.)<br><br>
    Október 29-én reggel bevártam Bacsinszky atya feleségét. Suttogva elmondtam neki milyen volt az éjszakánk. Figyelmeztettem, hogy nappal senki segítségét sem fogadhatja el. Csak azzal szabad ellátnunk betegeinket, amit mi magunk hozunk be részükre. Sőt az étel felmelegítését sem lehet másra bízni. Különösen Odárkától óvtam. Ezután lementem a kápolnába szentmisére. Utána reggelizni készültem a zárdába, amikor a kórház kapuján belépett Chira Sándor prelátus atya és egyenesen felém tartott. Ő Ungvárról érkezett szenvedőink látogatására. Bickó András atya, a munkácsi parókia káplánja kíséretében. Megjelenésük fellelkesített. Megkértem őket, jöjjenek be a fogadó szobába, ahol is elmondtam éjszaka összes titkait. A prelátus atya nagyon kért, hogy szombatig tartsak éjszakai ügyeletet betegeink ágynál. Akkor már hazaszállíthatjuk püspök urunkat. Bickó atya elgondolkozva hozzáfűzte: "Mindazt amit éjjel mondott önnek Odárka, minél előbb el kell mondania a főorvos úrnak, de föltétlenül két tanú előtt."<br><br>
    A megboldogult és mindnyájunk által szeretett prelátus atya, de magam is így találtuk helyénvalónak. Együttesen határoztuk el, hogy még aznap bemegyek a főorvoshoz Hilária nővérrel, a sebészet főnővérével, lehetőleg akkor, amikor a titkárnő is ott lesz. Így is történt.<br><br>
    Ebéd után Hilária nővérrel (sajnos már nem él) elindultunk a hivatalos beszélgetésre. Dr. Bergman hellyel kínált és türelmetlenül érdeklődött: "Mi újság?"<br><br>
    "Híreim nem a legjobbak" -- feleltem.<br><br>
    "No, mi történt?" -- érdeklődött.<br><br>
    "Kötelességemnek tartom, hogy megmondjam önnek, hogy a segítségünkre felvett leány -- Odárka --, feltevésem szerint nem becsületes és ezért ittléte veszélyes."<br><br>
    Semmit sem rejtegetve előadtam az éjszakai beszélgetést. Hozzátettem azt is, ha továbbra is a főnővér raktárában alszik, minden fáradság nélkül meglophat bennünket. A felelősség a főorvos urat és a főnővért fogja terhelni. Ezért azt ajánlom, bocsássa el.<br><br>
    Dr. Bergman hol elfehéredett, hol elvörösödött, nem tudott szóhoz jutni. Pár perc hallgatás után lesütött szemekkel kinyögte: "Ha így van, akkor még ma dupla zárakat kell felszerelni a gyógyszeres szekrényekre. Odárkát szemmel tartjuk, de pár nap próbaidőre had maradjon."<br><br>
    E pár nap alatt a leány mást sem csinált, mint a folyosón szaladgált és port törölgetett, miközben figyelte, ki jön a püspök atyához látogatóba. Bergman szintén éjjel-nappal nyugtalanul járt- kelt. Betegeinél óránként megjelent. Odárka miatt nagyon haragudott ránk. Majd este azt ajánlotta, helyezzük át Bacsinszky atyát a teológusok kórtermébe, hogy püspök urunknak kellő nyugalma legyen. Püspök atyánk azonban arra kérte a főorvost, ne tegye ezt, hisz számára így kellemesebb a kórházi lét.<br><br>
    Dr. Bergman bosszúsan éjjeli vizitre indult helyettesével, amire sem korábban, sem későbben nem volt példa a kórházban. Éjjel egy óra volt, amikor hozzánk betértek. Felületesen megnézték betegeinket, majd a főorvos halkan, de parancsolóan arra kért, tartsak velük, bár két szolgálatban lévő nővér kísérte őket. Én határozottan ellentmondtam. Arra hivatkoztam, hogy éjjeli pihenésemet unokabátyámért áldozom fel, aki magas lázban hol jobbra, hol balra hánykolódik, s minden ilyen mozdulat halálos lehet számára felügyelet nélkül. Nem mentem velük.<br><br>
    Október 30-án, csütörtökön a főorvos haragja már reggeltől nem ismert határt. Korán reggel átadtam betegeinket Bacsinszky Dániel feleségének védelmébe, majd szentmise után gyorsan végig látogattam minden osztályt, felügyelve a rendre, amint azt általában szoktam. Odárkát megdicsértem az ablakok megtisztításáért és megbíztam a folyosón levő virágok gondozásával.<br><br>
    E napon tekintettel a betegeinket körülvevő egyre félelmetesebb veszélyekre Dr. Fedinec hazaengedte Breznay András atyát, Bugir Mihályt és Maszlej Mihályt.<br><br>
    Ebéd után püspök urunkat meglátogatta Vaszkó Péter atya, akit a tragikus események után többször kihallgattak a rendőrség és a belügyi szervek emberei.<br><br>
    Az érdekelte őket, miért nem kísérte el ő is a vendégeit, kik voltak a gonosztevők, milyen a hangulat a faluban, mit beszélnek az emberek stb. Elmesélte, hogy a tragédia utáni héten szinte állandóan zaklatták. A parochus megsemmisítése a kezükre játszott volna a bűnös nyomok minél gyorsabb eltűntetésében.<br><br>
    Péter atya elsírta magát, amikor meglátta püspök atyánkat szájában a fém kapcsokkal. Mint jó gyermekét, úgy nyugtatta őexcellenciája a kétségbeesettet: "Ne sírj Péter, tűrni és vért ontani az Istenért, a hitért, a szent katolikus Egyházért nagy kegyelem és megtiszteltetés."<br><br>
    Már elmenni készült, amikor püspök atyánk megbízta: "Légy szíves Péterkém, kérd meg nevemben az apósodat, az idős Dániel atyát, látogasson meg bennünket a legszentebb Oltáriszentséggel. Nagyon hálás lennék érte." Péter atya, miután megígérte, hogy a püspök atya kívánságát teljesíti, elbúcsúzott és Dániel atya feleségével együtt elhagyta a kórházat.<br><br>
    Este meglátogatott bennünket Dr. Bergman, bár ez az éjszaka sokkal nyugodtabb volt az előzőnél.<br><br>
    Október 31-én, pénteken korán reggel megérkezett Dániel várva várt édesatyja a legszentebb Oltáriszentséggel. A betegszobában nagy ünnep volt. Püspök atyánk meggyónt és magához vette az Oltáriszentséget. Dániel atya továbbra is olyan állapotban volt, hogy Isten akaratában megnyugvást kereső édesapja csak megáldani tudta. (Nem sokkal később az idős Dániel atya is az ungvári börtönben halt meg.)<br><br>
    Ebédidőben megérkezett püspök atyánk két leánytestvére Nagybocskóról. A beteg azzal vigasztalta aggódó testvéreit, hogy már sokkal jobban érzi magát. Üvegcsövön keresztül megitta az otthoni kakaót, érdeklődött hozzátartozói felől és megígérte, amint felépül, ha az Úr is úgy akarja, hazalátogat egy kicsit megpihenni. Miután elbúcsúzott tőlük, nyugodt álomba merült. Ekkor én is a zárdába mentem egy keveset pihenni, hogy az éjszakai ügyeletre felkészüljek.<br><br>
    Visszatértemkor egy jogászt találtam betegeim ágya mellett, aki püspök atyánkat kérdezte, hogy mire emlékezik a tragédiából. Püspök atyánk azt válaszolta, hogy semmire. Az utolsó emléke az, hogy beült a lovas kocsiba, a következő a kórházi ágyon való ébredés.<br><br>
    A jogász távozása után nedves törülközővel felfrissítettem megizzadt testét és segítettem megvacsorázni. Dániel atyát drága felesége látta el és gondozta. Ő később ismerőseihez ment éjszakára. Én betegeimmel egyedül maradtam.<br><br>
    Püspök atyánk homlokáról patakzott a verejték. Alig töröltem le puha gyolccsal a csillogó gyöngyszemeket, máris újak borították a homlokát. Eltűnődtem és meghökkenve gondolkoztam, hogyan lehetséges ez, hiszen idáig még nem láttam őt így verejtékezni. Nem tudtam felfogni mi történt. Később megértettem. Ezek a ragyogó, apró kis verejték cseppek utolsók voltak a tiszta, szent, türelmesen szenvedő mártírunk homlokán. Közben kopogtattak. Szerzetünk tisztelendő főnöknő anyja -- Gerevics Ignácia -- jelent meg az ajtóban. Nagyon csodálkoztam, hogy ilyen késői időpontban érkezett Ungvárról, hogy betegünket meglátogassa. Ezt szóvá is tettem. Ő üdvözölte püspök atyánkat és szerényen bocsánatot is kért. Késését azzal indokolta, hogy Bergman főorvos tartotta fel az udvaron.<br><br>
    "És mit akart?" -- bátorkodtam megkérdezni.<br><br>
    "Elmondta, mennyire sajnálja betegeinket, szeretne segíteni, de hogy Teofila nővér nem fogadja el ajánlásait. Panaszkodott, hogy egyszerűen figyelembe sem veszi utasításait. Kérte, hogy legalább egy éjszakára váltsam fel önt nővéreinkkel, akik szívesen virrasztanának püspök atyánk és Dániel atya ágyánál. Ki kell pihennie magát, hogy nappal el tudja látni feladatait."<br><br>
    "Mit válaszolt neki, drága anyám?"<br><br>
    "Megígértem, teljesítem kérését." -- válaszolta csendesen Ignácia anya.<br><br>
    "Anyám! Nagyon kérem, ne tegye! Tessék elhinni, nem fáradok el e türelmes betegek mellett."<br><br>
    Biztos voltam abban, hogy főnöknő anyánk mit sem tud a fenyegető veszélyről, mely egyre nyilvánvalóbbá vált számomra. Kedves főnöknő anyánk a püspök atyához fordulva kérdezte: "Mit tegyek? Kire hallgassak excellenciás atyám?"<br><br>
    "A főnöknő anya akarata számunkra parancs. Igaz nővérke?" -- volt a válasz.<br><br>
    Mintha megbénultam volna, egy szót sem tudtam kipréselni magamból. Megértettem, nincs többé jogom alkudozni. Lehajtottam fejemet, hogy ne lássák könnyeimet.<br><br>
    A mi jó, rendszerető és szigorú atyánk így folytatta: "Igaz nővérke, menjen és pihenje ki magát. Mi pedig megpróbálunk egy kicsit szunyókálni. Áldja meg az Úristen önfeláldozó ápolásáért, irántunk tanúsított figyelméért.<br><br>
    Megáldott, én pedig meghatódottságomban térdre borulva csókoltam meg rózsafüzérrel átfont áldó kezét. Majd felállva halkan suttogtam: "Dicsértessék a Jézus Krisztus."<br><br>
    Főnöknő anyánk is búcsút vett, akit püspök atyánk szintén megáldott, és kimentünk a szobából. A folyosón már várt a két Bazil rendi nővér, akik engem jöttek felváltani. Sajnos nem beszélhettem velük bővebben. Súgva kértem őket, vigyázzanak, ne hagyják magukat befolyásolni, óvakodjanak a főorvos fondorlataitól, egy percre se hagyják magukra szenvedő betegeinket. Mint később elbeszélték, amint bementek a kórterembe, leültek csendesen imádkozni, mivel betegeink csendesen szunyókáltak.<br><br>
    Mi Ignácia anyával a kápolnába mentünk imádkozni. Később bezártuk a kápolnát és átmentünk a klauzurába. Alig kezdtünk beszámolni egymásnak aggodalmainkról, mikor a bejárati csengő megszólalt. Szaladtam ajtót nyitni. Szomorú hírt kaptunk: drága püspök atyánk haldoklik. Visszarohantunk a sebészetre, de sajnos hiába. Nem volt segítség. Dr. Fedinec és az ügyeletes Dr. Miskolci szintén odasiettek. Adrenalint fecskendeztek a szívizomba, de minden igyekezetük hiába való volt. A mi szeretett Teodor püspök atyánk örökre elaludt.<br><br>
    Tanácstalanul kezdtük faggatni a nővéreket a történtekről. Ők sírva mesélték: alighogy elmentünk, megjelent a főorvos és helyettese, éjjeli vizitet tartottak. Dr. Bergman parancsoló mozdulattal kitessékelte a nővéreket a folyosóra és ott utasította őket, hogy tartsanak vele. Hiába próbálták meggyőzni a főorvost, hogy ők önként vállalták a betegek melletti ügyeletet. Az szúrós szemmel elfojtott hangon förmedt rájuk: "Megparancsolom, hogy utánam jöjjenek mindössze öt percre!". Visszatérve, valóban 5-8 perc múlva, besiettek a kórterembe. Megnyugvásukra a betegeket ugyanolyan helyzetben találták, ahogyan hagyták. Remegve súgták egymásnak: "Hála Istennek! Semmi sem történt." Abban a pillanatban sóhajt hallottak: "Oh Jézusom!" és az ezt követő erős, az egész testet megrázó görcs örökre befejezte a jóságos szív működését.<br><br>
    Elkeseredve, lelkünk mélyéig elszomorodva vizsgáltuk végig kezét, lábát, egész testét, hogy nem látható-e rajta a halál okozója.<br><br>
    Feleszmélve Bacsinszky atya kapcsolódott tanácskozásunkba mondván: "Volt itt egy lány és püspök atyánk orra alá tartott valamit." Nem volt időnk tovább kérdezősködni, mert Dániel atya ismét elaludt. Dr. Fedinec feltételezte, hogy a méreg az orron, a nyálkahártyán került a szervezetébe. Ezt látszott igazolni a megboldogult orrától kezdődő kékülés is. A két orvos (természetesen csak egymás közt) megállapította, hogy a gyilkos szer "cián kálium" lehetett, melynek hatására bizonyos idő múltán (kb. 10 perc) fulladásos halál állt be.<br><br>
    Bánatosan, szomorúan, de Isten akaratába beletörődve virrasztottunk reggelig püspök atyánk mellett a kórteremben. Dr. Miskolci értesíteni akarta a főorvost. Feltárcsázta Dr. Bergman telefonszámát és akaratlanul kihallgatta amint Bergman valakinek bejelentette: "A rámbízott feladatot teljesítettem." Az ügyeletes orvos csöndesen, gyorsan letette a kagylót és csak reggel jelentette a főorvosnak: "Az éjjeli vizit után nem sokkal, azaz fél egykor Romzsa Teodor betegünk elhunyt."<br><br>
    A szerencsétlen gyilkos -- Dr. Bergman -- bejött a sebészetre meggyőződni tettének sikeréről. Nekünk kifejezte együttérzését és megengedte, hogy püspök atyánkat az ágyon reverendába öltöztessük, sőt azt is, hogy miután megkapjuk a koporsót, a püspök atyát a kápolnában felravatalozzuk. Azt is megengedte, hogy aki szeretne elbúcsúzni és végső tiszteletét a halottnak megadni, azt kórházi kápolnánkban megteheti. Úgy látszik emberségességét kívánta ezzel bizonyítani.<br><br>
    Így is történt. November 1-én, szombaton egész nap és a rákövetkező vasárnap délig a mi kedves halottunk elárvult gyermekei között lehetett a munkácsi kórház kápolnájában.<br><br>
    A kórház betegei szomorúan szorongtak a kis kápolnában. Odárka gyakran leszaladt körülnézni. Keserű könnyeket ejtett a ravatal mellett...<br><br>
    November 2-án, vasárnap ebéd után összeült egy hét orvosból álló bizottság. Ezt a területi Egészségügyi Hivatal ungvári orvosaiból toborozták.<br><br>
    Püspök urunk holttestét átvitték a kápolnából a boncoló terembe. Arra már nem emlékszem, ki végezte a boncolást, csak arra, hogy a mi orvosaink közül bekérették a sebészeti osztály vezetőjét, Dr. Fedinecet és az éjszakai ügyeletes orvost, Dr. Miskolcit. A bizottság megállapította, hogy a halál oka agyvérzés volt.<br><br>
    Dr. Fedinec meggyőződése ellenére kénytelen volt aláírni ezt a hamis diagnózist, amiért aztán élete végéig kínozta lelkiismerete.<br><br>
    Boncolás után felöltöztettük drága vértanúnkat püspöki rendjéhez méltó ornátusba, majd ezután nagy tömeg kísérte a görögkatolikus templomba. A hatóságok rendelkezése szerint egyelőre a munkácsiba. Ungvárra sötétedés után engedélyezték az átszállítását. (Bizonyára azért tették ilyen késői időpontra, hogy minél kevesebb nép legyen a környéken.)<br><br>
    A gyászkíséret püspök atyánk katafalkjával[2] az éjszaka kellős közepén érkezett meg az ungvári görögkatolikus székesegyházhoz. Bár a hatóság mindent megtett annak érdekében, hogy minél csendesebb és észrevétlenebb legyen a hazatérés, a katedrális mégis megtelt a hívőkkel, akik sírva, zokogva várták a görögkatolikus hitért mártírhalált halt szeretett püspök urunkat.<br><br>
    Munkácsról Ungvárra egy nyitott teherautón szállították a koporsót. Püspök atyánkat pap testvérei és Bazil rendi nővérek kísérték. Az előbbiek kezükben vitték be koporsóját a székesegyházba, a nővérek pedig, miként az úton, a katedrálisban is égő gyertyákkal álltak a ravatal két oldalán.<br><br>
    Kárpátalja elárvult népe nehéz szívvel búcsúzott egész éjjel és a következő napon (november 3-án, hétfőn) drága atyjától. A temetés november 4-én volt. A Szent Liturgiát a teológusok énekkara énekelte. Drága halottunkat lélekbe markolóan búcsúztatta Chira Sándor prelátus atya. Püspök atyánk földi maradványait a katedrális alatti kriptában helyezték örök nyugalomra. Emléke örökké élni fog! Nyugodjon békében! Rendíthetetlen erős lelke örökké velünk van!<br><br>
    A szerencsétlen Odárka elkéredzkedett a temetésre és soha többé nem tért vissza a munkácsi kórházba. Hogy valóban volt-e a temetésen, nem tudom. Én közben Ignácia anyámnak. valamint Chira prelátus atyának óhaja szerint Bacsinszky atya ágya mellett maradtam.<br><br>
    A munkácsi gimnázium egykori hitoktatója, a fiatalok kedvence és barátja, a lelkipásztori tevékenységben buzgó és fáradhatatlan Bacsinszky Dániel még sokáig maradt kórházunkban. A lábtörés alaposan megkínozta. Három hét múlva a gipszkötésen genny szivárgott ki. A gipszpólya felvágása után szörnyű látvány tárult elénk. A ferdén tört csontok és csont szilánkok gennyben úsztak. Az isteni gondviselés segíthette Dr. Fedinec Sándort, hogy sikerült megmentenie ezt a lábat és betegünk életét. Doktorunk megszerezte az akkor még kísérleti penicillint, ami abban az időben nem volt könnyű feladat. A seb szépen tisztult, ezután a lábat ismét gipszágyba helyezték. Egy hónap múltán a nyílt seb a lábon begyógyult. A beteg közérzete javult. Ekkor történt egy esti átkötözés alatt (amit eleinte Dr. Fedinec végzett, majd később a műtős nővér) a következő baleset. Áramszünet miatt a nővér, hogy munkáját folytatni tudja, gyufát gyújtott, s egy szikra lángra lobbantotta a vattát a beteg lábán. Az égési sebek jobban megkínozták Dániel atyát, mint a törés. Még kezén az ujjai is megégtek, mikor a nővér az égő vattát próbálta a beteg lábán eloltani. Dániel atya csodálatosan tűrte szenvedéseit. A hitért, a hívőkért, a bűnösökért ajánlotta fel azokat. Csendes szenvedése mindenkit megrendített. Három hónapig feküdt kórházunkban.<br><br>
    1948. január 24-25 körül felesége kívánságára hazaengedték Ungvárra, kedves családjához a ceholnyai parókiára.<br><br>
    Később. 1949. június 21-én letartóztatták és tíz évre ítélték. 1955-ben szabadult aláásott egészséggel. Ezután gyári munkásként dolgozott. 1968-ban december 12-én szívinfarktus következtében halt meg az Ungvári Városi kórházban.<br><br>
    Az ungvári hívők, főleg az akkori fiatalság ma is szeretettel gondol szentbeszédeire, istentiszteleteire, jóságára. Emléke örökké élni fog szívünkben. Az örök világosság fényeskedjék neki, nyugodjék békében!<br><br>

    <strong>Ungváron, 1989. november 1-én</strong><br><br>

    <h3>Kiegészítés</h3>
    Ahhoz, hogy teljesebb képet kapjunk ellenségeink sötét terveiről, úgy érzem, nem hiábavaló papírra vetnem az alább következő sorokat.<br><br>
    1948. január 26-án letartóztattak. A hatóságok e lépése meglepett, hiszen soha sem követtem el törvényellenes dolgot. A letartóztatási parancs szerint, amelyet aláírattak velem, szovjetellenes sajtótermék terjesztéséért vettek őrizetbe. Ez a "sajtótermék" mindössze egy "Jézus Szíve Naptár" volt, melyet 1928-ban adtak ki a Szt. Bazil rendi atyák Zsóvkvában. Az említett könyvecskét kölcsönkérte tőlem egy munkácsi asszony, aki mint kórházunk sebészetének betege minden reggel lejött kápolnánkba. Rosszat nem tételeztem fel róla.<br><br>
    A naptárban volt egy másfél oldal terjedelmű cikk "Bolsevikok" címmel. Ezzel bizonyították bűnösségemet, holott én még a tartalmát sem ismertem, csak később a börtönben olvashattam el, amikor a nyomozó bűnösségem alátámasztására megmutatta. Az írás szerzője arra kérte, szólította fel a népet, buzgón imádkozzanak szegény orosz testvéreinkért, akik a kommunizmus igájában sínylődnek. Ecsetelte az 1927-es évet, az éhezés évét, mely nemcsak Ukrajna, de az egész Szovjetúnió területén szedte áldozatait.<br><br>
    Az ungvári börtönből rövid idő múlva, március 6-án, Nyikityin nyomozó és két civil ruhás őr kíséretében, repülőgépen Kievbe szállítottak. Ott a Korolenko út 33-as számú épületének belső börtönében egy pici, sötét cellának lettem egyedüli lakója.<br><br>
    A nyomozó osztály főnöke, Haritonov, foglalkozott ügyemmel. Már az első éjszakai kihallgatáson kinevetett, amikor arról beszéltem, hogy egy könyv miatt tartóztattak le. Azt mondta: "Ez csak egy csali volt az ügyes halacska kifogására.' -- most fontosabb tevékenységeimről fogunk tárgyalni.<br><br>
    "Arról meséljen, mi történt a maguk püspökével?"<br><br>
    Én őszintén beszámoltam a járművek összeütközéséről, a dzsipből kiugró gyilkosokról, akik a sebesülteket vasrudakkal igyekeztek a másvilágra küldeni.<br><br>
    "Mit csináltak velük, miután a postaautó beszállította őket?"<br><br>
    "Akinél arra szükség volt, megműtötték."<br><br>
    "A püspök hol sérült meg?"<br><br>
    "Törést szenvedett az alsó állkapcsán, kiverték fogait."<br><br>
    "Milyen állapotban vitték be Bacsinszkyt?"<br><br>
    "Nála koponyaalapi törést, lapocka- és bordatörést és a jobb láb két csontjának spirális-szilánkos törését állapították meg."<br><br>
    "És a többiek?"<br><br>
    Aprólékosan, pontosan elmondtam amit tudtam. Majd arra is feleltem, hogy ki végezte a műtéteket.<br><br>
    "Kik jártak be látogatni?"<br><br>
    "Püspök urunk édestestvérei, Chira Sándor prelátus atya, a mi munkácsi papjaink, de minden látogatót nem láttam, mivel nappal én az egész kórház területén láttam el feladataimat."<br><br>
    "Mi volt a maga munkája?"<br><br>
    "Főállásban adminisztrációs főnővérként, mellékállásban a sebészeti osztály éjjeli ügyeletes nővéréként dolgoztam."<br><br>
    "Így éjszakánként is fél műszakot teljesített?"<br><br>
    "Igen."<br><br>
    "Hát ennyire igyekezett, hogy püspökét a másvilágra segítse?"<br><br>
    "Hogy mer engem ennyire megsérteni, megbántani?" -- kérdeztem.<br><br>
    "Ez sértés? Be fogjuk bizonyítani magának, hogy ez a valóság. Rendben van, erről majd később beszélgetünk."<br><br>
    Egy fél évet töltöttem magánzárkában. Csak éjjel vittek kihallgatásra, s minden éjjel a tragédiával kapcsolatban kérdezősködtek. Haritonov kollégái is segítettek. Ketten, hárman, volt mikor négyen is. Mocskos, gúnyos szavaikkal, kétértelmű anekdótáikkal teljesen kimerítettek.<br><br>
    Igyekeztek a beszédet arra a lányra terelni, aki a sebészeten olyan szokatlan módon jelent meg abban az időben. Én nyilván nem akartam megérteni próbálkozásaikat. Elhatároztam, kivárom, amíg ők említik először.<br><br>
    A hatodik hónap végén, amikor már alig lézengtem az átélt tortúráktól, ismét éjszakai kihallgatásra vezettek. Haritonov szobájában rajta kívül három személy is ült.<br><br>
    "Barátaim hallani akarják, hogyan halt meg a maguk püspöke. Beszéljen!"<br><br>
    "Nem tudom." -- válaszoltam.<br><br>
    "Hogyan?"<br><br>
    "Püspök urunk halálának okát nem ismerhetem. Azt azonban tudom, hogy negyedik nap, amikor testvérei meglátogatták, dicsekedett, hogy már sokkal jobban érzi magát, mint az elmúlt napokban."<br><br>
    "Hogyan lehetséges hát, hogy még azon az éjszakán meghalt?"<br><br>
    "Nem tudhatom, azon az éjszakán nem voltam ügyeletes."<br><br>
    "Ki volt az ügyeletes?" -- ordította Haritonov.<br><br>
    "Többen voltak, név szerint nem emlékszem, de megnézheti az éjjeli ügyelet naplóját."<br><br>
    "És hol volt az a lány, akit maguk segítségül felvettek?" -- kiáltott közbe a három idegen közül az egyik "bezpekás"[3]<br><br>
    "Mi senkit sem alkalmaztunk, de azokban a napokban valóban dolgozott nálunk egy "szanitarka", akit a főorvos létszámon felül alkalmazott."<br><br>
    "Ő hol tartózkodott azon a kritikus éjszakán?" -- ordított ismét Haritonov.<br><br>
    "A főorvos utasítására fekvőhelye a sebészeti osztály gyógyszer raktárában volt." -- válaszoltam.<br><br>
    "Ő hol volt az éjjeli vizit alatt?"<br><br>
    "Nem tudom!" - válaszoltam.<br><br>
    "Ezek szerint mi többet tudunk, mint maga. Ő ölte meg a püspököt!"<br><br>
    "Hogyan? Mi módon?" -- kérdeztem a meglepetéstől, azt hallván, hogy ők maguk is az igazat állítják.<br><br>
    "Azt majd elmondja ő magának. Zárkája a magáéval szomszédos. Eléggé nyugtalan, hisztériás, nem ilyen nyugodt, mint maga, ezért vele nem lehetünk liberálisak, nem vehetjük le róla a bilincseket. Tudomásunk szerint nem egyedül ölte meg a püspököt."<br><br>
    Hallgattam és készültem a halálra. Úgy éreztem, nem bírom elviselni tovább a hozzám vágott igazságtalanságaikat, elmondom, szemükbe vágom az igazságot. De használok-e ezzel drága mártírunk dicsőségének? Nem vonok-e sok ártatlan embert magam után?<br><br>
    "Miért hallgat? Nem tudja, ki volt a lány segítőtársa? Ön, tisztelt anya! Igen maga, maga, maga!" -- üvöltötték mindnyájan.<br><br>
    "Nem kerül ki élve a kezünkből, amíg alá nem írja, hogy közreműködött a püspök meggyilkolásában!"<br><br>
    "Soha! Még ha itt élve darabolnak fel, akkor sem! Egy kis madárkától sem tudnám az életét elvenni és maguk azt akarják, hogy püspök atyánk meggyilkolásában részt vállaljak? Soha!"<br><br>
    "Nem akarja? Hát mi megtaláljuk a módját, bebizonyítjuk a gyilkosságban való résztvételét. Majd szembesítjük Odárkával."<br><br>
    Haritonov felvette a kagylót és beleordított.<br><br>
    "Hozzák be Odárkát!"<br><br>
    "Várjanak egy kicsit!" -- adott újabb utasítást a telefonba kollégája!<br><br>
    "Rábírjuk mi a beismerő vallomás aláírására anélkül is." -- tette hozzá harmadik társuk.<br><br>
    "Nem hiszem." -- mondtam csendesen.<br><br>
    "Nem? Odárka emlékeztetni fogja önt első éjszakai beszélgetésükre, amikor őszintén feltárta lelkét magának."<br><br>
    "Erre emlékszem, no és? Én is emlékeztetem válaszaimra, amelyek egyáltalán nem tetszettek neki."<br><br>
    "Eddig miért nem beszélt róla?"<br><br>
    "Mert nem kérdezték."<br><br>
    "Hogy hogy nem?! Én számtalanszor kérdeztem. Nem volt-e maguk között idegen medikus abban az időben?" -- ordított Haritonov.<br><br>
    "Igen, ilyen kérdést én valóban kaptam, csakhogy az a fiatal leányka nem volt és nem lehetett még medikus. Hisz őszinte vallomásában elárulta, hogy tizenhárom éves korától az erdőben a Bonderócok között tartózkodott, hát hol végezhetett egészségügyi iskolát, vagy legalább is tanfolyamot?"<br><br>
    "Szóval megtudta, hogy ő 'Bonderovka', erdei szökevény, a kommunizmus ellensége, de hallgatott róla, tehát részese lett a gyilkosságnak."<br><br>
    "Ez nem felel meg az igazságnak! (Határozottan és erélyesebben válaszoltam.) Még ugyanazon a napon Hilária főnővérrel bementünk a főorvos irodájába, ahol jelen volt titkárnője is és én részletesen beszámoltam Dr. Bergmannak Odárka éjjeli vallomásáról. Figyelmeztettem a lány ottlétének veszélyeiről is, hogy meglophatja a gyógyszertárt, stb."<br><br>
    Ezt hallván a nyomozók rendkívül idegesen egymásra néztek, majd mérgükben a robbanásig zavartak lettek. Szinte tomboltak, amikor rájöttek, hogy előre felépített tervük összedőlt. Úgy látszik Dr. Bergman nem számolt be nekik jelentésemről, s azért biztosra vették tervük sikerét.<br><br>
    "Miért nem értesítette a milicista(-rendőri) szerveket erről?" -- kérdezték.<br><br>
    "Nem tudtam az arra vezető utat. Annak mondtam el, aki őt munkára felvette."<br><br>
    Haritonov olyan erővel csapott az asztalra, hogy onnan minden lerepült. Ez után felvette ismét a kagylót és kiadta a parancsot: "Azonnal szállítsák Bergmant Kievbe."<br><br>
    Majd tehetetlenségükben, azt hangoztatva, hogy sajnálnak, mert fáradt vagyok, visszavezettettek a cellába. Alig, hogy kiléptem a folyosóra, az őrök jelezték egymásnak, hogy rabot kísérnek. Ilyenkor, hogy a foglyok ne lássák egymást, az egyiket rögtön a folyosón sűrűn elhelyezett fémszekrénybe tuszkolták. Ez alkalommal engem tuszkoltak az egyik szekrénybe. Alighogy bekerültem a "box"-ba, melyben csak egy ember férhetett el állva, rögtön elaludtam és különös szép álmot láttam.<br><br>
    A munkácsi kórházban voltam. Valaki csenget zárdai lakásunk bejáratánál. Szaladok, hogy kinyissam az ajtót és meglepetésemre a mi drága Mártírunk, Teodor püspök áll előttem, reverendában, egy levéllel a kezében. Tekintete bizalomkeltő, jóságos, valóban atyai volt. (Közben tudatában voltam annak, hogy nem él, s éppen az ő tragikus halála miatt szenvedek.) Kértem jöjjön be a társalgóba, de ő egy árva szót sem szólva kezembe nyomta a levelet, majd egy pillanatig fejem felett tartva kezeit, megáldott és karjait feljebb emelve, mint életében amint "Emeljük fel Szívünket" soroknál tette a Szent Liturgiában, könnyedén felemelkedett a földről és eltűnt. Elkeseredve, hogy már nem látom, kinyitottam a levelet és az ő halálának értesítője volt. Ugyanaz a nyomtatvány, mely a mi nyomdáink egyikében készült. A gyászjelentés a kezeimben nőni kezdett. Pillanatok alatt akkora lett, hogy széttárt karjaimmal alig tudtam megtartani. Végre megállott előttem, mint egy fehér film vetítő vászon és a gyászjelentés szövege helyébe ragyogó, arany betűkkel ez jelent meg: "Dicsősége hirdetését hagyjad a jövőnek." Alatta püspök atyánk kereszttel ellátott aláírása. Ebben a pillanatban kinyílt a box ajtaja és a börtönőr tovább vezetett a cellám felé. A mai napig sem tudom elfelejteni azt a boldogságot, amit akkor éreztem. Gyógyír volt számomra ez az álom. Csodálatos lelki és testi erőt adott a börtönben lévő következő napokra és egész eddigi életemre.<br><br>
    Akkor értettem meg, hogy az Úr nem kívánja tőlem azt a hősiességet, hogy a hitetleneknek az igazságot bebizonyítsam. Megértettem, hogy addig kell hallgatnom róla, amíg az Anyaszentegyháznak lesz vallomásomra szüksége. Megerősödve, mint az apostolok a Szentlélek Úristen eljövetelének napján, tudtam hogyan kell a továbbiakban viselkednem. Végtelenül megkínzott lelkemben felébredt a remény szikrája. Még élnem kell, mert eljön az idő, amikor tanúskodnom kell majd tiszta szívű püspök atyánk utolsó napjairól.<br><br>
    Csodálatos álmom után rólam két hétig megfeledkeztek. Isten kegyelmével felbuzdítva, éjjel-nappal hálát adtam az isteni Gondviselésnek, hogy azon a bizonyos napon találkozhattam Chira Sándor prelátus atyával és Brekó András atyával a kórház udvaron, s tanácsot kérhettem tőlük Odárkával kapcsolatban. Okos tanácsukért életem végéig hálás maradok. Imáimban egészségükért fohászkodtam a Jóistenhez, hogy találkozhassunk és személyesen megköszönhessem közvetítésüket a bölcs isteni Gondviselés és az én gyarlóságom között.<br><br>
    Kívánságom teljesült. Hála legyen égi Szűz Anyánknak, állandó segítségéért és gyámkodásáért, amit éreztem nehéz időkben különösen, de egész életemen át.<br><br>
    Két hét múlva meglátogatott a börtöni orvosnő az ápolónővel. Figyelmesen megvizsgált és kedvesen elbeszélgetett velem egészségemmel kapcsolatos problémáimról. Megígérte, hogy mivel nagyon gyenge vagyok, fekvést rendel és táplálóbb kosztot is ír ki számomra. Súlyosbodó egészségi állapotomra való tekintettel javasolni fogja főnökeinek, hogy helyezzenek át hozzám egy fogoly asszonyt, aki ápolna és mozgásban is kissé segítene. Így került hozzám egy fiatal "Olja" nevezetű fogoly. Bemutatkozott, mint a múltban, a munkácsi kórházban Odárka, hogy az Ukrán Nacionalista Mozgalom tagja volt, s emiatt került ide. Viselkedése velem szemben valóban nagyon előzékeny, kedves és figyelmes volt. Makacsul ismételgetett kérdéseiből azonban hamar rájöttem, hogy ő is besúgó, a KTB munkása, mint Odárka volt. Egy hónapi együttlét alatt minden igyekezete ellenére sem tudott meg tőlem többet, mint a nyomozók.<br><br>
    Amikor elvitték tőlem, Haritonov még három napon át hivatott, de csak nappal. Elővéve azt az ungvári vékony iratcsomót, amelyben szovjet ellenes irodalom terjesztésével vádoltak, gyors ütemben igyekezett ügyemet befejezni. Se az Odárkával való szembesítésről, se Dr. Bergmannak Kievbe jöveteléről, de még a megboldogult püspök atyánkról sem esett többet szó. Azt a vastag irattömböt, amely félévi kievi kihallgatásaim anyagait tartalmazta, szintén nem láttam többé.<br><br>
    Egy pár nap múlva bejött cellámba a börtön főnök egy irattartóval és felolvasta az Öttagú Moszkvai Bíróság ítéletét. Eszerint tíz évre ítéltek a büntető törvénykönyv 54/10-es paragrafusának 2-ik cikkelye alapján. Büntetésemet javító munkára alakított speciális táborban kell letöltenem.<br><br>
    Aznap hordágyon elszállítottak a lukjánovói elosztó táborba, ahol még egy hónapig tartottak. Innen a mordovai táborokba szállítottak, ahol kórházban feküdtem fél évig. Hála a Jóistennek és égi, jóságos Szűzanyánknak, felerősödtem után ugyanabban a kórházban alkalmaztak ápolónőként.<br><br>
    Sztalin halála után ügyemet felülvizsgálták és a Legfelsőbb Bíróság 1955-ben hét év, hét hónap és egy nap börtön és láger után felmentett. Jelenleg rehabilitálva vagyok.<br><br>
    A múltat idézve, mindég álmom jut eszembe, mely a legnehezebb helyzetben megerősített és megmentette az én és rendtársaim szerzetesi becsületét a borzalmas rágalomtól, amit ellenségeink püspök atyánk meggyilkolásával kapcsolatosan felépítettek.<br><br>
    Ezenkívül kötelességemnek tartom, hogy felhívjam egyházi elöljáróink figyelmét a halál előtti jelenségre, amely apró igazgyöngyszerű és fényű izzadságban jelent meg püspök atyánk homlokán. Negyvenkét évig voltam kórházi ápolónővér. Számtalan beteget láttam. Sok haldoklót ápoltam, de ilyen jelenségre nem emlékezem. Már akkor is éreztem, hogy nem mindennapi jelenségnek vagyok tanúja, amikor Ignácia anya belépett. Látván a szaporán ismétlődő gyöngyszerűen csillogó verejték cseppeket, idáig ismeretlen aggódó töprengés fogott el. Nem sokkal később, amikor tanácstalanul virrasztottunk megboldogult püspök atyánk felett, megértettem, hogy nem egyszerű földi halandót ápoltam. Ezen érzések közben vádolom magamat, amiért nem őriztem meg a Mártírunk verejtékével átitatott értékes gyolcs darabokat. Ezért midőn felöltöztettük reverendába excellenciás atyánkat, összegyűjtöttem a halottas ágyról a maradék kötszereket. Kivágtam Mártírunk reverendájának belső hajtásaiból kis darabokat, majd néhány tincset a hajából is. Temetése után ebből az anyagból szerzetes nővéreimmel együtt szív alakú ereklyéket varrtunk és szétosztottuk a megboldogult legközelebbi rokonai, paptársai és a nővérek között. Az én szívecskémet a börtönőr sajnos megtalálta és elvette.<br><br>
    Felidézve a tragikus történelmi eseményeket, amelyek 1947-ben érték görögkatolikus püspökségünket, beszámolóm végére értem. Célomat elérve felkiáltok mint Simeon tette: "Most bocsásd el Uram szolgádat..."<br><br>
    Továbbra is égi, jó Szűzanyánk palástjának védelmébe ajánlva magamat és sokat szenvedett népünket, tiszta szívvel, fáradhatatlanul kérek teljes értékű vallásszabadságot a munkácsi görögkatolikus egyházmegyénknek, valamint minden egyes katolikus egyházunknak a nagy Szovjetúnióban.<br><br>
    Mi hiszünk az ima mindenhatóságában. Azért megpróbáltatásaink kemény útján az ungvári Ceholnyai dombocskán, akár zuhog az eső, vagy tombol a tél, jó vagy rossz időben a nyílt ég alatt buzgón imádkozzuk és énekeljük:<br><br>
    "Édes jó Anyánk, mennyei Pátrónánk,<br>
    Könyörögj érettünk szent Fiadnál,<br>
    Hogy Kelet a Nyugattal egységben<br>
    Zengje a hála énekét békében!"<br><br>
    <strong>Ungváron, 1989. november 1-én</strong><br><br>
    <strong>M. Teofila O.S.B.M.</strong><br><br>
    * * *<br><br>
    Hálával, imáimmal s szeretettel gondolok Dr. Bártfay István hajdani ügyvéd és vármegyei főügyészre, aki többször buzdított a visszaemlékezés megírására. Később, halála előtt nem sokkal, már betegen, fordította történelmi vallomásomat ukrán nyelvről magyarra.<br><br>
    "Örök világosság fényeskedjék neki! Nyugodjék békében!"<br><br>

    1 "Szanitarka" sajátságos szovjet egészségügyi beosztott, aki mind a betegellátó, mind a takarítónő feladatait látja el.<br><br>
    2 Katafalk a holttest ünnepélyes felravatalozásához használatos díszes, magasabb állvány.<br><br>
    3 "Komitet derzsavnoji bezpeki": Állambiztonsági Bizottság. Az ukrajnai KGB, ÁVO. Rövidítve egyszerűen "bezpeká"-nak nevezték. Ezt a szót a kárpátaljai magyarok is átvették, az ávósokat "bezpekásoknak", vagy kék parolijuk után "kékeknek" nevezik.<br><br>
@endsection