<h2>Bérmálkozás</h2>

A bérmálás szentsége a keresztséggel és az Eucharisztiával együtt alkotja a "keresztény beavatás szentségeinek" együttesét, melynek egységét őrizni kell. Meg kell tehát magyarázni a híveknek, hogy a bérmálás fölvétele szükséges a keresztségi kegyelem teljessé válásához. A keresztények ugyanis "a bérmálás szentségével még tökéletesebben kötődnek az Egyházhoz, a Szentlélek különleges ereje tölti el őket, ezért szigorúbb a kötelezettségük, hogy Krisztus igazi tanúiként szavukkal és életmódjukkal terjesszék és védelmezzék a hitet".<br><br>

<strong>A bérmálás az üdvösség rendjében </strong><br><br>
Az Ószövetségben a próféták hirdették, hogy az Úr Lelke meg fog nyugodni a várt Messiáson üdvözítői küldetése miatt. A Szentlélek leszállása Jézusra, amikor Őt János megkeresztelte, jel volt arra, hogy Ő az, aki eljövendő volt, Ő a Messiás, az Isten Fia. Jézus a Szentlélektől fogantatott; egész élete és egész küldetése teljes közösségben volt a Szentlélekkel, akit az Atya Neki "nem mértékkel ad" (Jn 3,34).<br><br>
A Léleknek ez a teljessége azonban nem maradt egyedül a Messiásé, hanem közölni kellett az egész messiási néppel. Krisztus ismételten megígérte a Lélek e kiáradását, és az ígéretet először húsvét napján, majd még ragyogóbban pünkösdkor teljesítette. A Szentlélektől eltelve kezdik az Apostolok hirdetni "Isten nagy tetteit" (ApCsel 2,11); és Péter elmagyarázza, hogy a Léleknek ez a kiáradása a messiási idők jele. Akik akkor hittek az Apostolok prédikációjának és megkeresztelkedtek, elnyerték a Szentlélek ajándékát.<br><br>
"Ettől az időtől kezdve az Apostolok Krisztus akarata szerint az újonnan megkeresztelteknek kézrátétellel közvetítették a Lélek ajándékát, mely beteljesíti a keresztség kegyelmét." Ebből következett, hogy a Zsidókhoz írt levélben az első keresztény oktatás elemei között megemlítik a keresztségről és a kézrátételről szóló tanítást. Ezt a kézrátételt a katolikus hagyományban joggal tekintették a bérmálás szentsége kezdetének, mely bizonyos módon folytonossá teszi az Egyházban a pünkösd kegyelmét."<br><br>
Hogy a Szentlélek ajándékát még jobban kifejezzék, a kézrátételhez nagyon korán kapcsolták a krizmával, a jó illatú olajjal való megkenést. E megkenés megvilágítja a "krisztusi" elnevezést, ami "fölkentet" jelent, és eredetét magától Krisztustól veszi: "Isten kente fel Őt Szentlélekkel" (ApCsel 10,38). A megkenés e rítusa mind a mai napig él Keleten és Nyugaton egyaránt. Ezért nevezik ezt a szentséget Keleten krizmációnak, `krizmával történő fölkenésnek' vagy müronnak, `krizmának'. Nyugaton a confirmatio elnevezés arra utal, hogy ez a szentség egyidejűleg megszilárdítja a keresztséget és megerősíti a keresztségi kegyelmet.<br><br>

<strong>KÉT HAGYOMÁNY: KELET ÉS NYUGAT </strong><br><br>
Az első századokban a bérmálás a keresztséggel együtt általában egyetlen szertartás volt, Szent Ciprián kifejezése szerint "kettős szentség". A gyermekkeresztség gyakorivá válása, éspedig a húsvéton kívül is egész éven át, valamint a plébániák sokasodása egyéb okok mellett lehetetlenné tette, hogy a püspök minden keresztségi szertartásnál jelen legyen. Mivel azonban a keresztség beteljesedését a püspöknek akarták fönntartani, Nyugaton szokásba jött, hogy a két szentség kiszolgáltatását időben elválasztották egymástól. Keleten a két szentséget együtt tartották; a keresztelő pap bérmál. De a bérmálást csak a püspök által megszentelt müronnal lehet végezni.<br><br>
Egy Róma városában honos szokás -- a keresztséget követő kétszeri megkenés a szent krizmával -- elősegítette a nyugati gyakorlat kialakulását. Az első megkenést a pap végezte, aki a keresztségi fürdőből távozó újonnan megkereszteltet azonnal megkente, majd másodszor a püspök kente meg a homlokán. A pap által végzett, krizmával való első megkenés a keresztelés szertartásának része maradt; azt jelenti, hogy a megkeresztelt részesedik Krisztus főpapi, prófétai, királyi hivatalában. Ha a keresztséget felnőttnek szolgáltatják ki, akkor csak egy keresztség utáni megkenés van: a bérmálásé.<br><br>
A keleti egyházak gyakorlata inkább a keresztény beavatás egységét emeli ki. A latin Egyház gyakorlata viszont szemlélteti az új keresztény közösségét a püspökével mint olyannal, aki egyháza egységét, katolicitását és apostoliságát őrzi, és ezáltal biztosítja az összetartozást Krisztus Egyházának apostoli eredetével.<br><br>

<strong>A bérmálás szertartása és jelei </strong><br><br>
E szentség szertartásában figyelmet érdemel a megkenés jele, és az, amit a megkenés jelez és kifejez: a lelki pecsét.<br><br>
A megkenésnek az ókori és a szentírási szimbolikában gazdag jelentése van: az olaj a túláradó bőség és az öröm jele; megtisztít (fürdő előtti és utáni megkenés) és rugalmassá tesz (az atléták és birkózók megkenése); a gyógyulás jele, mert enyhíti a zúzódások és sebek fájdalmát; széppé, egészségessé és erőtől duzzadóvá tesz.<br><br>
Az olajjal való megkenés mindezen jelentései megismétlődnek a szentségi életben. A keresztség előtti megkenés a katekumenok olajával megtisztítást és megerősítést jelent; a betegek megkenése gyógyulás és megerősítés. A szent krizmával való megkenés a keresztség után, a bérmáláskor és a papszenteléskor az Istennek szenteltség jele. A bérmálás által a keresztények, vagyis a "fölkentek" fokozottan részesednek Jézus Krisztus küldetésében és a Szentlélek teljességében -- ami Krisztust eltöltötte --, hogy egész életük Krisztus jó illatát árassza.<br><br>
E megkenés által a bérmálkozó megkapja a "jegyet", a Szentlélek pecsétjét. A pecsét (a mindennapi gyakorlatban) a személy szimbóluma, tekintélyének, tulajdonjogának jele egy tárgyon -- így jelölték meg az ókorban a katonákat a vezéreik és a rabszolgákat uraik pecsétjével --; érvényessé tesz egy jogi aktust vagy egy dokumentumot, és bizonyos körülmények között titkosítja azt.<br><br>
Maga Jézus kijelenti, hogy Ő meg van jelölve Atyja pecsétjével. A keresztény is meg van jelölve egy pecséttel: "Isten az, aki minket veletek együtt megerősít és fölken Krisztusban. Pecsétjével megjelölt minket és foglalóul szívünkbe árasztotta a Lelket." (2Kor 1,21--22) A Szentlélek e pecsétje azt jelenti, hogy az ember egészen Krisztushoz tartozik, végleg az Ő szolgálatába van állítva, de azt is jelenti, hogy ígéretet kapott az isteni oltalomra a végső idők nagy megpróbáltatásában.<br><br>

<strong>A BÉRMÁLÁS KISZOLGÁLTATÁSA </strong><br><br>
Egy fontos cselekmény, mely megelőzi a bérmálás szertartását, mégis hozzátartozik, a krizmaszentelés. Nagycsütörtökön konszekrálja a püspök a krizma-misében az egész egyházmegye számára szükséges krizmát. Egyes keleti egyházakban a krizmaszentelés a pátriárkának van fönntartva:<br><br>
Az antiochiai liturgia így fejezi ki a szent krizma (görögül müron) konszekrálásának epiklézisét: "[Atyánk, (...) küldd el a Szentlelket] ránk és erre az előttünk lévő olajra, és szenteld meg, hogy azok számára, akiket vele megkennek és megjelölnek, szent müron, papi müron, királyi kenet legyen, ragyogó öltözet, az üdvösség köntöse, az élet őrzője, lelki ajándék, a lelkek és testek életszentsége, a szív vigassága, örök kedvesség, fogyhatatlan öröm, sértetlen pecsét, a hit pajzsa és félelmetes sisakja a gonosz ellenség minden művével szemben."<br><br>
Amikor a bérmálást a keresztségtől elkülönítetten szolgáltatják ki, mint a római szertartásban általában, a szentség liturgiája azzal kezdődik, hogy a bérmálkozó megújítja a keresztségi ígéreteket és hitvallást tesz. Így válik nyilvánvalóvá, hogy a bérmálás a keresztséghez kapcsolódik. Amikor felnőttet keresztelnek, az közvetlenül a keresztség után részesül a bérmálásban és az Eucharisztiában.<br><br>
A római szertartásban a püspök kitárja karjait az összes bérmálandó fölé -- e gesztus az apostoli idők óta a Lélek ajándékozásának jele. Közben kéri a püspök a Szentlélek kiáradását:<br><br>
"Mindenható Isten, a mi Urunk, Jézus Krisztusnak Atyja, ki e szolgáidat vízből és Szentlélekből új élettel ajándékoztad meg, megszabadítván őket a bűntől, Urunk, küldd le reájuk a Vigasztaló Szent Lelket; add nekik a bölcsesség és az értelem lelkét, a jótanács és az erősség lelkét, a tudomány és a jámborság lelkét; töltsd be őket félelmed lelkével. Krisztus, a mi Urunk által."<br><br>
Ezután következik a szentség lényeges mozzanata. A latin szertartásban "a bérmálás szentségének kiszolgáltatása a homlokon való megkenéssel kézrátétel közben és e szavakkal történik: ’Accipe signaculum doni Spiritus Sancti’, vagyis: ’Vedd a Szentlélek ajándékának jelét’".<br><br>
A békecsók, mely zárja a szentség szertartását, a püspökkel és a többi hívővel való egyházi közösséget jelzi és nyilvánítja ki.<br><br>


<strong>A bérmálás hatásai </strong><br><br>
A szertartásból nyilvánvaló, hogy a bérmálás szentségének hatása a Szentlélek sajátos kiáradása, amint az egykor, pünkösd napján az Apostolokkal történt.<br><br>
Ezért a bérmálás növeli és elmélyíti a keresztségi kegyelmet:<br><br>
<ul>
    <li>mélyebben meggyökereztet bennünket az istengyermekségben, melyben azt mondhatjuk: "Abba, Atya" (Róm 8,15); </li>
    <li>erősebben egyesít bennünket Krisztussal; </li>
    <li>gyarapítja bennünk a Szentlélek ajándékait; </li>
    <li>tökéletesebben kapcsol az Egyházhoz; </li>
    <li>nekünk ajándékozza a Szentlélek sajátos erejét, hogy Krisztus igaz tanúiként szóval és cselekedettel terjesszük és védelmezzük a hitet, Krisztus nevét bátran valljuk meg és ne szégyenkezzünk a Kereszt előtt. </li>
</ul>
"Emlékezzél arra, hogy lelki pecsétet kaptál: a bölcsesség és az értelem Lelkét, a tanács és az erősség Lelkét, a tudás és a jámborság Lelkét, a szent félelem Lelkét, és őrizd meg, amit kaptál! Megpecsételt téged az Atyaisten, megerősített téged az Úr Krisztus, és a zálogul adta a Lelket a szívedbe."<br><br>
A bérmálást, a keresztséghez hasonlóan, melynek beteljesedése, csak egyszer szolgáltatják ki. A bérmálás ugyanis a lélekbe eltörölhetetlen lelki jegyet (karaktert) nyom, ami annak a jele, hogy Jézus Krisztus egy keresztényt Lelkének pecsétjével megjelölt, és fölülről származó erőbe öltöztette, hogy az Ő tanúja legyen.<br><br>
Ez a "karakter" tökéletesíti a hívők keresztségben kapott általános papságát. A megbérmált "megkapja a hatalmat, hogy a Krisztusba vetett hitet nyilvánosan mintegy hivatalból (quasi ex officio) szavakkal megvallja".<br><br>

<strong>Ki veheti föl ezt a szentséget? </strong><br><br>
Minden megkeresztelt ember, aki még nincs megbérmálva, bérmálkozhat és meg is kell bérmálkoznia. Mivel a keresztség, a bérmálás és az Eucharisztia egységet alkot, "a hívők (...) kötelesek ezt a szentséget megfelelő időben fölvenni", mert a bérmálás és az Eucharisztia nélkül a keresztség szentsége ugyan érvényes és hatékony, de a keresztény beavatás befejezetlen marad.<br><br>
A latin szokás évszázadok óta az "aetas discretionist", az `értelem használatának' korát jelöli meg alsó korhatárul a bérmálás fölvételéhez. Halálveszélyben azonban a gyermekeket is meg kell bérmálni, akkor is, ha még nem jutottak el értelmük használatára.<br><br>
Ha a bérmálást olykor a "keresztény nagykorúság szentségének" nevezik is, a hitbeli felnőttséget nem szabad azonosítani a természetes felnőttkorral. Azt sem szabad elfelejteni, hogy a keresztségi kegyelem ingyenes és érdemeket megelőző kiválasztás kegyelme, mely nem igényli a "jóváhagyást" ahhoz, hogy hatékony legyen. Szent Tamás emlékeztet erre:<br><br>
"A testi életkor nem mérvadó a lélek számára; ezért az ember már gyermekkorban elérheti a lelki tökéletességet, melyről a Bölcsesség könyve beszél: ’A tisztes öregség nem a hosszú élet, és nem az évek számával mérik’ (4,8). Ebből következik, hogy sokan gyermekkorukban küzdöttek bátran a vértanúságig a Szentlélektől kapott erővel Krisztusért."<br><br>
Ezért a bérmálási előkészítésnek arra kell irányulnia, hogy a keresztényt Krisztussal szorosabb egységre, a Szentlélekkel -- működésével, ajándékaival és irányításával -- elevenebb kapcsolatra vezesse, hogy ezáltal a keresztény élet apostoli kötelezettségeit jobban vállalhassa. Ezért a bérmálási oktatásnak arra kell törekednie, hogy fölébressze a Jézus Krisztus Egyházához tartozás érzékét, mind az egyetemes Egyház, mind a plébániai közösség vonatkozásában. Ez utóbbinak különös felelőssége van a bérmálkozók fölkészítéséért.<br><br>
A bérmálás fölvételéhez szükséges a kegyelem állapota. A gyónáshoz kell folyamodni, hogy a Szentlélek ajándékának fogadására a lélek megtisztuljon. Ezenkívül buzgó imádsággal kell készülni arra, hogy a Szentlélek erejét és kegyelmeit belső készséggel fogadják.<br><br>
A bérmáláshoz -- miként a keresztséghez is -- a jelölteknek bérmaapától vagy bérmaanyától kell lelki segítséget kérniük. E két szentség egységének hangsúlyozására ajánlott, hogy a keresztszülő legyen a bérmaszülő is.<br><br>

<strong>A bérmálás kiszolgáltatója </strong><br><br>
A bérmálás eredeti kiszolgáltatója a püspök.<br><br>
Keleten rendszerint a keresztelő pap az, aki rögtön, ugyanabban a szertartásban elvégzi a bérmálást. Ám ezt a pátriárka vagy püspök által megáldott szent krizmával teszi, és ez kifejezi az Egyház apostoli egységét, melynek kötelékeit a bérmálás szentsége megerősíti. Ugyanez történik a latin Egyházban felnőttek keresztelésekor, vagy amikor az Egyház teljes közösségébe visszafogadnak egy más keresztény közösségben megkereszteltet, aki még nincs érvényesen megbérmálva.<br><br>
A latin szertartásban a bérmálás rendes kiszolgáltatója a püspök. Jóllehet, ha szükséges, a püspök fölhatalmazást adhat papoknak bérmálásra, neki magának kell bérmálnia, hogy feledésbe ne menjen, hogy éppen ennek érdekében vált ketté időben a bérmálás és a keresztelés. A püspökök az apostolok utódai, ők kapták meg az egyházi rend szentségének teljességét. Amikor ők bérmálnak, az jól kifejezi, hogy e szentség hatására a megbérmáltak szorosabban kötődnek az Egyház apostoli eredetéhez és azon küldetéséhez, hogy tanúskodjék Krisztusról.<br><br>
Ha egy keresztény halálveszélyben van, bármely pap megbérmálhatja. Az Egyház ugyanis nem akarja, hogy egyetlen gyermeke, még a legkisebb is úgy távozzon ebből a világból, hogy a Szentlélek által a krisztusi nagykorúság ajándékával nem válik teljessé.<br><br>