<h2>Betegek szentsége</h2>

"A betegek szent kenetével és a papok imádságával az egész Egyház ajánlja a szenvedő és megdicsőült Krisztusnak a betegeket, hogy nekik enyhületet és üdvösséget szerezzen; sőt buzdítja őket, hogy szabadon csatlakozva Krisztus szenvedéséhez és halálához, szolgáljanak Isten népének javára." <br><br>

<strong>A BETEGSÉG AZ EMBERI ÉLETBEN </strong><br><br>
A betegség és a fájdalom az emberi életnek mindig a legsúlyosabb problémái közé tartozott. A betegségben az ember megtapasztalja tehetetlenségét, korlátait, végességét. Minden betegség megsejtetheti velünk a halált. <br><br>
A betegség szorongáshoz, önmagába zárkózáshoz, néha kétségbeeséshez és Isten elleni lázadáshoz vezethet. De érettebbé is teheti a személyt, segítheti, hogy fölismerje élete lényegtelen dolgait és afelé forduljon, ami lényeges. A betegség nagyon gyakran indítja el az istenkeresést, a visszatérést Őhozzá. <br><br>


<strong>A BETEG ISTEN ELŐTT </strong><br><br>
Az ószövetségi ember a betegséget Istennel kapcsolatban éli meg. Panaszkodik Isten előtt a betegség miatt, és Tőle, az élet és halál Urától kér gyógyulást. A betegség a megtérés útja lesz, és az Istentől nyert megbocsátás meghozza a gyógyulást. Izrael népe átéli, hogy a betegség titokzatos módon összefügg a bűnnel és a rosszal, s az Istenhez való hűség az Ő törvénye szerint visszaadja az életet: "Hiszen Én, az Úr vagyok a te gyógyítód" (Kiv 15,26). Izaiás próféta előre látja, hogy a szenvedésnek a mások bűneiért való engesztelés értelme is lehet. Megjövendöli, hogy Isten el fogja hozni Sionnak az időt, amikor megbocsát minden vétket és meggyógyít minden betegséget. <br><br>


<strong>AZ ORVOS KRISZTUS </strong><br><br>
Krisztus együttérzése a betegekkel, valamint számos gyógyítása mindenféle betegségből nyilvánvaló jele annak, hogy Isten meglátogatta az Ő népét és Isten országa közel van. Jézusnak nemcsak a gyógyításhoz volt hatalma, hanem a bűnök megbocsátásához is: Azért jött, hogy az egész embert -- a lelket és testet -- meggyógyítsa. Ő az orvos, akire a betegeknek szükségük van. Az összes szenvedő iránti együttérzése olyan messzire megy, hogy azonosul velük: "Beteg voltam és meglátogattatok" (Mt 25,36). A betegek iránti különös szeretete a századok során arra indította a keresztényeket, hogy karolják föl a testben vagy lélekben szenvedőket; ez késztetett fáradhatatlan erőfeszítésekre a szenvedések enyhítése végett. <br><br>
Jézus gyakran elvárta a betegektől, hogy higgyenek. Jeleket alkalmazott a gyógyításnál: nyálat és kézrátételt, sarat és lemosást. A betegek keresték, hogy érinthessék Őt, "mert erő áradt belőle, mely mindenkit meggyógyított" (Lk 6,19). Így a szentségekben Krisztus továbbra is "megérint" bennünket, hogy meggyógyítson. <br><br>
A sok szenvedéstől megindultan Krisztus nemcsak megengedte, hogy a betegek megérintsék Őt, hanem nyomorúságainkat magáévá teszi: "Szenvedéseinket magára vette és betegségeinket ő hordozta" (Mt 8,17). De nem minden beteget gyógyított meg. Gyógyításai Isten országa eljövetelének jelei voltak, egy sokkal mélyebbre ható gyógyulást hirdettek: a bűn és a halál fölötti győzelmet az ő húsvétja által. A kereszten Krisztus a rossz egész terhét magára vette, elvette a "világ bűnét" (Jn 1,29), aminek a betegség csak egyik következménye. Szenvedésével és kereszthalálával Krisztus a szenvedésnek új értelmet adott: hasonlóvá tud tenni bennünket Őhozzá, és egyesíthet az Ő megváltó szenvedésével. <br><br>


<strong>"GYÓGYÍTSATOK BETEGEKET..." </strong><br><br>
Krisztus fölszólította tanítványait, hogy kövessék Őt és vegyék föl keresztjüket. Őt követve a tanítványok új szemmel látják a betegséget és a betegeket. Jézus bekapcsolja őket a maga szegény és szolgáló életébe. Részesíti őket az együttszenvedés és a gyógyítás szolgálatából: "És elmenvén prédikálták, hogy tartsanak bűnbánatot; és sok ördögöt kiűztek, és olajjal megkentek sok beteget, és meggyógyították őket" (Mk 6,12--13). <br><br>
A föltámadott Úr megismétli ezt a küldést ("A nevemben (...) betegekre teszik a kezüket, és azok meggyógyulnak"; Mk 16,17--18), és megerősíti azokkal a jelekkel, melyeket az Egyház az Ő nevének segítségül hívásával művel. Ezek a jelek különleges módon kinyilvánítják, hogy Jézus valóban "az üdvözítő Isten". <br><br>
A Szentlélek egyes embereknek különleges, gyógyító karizmát ajándékoz, hogy megmutassa, milyen ereje van a Föltámadott kegyelmének. Azonban még a legbuzgóbb imádság sem nyeri el minden betegség gyógyulását. Így kell Pálnak megtanulnia az Úrtól: "elég neked az én kegyelmem. Mert az erő a gyöngeségben nyilvánul meg" (2Kor 12,9); és az elviselendő szenvedéseknek a következő értelme lehet: "Testemben kiegészítem, ami Krisztus szenvedéséből hiányzik, testének, az Egyháznak a javára" (Kol 1,24). <br><br>
"Gyógyítsatok betegeket!" (Mt 10,8). E feladatot az Egyház az Úrtól kapta, és igyekszik megvalósítani, amikor ápolja a betegeket és közbenjáró imádságával kíséri őket. Az Egyház hisz Krisztusnak, a lélek és a test orvosának éltető jelenlétében. E jelenlét elsősorban a szentségeken keresztül hat, egészen sajátos módon az Eucharisztia által, a kenyér által, mely örök életet ad, s melynek a testi gyógyulással való kapcsolatát Szent Pál hangsúlyozza. <br><br>
Az apostoli Egyház ismer egy saját szertartást a betegek számára, melyről Szent Jakab tanúskodik: "Beteg valaki közületek? Hívassa el az Egyház papjait, és azok imádkozzanak fölötte, és kenjék meg olajjal az Úr nevében. A hitből fakadó ima megszabadítja a beteget, és az Úr talpra állítja. Ha pedig bűnöket követett el, bocsánatot nyer." (Jak 5,14--15) A hagyomány e szertartásban az Egyház hét szentségének egyikét ismeri föl. <br><br>


<strong>A BETEGEK SZENTSÉGE </strong><br><br>
Az Egyház hiszi és vallja, hogy a hét szentség közül az egyik egész különlegesen arra van rendelve, hogy megerősítse a betegség által megpróbáltakat: a betegek kenete: <br><br>
"A betegek e szent kenetét Krisztus, a mi Urunk mint az Újszövetség valóságos és különálló szentségét alapította, Márk utal rá, Jakab pedig, az apostol és az Úr testvére, ajánlotta a híveknek és kihirdette." <br><br>
Az ókortól kezdve mind Kelet, mind Nyugat liturgikus hagyományában vannak tanúi annak, hogy megszentelt olajjal megkenték a betegeket. A századok során a betegek kenetét egyre inkább csak a haldoklóknak szolgáltatták ki. Ezért kapta az utolsó kenet nevet. E fejlemény ellenére a liturgia nem szűnt meg imádkozni az Úrhoz, hogy a beteg nyerje vissza egészségét, amennyiben ez üdvösségének javára válik. <br><br>
Az 1972. november 30-án kelt Sacram unctionem infirmorum kezdetű apostoli konstitúció a II. Vatikáni Zsinathoz csatlakozva elrendelte, hogy a római szertartásban a következőket kell megtartani: <br><br>
A betegek kenetének szentségét azoknak szolgáltassák ki, akiknek egészségét súlyos betegség támadta meg. A beteget kenjék meg homlokán és kezein az előírt módon megáldott olívaolajjal vagy a körülményeknek megfelelően más, az előírt módon megáldott növényi olajjal, és közben a következő szavakat mondják: "E szent kenet által és nagy irgalmassága szerint segítsen meg téged az Úr a Szentlélek kegyelmével; szabadítson meg bűneidtől, üdvözítsen téged, és erősítsen meg jóságosan!" <br><br>


<strong>Ki veheti föl és ki szolgáltathatja ki ezt a szentséget? </strong><br><br>
A betegek kenete "<strong>nemcsak a halálveszélyben lévők szentsége. Ezért fölvételére már az az időszak is biztosan alkalmas, amikor a hívő élete betegség vagy öregség miatt kezd veszélybe kerülni.</strong>" <br><br>
Ha egy beteg, aki fölvette a szentséget, visszanyeri egészségét, újra fölveheti a szentséget, ha ismét súlyosan megbetegszik. Ugyanazon betegségben is meg lehet ismételni, ha rosszabbodik az állapot. Ajánlott fölvenni a betegek kenetét komoly sebészi beavatkozás előtt. Ugyanez a helyzet az időseknél, akiknek az állapota egyre törékenyebbé válik. <br><br>
<strong>A betegek kenetének kiszolgáltatói kizárólag a papok</strong> (püspökök vagy áldozópapok). A lelkipásztorok kötelessége oktatni a híveket e szentség jótéteményeiről. A híveknek bátorítaniuk kell a betegeket, hogy papot hívjanak és e szentséget fölvegyék. A betegek készüljenek föl lelkipásztorok és az egész egyházi közösség segítségével, melynek a betegeket egész különlegesen körül kell vennie imádsággal és testvéri gondoskodással. <br><br>


<strong>Hogyan szolgáltatják ki ezt a szentséget? </strong><br><br>
Mint minden szentség, a betegek kenete is liturgikus és közösségi cselekmény, akár otthon, kórházban vagy templomban, akár egy betegnek, illetve a betegek egész csoportjának szolgáltatják ki. Nagyon megfelelő, hogy az Eucharisztia, az Úr húsvétjának emlékezete keretében kerüljön kiszolgáltatásra. Amikor a körülmények megengedik, a betegek kenetét megelőzheti a gyónás és követheti a szentáldozás. Az Eucharisztia, mint Krisztus húsvétjának szentsége, a földi zarándoklét utolsó szentsége, az "útravaló"az örök életbe történő "átmenethez". <br><br>
Szó és szentség megbonthatatlan egészet alkot. A bűnbánat fölindítása, majd igeliturgia nyitja meg a szertartást. Krisztus szavai és az apostolok tanítása fölélesztik a beteg és a közösség hitét, hogy az Úrtól kérjék Lelkének erejét. <br><br>
A szentség kiszolgáltatása lényegileg a következő elemekből áll: az "Egyház papjai" kezüket csöndben fölteszik a betegekre; az Egyház hitében imádkoznak a betegekért; ez a szentség epiklézise; föladják a kenetet, lehetőleg püspök által megszentelt olajjal. <br><br>
Ezek a liturgikus cselekmények mutatják, hogy e szentség milyen kegyelmet ad a betegeknek. <br><br>


<strong>A betegek kenetének hatásai </strong><br><br>
A Szentlélek különleges ajándéka. A szentség első kegyelme a megerősítés kegyelme, a lélek békéje és ereje azoknak a nehézségeknek legyőzésére, melyek a súlyos betegséggel vagy az öregséggel járnak együtt. E kegyelem a Szentlélek ajándéka, mely megújítja az Istenbe vetett hitet és bizalmat, és az erőt a Gonosz kísértéseivel, nevezetesen a kétségbeesés és a halálfélelem kísértésével szemben. Az Úrnak e segítsége a Szentlélek erejében akarja elvezetni a beteget a lélek gyógyulásához, de a test gyógyulásához is, ha ez Isten akarata. És "ha bűnöket követett el, bocsánatot nyer" (Jak 5,15). <br><br>
Egyesülés Krisztus szenvedésével. E szentség kegyelme által a beteg megkapja az erőt és az ajándékot, hogy még bensőségesebben egyesüljön az Úr szenvedésével. Bizonyos értelemben fölszentelődik arra, hogy az Üdvözítő megváltó szenvedéséhez hasonulva gyümölcsöt hozzon. A szenvedés, az eredeti bűn következménye új értelmet nyer: részesedés lesz Jézus üdvözítő művében. <br><br>
Egyházi kegyelem. A hívők, akik e szentséget fölveszik, "szabadon egyesülve Krisztus szenvedésével és halálával, Isten népének lelki javához" járulnak hozzá. Az Egyház a betegek kenetének kiszolgáltatásakor a szentek közösségében jár közben a betegekért. A beteg viszont a szentség kegyelme által hozzájárul az Egyház gyógyulásához és minden ember javához, akikért az Egyház szenved és Krisztus által fölajánlja magát Istennek, az Atyának. <br><br>
Fölkészülés a végső átmenetelre. Ha a betegek kenetének szentségét mindazoknak kiszolgáltatják, akik súlyos betegségben vagy gyöngeségben szenvednek, egész különlegesen szól azoknak, akik "a halál küszöbén" állnak, olyannyira, hogy e szentséget "az elmenők szentségének" is nevezik. A betegek kenete véglegessé teszi hasonlóságunkat Krisztus halálával és föltámadásával, amit a keresztség már megkezdett bennünk. Befejezi a szent megkenéseket, melyek az egész keresztény életet meghatározzák; a keresztségé megpecsételte bennünk az új életet; a bérmálásé megerősített a jelen élet küzdelmére. Ez az utolsó kenet földi életünk végét bástyázza körül, tekintettel az atyai házba történő belépés előtti utolsó harcokra. <br><br>


<strong>A szent útravaló, a keresztény ember utolsó szentsége </strong><br><br>
A haldoklóknak az Egyház a betegek kenete mellett fölajánlja az Eucharisztiát, mint útravalót. Az Atyához való átmenetel e pillanatában a Krisztus testével és vérével való egyesülésnek egész különös jelentése és fontossága van. Az örök élet magva és a föltámadás ereje az Úr szava szerint : "Aki eszi az én testemet és issza az én véremet, annak örök élete van, és Én föl fogom támasztani őt az utolsó napon" (Jn 6,54). Az Eucharisztia, a meghalt és föltámadott Krisztus szentsége ekkor a halálból az életre, az evilágból az Atyához való átmenetel szentsége. <br><br>
Ily módon miként a keresztség, a bérmálás és az Eucharisztia szentsége egységet alkot, melyet a "keresztény beavatás szentségeinek" nevezünk, elmondható, hogy a bűnbánat, a szent kenet és az Eucharisztia a keresztény élet végén -- amennyiben útravalót adnak -- olyan egységet alkotnak, melyet a "hazatérésre fölkészítő szentségeknek" nevezhetünk, azaz lezárják a zarándokságot. <br><br>