<h2>Bűnbánat szentsége</h2>

"Akik a bűnbánat szentségéhez járulnak, azok Istent sértő bűneikre Isten irgalmas bocsánatát kapják meg. Egyszersmind kibékülnek az Egyházzal, melyet megsebeztek bűnükkel, s mely szeretetével, példájával és imájával közreműködik megtérésükben."<br><br>

<strong>Hogyan nevezik ezt a szentséget?</strong><br><br>
<ul>
    <li>A megtérés szentségének nevezik amiatt, hogy szentségileg megvalósítja Jézus megtérésre szólító hívását, tudniillik az elhatározást a visszatérésre az Atyához, akitől az ember a bűn által eltávolodott.</li>
    <li>A bűnbánat szentségének nevezik amiatt, hogy megszenteli a keresztény bűnös személyes és egyházi megtérésének, bűnbánatának és elégtételének útját.</li>
    <li>A gyónás (a bűnök megvallása) szentségének nevezik amiatt, hogy a bűnök beismerése, megvallása a pap előtt e szentség lényeges összetevője. Mélyebb értelemben ez a szentség "hitvallás" is, mert elismeri és dicséri Isten szentségét és irgalmasságát a bűnös emberek iránt. </li>
    <li>A bűnbocsánat szentségének nevezik, amiatt, hogy a pap szentségi föloldozása által Isten "bocsánatot (...) és békét" ad a bűnbánónak. </li>
    <li>A kiengesztelődés szentségének is nevezik, mert a bűnösnek ajándékozza Isten megengesztelődő szeretetét: "Engesztelődjetek ki Istennel!" (2Kor 5,20). Aki Isten irgalmas szeretetéből él, kész arra, hogy megfeleljen az Úr fölhívásának: "Menj, és előbb békülj ki felebarátoddal!" (Mt 5,24). </li>
</ul>

<strong>Mire jó a kiengesztelődés szentsége a keresztség után? </strong><br><br>
"Megtisztultatok, (...) megszentelődtetek, (...) megigazultatok az Úr Jézus Krisztus nevében és Istenünk Lelkében!"(1Kor 6,11). Tudatosítanunk kell, mily nagy Isten ajándéka, amit a keresztény beavatás szentségeiben kaptunk, hogy fölfogjuk, mennyire idegen a bűn attól, aki Krisztust öltötte magára. Ám Szent János apostol ezt is írja: "Ha azt állítjuk, hogy nincs bűnünk, saját magunkat vezetjük félre, és nincs meg bennünk az igazság" (1Jn 1,8). És maga az Úr tanított bennünket így imádkozni: "Bocsásd meg a mi vétkeinket" (Lk 11,4), egymás elleni vétkeink megbocsátását összekötvén azzal a megbocsátással, amit Isten ad a mi bűneinkre.<br><br>
A megtérés Krisztushoz, a keresztségből való új születés, a Szentlélek ajándékai, Krisztus táplálékul magunkhoz vett teste és vére bennünket szentté és feddhetetlenné tett "Őelőtte" (Ef 1,4), miként maga az Egyház, Krisztus jegyese Őelőtte "szent és szeplőtelen" (Ef 5,27). A keresztény beavatásban kapott új élet azonban sem az emberi természet törékenységét és gyöngeségét, sem a hagyomány által concupiscentiának nevezett bűnre való hajlandóságot nem szüntette meg, s ez utóbbi megmarad a megkereszteltekben, hogy próbára tétessenek a keresztény élet harcában Krisztus kegyelmétől támogatva. Ez a harc a megtérés harca az életszentségért és az örök életért, melyre az Úr szüntelenül hív minket.<br><br>

<strong>A belső bűnbánat </strong><br><br>
Miként már a Prófétáknál is, Jézusnál a meghívás a megtérésre és a bűnbánatra elsősorban nem a külső cselekedetekre irányul, a "zsákra és hamura", böjtölésre és önmegtagadásokra, hanem a szív megtérésére, a belső bűnbánatra. Enélkül a bűnbánat cselekedetei terméketlenek és hazugok; ezzel szemben a belső megtérés e lelkület látható jelekkel való kifejezésére sarkall gesztusokban és bűnbánati gyakorlatokban.<br><br>
A belső bűnbánat az egész élet gyökeresen új iránya, visszafordulás teljes szívből Istenhez, a bűn elhagyása, elfordulás a rossztól, elkövetett gonosz cselekedeteink megtagadása. Ugyanakkor magában foglalja a vágyat és az elhatározást az élet megváltoztatására, reménykedve az isteni irgalmasságban és bízva az Ő kegyelmének segítségében. A szív e megtérését üdvös fájdalom és szomorúság kíséri, melyet az egyházatyák animi cruciatus-nak, a `lélek gyötrelmének' és compunctio cordis-nak, a `szív bánkódásának' neveznek.<br><br>
Az ember szíve nehéz és megkérgesedett. Istennek az emberbe új szívet kell adnia. A megtérés elsősorban Isten kegyelmének műve, aki megteszi, hogy a szívünk visszatér Őhozzá: "Téríts magadhoz minket, Uram, és mi megtérünk" (Siral 5,21). Isten adja nekünk az erőt, hogy újra tudjunk kezdeni. Amikor a szívünk fölfedezi Isten szeretetének nagyságát, megrendül a bűn szörnyűségétől és súlyától, és kezd félni attól, hogy bűnnel megbántsa Istent és elszakadjon Tőle. Az emberi szív megtér, ha föltekint arra, akit bűneink keresztülszúrtak.<br><br>
"Tekintsünk Krisztus vérére, és megértjük, mennyire értékes Atyja számára; mert üdvösségünkért kiontva az egész világnak meghozta a bűnbánat kegyelmét."<br><br>
Húsvét óta a Szentlélek vádolja a világot a bűnről, tudniillik, hogy a nem hittek abban, akit az Atya küldött. De ugyanez a Lélek, aki fölfedi a bűnt, a Vigasztaló, aki nyújtja az emberi szívnek a bűnbánat és a megtérés kegyelmét.<br><br>

<strong>A bűnbánat és a kiengesztelődés szentsége </strong><br><br>
A bűn elsősorban Isten megbántása, a vele való közösség megszakítása. Ugyanakkor kárt okoz az Egyház közösségének is. Ezért a megtérés egyidejűleg hozza Isten bűnbocsánatát és a kiengesztelődést az Egyházzal, amit a bűnbánat és a kiengesztelődés szentsége liturgikusan kifejez és megvalósít.<br><br>
Egyedül Isten bocsátja meg a bűnöket. Mivel Jézus az Isten Fia, önmagáról mondja: "az Emberfiának van hatalma a földön megbocsátani a bűnöket" (Mk 2,10), és Ő maga gyakorolja ezt az isteni hatalmat: "Bocsánatot nyertek bűneid!" (Mk 2,5). Sőt isteni tekintélye folytán átadja az embereknek, hogy az Ő nevében gyakorolják ezt a hatalmat.<br><br>
Krisztus úgy akarta, hogy egész Egyháza imádságaiban, életében és cselekedeteiben jele és eszköze legyen annak a megbocsátásnak és kiengesztelődésnek, melyet Ő vére árán szerzett nekünk. A föloldozás hatalmának gyakorlását azonban az apostoli hivatalra bízta. Ez van megbízva "a kiengesztelődés szolgálatával" (2Kor 5,18). Az Apostol "Krisztus nevében" kapta küldetését; általa maga Isten buzdít és kér: "engesztelődjetek ki az Istennel" (2Kor 5,20).<br><br>

<strong>A BŰNBOCSÁNAT SZENTSÉGE </strong><br><br>
Krisztus a bűnbánat szentségét Egyházának valamennyi bűnös tagja, mindenekelőtt azok számára alapította, akik a keresztség után súlyos bűnbe estek és így elvesztették a keresztségi kegyelmet és az egyházi közösséget megsebezték. Nekik a bűnbánat szentsége új lehetőséget nyújt a megtérésre és a megigazulás kegyelmének visszanyerésére. Az egyházatyák ezt a szentséget úgy mutatják be, mint "második mentődeszkát a kegyelem elvesztésének hajótörése után".<br><br>
A századok folyamán a konkrét forma, melynek keretében az Egyház ezt az Úrtól kapott hatalmat gyakorolta, sokat változott. Az első századokban a keresztségük után különösen súlyos bűnöket (pl. bálványimádás, emberölés vagy házasságtörés) elkövető keresztények kiengesztelődése rendkívül szigorú fegyelmi követelményhez volt kötve: a bűnbánóknak bűneik miatt sokszor éveken át nyilvánosan kellett vezekelniük, mielőtt a megbocsátást elnyerték. E "bűnbánók rendjébe" (mely csak bizonyos súlyos bűnök levezeklésére szolgált) csak ritkán, egyes vidékeken az életben csak egyszer bocsátottak valakit. A keleti szerzetesi hagyománytól indítva a 7. században ír misszionáriusok hozták Európába a "magánbűnbánat" gyakorlatát. Ez nem igényelt hosszadalmas, nyilvános vezeklést az Egyházzal történő kiengesztelődés előtt. A szentség ettől kezdve a bűnbánó és a pap között rejtett módon valósult meg. Ez az új gyakorlat biztosította az ismétlés lehetőségét és elvezetett a rendszeres gyónás gyakorlatához. Lehetővé tette, hogy egyetlen szentségi cselekményben lehessen föloldozni a súlyos és a bocsánatos bűnöket. Nagy vonalakban az Egyház a bűnbánattartásnak ezt a formáját gyakorolja napjainkig.<br><br>
A különböző változások ellenére, melyeken a szentség szertartása és fegyelme a századok során átment, alapszerkezete változatlan maradt. Két egyenlőképpen lényeges eleme van: egyrészt a Szentlélek hatására megtérő ember cselekedete, a bánat, a bűnvallás és az elégtétel; másrészt Isten cselekedete az Egyház szolgálata által. Az Egyház, mely a püspök és papjai által Jézus Krisztus nevében a bűnbocsánatot adja és meghatározza az elégtétel módját, imádkozik a bűnösért és vele együtt bűnbánatot tart. Így a bűnös meggyógyul és újra fölvétetik az egyházi közösségbe.<br><br>
A latin Egyházban használatos föloldozási forma kifejezi a szentség lényegi elemeit: az irgalmasság Atyja a forrása minden megbocsátásnak. Ő viszi végbe a bűnösök kiengesztelődését Fiának húsvétja és Lelkének ajándéka erejével, az Egyház imádsága és szolgálata által:<br><br>
"Isten, a mi irgalmas Atyánk, aki szent Fiának kereszthalála és föltámadása által kiengesztelte önmagával a világot, és kiárasztotta a Szentlelket a bűnök bocsánatára, az Egyház szolgálata által bocsásson meg neked, és adja meg a békét. És én föloldozlak téged bűneidtől az Atya és a Fiú és a Szentlélek nevében."<br><br>

<strong>A bűnbánó cselekedetei </strong><br><br>
"A bűnbánattartás arra készteti a bűnöst, hogy szívesen vállaljon mindent; szívében bánat, ajkán bűnvallomás; cselekedetében teljes alázat vagy gyümölcsöző elégtétel."<br><br>
<strong>A BÁNAT </strong><br><br>
A bűnbánó cselekedetei között az első a bánat, ami "a lélek fájdalma az elkövetett bűn fölött, az utálat iránta, azzal az elhatározással, hogy többé nem vétkezik".<br><br>
Amikor a bánat a mindennél jobban szeretett Isten iránti szeretetből fakad, "tökéletes bánatnak" (a szeretet bánatának) nevezzük. Ez a bánat eltörli a bocsánatos bűnöket; sőt elnyeri a halálos bűnök bocsánatát is, ha együtt jár azzal a szilárd elhatározással, hogy a bűnbánó, mihelyt alkalma nyílik, szentségi gyónáshoz járul.<br><br>
Az úgynevezett "tökéletlen" bánat (attritio) is Isten ajándéka és a Szentlélek indítása. A bűn rútságának szemléléséből vagy a bűnöst fenyegető örök kárhozattól és egyéb büntetésektől való félelemből fakad. A lelkiismeret ilyen megrendülése belső fejlődést indíthat el, melyet a kegyelem működése alatt a szentségi föloldozás beteljesít. A tökéletlen bánat önmagában nem nyeri el a súlyos bűnök megbocsátását, de a bűnbánót fölkészíti arra, hogy a szentségi gyónásban azt elnyerje.<br><br>
E szentség vételére az Isten igéjének fényében végzett lelkiismeretvizsgálattal kell fölkészülni. A legalkalmasabb szövegeket a Tízparancsolatban, valamint az evangéliumok és az apostoli levelek erkölcsi tanításában lehet megtalálni: a hegyi beszédben és az apostoli intelmekben. (<a href="http://pestiferences.ofm.hu/templom/index6.html">http://pestiferences.ofm.hu/templom/index6.html</a>)<br><br>

<strong>A BŰNÖK MEGVALLÁSA, A GYÓNÁS </strong><br><br>
A bűnök megvallása (vádolása) pusztán emberi szempontból nézve is megszabadító, és megkönnyíti a másokkal való megbékélést. A gyónásban a megvallás által az ember szembenéz a bűnökkel, melyekben vétkesnek bizonyult; vállalja a felelősséget, és ezáltal újból megnyílik Isten és az Egyház közössége felé, hogy lehetővé váljon egy új jövő.<br><br>
A papnak tett bűnvallomás a bűnbocsánat szentségének lényeges része: "A bűnbánóknak a gyónásban föl kell sorolniuk valamennyi halálos bűnüket, melyeknek gondos lelkiismeretvizsgálat után tudatában vannak, még ha egészen titokban és a Tízparancsolat két utolsó parancsa ellen követték is el; mert ezek a bűnök néha súlyosabban megsebzik a lelket és veszélyesebbek, mint azok, amelyeket egész nyilvánosan követtek el":<br><br>
"Amikor a krisztushívők igyekeznek megvallani összes bűnüket, amire emlékeznek, mindent az isteni irgalmasság elé tárnak, hogy bocsánatot nyerjenek. Aki azonban másként cselekszik és valamit tudatosan visszatart, valójában semmit sem tár a pap által az isteni Jóság elé megbocsátásra. ‘Ha ugyanis a beteg szégyelli fölfedni a sebét az orvosnak, az orvosság nem gyógyítja meg azt, amit nem ismer.’"<br><br>
Az Egyház parancsolata szerint "<strong>minden hívő, miután eljutott a megkülönböztetés korára, köteles meggyónni súlyos bűneit, melyeknek tudatában van, legalább évente egyszer</strong>." Aki tudatában van annak, hogy halálos bűnt követett el, még ha a bűn fölött mélységes bánatot is érez, ne járuljon a szentáldozáshoz anélkül, hogy szentségi föloldozásban nem részesült, kivéve, ha a szentáldozásnak súlyos indoka van és lehetetlen meggyónni. A gyermekek kötelesek a bűnbocsánat szentségéhez járulni, mielőtt elsőáldozók lennének.<br><br>
A mindennapos hibák (a bocsánatos bűnök) gyónása szorosan véve nem kötelező, de az Egyház nyomatékosan ajánlja. Bocsánatos bűneink rendszeres meggyónása segítséget jelent lelkiismeretünk alakításában, a rossz hajlamaink elleni küzdelemben, lehetővé teszi, hogy Krisztus gyógyítson bennünket és a Lélek életében gyarapodjunk. Ha gyakrabban fogadjuk Isten irgalmasságának ajándékát e szentségben, az sürgetni fog, hogy mi magunk is irgalmasszívűek legyünk, mint Ő:<br><br>
"Aki megvallja bűneit, és vádolja bűneit, már Istennel cselekszik. Isten vádolja bűneidet; ha te is vádolod, csatlakozol Istenhez. Az ember és a bűnös bizonyos értelemben két valóság: ha azt hallod, ember, azt Isten teremtette; ha azt hallod, bűnös, az az ember műve. Töröld le, amit te műveltél, hogy Isten megmentse azt, amit Ő alkotott (...). Amikor kezd nem tetszeni neked, amit műveltél, akkor kezdődnek a jó cselekedeteid, mert vádolod a gonosz cselekedeteidet. A jó cselekedetek kezdete a rossz cselekedetek megvallása. Teszed az igazságot, és világosságra jössz."<br><br>

<strong>AZ ELÉGTÉTEL </strong><br><br>
Sok bűn kárt okoz a felebarátnak. Amennyire lehetséges, a kárt jóvá kell tenni (például vissza kell adni a lopott holmit, helyre kell állítani a megrágalmazott jóhírét, elégtételt kell adni a sértésért). Ezt már maga az igazságosság is megköveteli. A bűn azonban megsebzi és elgyengíti magát a bűnöst, továbbá Istenhez és a felebaráthoz fűződő kapcsolatait is. A feloldozás elveszi a bűnt, de nem szüntet meg minden jogtalanságot, melyet a bűn okozott. Miután a bűnös kiemelkedett a bűnből, még el kell nyernie a teljes lelki egészséget. Még kell valamit tennie, hogy jóvátegye bűneit: megfelelő módon "elégtételt" kell adnia, ki kell "engesztelnie" bűneit. Ezt az elégtételt "vezeklésnek" is nevezik.<br><br>
A vezeklésnek, amit a gyóntató kiró, tekintettel kell lennie a bűnbánó személyes helyzetére és lelki javát kell szolgálnia. Amennyire lehetséges, arányban kell állnia az elkövetett bűnök természetével és súlyosságával. Az elégtétel lehet imádság, valaminek a fölajánlása, az irgalmasság cselekedetei, a felebarát szolgálata, önmegtagadás, áldozatvállalás, s főként a napi keresztünk türelmes viselése. Az ilyen vezeklések segítenek bennünket abban, hogy hasonlóvá váljunk Krisztushoz, aki egyedül és egyszer s mindenkorra kiengesztelte bűneinket. Lehetővé teszik, hogy társörökösei legyünk a föltámadott Krisztusnak, mert "együtt szenvedünk vele" (Róm 8,17):<br><br>

<strong>A szentség kiszolgáltatója </strong><br><br>
Mivel Krisztus a kiengesztelődés szolgálatát Apostolaira bízta, utódaik, a püspökök és azok munkatársai, a papok folytatják e szolgálatot. Valójában ugyanis a püspököknek és a papoknak az egyházi rend szentségének erejéből hatalmuk van minden bűnt megbocsátani "az Atya és a Fiú és a Szentlélek nevében".<br><br>
A bűnök megbocsátása kiengesztel Istennel, de az Egyházzal is. A püspököt tehát, a részegyház látható fejét ősidők óta joggal tekintik úgy, mint akit elsődlegesen megillet a kiengesztelődés hatalma és szolgálata: ő a bűnbánati fegyelem szabályozója. Munkatársai, a papok annyiban végzik ezt a szolgálatot, amennyiben püspöküktől (vagy egy szerzetesi elöljárótól) vagy a Pápától az egyházjognak megfelelően megbízatást kapnak.<br><br>
Néhány különösen súlyos bűnt kiközösítéssel sújtanak, a legkomolyabb egyházi büntetéssel, ami megakadályozza a szentségek vételét és bizonyos egyházi cselekedetek végzését. A kiközösítés alól föloldozást az egyházjog szerint csak a Pápa, a helyi püspök vagy egy általa erre fölhatalmazott pap adhat. Halálveszélyben azonban bármely pap, még ha nem is rendelkezik gyóntatási joghatósággal, minden bűn és minden kiközösítés alól föloldozhat.<br><br>
A papoknak buzdítaniuk kell a híveket a bűnbocsánat szentségének vételére, és készségesnek kell lenniük a gyóntatásra, valahányszor a keresztények azt ésszerű módon kérik.<br><br>
Amikor a pap a bűnbocsánat szentségét kiszolgáltatja, a jó Pásztor szolgálatát végzi, aki keresi az elveszett bárányt; az irgalmas szamaritánusét, aki bekötözi a sebeket; az atyáét, aki a tékozló fiúra vár és visszatértekor szeretettel fogadja; az igazságos bíróét, aki személyválogatás nélkül hoz igazságos és irgalmas ítéletet. Egyszóval a pap Isten bűnös iránti irgalmas szeretetének jele és eszköze.<br><br>
A gyóntató Isten megbocsátásának nem ura, hanem szolgája. E szentség szolgájának egyesülnie kell Krisztus szándékával és szeretetével. Ismernie kell a keresztény erkölcstant, az emberi életet, tisztelnie kell azt, aki elesett és szelídnek kell lennie iránta; szeretnie kell az igazságot, hűségesnek kell lennie az Egyház Tanítóhivatalához, türelemmel kell vezetnie a bűnbánót a gyógyulás és a teljes érettség felé. Imádkoznia és vezekelnie kell érte, és Isten irgalmasságára kell bíznia.<br><br>
Figyelembe véve e szolgálat szent voltát és nagyságát, valamint a személyeket megillető tiszteletet, az Egyház kinyilvánítja, hogy minden pap, aki gyóntat, a legsúlyosabb büntetés terhe mellett köteles a bűnbánó által meggyónt bűnökre vonatkozóan abszolút hallgatást tartani. Ugyanígy nem használhatja föl azokat az ismereteket, amelyeket a gyónó életére vonatkozóan a gyónásból tud. E gyónási titkot, mely semmiféle kivételt nem ismer, "szentségi pecsétnek" nevezik, mert mindaz, amit a gyónó a papra rábízott, e szentség által "lepecsételve" marad.<br><br>

<strong>E szentség hatásai </strong><br><br>
"A bűnbánat szentségének minden ereje abban áll, hogy visszaállít minket Isten kegyelmébe, és bensőséges barátságban összekapcsol Vele." E szentség célja és hatása tehát az Istennel való kiengesztelődés. Azok, akik a bűnbánat szentségét töredelmes szívvel és vallásos fölkészültséggel fogadják, "a lelkiismeret békéjét és derűjét a lélek nagy vigasztalásával együtt" szokták érezni. Az Istennel történő kiengesztelődés szentsége ugyanis igazi "lelki föltámadást" hoz az istengyermeki élet méltóságának és javainak -- melyek közül a legdrágább az istenbarátság -- helyreállításával.<br><br>
E szentség kiengesztel bennünket az Egyházzal. A bűn gyengíti vagy megtöri a testvéri közösséget. A bűnbánat szentsége megújítja vagy helyreállítja azt. Ebben az értelemben nem csupán azt gyógyítja, akit visszavisz az egyházi közösségbe, hanem elevenítő hatása van az Egyház életére is, amely elszenvedte egyik tagjának bűnét. A bűnös, aki visszakerül a szentek közösségébe vagy megszilárdul benne, a lelki javak Krisztus Testének élő -- akár még zarándokló, akár már az égi hazában otthon lévő -- tagjai közötti kölcsönös közlése által megerősödik.<br><br>
"Ez az Istennel való kiengesztelődés maga után vonja a kiengesztelődés egyéb formáit is, amelyek más sebeket is gyógyítanak. A gyónó, aki bocsánatot nyert, kiengesztelődik legmélyebb énjében önmagával, miáltal visszanyeri belső igaz voltát; kiengesztelődik testvéreivel, akiket megbántott és megsértett; kiengesztelődik az Egyházzal és az egész teremtett világgal."<br><br>
Ebben a szentségben a bűnös, átadva magát Isten irgalmas ítéletének, bizonyos módon elővételezi az ítéletet, mely e földi élet végén következik. Ugyanis most, ebben az életben kapjuk a választási lehetőséget az élet és a halál között, és csak a megtérés útján léphetünk be a mennyek országába, ahonnan a súlyos bűn kizár. A bűnös -- a bűnbánat és a hit által megtérve Krisztushoz -- átmegy a halálból az életre, és "nem megy ítéletre" (Jn 5,24).<br><br>

<strong>A búcsúk </strong><br><br>
"A búcsú Isten színe előtt a már megbocsátott bűnökért járó, ideigtartó büntetések elengedése, melyet a keresztény hívő, aki megfelelően fölkészült és teljesítette a kiszabott föltételeket, elnyer az Egyház segítségével, amely mint a megváltás szolgálója Krisztus és a szentek elégtételt nyújtó érdemeinek kincstárát hivatalosan kezeli és abban részesít."<br><br>
"A búcsú részleges vagy teljes, attól függően, hogy a bűnökért járó ideigtartó büntetéstől részlegesen vagy teljesen szabadít-e meg." "Minden hívő nyerhet búcsúkat (...) önmaga számára vagy az elhunytak javára."<br><br>

<strong>A BŰNÖK BÜNTETÉSE </strong><br><br>
Hogy az Egyház e tanítását és gyakorlatát megérthessük, tudnunk kell, hogy a bűnnek kettős következménye van. A súlyos bűn megfoszt az Istennel fönnálló közösségtől és ezért alkalmatlanná tesz az örök életre, és az ettől való megfosztottság "az örök büntetés". Másrészt minden bűn, még a legkisebb is, a teremtményekhez való rendetlen ragaszkodással jár, ami szükségessé teszi a tisztulást, akár itt a földön, akár a halál után, az úgynevezett purgatóriumban (tisztítótűz, tisztítóhely). E tisztulás szabadít meg attól, amit "ideigtartó büntetésnek" nevezünk. E kétféle büntetést nem szabad valamiféle bosszúnak tartani, mellyel Isten az embert kívülről sújtja, hanem nagyon is a bűn természetéből származó valóságként kell fölfogni. Egy lángoló szeretetből fakadó megtérés létrehozhatja a bűnös teljes megtisztulását, úgyhogy semmi büntetés nem marad fönn.<br><br>
A bűn megbocsátása és az Istennel fennálló közösség helyreállítása magával hozza a bűn örök büntetéseinek elengedését. Az ideigtartó büntetések azonban megmaradnak. A keresztény embernek mindenfajta szenvedést és megpróbáltatást türelemmel viselve, és amikor eljön a nap, a halált derűs lélekkel fogadva, törekednie kell arra, hogy a bűn ezen ideigtartó büntetéseit kegyelemnek tekintse; az irgalmasság és szeretet cselekedetei, az imádság és a különböző vezeklési gyakorlatok által igyekeznie kell, hogy teljesen levesse magáról a "régi embert" és magára öltse az "új embert".<br><br>

<strong>A bűnbánat szentségének kiszolgáltatása </strong><br><br>
A többi szentséghez hasonlóan a bűnbánat szentsége is liturgikus cselekmény. A szentség kiszolgáltatásának elemei rendszerint a következők: köszöntés és a pap áldása, Isten igéjének olvasása -- a lelkiismeretet megvilágosítására és a bánat fölkeltésére -- és buzdítás a bánatra; gyónás, mely beismeri a bűnöket és föltárja a pap előtt; elégtétel kirovása és elfogadása; a pap által adott föloldozás; hálaadás, majd elbocsátás a pap áldásával.<br><br>
A bizánci liturgia a föloldozásnak többféle, könyörgő formáját ismeri, amelyek csodálatosan kifejezik a megbocsátás misztériumát, például: "Isten, aki Nátán prófétán keresztül megbocsátott Dávidnak, midőn az minden bűnét megvallotta, és megbocsátott Péternek, aki keservesen sírt, és a bűnös nőnek, aki könnyeivel öntözte a lábát, a vámosnak és a tékozló fiúnak, ugyanez az Isten bocsásson meg neked általam, bűnös által ebben a világban és a másikban, és anélkül, hogy elítélne, szólítson téged félelmetes ítélőszéke elé. Aki áldott mindörökkön örökké. Amen."<br><br>
A bűnbánat szentsége helyet kaphat közösségi bűnbánati szertartás keretében is, melynek során a hívek együtt készülnek föl a gyónásra és együtt adnak hálát az elnyert bocsánatért. Ebben az esetben a bűnök személyes megvallása és az egyéni föloldozás az igeliturgiában -- olvasmányok, homília, közös lelkiismeretvizsgálat, közös ima a bűnbocsánatért, Miatyánk, közös hálaadás -- kap helyet. Ez a közösségi ünneplés világosabban kifejezi a bűnbánat egyházi--közösségi jellegét. Bármilyen formában történjék, a bűnbánat szentsége természeténél fogva mindig liturgikus, azaz egyházi és nyilvános cselekmény.<br><br>
Súlyos szükség esetén a kiengesztelődés közösségi formáját is lehet választani általános gyónással és föloldozással. Ilyen súlyos szükség a közvetlen halálveszély, amikor a papnak vagy papoknak nincs elegendő ideje-idejük meghallgatni valamennyi bűnbánó gyónását. Ilyen helyzet van akkor is, ha nincs elegendő gyóntató, aki a sok gyónó egyéni gyónását megfelelő időn belül meg tudná hallgatni, s ennek következtében a bűnbánók saját hibájukon kívül hosszú ideig nélkülözni kényszerülnének a szentségi kegyelmet vagy a szentáldozást. Ebben az esetben a föloldozás érvényességéhez a hívekben meg kell lenni a szándéknak, hogy súlyos bűneiket a lehető leghamarabb egyénileg meggyónják. Annak megítélése, hogy egy általános föloldozás szükséges feltételei megvannak-e, a megyéspüspökre tartozik. A hívők nagy száma egy nagy ünnepen vagy zarándoklatokon nem jelent ilyen szükséghelyzetet.<br><br>
"Az egyéni és teljes bűnvallomás és feloldozás marad változatlanul a hívek Istennel és az Egyházzal történő kiengesztelődésének az egyedüli és rendes módja, kivéve, ha egy ilyen bűnvallomás fizikailag vagy erkölcsileg lehetetlen." Ennek nagyon mély alapjai vannak. Krisztus cselekszik minden szentségben. Ő személyesen fordul minden egyes bűnöshöz: "Fiam, bocsánatot nyertek bűneid" (Mk 2,5). Ő az orvos, aki egyenként fordul minden beteghez, akinek szüksége van rá, hogy meggyógyítsa; Ő emel föl minden beteget, és viszi be újra a testvéri közösségbe. Ezért a személyes gyónás az Istennel és az Egyházzal történő kiengesztelődés legkifejezőbb formája.<br><br>