<h2>Egyházi rend szentsége</h2>
Az egyházi rend az a szentség, mely által a Krisztustól Apostolaira bízott küldetés teljesítése folytatódik az Egyházban az idők végezetéig: tehát az apostoli szolgálat szentsége. Három fokozata van: a püspökség, az áldozópapság és a diakonátus. <br><br>

<strong>Miért egyházi rend, "ordo" e szentség neve? </strong><br><br>
Az ókori Rómában az ordo szó polgári testületeket, elsősorban a kormányzók testületét jelentette. Az ordinatio valamilyen ordóba való fölvételt jelent. Az Egyházban voltak testületek, melyeket a hagyomány, nem szentírási alapok nélkül, kezdettől fogva görögül taxeisznek, latinul ordinesnek nevezett: így beszél a liturgia ordo episcoporum, ordo presbiterorum, ordo diaconorumról. Más csoportokat is neveztek ordónak, például a katekumenokat, a szüzeket, a házastársakat, az özvegyeket... <br><br>
Az Egyház valamely testületébe való befogadás ordinatiónak nevezett szertartással történt, tudniillik vallási és liturgikus cselekménnyel, ami fölszentelés, áldás vagy szentség volt. Ma az ordinatio szó fönn van tartva annak a szentségi cselekménynek jelölésére, mely a püspökök, a papok és a diákonusok rendjébe fogad be, és fölülmúlja a közösség által végzett puszta választást, kijelölést, megbízást vagy beiktatást, mert a Szentlélek ajándékát hozza, mely lehetővé teszi a "szent hatalom" (sacra potestas) gyakorlását, és csak magától Krisztustól származhat Egyháza által. Az ordinatiót consecratiónak, `fölszentelésnek' is nevezik, mivel elkülönítés és feladat átadása, amelyet maga Krisztus végez Egyháza javára. A püspök kézföltétele a fölszentelő imádsággal együtt látható jele ennek a fölszentelésnek. <br><br>

<strong>Az egyházi rend szentsége az üdvösség rendjében </strong><br><br>
<strong>AZ ÓSZÖVETSÉG PAPSÁGA </strong><br><br>
A választott népet Isten "papi királysággá és szent néppé" (Kiv 19,6) tette. De Izrael népén belül Isten kiválasztotta a tizenkét törzs egyikét, Lévi törzsét, és elkülönítette a liturgikus szolgálatra. Maga Isten volt a leviták öröksége. Az Ószövetség első papjait sajátos szertartással szentelték föl. "Arra rendelték (őket), hogy az Isten tiszteletében képviseljék az embereket és a bűnökért áldozatokat mutassanak be." <br><br>
Ez a papság, bár arra lett alapítva, hogy Isten igéjét hirdesse s hogy az áldozatok és imádság által az Istennel való közösséget újra megszilárdítsa, alkalmatlan maradt az üdvösség megvalósítására, mert rászorult az áldozatok szüntelen ismétlésére anélkül, hogy eljutott volna a végső megszenteléshez, melyet egyedül Krisztus áldozata valósított meg. <br><br>
Az Egyház liturgiája mégis az ároni papságban, a leviták szolgálatában, valamint a hetven "vén" beiktatásában látja az Újszövetség fölszentelt papságának előképeit. A latin szertartás püspökszentelésének szentelési prefációjában így imádkozik az Egyház: <br><br>
"Urunk, Jézus Krisztus Istene és Atyja, (...) aki kegyelmed igéje által meghatároztad az Egyház rendjét. Kezdettől fogva kiválasztottad Ábrahám igazi gyermekeinek szent népét; elöljárókat és papokat állítottál, és szentélyedet soha nem hagytad szolgák nélkül..." <br><br>
A papszentelés alkalmával az Egyház így imádkozik: <br><br>
"Urunk, szentséges Atyánk, (...) már az Ószövetségben hivatalokat és szolgálatokat állítottál szent jelül: Mózest és Áront te rendelted arra, hogy népedet vezessék és megszenteljék. Segítségükre a közös műhöz férfiakat hívtál meg további szolgálatra és hivatalra. A pusztai vándorlás során a hetven vént Mózes lelkéből részesítetted (...). Áron fiainak részt adtál atyjuk hivatalából." <br><br>
És az Egyház a diákonusszentelés fölszentelő imádságában megvallja: <br><br>
"Mindenható Isten, (...) Egyházadat (...) az új templom nagyobbodására növeled és gyarapítod, a szent teendők ellátására a szolgálattevők hármas fokozatát alapítottad, hogy nevednek szolgáljanak, mint már kezdetben kiválasztottad Lévi fiait az első sátor szolgálatára." <br><br>

<strong>KRISZTUS EGYETLEN PAPSÁGA </strong><br><br>
Az ószövetségi papság összes előképe Jézus Krisztusban teljesedik be, aki "az egyetlen közvetítő Isten és ember között" (1Tim 2,5). Melkizedekben, "a magasságbeli Isten papjában" (Ter 14,18) a keresztény hagyomány Krisztus papságának előképét látja; Ő az egyetlen "Melkizedek rendje szerint való főpap" (Zsid 5,10; 6,20), "a szent, ártatlan, szeplőtelen" (Zsid 7,26), aki "egyetlen áldozattal egyszer s mindenkorra tökéletességre vezette a megszentelteket" (Zsid 10,14), tudniillik egyetlen keresztáldozatával. <br><br>
Krisztus megváltó áldozata egyetlen: egyszer és mindenkorra történt meg. És mégis az Egyház eucharisztikus áldozatában jelenvalóvá válik. Ugyanezt kell mondanunk Krisztus egyetlen papságáról: jelenvalóvá válik a szolgálati papság által, anélkül, hogy Krisztus papságának egyetlenségét csorbítaná: "És ezért Krisztus az egyetlen igazi pap, a többiek csak az ő szolgái". <br><br>

<strong>KÉT RÉSZESEDÉS KRISZTUS EGYETLEN PAPSÁGÁBAN </strong><br><br>
Krisztus, a főpap és egyetlen közvetítő az Egyházat Istennek és Atyjának papi országgá tette. A hívők egész közössége, mint ilyen, papi jellegű. A hívők -- ki-ki a hivatásának megfelelően -- keresztségi papságukat gyakorolják Krisztusnak, a papnak, prófétának és királynak küldetésében való részesedésük által. A keresztség és a bérmálás szentségei által a hívők "szent papsággá szenteltetnek". <br><br>
A püspökök és papok szolgálati vagyis hierarchikus papsága és az összes hívő általános papsága, jóllehet "mindegyik a maga sajátos módján, részesedik Krisztus egyetlen papságában" "lényegük szerint" különböznek, bár "egymáshoz vannak rendelve". Milyen értelemben? Míg a hívők általános papsága a keresztségi kegyelemnek, a hit, a remény és a szeretet életének, valamint a Lélek szerinti élet gyarapodásában valósul meg, addig a szolgálati papság az általános papság szolgálatában áll, és az összes keresztények keresztségi kegyelmének kibontakoztatására irányul. Egyike azon eszközöknek, melyekkel Krisztus szüntelenül építi és vezeti a maga Egyházát. Éppen ezért egy külön szentséggel, az egyházi rend szentségével adják át. <br><br>

<strong>KRISZTUS, A FŐ SZEMÉLYÉBEN... </strong><br><br>
A fölszentelt szolga egyházi szolgálatában maga Krisztus van jelen Egyháza számára mint testének Feje, nyájának Pásztora, a megváltás áldozatának Főpapja és az igazság Tanítója. Ez az, amit az Egyház kifejez, amikor azt állítja, hogy a pap az egyházi rend szentségének erejéből in persona Christi Capitis, `Krisztusnak, a Főnek személyében' cselekszik: <br><br>
"Így tehát a pap ugyanaz, Jézus Krisztus, akinek szent személyét az Ő meghívott szolgája viseli. Ez ugyanis a papszentelés miatt hasonlóvá válik a Főpaphoz, és hatalma van, hogy magának Krisztusnak személyében és erejével cselekedjék." <br><br>
"Krisztus az egész papság forrása; mert a Törvény alatti pap az Ő előképe volt, és az új Szövetség papja Krisztus személyében cselekszik." <br><br>
A fölszentelt szolgálat, főként a püspökök és papok szolgálata által válik láthatóvá a hívők közösségében Krisztusnak, az Egyház Fejének jelenléte. Antiochiai Szent Ignác szép kifejezése szerint a püspök tüposz tou Patrosz, az `Atya Isten élő képmása'. <br><br>
Krisztus jelenlétét a szolgában nem úgy kell érteni, mintha minden emberi gyöngeség, az uralkodhatnámság, a tévedések, azaz a bűn ellen védett lenne. A Szentlélek ereje a szolga nem minden cselekedeténél mutatkozik meg egyforma erővel. Míg a szentségekben ott van a biztosíték, hogy még a kiszolgáltató bűnössége sem tudja akadályozni a kegyelem gyümölcsét, addig sok más cselekedetben a szolga emberi pecsétje nyomot hagy, ami nem mindig az evangélium iránti hűség jele, ezért az Egyház apostoli termékenységének árthat. <br><br>
Ez a papság szolgálati. "Az a hivatal pedig, amelyet az Úr népe pásztoraira rábízott, igazi szolgálat." Teljes egészében Krisztusra és az emberekre irányul. Teljesen Krisztustól és az egyetlen papságától függ, s az emberekért és az egyházi közösség javára van. Az egyházi rend szentsége "szent hatalmat" közvetít, mely nem más, mint Krisztus hatalma. E tekintély gyakorlásának Krisztus példájához kell igazodnia, aki szeretetből utolsóvá és mindenki szolgájává lett. "Így tehát joggal mondta az Úr, hogy a nyájról való gondoskodás az iránta érzett szeretet bizonyítéka." <br><br>

<strong>..."AZ EGÉSZ EGYHÁZ NEVÉBEN" </strong><br><br>
A szolgálati papságnak nem csupán az a feladata, hogy Krisztust, az Egyház Fejét a hívek gyülekezete előtt megjelenítse; az egész Egyház nevében is cselekszik, amikor Isten elé terjeszti az Egyház imádságát, és különösen, amikor bemutatja az eucharisztikus áldozatot. <br><br>
Az "egész Egyház nevében" nem azt jelenti, hogy a papok a közösség megbízottai. Az Egyház imádsága és áldozata nem választható el fejének, Krisztusnak imádságától és áldozatától. Mindig Krisztus kultusza Egyházában és Egyháza által. Az egész Egyház, Krisztus Teste imádkozik és ajánlja föl magát "őáltala, ővele és őbenne" a Szentlélekkel egységben az Atyaistennek. Az egész test -- a fő és a tagok -- imádkozik és ajánlja föl önmagát, s ezért azokat, akik a Testben különleges módon szolgálnak, nem csupán Krisztus szolgáinak, hanem az Egyház szolgáinak is nevezik. Mivel a szolgálati papság Krisztust képviseli, képviselheti az Egyházat. <br><br>

<strong>Az egyházi rend szentségének három fokozata </strong><br><br>
"Így az isteni alapítású egyházi szolgálatot különböző rendekben gyakorolják azok, akiket már ősidőktől fogva <strong>püspököknek, áldozópapoknak, diákonusoknak</strong> hívnak." Az Egyház liturgiájában, Tanítóhivatalában és állandó gyakorlatában kifejezett katolikus tanítás a Krisztus papságában való szolgálati részvételnek két fokozatát ismeri: a püspökséget és az áldozópapságot. A diakonátus feladata az, hogy őket segítse és szolgálja. Ezért a mai szóhasználatban a sacerdos kifejezés a püspököket és a papokat jelöli, a diákonusokat nem. Mégis a katolikus tanítás az, hogy a három fokozatot -- a papságban való részesedés fokozatait (püspökség és papság) és a szolgálat hivatalának fokozatát (diakonátus) -- "ordinatiónak" nevezett szentségi cselekménnyel, azaz az egyházi rend szentségével adják át: <br><br>
"A diákonusokat mindenki úgy tisztelje, mint Jézus Krisztust, a püspököt, mint az Atya képmását, a presbitereket pedig, mint Isten szenátusát, mint az apostolok kollégiumát. Ezek nélkül nem lehet Egyházról beszélni." <br><br>

<strong>A PÜSPÖKSZENTELÉS -- AZ EGYHÁZI REND SZENTSÉGÉNEK TELJESSÉGE </strong><br><br>
"Az Egyházban az első időktől gyakorolt különféle szolgálatok között a hagyomány tanúsága szerint az első helyen áll azoké, akik püspökként a kezdettől folyamatos utódlás által az apostoli magvetés folytatói." <br><br>
Azért, hogy nemes küldetésüket méltó módon betölthessék, "e nagy hivatalok betöltéséhez az apostolok Krisztustól a leszálló Szentlélek különleges kiáradását nyerték, ők maguk pedig kézrátétellel adták tovább munkatársaiknak azt a lelki adományt, mely a püspökszentelésben jutott el mihozzánk". <br><br>
A II. Vatikáni Zsinat "tanítja, hogy a püspökszentelés az egyházi rend teljességét adja, melyet mind az Egyház liturgikus szokása, mind az egyházatyák szava főpapságnak, a szent szolgálat teljességének (summájának) nevez". <br><br>
"A püspökszentelés a megszentelés hivatalával magával hozza a tanítás és a kormányzás hivatalát is (...). Nyilvánvaló, hogy a kézrátétel és a szentelés szavai úgy adják át a Szentlélek kegyelmét és úgy vésik be a szentségi karaktert, hogy a püspökök kiemelkedő és szemmel látható módon magának Krisztusnak a tanítói, pásztori és főpapi hivatalában részesednek és az ő személyében cselekszenek." "Így tehát a püspökök a nekik adott Szentlélek által a hit igaz és hiteles tanítói, igaz és hiteles főpapok és pásztorok lettek." <br><br>
"A püspöki testület tagjává a szentségi fölszentelés, valamint a kollégium fejével és tagjaival való hierarchikus közösség által válik valaki." A püspöki rend kollegiális jellege és természete többek között abban az ősi egyházi szokásban is megmutatkozik, hogy az új püspök fölszentelését több püspök végzi. A püspök törvényes fölszenteléséhez ma Róma püspökének különleges intézkedése szükséges, mert az egy Egyházban a részegyházak közösségének ő a legfőbb látható köteléke és szabadságuk biztosítéka. <br><br>
Minden püspök Krisztus helyetteseként a rábízott részegyház fölött birtokolja a pásztori hivatalt; ugyanakkor terheli őt az összes részegyházról való gondoskodás, melyet valamennyi püspöktestvérével kollegiálisan kell viselnie. "Jóllehet minden püspök a nyáj csak rábízott részének szent pásztora, mint törvényes apostolutód isteni intézkedés és parancs alapján a többi püspökkel együtt letéteményese az Egyház apostoli feladatának." <br><br>
Az eddig mondottakból érthető, miért van sajátos jelentősége a püspök által celebrált Eucharisztiának mint az oltár körül annak vezetése alatt összegyűlt Egyház kifejezésének, aki láthatóan jeleníti meg Krisztust, a Jó Pásztort és Egyházának Fejét. <br><br>

<strong>A PAPOK -- A PÜSPÖK MUNKATÁRSAINAK FÖLSZENTELÉSE </strong><br><br>
"Krisztus, akit az Atya megszentelt és a világba küldött, apostolai által saját fölszenteltségének és küldetésének részeseivé tette utódaikat, a püspököket, akik szolgálatuk hivatalát az Egyházban különböző fokokban egyes személyeknek törvényesen átadták." A püspökök "szolgálati feladata alárendelt fokon átszállt a papokra, hogy a papi rendbe kerülve a Krisztustól kapott apostoli küldetés teljesítésére a püspöki rend munkatársai legyenek". <br><br>
"A papok hivatala, mivel a püspöki rendhez kapcsolódik, részesedik abban a tekintélyben, mellyel maga Krisztus építi, megszenteli és kormányozza testét. Ezért a papságot, mely föltételezi ugyan a keresztény beavatás szentségeit, külön szentség adja, mely a Szentlélek kenetével szentségi karakterrel pecsételi meg a papok lelkét, s általa hasonlóvá lesznek a Pap Krisztushoz, úgyhogy már Krisztusnak, a Főnek személyében cselekedhetnek." <br><br>
"Az áldozópapok, jóllehet nincs főpapi méltóságuk és hatalmuk gyakorlásában a püspököktől függnek, a papi méltóság révén hozzájuk kapcsolódnak; és az egyházi rend szentségének erejéből Krisztusnak, a legfőbb és örök papnak a képmása szerint az evangélium hirdetésére, a hívek lelkipásztori gondozására és az istentisztelet végzésére szentelik őket mint az Újszövetség igazi papjait." <br><br>
Az egyházi rend szentségének erejéből a papok részesei annak az egyetemes küldetésnek, amit Krisztus az apostolokra bízott. A lelki adomány, melyet a papok a szentelésben kaptak, nem valamilyen korlátozott és helyhez kötött küldetésre készíti föl őket, hanem az üdvösség egyetemes küldetésére "egészen a föld határáig"(ApCsel 1,8), oly módon, hogy "készek legyenek az evangéliumot mindenütt hirdetni". <br><br>
"Szent hivatalukat főképp az Eucharisztia ünneplésekor, vagyis a szent áldozati lakomán gyakorolják; itt mintegy Krisztus személyében tevékenykedve és az ő misztériumát hirdetve összekapcsolják a hívők önátadását főjük áldozatával; és az Újszövetség egyetlen áldozatát, tudniillik Krisztus áldozatát, aki egyszer ajánlotta föl önmagát az Atyának szeplőtelen áldozatul, jelenvalóvá teszik és alkalmazzák az Úr eljöveteléig." Egész papi szolgálatuk ebből az egyetlen áldozatból meríti erejét. <br><br>
"Az áldozópapok, akik a püspökök gondos munkatársai, segítői és szervei, Isten népének hivatott szolgái, egyetlen papi testületet (presbitériumot) alkotnak püspökükkel, bár más a rájuk bízott feladat. A híveknek egy-egy helyi közösségében valamiképpen jelenvalóvá teszik a püspököt, akihez bizalom és segítőkészség fűzi őket, s akitől átvállalják feladatainak és gondjainak egy részét mindennapi fáradozásukkal." A papok a szolgálatukat csak a püspökkel közösségben és tőle való függőségben gyakorolhatják. Az engedelmességi ígéret, amit a szenteléskor a püspöknek tesznek, és a püspök békecsókja a szentelési liturgia végén azt jelzi, hogy a püspök munkatársainak, fiainak, testvéreinek, barátainak tekinti őket, s hogy ők viszont szeretettel és engedelmességgel tartoznak neki. <br><br>
"A szentelés által a papi rend tagjaivá lett papokat a szentségi testvériség köteléke fűzi egymáshoz; abban az egyházmegyében, melynek szolgálatára püspökük vezetése alatt szentelték őket, egy presbitériumot alkotnak." A presbitérium egysége fejeződik ki abban a liturgikus szokásban, hogy a papszenteléskor a püspökök után az áldozópapok is ráteszik kezüket az újonnan fölszenteltre. <br><br>

<strong>A DIÁKONUSOK SZENTELÉSE -- "A SZOLGÁLATRA" </strong><br><br>
"A hierarchia alsóbb fokán állnak a diákonusok, akik ‘nem papságra, hanem szolgálatra’ kapják a kézfeltételt." A szentelendő diákonus fejére egyedül a püspök teszi rá a kezét, így jelezvén, hogy a diákonus szolgálata feladataiban kapcsolódik sajátosan a püspökhöz. <br><br>
A diákonusok sajátos módon részesednek Krisztus küldetésében és kegyelmében. A fölszentelés szentségi pecséttel (character) látja el őket, mely eltörölhetetlen, és Krisztushoz tesz hasonlóvá, aki "diákonus", azaz mindenki szolgája lett. A diákonusok föladata többek között, hogy a püspöknek és a papoknak szolgáljanak az isteni misztériumoknál, elsősorban az Eucharisztia ünneplése során, áldoztassanak, eskessenek és megáldják a házaspárt, hirdessék az evangéliumot és prédikáljanak, temessenek és végezzék a szeretet különféle szolgálatait. <br><br>
A II. Vatikáni Zsinat után a latin Egyház "mint az egyházi hierarchia sajátos és állandó fokozatát" helyreállította a diakonátust. A keleti egyházak mindig megőrizték. Ez az állandó diakonátus, amit nős emberek is fölvehetnek, jelentősen gazdagítja az Egyház küldetését. Tanácsos és hasznos, hogy olyan férfiak, akik az Egyházban -- akár liturgikus és pasztorális életében, akár a szociális és karitatív tevékenységében -- valóban diákonusi szolgálatot látnak el, "megerősödjenek az apostoloktól áthagyományozott kézfeltétel által, és szorosabban kötődjenek az oltárhoz, hogy ezáltal a diakonátus szentségi kegyelmével hatékonyabban tölthessék be tisztüket". <br><br>

<strong>A szentség kiszolgáltatása </strong><br><br>
A püspök-, pap- vagy diákonusszentelés, mivel a részegyház életében annyira fontos, megköveteli a hívők minél nagyobb számú részvételét. Lehetőség szerint vasárnap, a székesegyházban és az alkalomhoz illő ünnepélyességgel történjen. A három szentelés, tudniillik a püspök-, pap- és diákonusszentelés szerkezete ugyanaz. Helyük a szentmise keretében van. <br><br>
Az egyházi rend szentségének lényegi szertartása mindhárom fokozatban abban áll, hogy a püspök ráteszi kezét a szentelendő fejére, és a megfelelő szentelő imádsággal kéri Istentől a Szentlélek kiárasztását és a különös kegyelmi ajándékokat ahhoz a szolgálathoz, amelyre a jelöltet szenteli. <br><br>
Mint valamennyi szentség esetében, itt is vannak kiegészítő szertartások. Ezek a különböző liturgikus hagyományokban nagy változatosságot mutatnak, de közös bennük, hogy a szentségi kegyelem különböző szempontjait fejezik ki. Így a latin Egyházban a bevezető szertartások -- a szentelendő bemutatása és kiválasztása, a püspök beszéde, a szentelendő megkérdezése, a mindenszentek litániája -- azt fejezik ki, hogy a jelölt kiválasztása az Egyház szokásainak megfelelően történt. Ezek készítik elő az ünnepélyes fölszentelést. A fölszentelést követő szertartások szimbolikus módon fejezik ki és zárják le a végbement misztériumot: a püspököt és a papot szent krizmával kenik meg, ami a szolgálatukat termékennyé tevő Szentlélekkel való fölkenés jele. A püspöknek átadják az evangéliumos könyvet, a gyűrűt, a mitrát és a pásztorbotot az evangélium hirdetésére szóló apostoli küldetése, Krisztus jegyese, az Egyház iránti hűsége és az Úr nyája fölötti pásztorkodás jeleként. A papnak átadják a paténát és a kelyhet a szent nép áldozatának jeleként, melyeket Istennek kell bemutatnia. A diákonusnak, aki Krisztus evangéliumának hirdetését kapta küldetésül, átadják az evangéliumos könyvet. <br><br>

<strong>Ki szolgáltathatja ki ezt a szentséget? </strong><br><br>
Krisztus kiválasztotta az apostolokat, és részt adott nekik a maga küldetésében és hatalmában. Az Atya jobbjára emeltetvén nem hagyja el nyáját, hanem mindig őrzi az Apostolok és vezeti a pásztorok által, akik ma folytatják az ő művét. Krisztus tehát egyeseket apostolként, másokat pásztorként "ad". Tevékenységét a püspökök által folytatja. <br><br>
Mivel az egyházi rend az apostoli szolgálat szentsége, a püspökökre, mint az Apostolok utódaira tartozik, hogy "a lelki ajándékot" és "az apostoli magvetést" továbbadják. Az érvényesen szentelt, azaz az apostoli jogfolytonosságban álló püspökök az egyházi rend három fokozatának érvényes kiszolgáltatói. <br><br>

<strong>Ki veheti föl ezt a szentséget? </strong><br><br>
"A szent egyházi rendet érvényesen csak megkeresztelt férfi veheti föl." Az Úr Jézus férfiakat választott ki, hogy létrehozza a tizenkét apostol kollégiumát, és ugyanezt tették az apostolok, amikor munkatársakat választottak, akiknek folytatniuk kellett az ő feladatukat. A Püspökök Kollégiuma, melyhez az áldozópapok a papságban kapcsolódnak, jelenvalóvá és aktuálissá teszi a Tizenkettő kollégiumát Krisztus visszajöveteléig. Az Egyház tudja, hogy Urának e kiválasztása kötelezi. Emiatt nem lehetséges a nők pappá szentelése. <br><br>
Senki sem formálhat jogot ahhoz, hogy fölvegye az egyházi rend szentségét. Ugyanis senki nem tulajdoníthatja magának ezt a hivatalt. Ehhez Istentől kell meghívást kapni. Aki jeleit észleli, hogy Isten fölszentelt szolgálatra hívja, kívánságát alázatosan alá kell vetnie az Egyház tekintélyének, melynek joga és felelőssége valakit az egyházi rend fölvételére bocsátani. Mint minden kegyelmet, ezt a szentséget is csak ingyenes ajándékként lehet fogadni. <br><br>
Az állandó diákonusok kivételével a latin Egyház rendes körülmények között minden fölszentelt szolgáját olyan hívő férfiak közül választják, akik nőtlenek, és megvan az akaratuk, hogy a cölibátust "a mennyek országáért" megtartják (Mt 19,12). Akik arra kaptak meghívást, hogy osztatlanul az Úrnak és az ő dolgainak szenteljék magukat , egészen átadják magukat Istennek és az embereknek. A cölibátus annak az új életnek a jele, melynek szolgálatára szentelik az Egyház szolgáját; az örvendező szívvel vállalt cölibátus ragyogóan hirdeti Isten országát. <br><br>
A keleti egyházakban évszázadok óta más egyházfegyelem van érvényben: míg a püspököket kizárólag nőtlen férfiak közül választják, addig nős férfiakat diákonussá és áldozópappá szentelhetnek. Ez a gyakorlat hosszú idő óta törvényesnek számít; ezek a papok közösségeikben gyümölcsöző szolgálatot teljesítenek. Egyébként a keleti egyházakban a papi cölibátus nagy tiszteletnek örvend, és a papok közül sokan teljesen szabadon választják Isten országáért. Mind Keleten, mind Nyugaton, aki megkapta az egyházi rend szentségét, többé nem köthet házasságot. <br><br>

<strong>Az egyházi rend szentségének hatásai </strong><br><br>
<strong>AZ ELTÖRÖLHETETLEN JEGY </strong><br><br>
E szentség a Szentlélek sajátos kegyelme által Krisztushoz teszi hasonlóvá a szentelendőt, hogy Krisztus eszköze legyen az ő Egyháza javára. A szentelés hozza a képességet, hogy Krisztusnak, az Egyház Fejének követeként az ő hármas, papi, prófétai és királyi hivatalában cselekedjék. <br><br>
Miként a keresztségnél és a bérmálásnál a Krisztus hivatalában való részesedés egyszer s mindenkorra szól, úgy az egyházi rend szentsége is eltörölhetetlen lelki jegyet ad, és sem megismételni, sem időlegesen kiszolgáltatni nem lehet. <br><br>
Az érvényesen fölszentelt személy súlyos indokok alapján fölmenthető a kötelezettségek alól, melyek a fölszenteléssel adódnak, vagy gyakorlásuktól el lehet őt tiltani, de a szó szoros értelmében nem válhat újra laikussá, mert a szenteléssel belé vésett karakter mindig megmarad. A szentelése napján kapott meghívás és a küldetés maradandóan megjelölik őt. <br><br>
Mivel Krisztus az, aki a fölszentelt szolga által megvalósítja az üdvösséget, ennek méltatlansága nem akadályozza meg, hogy Krisztus cselekedjék. Szent Ágoston határozottan állítja: <br><br>
"A gőgös szolga az ördögök közé számít, de Krisztus ajándéka miatta nem szennyeződik be; ami rajta keresztül kiárad, megőrzi a maga tisztaságát; ami keresztülfolyik rajta, kristálytisztán jut el a termékeny talajba. (...) A szentség lelki ereje olyan, mint a fény: tisztán érkezik el ahhoz, akit meg kell világosítania, és ha tisztátalanokon megy keresztül, nem szennyeződik be." <br><br>

<strong>A SZENTLÉLEK KEGYELME </strong><br><br>
A Szentlélek e szentségnek adott sajátos kegyelme a hasonlóság kegyelme a Pap, Tanító és Pásztor Krisztushoz, akinek a fölszentelt a szolgája lett. <br><br>
A sajátos szentségi kegyelem a püspök számára elsősorban az erősség kegyelme ("Spiritum Principalem", a Lelket, aki a legfőbb vezetőket állítja, kéri a püspököt fölszentelő imádság a latin szertartásban): ez teszi képessé arra, hogy Egyházát mint atya és pásztor határozottan és okosan vezesse és védelmezze; önzetlen szeretettel mindenki, egész különlegesen a szegények, betegek és ínséget szenvedők iránt. Ez a kegyelem sürgeti őt, hogy mindenkinek hirdesse az evangéliumot, hogy nyájának példaképe legyen, előtte járjon a megszentelődés útján, hogy az Eucharisztiában egyesüljön a Pap és Áldozat Krisztussal; és nem riad vissza attól, hogy életét adja juhaiért. <br><br>
"Atyánk, aki ismered a szíveket, szolgádnak, akit a püspöki szolgálatra meghívtál, add meg, hogy legeltesse szent nyájadat, és színed előtt kifogástalanul gyakorolja a magasztos papságot azáltal, hogy éjjel-nappal neked szolgál. Arcodat szüntelenül hangolja irgalmasságra, és ajánlja föl szent Egyházad áldozati adományait. A magasztos papság Lelkének erejéből legyen hatalma parancsod szerint megbocsátani a bűnöket. Rendelésed szerint ossza szét a szolgálatokat, és oldjon föl minden köteléket az Apostolaidnak adott hatalom erejében. Nyerje el tetszésedet szelídségével és tiszta szívével, hogy kellemes illatot ajánlhasson föl neked Fiad, Jézus Krisztus által..." <br><br>
A papszentelés által adott lelki ajándék fejeződik ki a bizánci szertartás következő imádságában, melyet a püspök a kézrátételkor mond: <br><br>
"Urunk, akit a papságra emelni méltóztattál, töltsd be a Szentlélek ajándékával, hogy méltó legyen arra, hogy kifogástalanul álljon oltárodnál, hirdesse országod evangéliumát, ellássa az igazság igéjének szolgálatát, fölajánlja neked az adományokat és a lelki áldozatot, megújítsa népedet az újjászületés fürdőjében, hogy nagy Istenünk és Üdvözítőnk, Jézus Krisztus visszajövetelének napján elébe mehessen a te egyszülött Fiadnak, és a te végtelen jóságodtól kapja meg hivatalának hűséges szolgálatáért a jutalmat." <br><br>
A diákonusoknak pedig "a szentségi kegyelem megadja az erőt, hogy Isten népének a liturgia, az ige és a szeretet diakoniájában a püspökkel és presbitériumával közösségben szolgáljanak". <br><br>
A papság kegyelmének és a feladat nagyságának láttán a szent tanítók sürgetést éreztek a megtérésre, hogy életük megfeleljen Annak, akinek a szentség a szolgáivá tette őket. Nazianzi Szent Gergely fiatal papként így kiáltott föl: <br><br>
"Előbb tisztává kell lenni, és csak utána tisztítani; előbb meg kell tanulni a bölcsességet, és csak utána tanítani; előbb fénnyé kell válni, és csak utána másokat megvilágítani; előbb közeledni kell Istenhez, és csak utána hozzá vezetni másokat; előbb meg kell szentelődni, és utána megszentelni; kézen fogni és okosan tanácsot adni." "Tudom, kinek szolgái vagyunk, milyen szinten állunk, és ki az, aki felé úton vagyunk. Ismerem Isten magasztosságát és az ember gyöngeségét, de erejét is." Ki tehát a pap? "Ő az igazság védelmezője; az angyalok közé lép, az arkangyalokkal dicsőít, feljuttatja az áldozatokat a mennyei oltárra, részt vesz Krisztus papi szolgálatában, megújítja a teremtményt, helyreállítja benne Isten képmását, újjáalkotja a mennyei világ számára, s ami a legmagasztosabb, megistenül és másokat megistenít." <br><br>
És a szent ars-i plébános mondja: "A pap folytatja a megváltás művét a földön". (...) "Ha valaki itt a földön helyesen értené, hogy mi a pap, meghalna, de nem a rémülettől, hanem a szeretettől". (...) "A papság Jézus Szívének szeretete." <br>