<h2>Eucharisztia</h2>

A szent Eucharisztia befejezi a keresztény beavatást. Akik a keresztség által fölemeltettek a királyi papság méltóságára és a bérmálás által mélyebben hasonulóvá váltak Krisztushoz, az Eucharisztia által az egész közösséggel együtt részesednek az Úr áldozatában. <br><br>
"Üdvözítőnk az utolsó vacsora alkalmával, azon az éjszakán, melyen elárultatott, megalapította testének és vérének eucharisztikus áldozatát, hogy így a kereszt áldozatát a századokon át eljöveteléig megörökítse, és így szeretett jegyesére, az Egyházra bízza halálának és föltámadásának emlékezetét: az irgalom szentségét, az egység jelét, a szeretet kötelékét mint húsvéti lakomát, melyen Krisztust vesszük magunkhoz, lelkünket kegyelem tölti el, s a jövendő dicsőség záloga nekünk adatik." <br><br>

<strong>Az Eucharisztia -- az egyházi élet forrása és csúcsa </strong><br><br>
Az Eucharisztia "az egész keresztény élet forrása és csúcsa". "Az összes szentség, mint minden más egyházi szolgálat és az apostoli tevékenység is, a szent Eucharisztiához tartozik és reá irányul. Az Eucharisztiában ugyanis benne van az Egyház minden lelki java (Krisztus, a mi Húsvétunk)." <br><br>

<strong>Hogyan nevezik ezt a szentséget? </strong><br><br>
E szentség kimeríthetetlen gazdagsága fejeződik ki különböző elnevezéseiben, melyek közül mindegyik más szempontra utal. Nevei: <br><br>
<ul>
    <li>Eucharisztia, mert hálaadás Istennek. Az eucharisztein (Lk 22,19; 1Kor 11,24) és az eulogein (Mt 26,26; Mk 14,22) szavak azokra a zsidó áldásokra emlékeztetnek, amelyek -- különösen étkezések alatt -- magasztalták Isten műveit: a teremtést, a megváltást és a megszentelést.</li>
    <li>Úrvacsora, mert arról a vacsoráról van szó, amelyet az Úr szenvedése előestéjén tanítványaival költött el, és a Bárány mennyei Jeruzsálem-béli menyegzős lakomájának elővételezéséről. </li>
    <li>Kenyértörés, mert a zsidó étkezésnek ezt a sajátos szertartását használta föl Jézus, amikor családfőként megáldotta és szétosztotta a kenyeret, különösen az utolsó vacsorán. E cselekedetről ismerik fel Őt föltámadása után a tanítványok. Az első keresztények eucharisztikus összejöveteleiket "kenyértörésnek" nevezték. Ezzel azt akarták mondani, hogy mindazok, akik az egy, megtört kenyérből,  Krisztusból esznek, közösségre lépnek vele és őbenne egyetlen testet alkotnak. </li>
    <li>Eucharisztikus összejövetel (szünaxisz), mert az Eucharisztiát a hívők összejövetelében, az Egyház látható megjelenésében ünneplik. </li>
    <li>Az Úr szenvedésének és föltámadásának emlékezete. </li>
    <li>Szent áldozat, mert megjeleníti az üdvözítő Krisztus egyetlen áldozatát, s mert magába zárja az Egyház fölajánlását; szentmiseáldozat, "a dicséret áldozata" (Zsid 13,15), lelki áldozat, tiszta és szent áldozat, mert az Ószövetség összes áldozatát beteljesíti és fölülmúlja. </li>
    <li>Szent és isteni liturgia, mert az Egyház egész liturgiája e szentség ünneplésében találja meg középpontját és legtömörebb kifejezését; ugyanebben az értelemben nevezik a szent misztériumok ünneplésének is. Beszélünk a legszentebb Szentségről (Sanctissimum Sacramentum) is, mert az Eucharisztia a szentségek szentsége. Ez a név a tabernákulumban őrzött szentségi színekre is használatos. </li>
    <li>Communio, mert e szentség révén egyesülünk Krisztussal, aki testében és vérében részesít azért, hogy egy testet alkossunk Vele; nevezik az Eucharisztiát görögül ta hagia, latinul sancta, `szent dolgoknak' is -- ez az Apostoli hitvallásban szereplő `szentek     közössége' elsődleges jelentése --; egyéb nevei: angyalok kenyere, mennyei kenyér, halhatatlanság gyógyszere, viaticum, `útravaló'. </li>
    <li>Szentmise, mert a liturgia, amelyben az üdvösség misztériuma beteljesedik, a hívek küldetésével (missio) végződik, hogy Isten akaratát mindennapi életükben betöltsék. </li>
</ul>
<strong>Az Eucharisztia az üdvösség rendjében </strong><br><br>
<strong>A KENYÉR ÉS A BOR JELEI </strong><br><br>
A szentmise közepén a kenyér és a bor Krisztus szavai és a Szentlélek segítségül hívása által Krisztus testévé és vérévé válik. Parancsának megfelelően az Egyház az Ő dicsőséges eljöveteléig folytatja azt, amit az Úr szenvedése előestéjén tett: "Kezébe vette a kenyeret (...)" "Kezébe vette a borral telt kelyhet (...)." A kenyér és a bor titokzatos módon Krisztus testévé és vérévé válnak, ugyanakkor a teremtés jóságának jelei maradnak. A fölajánlásban hálát adunk a Teremtőnek a kenyérért és a borért, "az emberi munka" gyümölcséért, ami előbb a "föld gyümölcse" és a "szőlőtő termése", azaz a Teremtő adományai. Az Egyház Melkizedeknek, a királynak és papnak a gesztusában, amikor fölajánlotta "a kenyeret és bort" (Ter 14,18), saját fölajánlásának előképét látja. <br><br>
Az Ószövetségben a kenyeret és a bort a zsengeáldozatok között ajánlották föl a Teremtő iránti hála jeleként. Az Egyiptomból való kivonulás összefüggésében még egy új jelentéssel gyarapodtak. A kovásztalan kenyerek, melyeket Izrael népe minden évben a pászkaünnepen evett, az Egyiptomból való szabadító kivonulás sietségére emlékeztetnek; a pusztai manna állandóan Izrael emlékezetébe idézi, hogy Isten szavának kenyeréből él. Végül a mindennapi kenyér az Ígéret földjének gyümölcse, záloga annak, hogy Isten hűséges ígéreteihez. Az "áldás kelyhe" (1Kor 10,16) a zsidók húsvéti vacsorájának a végén a bor ünnepi öröméhez eszkatologikus jelentést kapcsol: Jeruzsálem messiási helyreállításának várását. Jézus úgy alapította meg Eucharisztiáját, hogy a kenyér és a kehely áldásának új és végleges értelmet adott. <br><br>
A kenyérszaporítás csodái, amikor az Úr áldást mondott, megtörte a kenyereket és tanítványai által szétosztotta a sokaság táplálékául, előképei az Ő egy eucharisztikus kenyere túláradó bőségének: a Kánában borrá változtatott víz jele már Jézus megdicsőülésének óráját hirdeti. Magát a beteljesedést nyilvánítja ki a menyegzői lakoma az Atya országában, ahol a hívők a Krisztus vérévé vált új bort fogják inni. <br><br>
Az Eucharisztia első bejelentése megosztotta a tanítványokat, miként a szenvedés bejelentése megbotránkoztatta őket: "Kemény beszéd ez! Ki hallgathatja?" (Jn 6,60). Az Eucharisztia és a kereszt a botrány sziklái. Egy és ugyanarról a misztériumról van szó, és mindig megoszlásra adnak alkalmat: "Ti is el akartok menni?" (Jn 6,67): az Úr e kérdése végig hangzik a századokon mint szeretetének meghívása annak fölfedezésére, hogy egyedül Ő az, akinél "az örök élet igéi" vannak (Jn 6,68); és a hitben elfogadni Eucharisztiájának ajándékát azt jelenti, hogy Őt magát fogadjuk be. <br><br>

<strong>AZ EUCHARISZTIA ALAPÍTÁSA </strong><br><br>
Az Úr, mivel szerette övéit, mindvégig szerette őket. Tudván, hogy eljött az óra, amikor ebből a világból átmegy az Ő Atyjához, a vacsora közben megmosta lábukat, és átadta nekik a szeretet parancsát. Hogy rájuk hagyja e szeretet zálogát, s hogy övéitől soha ne távozzon el és húsvétja részeseivé tegye őket, halála és föltámadása emlékezetéül megalapította az Eucharisztiát, és megparancsolta Apostolainak, "akiket akkor az Újszövetség papjaivá szentelt," hogy visszajöveteléig ünnepeljék. <br><br>
A három szinoptikus evangélium és Szent Pál hagyták ránk az Eucharisztia alapításának elbeszélését; Szent János a maga részéről idézi Jézus szavait a kafarnaumi zsinagógában, amelyek előkészítették az Eucharisztia alapítását: Krisztus az élet égből alászállott kenyerének nevezi önmagát. <br><br>
Jézus a húsvéti időt választotta arra, hogy megtegye, amit Kafarnaumban előre mondott: testét és vérét adja tanítványainak: <br><br>
"Elérkezett a kovásztalan kenyér napja, amikor meg kellett ölni a húsvéti bárányt. Jézus elküldte Pétert és Jánost ezzel a megbízatással: ’Menjetek, készítsétek el a húsvéti bárányt, hogy elkölthessük’. (...) Elmentek és el is készítették a húsvéti bárányt. Amint elérkezett az óra, asztalhoz ült a tizenkét apostollal együtt. Így szólt hozzájuk: ’Vágyva vágytam rá, hogy ezt a húsvéti bárányt elköltsem veletek, mielőtt szenvedek. Mondom nektek, többé nem eszem húsvéti bárányt, míg be nem teljesedik Isten országában.’ (...) Most a kenyeret vette kezébe, hálát adott, megtörte és odanyújtotta nekik ezekkel a szavakkal: ’Ez az én testem, amely értetek adatik. Ezt cselekedjétek az én emlékezetemre.’ Ugyanígy a vacsora végén fogta a kelyhet is, és azt mondta: ’Ez a kehely az új szövetség az én véremben, mely értetek kiontatik’." (Lk 22,7--20) <br><br>
Amikor Jézus az utolsó vacsorát apostolaival a húsvéti lakoma keretében ünnepelte, a zsidó húsvétnak megadta végső értelmét. Valójában ugyanis Jézus átmenetele a halálon és a föltámadáson át az Ő Atyjához, tudniillik az új húsvét, elővételezve lett az utolsó vacsorán, és ezt ünnepeljük az Eucharisztiában, mely beteljesíti a zsidó húsvétot és elővételezi az Egyház végső húsvétját az Ország dicsőségében. <br><br>

<strong>"EZT CSELEKEDJÉTEK AZ ÉN EMLÉKEZETEMRE" </strong><br><br>
Jézus parancsa, hogy gesztusait és szavait ismételjék, "amíg el nem jön" (1Kor 11,26), nemcsak annyit követel, hogy emlékezzünk Jézusra és arra, amit Ő tett. A parancs arra irányul, hogy az Apostolok és utódaik Krisztus -- az Ő élete, halála, föltámadása és az Atyánál értünk való közbenjárása -- emlékezetét liturgikusan ünnepeljék. <br><br>
Az Egyház kezdettől fogva hű maradt az Úr parancsához. A jeruzsálemi egyházról ez olvasható: <br><br>
"Állhatatosan kitartottak az apostolok tanításában és közösségében, a kenyértörésben és az imádságban. (...) Egy szívvel-lélekkel mindennap összegyűltek a templomban. A kenyeret házaknál törték meg, s örömmel és tiszta szívvel vették magukhoz az ételt." (ApCsel 2,42.46) <br><br>
A keresztények elsősorban "a szombatok első napján", azaz vasárnap, Jézus föltámadásának napján gyűltek össze, hogy "megtörjék a kenyeret" (ApCsel 20,7). Az Eucharisztia ünneplése egészen napjainkig ugyanúgy folytatódik annyira, hogy ma az Egyházban mindenütt azonos alapszerkezettel ünnepeljük. Az Eucharisztia az Egyház életének állandó középpontja. <br><br>
Isten zarándok népe Jézus húsvéti misztériumát hirdetve, "amíg el nem jön" (1Kor 11,26), szentmiséről szentmisére "a kereszt szűk ösvényén" halad előre a mennyei lakoma felé, amelyen az összes választottak az Ország asztalához fognak ülni. <br><br>

<strong>IV. Az Eucharisztia liturgikus ünneplése </strong><br><br>
<strong>MINDEN IDŐK SZENTMISÉJE </strong><br><br>
A 2. századból ismerjük Szent Jusztinosz vértanú tanúságát az eucharisztikus ünneplés alapszerkezetéről. És e szerkezet mind a mai napig az összes nagy liturgia-családban azonos maradt. Íme, mit ír ő 155 körül, hogy a pogány Antoninus Pius (138--161) császárnak elmagyarázza, mit tesznek a keresztények: <br><br>
"A Napról elnevezett napon mindannyian, városokban és a falvakban egyaránt, összejövetelt tartunk. <br><br>
És fölolvassuk az Apostolok emlékiratait és a Próféták írásait, amint azt az idő engedi. <br><br>
A felolvasó elhallgatása után az elöljáró beszédében int és buzdít, hogy ezeket a szép dolgokat tetteinkkel utánozzuk. <br><br>
Majd mindannyian fölállunk és közösen imát mondunk." <br><br>
"Közösen imádkozunk magunkért (...) meg a többiekért, (...) hogy miután az igazságot megtanultuk, a helyes életre törekedjünk, tetteinkben a jót kövessük, s azon legyünk, hogy parancsait megtartsuk, és az örök üdvösséget elnyerjük. <br><br>
Imáink befejezésekor csókkal köszöntjük egymást. <br><br>
Ezek után a testvérek elöljárójához kenyeret és kelyhet visznek vízzel vegyített borral, aki kezébe veszi, dicséretet és dicsőítést mond a mindenség Atyjának a Fiú és a Szentlélek neve által, hálát ad neki (görögül: eucharisztian), és áldást mond hosszasan azokért, amiket nekünk adott, hogy Ő bennünket ezekre méltatott. <br><br>
Imái és hálaadása befejezéseképpen az egész nép ráfeleli az Áment. (...) Az elöljáró hálaadása és az egész nép felelete után az általunk diákonusoknak nevezettek minden jelenlevőnek osztanak a hálaadás kenyeréből és a vízzel elegyített borából, visznek belőle a távollevőknek is. <br><br>

Az Eucharisztia liturgiája ma is alapvetően abban a szerkezetben történik, mely századokon át megmaradt. Két, szoros egységet alkotó fókusz körül bontakozik ki. <br><br>
<ul>
    <li >gyülekezés, igeliturgia az olvasmányokkal, a homíliával és az egyetemes könyörgéssel; </li>
    <li >az eucharisztikus liturgia a kenyér és a bor fölajánlásával, a konszekráló hálaadással és az áldozással. </li>
</ul>
Az igeliturgia és az eucharisztikus liturgia "egyetlen istentiszteleti cselekményt" alkotnak. Valójában ugyanis az Eucharisztiában számunkra megterített asztal egyszerre Isten igéjének és az Úr Testének asztala. <br><br>
Nemde ugyanaz a folyamat játszódik le itt, mint a föltámadott Jézus tanítványaival elköltött húsvéti lakomáján? Útközben ő maga magyarázta nekik az Írásokat, majd asztalhoz ült velük, "kezébe vette a kenyeret, megáldotta, megtörte és odanyújtotta nekik". <br><br>

<strong>AZ ÜNNEPLÉS FOLYAMATA </strong><br><br>
Valamennyien összegyűlnek. A keresztények az eucharisztikus ünneplésre egy helyen jönnek össze. Ezen a helyen a fő hely magát Krisztust illeti, aki az Eucharisztia főszereplője. Ő az Újszövetség főpapja. Láthatatlanul Ő maga vezet minden eucharisztikus ünnepet. Őt képviselve vezeti az összejövetelt a püspök vagy a pap (Krisztusnak, a Főnek személyében cselekedve), beszédet tart az olvasmányok után, átveszi az adományokat és elmondja az eucharisztikus imádságot. Az ünneplésben valamennyien részt vesznek, mindenki a maga módján: a felolvasók, az adományvivők, az áldoztatók és az egész nép, melynek Amenje a részvételt fejezi ki. <br><br>
Az igeliturgia magában foglalja "a próféták írásait", vagyis az Ószövetséget, és az "Apostolok emlékiratait", azaz leveleiket és az evangéliumokat; a homília után -- mely arra buzdít, hogy a hallott igét úgy fogadjuk, mint Isten szavát, amint valójában az is, és váltsuk tettekre -- közbenjáró könyörgések következnek minden emberért az Apostol szavai szerint: "Mindenekelőtt arra kérlek, végezzetek imát, könyörgést, esedezést és hálaadást minden emberért, a királyokért és az összes elöljárókért" (1Tim 2,1--2). <br><br>
Az adományok bemutatása (offertorium): akkor az oltárhoz olykor körmenetben kenyeret és bort hoznak, melyeket a pap Krisztus nevében fölajánl az eucharisztikus áldozatban, melyben Krisztus testévé és vérévé válnak. Ez az utolsó vacsorán "a kenyeret és a kelyhet kezébe vevő" Krisztus gesztusa. "Ezt a tiszta áldozatot egyedül az Egyház ajánlja föl a Teremtőnek, az Ő teremtéséből hálaadással ajánlva föl neki." Az adományok fölajánlása az oltáron Melkizedek gesztusát idézi, és a Teremtő ajándékait Krisztus kezére bízza. Ő a maga áldozatában tökéletessé teszi az ember minden áldozatot bemutató törekvését. <br><br>
A keresztények az Eucharisztiának szánt kenyér és bor mellett kezdettől fogva a rászorulók támogatására is vittek magukkal adományokat. E gyűjtési szokás (collecta) mindig aktuális, és Krisztus példája serkenti, aki szegény lett, hogy minket gazdaggá tegyen: <br><br>
"A jómódúak és aki akar -- ki-ki szándékának megfelelően -- adakozik, azt, amit jónak lát; az összegyűjtött adományokat az elöljárónál helyezik letétbe, s az belőle gondoskodik az árvákról és özvegyekről és azokról, akik betegség vagy más ok miatt szükséget szenvednek, továbbá a bebörtönzöttekről és az átutazó idegenekről; egyszóval mindenkin segít, aki rászorul." <br><br>
Az anafora (kánon): az eucharisztikus imádsággal, a hálaadó és átváltoztató imádsággal elérkezünk az ünneplés szívéhez és csúcsához: <br><br>
A prefációban az Egyház Krisztus által a Szentlélekben hálát ad az Atyának minden művéért, a teremtésért, a megváltásért és a megszentelésért. Az egész közösség csatlakozik ahhoz a szüntelen dicsérethez, melyet az égi Egyház, az angyalok és a szentek a háromszor szent Istennek énekelnek. <br><br>
Az epiklézisben az Egyház kéri az Atyát, hogy küldje el Lelkét (vagy áldásának hatalmát) a kenyérre és a borra, hogy az Ő ereje által Jézus Krisztus Testévé és Vérévé váljanak; és hogy azok, akik részesednek az Eucharisztiában, egy test és egy lélek legyenek (egyes liturgiákban az epiklézist az anamnézis után helyezik). <br><br>
Az alapítás elbeszélésében Krisztus cselekedetének és szavainak ereje, valamint a Szentlélek hatalma a kenyér és a bor színe alatt szentségileg megjelenítik Krisztus Testét és Vérét, a kereszten egyszer s mindenkorra fölajánlott áldozatát. <br><br>
Az ezt követő anamnézisben az Egyház megemlékezik Jézus Krisztus szenvedéséről, föltámadásáról és dicsőséges eljöveteléről; bemutatja az Atyának az Fia áldozatát, aki megbékéltet bennünket Ővele. <br><br>
A közbenjáró imádságokban az Egyház kifejezi, hogy az Eucharisztiát az egész mennyei és földi Egyházzal, élőkkel és holtakkal együtt ünnepli, közösségben az Egyház pásztoraival, a Pápával, a megyéspüspökkel, papságával és diákonusaival, s az egész Egyház összes püspökeivel és egyházaikkal. <br><br>
Az áldozásban (kommunióban), melyet a Miatyánk és a kenyértörés előz meg, a hívők a "mennyből való kenyeret" és az "üdvösség kelyhét" veszik, Krisztus Testét és Vérét, aki önmagát adta "a világ életéért" (Jn 6,51). <br><br>
Mivel ez a kenyér és ez a bor ősi kifejezés szerint "eucharisztizált", "ezt a táplálékot mi Eucharisztiának nevezzük, melyből senki kívülálló nem részesülhet, csak az, aki igaznak fogadja el a tőlünk kapott tanítást és megmosdott a bűnök bocsánatára az újjászületés fürdőjében és úgy él, ahogyan azt Krisztus meghagyta." <br><br>

<strong>A szentségi áldozat: hálaadás, emlékezet, jelenlét </strong><br><br>
A keresztények az Eucharisztiát kezdettől fogva ünneplik, éspedig olyan formában, amely lényegét tekintve nem változott sem a korok, sem a liturgiák különbözősége miatt. Azért teszik ezt, mert kötelezőnek érzik a parancsot, amit az Úr szenvedésének előestéjén adott: "Ezt cselekedjétek az én emlékezetemre" (1Kor 11,24--25). <br><br>
Az Úr e parancsát teljesítjük, amikor az ő áldozatának emlékezetét ünnepeljük. Ezt cselekedvén azt ajánljuk föl az Atyának, amit Ő maga ajándékozott nekünk: teremtésének ajándékait, a kenyeret és a bort, melyek Krisztus szavaira és a Szentlélek erejéből Krisztus testévé és vérévé válnak: így Krisztus valóságosan és titokzatos módon jelenvalóvá válik. <br><br>
Ezért az Eucharisztiát úgy kell szemlélnünk, <br><br>
<ul>
    <li >mint hálaadást és dicséretet az Atyának; </li>
    <li >mint Krisztus és az ő teste áldozati emlékezetét; </li>
    <li >mint Krisztus jelenlétét szavai és Lelke erejének hatására. </li>
</ul>

<strong>HÁLAADÁS ÉS DICSÉRET AZ ATYÁNAK </strong><br><br>
Az Eucharisztia, Krisztus által a kereszten beteljesített üdvösségünk szentsége, a dicséret áldozata is hálaadásul a teremtés művéért. Az eucharisztikus áldozatban Krisztus halála és föltámadása által az egész Istentől szeretett teremtést fölajánljuk az Atyának. Krisztus által az Egyház a dicséret áldozatát ajánlhatja föl hálaadásul mindazért a jóért, szépért és igazért, amit Isten a teremtésben és az emberi nemben alkotott. <br><br>
Az Eucharisztia a hálaadás áldozata az Atyának, áldás, mellyel az Egyház háláját fejezi ki Istennek minden jótéteményéért: mindazért, amit Ő a teremtésben, a megváltásban és a megszentelésben tett. Az Eucharisztia tehát elsősorban "hálaadást" jelent. <br><br>
Az Eucharisztia a dicséret áldozata is, amellyel az Egyház az egész teremtés nevében énekli Isten dicsőségét. E dicsérő áldozat csak Krisztus által lehetséges: Ő személyéhez, dicséretéhez és közbenjárásához kapcsolja a híveket, és így a dicséret áldozatát Őáltala és Ővele ajánljuk föl az Atyának, és Őbenne nyer elfogadást. <br><br>

<strong>KRISZTUSNAK ÉS AZ Ő TESTÉNEK, AZ EGYHÁZNAK ÁLDOZATI EMLÉKEZETE </strong><br><br>
Az Eucharisztia Krisztus húsvétjának emlékezete, egyetlen áldozatának aktualizálása és szentségi fölajánlása az Ő teste, az Egyház liturgiájában. Minden kánonban az alapítás szavai után megtaláljuk az anamnézisnek vagy megemlékezésnek nevezett imádságot. <br><br>
A Szentírás értelmében a megemlékezés nem csupán visszaemlékezés elmúlt eseményekre, hanem azoknak a csodatetteknek a hirdetése, melyeket Isten az emberek javára művelt. Ezen események liturgikus ünneplésében bizonyos módon maguk az események jelenvalóvá és aktuálissá válnak. Így érti Izrael népe az Egyiptomból történt szabadulását: valahányszor ünneplik a húsvétot, a kivonulás eseményei megjelennek a hívők emlékezetében, hogy életüket ezen eseményeknek megfelelően alakítsák. <br><br>
Az Újszövetségben a megemlékezés új értelmet kap. Amikor az Egyház az Eucharisztiát ünnepli, Krisztus húsvétjára emlékezik, ami jelenvalóvá válik: az áldozat, amelyet egyszer s mindenkorra ajánlott föl a kereszten, mindig aktuális marad: "Valahányszor az oltáron megünnepeljük a keresztáldozatot, melyben ’Krisztus, a mi húsvéti bárányunk föláldoztatott’ (1Kor 5,7), megvalósul megváltásunk műve". <br><br>
Mivel az Eucharisztia Krisztus húsvétjának emlékezete, áldozat is. Az Eucharisztia áldozati jellege magukból az alapító szavakból is kitűnik: "Ez az én testem, mely értetek adatik", és "ez a kehely az új Szövetség az én véremben, mely értetek kiontatik" (Lk 22,19--20). Az Eucharisztiában Krisztus ugyanazt a testet adja, melyet értünk a kereszten odaadott, és ugyanazt a vért, melyet kiontott "sokakért (...) a bűnök bocsánatára" (Mt 26,28). <br><br>
Az Eucharisztia tehát áldozat, mert megjeleníti (jelenvalóvá teszi) a kereszt áldozatát, mert annak emlékezete, s mert annak gyümölcsét alkalmazza: <br><br>
Krisztus "a mi Urunk és Istenünk, (...) a kereszt oltárán egyszer áldozta föl magát a halál által az Atyának, (...) hogy az embereknek örök megváltást szerezzen: mivel azonban halála után az ő papsága nem szűnik meg (Zsid 7,24.27), az utolsó vacsorán, ťazon az éjszakán, amelyen elárultatottŤ (1Kor 11,23), (...) szeretett jegyesének, az Egyháznak (miként az emberi természet igényli) (...) látható áldozatot hagyott, hogy az a kereszten egyszer bemutatandó véres áldozatot megjelenítse, s emlékezete az idők végezetéig megmaradjon, és üdvözítő ereje azoknak a bűnöknek megbocsátására, melyeket naponta elkövetnek, alkalmaztassék." <br><br>
Krisztus áldozata és az Eucharisztia áldozata egy áldozat: "egy és ugyanaz az áldozati adomány; a papok szolgálatával fölajánló személy ugyanaz, mint aki akkor a kereszten föláldozta önmagát, csak az áldozatbemutatás módja különbözik". "S mivel ebben az isteni áldozatban, mely a szentmisében történik, ugyanaz a Krisztus van jelen és áldoztatik föl vérontás nélkül, aki a kereszt oltárán ťegyszer véresen áldozta föl önmagátŤ (...), ez az áldozat valóban engesztelő." <br><br>
Az Eucharisztia az Egyház áldozata is. Az Egyház, mely Krisztus teste, részt vesz Fejének áldozatában. Ővele teljes egészében áldozat lesz. Kapcsolódik az Ő minden emberért történő közbenjárásához az Atyánál. Az Eucharisztiában Krisztus áldozata az Ő teste tagjainak áldozata is lesz. A hívők élete, dicsérete, fájdalma, imádsága és munkája egyesül Krisztus életével, dicséretével, fájdalmával, imádságával és munkájával és az Ő teljes odaadásával; és ezáltal új értéket nyer. Krisztus oltáron jelenlévő áldozata minden keresztény nemzedéknek megadja a lehetőséget, hogy egyesüljön az Ő áldozatával. <br><br>
A katakombákban gyakran szélesre tárt karokkal, orante testtartásban imádkozó nő alakjában ábrázolják az Egyházat, mely -- mint a kereszten karjait kitáró Krisztus -- Őáltala, Ővele és Őbenne ajánlja föl önmagát és jár közben minden emberért. <br><br>
Az egész Egyház egyesül Krisztus áldozatával és közbenjárásával. A Pápa, aki Péter szolgálatát végzi az Egyházban, minden szentmiséhez kapcsolódik, melyben mint az egyetemes Egyház egységének jelét és szolgáját név szerint említik. A helyi püspök mindig felelős az Eucharisztia ünnepléséért, akkor is, ha egy pap mutatja be; megemlítik a nevét, hogy jelezzék, ő a részegyház vezetője a papság körében és a diákonusok segítségével. A közösség minden egyéb szolgálattevőért is közbenjár, aki érte és vele bemutatja az eucharisztikus áldozatot. <br><br>
"Az a szentmise érvényes, melyet a püspök vagy az ő megbízottja vezetésével ünnepelnek." <br><br>
"A papok szolgálata által a hívők lelki áldozata egyesül Krisztusnak, az egyetlen közvetítőnek áldozatával, melyet a papok keze az egész Egyház nevében vérontás nélkül és szentségi módon a szentmisében fölajánl egészen addig, amíg az Úr el nem jön." <br><br>
Krisztus áldozatával nemcsak a földön élő tagok, hanem azok is egyesülnek, akik már a mennyei dicsőségben vannak: az Egyház a Boldogságos Szűz Máriával közösségben és róla, valamint az összes szentekről megemlékezve ajánlja föl az eucharisztikus áldozatot. Az Egyház az Eucharisztiában bizonyos értelemben Máriával együtt áll a kereszt tövében, egyesülve Krisztus áldozatával és közbenjárásával. <br><br>
Az eucharisztikus áldozatot az elhunyt hívőkért is fölajánlják, "a Krisztusban elhunytakért, akik még nem tisztultak meg teljesen", hogy beléphessenek Krisztus világosságába és békéjébe. <br><br>
"Bárhol helyezzétek el ezt a testet: semmi aggodalmatok ne legyen miatta; csak arra kérlek titeket, hogy az Úr oltáránál emlékezzetek meg rólam, bárhol lesztek." <br><br>
"Azután (az anaforában) az elhunyt szent atyákért és püspökökért, és általában a közülünk elhunytakért (imádkozunk); mert hisszük, hogy ez nagyon javára válik azoknak a lelkeknek, akikért imádkozunk e szent és félelmetes áldozat színe előtt. (...) Mi magunk is könyörgéseket ajánlunk föl Istennek az elhunytakért, még ha bűnösök voltak is, (...) a bűneinkért föláldozott Krisztust ajánljuk föl, engesztelvén Istent, az emberek barátját mind értük, mind önmagunkért." <br><br>
Szent Ágoston csodálatos szintézisbe foglalta e tanítást, mely arra késztet, hogy egyre teljesebben vegyünk részt Megváltónk áldozatában, amit az Eucharisztiában ünneplünk: <br><br>
"Az egész megváltott közösség, azaz a szentek gyülekezete és társasága Istennek fölajánlott áldozat lesz a nagy Pap által, aki önmagát is fölajánlotta értünk a szenvedésben, hogy ily nagy Fő teste lehessünk a szolga alakja szerint. (...) Ez a keresztények áldozata: ’Sokan egy test vagyunk Krisztusban’ (Róm 12,5). Amit az Egyház az oltárnak a hívők számára is ismert szentségével gyakorol, ahol megbizonyosodik arról, hogy abban, amit föláldoz, önmaga áldoztatik föl." <br><br>

<strong>KRISZTUS JELENLÉTE SZAVÁNAK ÉS A SZENTLÉLEKNEK EREJE ÁLTAL </strong><br><br>
"Jézus Krisztus, aki meghalt, sőt aki föltámadt és az Isten jobbján közbenjár értünk" (Róm 8,34), Egyházában sokszorosan jelen van: igéjében, Egyháza imádságában, "ahol ketten vagy hárman összegyűltek az én nevemben" (Mt 18,20), a szegényekben, a betegekben, a foglyokban, a szentségeiben, melyeknek Ő a szerzője, a szentmise-áldozatban és azok személyében, akik a papi szolgálatot végzik, de "mindenekelőtt az eucharisztikus színek alatt". <br><br>
Krisztus jelenlétének módja az eucharisztikus színek alatt egyedülálló. És e jelenlét emeli az Eucharisztiát az összes szentség fölé, úgyhogy az Eucharisztia "a lelki élet beteljesedése és az összes szentség célja". Az Eucharisztia legszentebb szentségében "a mi Urunk, Jézus Krisztus teste és vére, emberi lelkével és istenségével együtt, azaz az egész Krisztus igazán, valóságosan és szubsztanciálisan van jelen". "E jelenlétet nem kizárólagosan nevezzük valóságosnak -- mintha az egyéb jelenlétek nem valóságosak volnának --, hanem kiemelő módon, mert e jelenlét szubsztanciális, benne ugyanis az egész és teljes Krisztus, az Isten és ember van jelen." <br><br>
E szentségben Krisztus a kenyér és a bor Krisztus testévé és vérévé változása által válik jelenvalóvá. Az egyházatyák határozottan állították az Egyház hitét abban, hogy Krisztus szavának és a Szentlélek tevékenységének hatékonysága van ezen átváltozás végrehajtására. Aranyszájú Szent János így nyilatkozik: <br><br>
"Nem ember az, aki megteszi, hogy az adományok Krisztus testévé és vérévé váljanak, hanem maga Krisztus, akit értünk megfeszítettek. A szavakat kimondó pap Krisztust jeleníti meg: de az erő és a kegyelem Istené. Ez az én testem -- mondja. Ez a szó változtatja át az áldozati adományokat." <br><br>
Szent Ambrus pedig ezt mondja erről az átváltozásról: <br><br>
Legyünk meggyőződve arról, hogy "olyan dolog áll előttünk, amit nem a természet alakított ilyenné, hanem az áldás konszekrálta, és az áldás hatékonysága meghaladja a természetet, hiszen az áldás erejéből éppen maga a természet változik át". "Krisztus szava tehát, aki a semmiből létre tudta hozni azt, ami nem volt, a már létezőt ne tudná átváltoztatni azzá, ami korábban nem volt? Nem kisebb dolog új dolgokat teremteni, mint a természeteket átváltoztatni." <br><br>
A Trienti Zsinat összefoglalja a katolikus hitet, amikor kijelenti: "Mivel pedig Krisztus, a mi Megváltónk azt mondta, hogy amit Ő a kenyér színe alatt fölajánlott, valóban az Ő teste, azért Isten Egyházában mindig élt a meggyőződés, és ez a szent zsinat újra kinyilvánítja: a kenyér és a bor konszekrációja által olyan átváltoztatás történik, ami a kenyér egész lényegét Krisztus, a mi Urunk testének lényegévé és a bor egész lényegét az ő vérének lényegévé változtatja át. Ezt a változást a szent, katolikus Egyház helyesen és sajátos értelemben transsubstantiatio-nak, `átlényegülésnek' nevezte." <br><br>
Krisztus eucharisztikus jelenléte az átváltoztatás pillanatában kezdődik, és addig tart, ameddig az eucharisztikus színek megmaradnak. Az egész Krisztus van jelen a színek mindegyikében, és az egész Krisztus van jelen azok minden egyes részében oly módon, hogy a kenyér megtörése Krisztust nem osztja meg. <br><br>
Az Eucharisztia tisztelete. A szentmise liturgiája során Krisztusnak a kenyér és a bor színe alatti valóságos jelenlétébe vetett hitünket többek között azzal is kifejezzük, hogy az Úr imádásának jeleként térdet hajtunk vagy mélyen meghajlunk. "Az Eucharisztia szentsége iránti imádást a katolikus Egyház nemcsak a szentmisében, hanem azon kívül is végezte és végzi azáltal, hogy a konszekrált ostyákat a lehető leggondosabban őrzi, a hívők imádása tárgyaként kihelyezi és a népsokaság örömére körmenetekben hordozza." <br><br>
A tabernákulum korábban arra szolgált, hogy az Eucharisztiát méltó körülmények között őrizzék annak érdekében, hogy a betegeknek és a távollevőknek a szentmisén kívül elvihessék. Ahogyan az Egyház elmélyült Krisztus valóságos eucharisztikus jelenlétének hitében, úgy ébredt tudatára az eucharisztikus színek alatt jelenlévő Krisztus csöndes imádása értelmének. Ezért a tabernákulumnak a templomban különösen méltó helyen kell állnia; és olyannak kell lennie, hogy az Krisztus valóságos jelenlétének igazságát az Oltáriszentségben kiemelje és nyilvánvalóvá tegye. <br><br>
Nagyon megfelelő, hogy Krisztus ilyen egyedülálló módon akart Egyháza számára jelenvaló maradni. Mivel ugyanis Krisztus látható alakjában elhagyni készült övéit, nekünk akarta ajándékozni szentségi jelenlétét; mivel arra készült, hogy a kereszten föláldozva önmagát üdvözítsen minket, akarta, hogy emlékünk legyen arról a szeretetről, amellyel Ő "mindvégig" (Jn 13,1), élete elajándékozásáig szeretett minket. Valóban, Ő eucharisztikus jelenlétében közöttünk marad, titokzatos módon, mint az, aki szeretett minket és önmagát adta értünk, éspedig olyan jelek alatt van jelen, melyek ezt a szeretetet kifejezik és közlik: <br><br>
"Az Egyháznak és a világnak nagyon szüksége van az Eucharisztia tiszteletére. A szeretet e szentségében Jézus vár bennünket. Ne sajnáljuk az időt, hogy találkozzunk vele az imádásban, a hittel teljes szemlélődésben, készen a világ bűneinek és jogtalanságainak engesztelésére. Soha ne szűnjön meg a mi imádásunk." <br><br>
"Hogy e szentségben Krisztus valóságos teste és valóságos vére van jelen, ahogy Szent Tamás mondja, ’érzékekkel nem, de az isteni tekintélyre támaszkodó hittel egyedül lehet megragadni. Ezért mondja Cirill a Lk 22,19 Ez az én testem, mely értetek adatik helyéről: Ne kételkedj, hogy igaz-e; hanem inkább hittel fogadd el az Üdvözítő szavait. Mivel ugyanis Ő az Igazság, nem hazudik’": <br><br>
<br /> Imádlak áhítattal, Isten, rejtelem! <br /> Aki e jelekben titkon vagy jelen. <br /> Néked egész szívem átadja magát, <br /> mert téged szemlélve elveszti magát. <br><br>
Szem, ízlés, tapintás megcsalódhatik, <br /> de a hallás rólad hittel biztosít: <br /> Hiszem, amit hinni Isten Fia szab, <br /> igédnél, Igazság, mi van igazabb? <br /><br /><br><br>
<strong>VI. A húsvéti lakoma </strong><br><br>
A szentmise egyszerre és elválaszthatatlanul a keresztáldozatot megörökítő áldozati emlékezés és az Úr testével és vérével való közösség szent lakomája. Az eucharisztikus áldozat ünneplése teljesen a Krisztussal történő bensőséges egyesülésre irányul az áldozás által. Áldozni annyit jelent, mint magát Krisztust fogadni, aki önmagát áldozta értünk. <br><br>
Az oltár, amely körül az Egyház az Eucharisztia ünneplésére összegyűl, ugyanannak a misztériumnak két oldalát mutatja meg: az áldozati oltárt és az Úr asztalát, már csak azért is, mert a keresztény oltár magának Krisztusnak szimbóluma, aki úgy van jelen hívei körében, mint a megbékéltetésünkért fölajánlott áldozat és az önmagát nekünk ajándékozó mennyei eledel. "Mi más Krisztus oltára, mint Krisztus testének képe?"-- mondja Szent Ambrus, és másutt: "Az oltár a test képe, és Krisztus teste van az oltáron." A liturgia az áldozatnak és a kommuniónak ezt az egységét számos imádságban fejezi ki. A római Egyház így imádkozik kánonjában: <br><br>
"Könyörögve kérünk, mindenható Istenünk, szent angyalod vigye áldozatunkat mennyei oltárodra isteni Fölséged színe elé, hogy mi, akik erről az oltárról Fiad szentséges testében és vérében részesülünk, minden mennyei áldással és kegyelemmel elteljünk." <br><br>
<strong>"VEGYÉTEK ÉS EGYETEK EBBŐL MINDNYÁJAN": A SZENTÁLDOZÁS </strong><br><br>
Az Úr sürgető meghívással fordul felénk, hogy az Eucharisztia szentségében magunkhoz vegyük Őt: "Bizony, bizony, mondom nektek: ha nem eszitek az Emberfia testét és nem isszátok az ő vérét, nem lesz bennetek élet" (Jn 6,53). <br><br>
Hogy meg tudjunk felelni ennek a meghívásnak, erre a nagy és szent pillanatra elő kell készülnünk. Szent Pál apostol lelkiismeretvizsgálatra buzdít: "Ezért, aki méltatlanul eszi a kenyeret vagy issza az Úr kelyhét, az Úr teste és vére ellen vét. Tehát vizsgálja meg magát mindenki, és csak úgy egyék a kenyérből és igyék a kehelyből, mert aki csak eszik és iszik anélkül, hogy megkülönböztetné az (Úr) testét, saját ítéletét eszi és issza" (1Kor 11,27--29). Annak, aki súlyos bűn tudatában van, meg kell gyónnia, mielőtt a szentáldozáshoz járul. <br><br>
A hívő e nagy szentség előtt nem tehet mást, mint hogy lángoló hittel és alázattal megismételje a százados szavait: "Uram, nem vagyok méltó, hogy hajlékomba jöjj, hanem csak egy szóval mondd, és meggyógyul az én lelkem!" Aranyszájú Szent János liturgiájában a hívők ugyanazon lelkülettel imádkozzák: <br><br>
"A te titkos vacsorádnak részesévé fogadj ma engem, Isten Fia, mert nem mondom ki ellenségeidnek a titkot, sem csókot nem adok neked, mint Júdás, hanem mint ama gonosztevő, kiáltom feléd: ’Emlékezzél meg rólam, Uram, a te országodban!’" <br><br>
E szentség vételének méltó előkészületeként a hívőknek meg kell tartaniuk az Egyházuk által előírt szentségi böjtöt. Magatartásukkal (ruha, testtartás) fejezzék ki azt a tiszteletet, ünnepélyességét és örömöt, mely megfelel annak a pillanatnak, amikor Krisztus a vendégünk lesz. <br><br>
Megfelel az Eucharisztia rendeltetésének, hogy a hívők, ha kellően föl vannak készülve, megáldoznak, amikor szentmisén vesznek részt: "Nagyon ajánlott a szentmisén való tökéletesebb részvétel abban a formában is, hogy a hívek az Úr testét a pap áldozása után ugyanabból az Áldozatból vegyék magukhoz". <br><br>
Az Egyház kötelezi a hívőket arra, hogy vasár- és ünnepnapon vegyenek részt az isteni liturgiában és gyónással fölkészülve legalább évente egyszer vegyék magukhoz az Eucharisztiát, lehetőleg a húsvéti időben. Az Egyház nyomatékosan ajánlja a hívőknek, hogy a szent Eucharisztiát vasár- és ünnepnapokon vagy még gyakrabban, akár minden nap vegyék magukhoz. <br><br>
A csak kenyér színe alatti szentáldozásban -- Krisztus mindkét szín alatti szentségi jelenléte következtében -- az Eucharisztia kegyelmi gyümölcseit egészen fogadni lehet. Lelkipásztori megfontolásból a latin szertartásban ez az áldozási forma a leggyakoribb. "A szentáldozás azonban akkor éri el jel természetének teljességét, ha mindkét szín alatt történik. Ebben a formában az eucharisztikus lakoma jele tökéletesebben fejeződik ki." A keleti szertartásokban ez a szentáldozás általános módja. <br><br>

<strong>A SZENTÁLDOZÁS GYÜMÖLCSEI </strong><br><br>
A szentáldozás elmélyíti egyesülésünket Krisztussal. Az Eucharisztia vételének a szentáldozásban a legfőbb gyümölcse a benső egyesülés Jézus Krisztussal. Az Úr mondja: "Aki eszi az én testemet és issza az én véremet, az bennem marad, én meg őbenne" (Jn 6,56). A Krisztusban való élet alapja az eucharisztikus lakoma: "Ahogy engem az élő Atya küldött és Én az Atya által élek, úgy az is, aki engem eszik, általam fog élni" (Jn 6,57). <br><br>
"Amikor az Úr ünnepein a hívők a Fiú testét magukhoz veszik, hirdetik egymásnak az örömhírt: megkaptuk az élet foglalóját; mint amikor az angyal Mária Magdolnának mondta: ’Krisztus föltámadott!’. Most is az életet és a föltámadást kapja az, aki magához veszi Krisztust." <br><br>
Amit az anyagi táplálék eredményez a testi életben, azt valósítja meg a szentáldozás csodálatos módon lelki életünkben. A föltámadott Krisztus -- "a Szentlélek által élő és éltető" -- testével való kommunió megőrzi, növeli és megújítja a keresztségben kapott kegyelmi életet. A keresztény élet e növekedése igényli, hogy az eucharisztikus kommunióval, zarándokságunk kenyerével táplálkozzék egészen halálunk órájáig, amikor `útravalóul' kapjuk. <br><br>
A szentáldozás elválaszt bennünket a bűntől. Krisztus teste, melyet a szentáldozásban magunkhoz veszünk, értünk "adatott", és a vér, amelyet iszunk, "sokakért kiontatott a bűnök bocsánatára". Ezért az Eucharisztia nem tud Krisztussal egyesíteni anélkül, hogy ne tisztítana meg az elkövetett bűnöktől és ne óvna meg a jövendő bűnöktől: <br><br>
"Valahányszor magunkhoz vesszük, az Úr halálát hirdetjük. Ha a halálát, akkor a bűnök bocsánatát hirdetjük. Ha valahányszor kiontatik a vér, a bűnök bocsánatára ontatik ki, akkor mindig úgy kell fogadnom, hogy mindig megbocsátja a bűneimet. Nekem, aki mindig vétkezem, mindig szükségem van az orvosságra." <br><br>
Amint a testi táplálék az elhasznált erő pótlására szolgál, úgy az Eucharisztia erősíti a szeretetet, mely a mindennapi életben természete szerint gyengül; és ez a fölelevenített szeretet eltörli a bocsánatos bűnöket. Amikor Krisztus nekünk ajándékozza önmagát, újra életre kelti szeretetünket, és képessé tesz arra, hogy a teremtmények iránti rendetlen ragaszkodásainkat megszakítsuk és benne meggyökerezzünk: <br><br>
"Mivel tehát Krisztus szeretetből halt meg értünk, amikor az áldozat idejében megemlékezünk az Ő haláláról, azt kérjük, hogy a Szentlélek eljövetele által adassék nekünk a szeretet; azt kérjük alázattal könyörögve, hogy e szeretet által, mellyel Krisztus minket arra méltatott, hogy megfeszíttessék értünk, mi is -- a Szentlélek kegyelmét elnyerve -- úgy tekinthessük a világot, mint ami számunkra megfeszíttetett, s mi magunk is megfeszíttessünk a világnak; (...) a szeretet ajándékát elnyerve, meghaljunk a bűnnek és Istennek éljünk." <br><br>
Az Eucharisztia e szeretet által, melyet föllobbant bennünk, megőriz minket a halálos bűnöktől. Minél inkább részesedünk Krisztus életében és minél inkább elmélyedünk barátságában, annál nehezebb lesz halálos bűnnel megszakítani a kapcsolatot Vele. De a halálos bűnök megbocsátására nem az Eucharisztia van rendelve, hanem a bűnbocsánat szentsége. Az Eucharisztia azok szentsége, akik teljes közösségben vannak az Egyházzal. <br><br>
A titokzatos Test egysége: az Eucharisztia teszi az Egyházat. Akik az Eucharisztiát magukhoz veszik, szorosabban kapcsolódnak Krisztushoz. Emiatt Krisztus valamennyi hívőt egy testbe kapcsol össze: az Egyházba. A szentáldozás ezt az Egyházba testesülést, ami a keresztség által már megvalósult, megújítja, megerősíti és elmélyíti. A keresztségben meghívást kaptunk arra, hogy egy testet alkossunk. Az Eucharisztia beteljesíti ezt a meghívást: "Az áldás kelyhe, amelyet megáldunk, nemde a Krisztus vérében való részesedés? S a kenyér, amelyet megtörünk, nemde a Krisztus testében való részesedés? Mi ugyanis sokan egy kenyér, egy test vagyunk, mivel mindnyájan egy kenyérből részesülünk" (1Kor 10,16--17): <br><br>
"Ha ti Krisztus teste és az Ő tagjai vagytok, misztériumotok oda van helyezve az Úr asztalára: a saját misztériumotokat kapjátok. Arra, ami vagytok, Amen-nal válaszoltok, és válaszolván aláírjátok. Hallod ugyanis: Krisztus teste; és te válaszolod: Amen. Légy Krisztus tagja, hogy igaz legyen az Amen." <br><br>
Az Eucharisztia kötelez a szegények iránt; hogy Krisztus értünk adott testét és vérét igazságban vehessük magunkhoz, Krisztust a legszegényebbekben, az Ő testvéreiben kell fölismernünk: <br><br>
"Megízlelted az Úr vérét, és még így sem ismered föl a testvéredet; (...) magát az asztalt is meggyalázod, amikor azt, aki ennek részese lett, nem tartod méltónak arra, hogy megoszd vele táplálékodat. (...). Minden bűnödtől megszabadított téged Isten, és ilyen asztalra méltatott: te pedig ettől sem lettél jóságosabb." <br><br>
Az Eucharisztia és a keresztények egysége. E misztérium nagysága láttán Szent Ágoston így kiáltott föl: "Ó, kegyes jóság szentsége! Ó, egység jele! Ó, szeretet köteléke!" Minél fájdalmasabban érezzük az Egyház megosztottságait, amelyek lehetetlenné teszik az Úr asztalánál való közös részvételt, annál fontosabbak az imádságok az Úrhoz, hogy a benne hívők teljes egységének napjai visszatérjenek. <br><br>
A keleti egyházak, amelyek nincsenek teljes közösségben a katolikus Egyházzal, az Eucharisztiát nagy szeretettel ünneplik. "Ezek az egyházak, jóllehet különváltak, valódi szentségeikkel rendelkeznek, kiváltképpen pedig az apostoli jogfolytonosság következtében van papságuk és Eucharisztiájuk, melyek révén igen szoros kapcsolatban állnak velünk mindmáig." Ezért "bizonyos kommunikáció in sacris, bizonyos körülmények között és az egyházi hatóság jóváhagyásával nem csupán lehetséges, hanem ajánlatos is". <br><br>
A reformációból született és a katolikus Egyháztól különvált egyházi közösségek "nem őrizték meg sértetlenül -- főleg az ordo szentségének hiánya miatt -- az eucharisztikus misztérium eredeti és teljes lényegét". Ezért a katolikus Egyház számára az intercommunio ezekkel a közösségekkel nem lehetséges. Mindazonáltal ezek a közösségek, "amikor a Szent Vacsorában megemlékeznek Urunk haláláról és föltámadásáról, megvallják, hogy az életet a Krisztussal való közösség jelenti, és várják az ő dicsőséges eljövetelét". <br><br>
Amikor a megyéspüspök ítélete szerint súlyos szükséghelyzet áll fönn, katolikus papok kiszolgáltatnak szentségeket (Eucharisztiát, a gyónás, betegek kenete szentségét) más keresztényeknek, akik nincsenek teljes közösségben a katolikus Egyházzal, de önként kérik: e szentségekre vonatkozóan a katolikus hitet meg kell vallaniuk és a szükséges fölkészültséggel kell rendelkezniük. <br><br>

<strong>VII. Az Eucharisztia -- "a jövendő dicsőség záloga" </strong><br><br>
Egy ősi imádságában így magasztalja az Egyház az Eucharisztia misztériumát: "Ó, szentséges lakoma, Krisztust vesszük rajta. Felidézzük szenvedésének emlékét, lelkünket kegyelem tölti el, és a jövendő dicsőség záloga nekünk adatik." Ha az Eucharisztia az Úr húsvétjának emlékezete, ha az oltár áldozatából részesülőket "a mennyei áldás és kegyelem teljessége" tölti el, akkor az Eucharisztia a mennyei dicsőség elővételezése is. <br><br>
Az utolsó vacsorán maga az Úr irányította tanítványai figyelmét a húsvétnak az Isten országában történő beteljesedésére: "Mondom nektek: mostantól nem iszom a szőlő terméséből addig, amíg majd az újat nem iszom veletek Atyám országában" (Mt 26,29). Valahányszor az Egyház az Eucharisztiát ünnepli, emlékezik erre az ígéretre, és tekintetét arra irányítja, "aki eljön" (Jel 1,4). Imádságában hívja az Ő eljövetelét: "Marana tha!" (1Kor 16,22), "Jöjj el, Uram Jézus!" (Jel 22,20). "Jöjjön el a te kegyelmed, és múljék el e világ!" <br><br>
Az Egyház tudja, hogy Eucharisztiájában az Úr már most eljön és benne közöttünk van. Mégis, ez a jelenlét elfátyolozott. Ezért ünnepeljük mi az Eucharisztiát úgy, hogy "reménykedve várjuk Üdvözítőnknek, Jézus Krisztusnak dicsőséges eljövetelét", és kérjük, hogy "országodban majd reményünk szerint (mindannyian) dicsőségedben örökre részesüljünk, amikor letörölsz szemünkről minden könnyet, és színről színre látunk téged, Istenünk. Hasonlók leszünk hozzád mindörökre, és vég nélkül dicsőítünk téged, Krisztus, a mi Urunk által". <br><br>
E nagy reménységnek, tudniillik az új égnek és az új földnek -- melyekben igazságosság lakik -- nincs biztosabb záloga, sem nyilvánvalóbb pecsétje, mint az Eucharisztia. Valójában valahányszor e misztériumot ünnepeljük, "megváltásunk műve valósul meg", és mi "egy kenyeret (...) (törünk meg), mely a halhatatlanság orvossága, ellenméreg, hogy meg ne haljunk, hanem mindig éljünk Jézus Krisztusban". <br><br>