<h2>Házasság</h2>

"A házassági szövetséget, amelyben a férfi és a nő az egész élet olyan közösségét hozza létre egymással, mely természeténél fogva a házasfelek javára, gyermekek nemzésére és nevelésére irányul, Krisztus Urunk a megkereszteltek között a szentség rangjára emelte."<br><br>
<strong>A házasság Isten tervében </strong><br><br>
A Szentírás a férfi és a nő Isten képére történt teremtésével kezdődik és a "Bárány menyegzőjének" látomásával (Jel 19,9) fejeződik be. A Szentírás az elsőtől az utolsó lapjáig beszél a házasságról és annak misztériumáról, alapításáról és értelméről, melyet Isten adott neki, eredetéről és céljáról, különböző megvalósulási formáiról az üdvösség történetében, a bűnből származó nehézségeiről és megújításáról "az Úrban" (1Kor 7,39), Krisztus és az Egyház új szövetségében. <br><br>

<strong>A HÁZASSÁG A TEREMTÉS RENDJÉBEN </strong><br><br>
"A házastársi szeretet és élet bensőséges közösségét a Teremtő alapította és vette körül törvényeivel (...). Maga (...) Isten a házasság szerzője." A házasságra szóló meghívás már a férfi és a nő természetében adva van, ahogyan ezek a Teremtő kezéből kikerültek. A házasság nem pusztán emberi intézmény, jóllehet a századok folyamán a különböző kultúrák, társadalmi struktúrák és szellemiségek szerint számtalan változáson ment keresztül. E változások nem tudták feledtetni a maradandó és általános vonásokat. Ennek az intézménynek a méltósága ugyan nem azonos fényességgel ragyog mindenütt, de minden kultúrában él a házastársi egység értéke iránti érzék. "A személy, valamint az emberi és a keresztény közösség üdvössége szorosan összefügg a házastársi és családi közösség jó állapotával." <br><br>
Isten, aki az embert szeretetből teremtette, meg is hívta a szeretetre, ami minden egyes ember veleszületett, alapvető hivatása. Az ember Isten képmására lett teremtve, aki maga "a szeretet" (1Jn 4,8.16). Mivel Isten férfinak és nőnek teremtette az embert, kölcsönös szeretetük annak az abszolút és fogyatkozhatatlan szeretetnek a képe, mellyel Isten az embert szereti. Ez a szeretet a Teremtő szemében jó, sőt nagyon jó. Ez a szeretet, melyet Isten megáldott, arra van rendelve, hogy termékeny legyen, s hogy a teremtés őrzésének közös művében valósuljon meg: "Isten megáldotta őket, és mondta nekik: ’Legyetek termékenyek, sokasodjatok, töltsétek be a földet, és vessétek uralmatok alá’" (Ter 1,28). <br><br>
A Szentírás elmondja, hogy a férfi és a nő egymásnak van teremtve: "Nem jó az embernek egyedül lennie" (Ter 2,18). A nő "hús az ő húsából", azaz a férfival egyenrangú, egészen közel áll hozzá, Isten segítségül adta mellé, így képviseli Istent, aki a mi segítségünk. "Ezért a férfi elhagyja atyját és anyját, feleségéhez ragaszkodik, és a kettő egy test lesz" (Ter 2,24). Maga az Úr mutatta meg, hogy ez kettőjük életének fogyatkozhatatlan egységét jelenti, amikor arra emlékeztetett, mi volt a Teremtő terve "kezdettől": "Így tehát már nem ketten vannak, hanem egy test"(Mt 19,6). <br><br>

<strong>A HÁZASSÁG A BŰN URALMA ALATT </strong><br><br>
A rosszat minden ember megtapasztalja környezetében és önmagában. E tapasztalat mutatkozik a férfi és a nő kapcsolatában is. Egységüket mindig fenyegette a megnemértés, az uralomvágy, a hűtlenség, a féltékenység és az összetűzések, melyek gyűlöletig és szakításig vezethetnek. Ez a rendetlenség kisebb vagy nagy fokú lehet, és kultúrák, korok és egyének szerint többé kevésbé legyőzhető; de úgy tűnik, egyetemes jellege vitathatatlan. <br><br>
Miként hitünk mondja, e rendetlenség, amelyet fájdalommal tapasztalunk, nem a férfi és a nő természetéből, nem is kapcsolatuk természetéből, hanem a bűnből származik. Az ősbűn -- mint Istennel való szakítás -- első következményként a férfi és a nő eredeti közösségének megtörését vonta maga után. Kapcsolatukat a kölcsönös vádaskodás megzavarta; a Teremtőtől ajándékba kapott, kölcsönös vonzalmuk uralkodássá és ösztönös vágyakozássá silányult; a férfi és a nő szépséges hivatását a termékenységre, a sokasodásra és a föld fölötti uralomra a szülés fájdalmai és a kenyérkeresés fáradalma terheli. <br><br>
És mégis, a teremtés rendje a súlyos zavar ellenére fönnmarad. A bűn által ütött sebek gyógyulásához a férfinak és a nőnek a kegyelem segítségére van szüksége, melyet Isten a maga végtelen irgalmában soha nem tagadott meg tőlük. E segítség nélkül a férfinak és a nőnek sohasem sikerülhet az életnek azt az egységét megvalósítani, amire Isten őket "kezdettől" teremtette. <br><br>

<strong>A HÁZASSÁG A TÖRVÉNY PEDAGÓGIÁJA ALATT </strong><br><br>
Isten a maga irgalmasságában nem hagyta magára a bűnös embert. A büntetések, melyeket a bűn maga után vont -- a szülés kínjai, az "arcod verejtékével" (Ter 3,19) végzett munka --, segédeszközök is, melyek a bűn rossz következményeit korlátok között tartják. A bűnbeesés után a házasság segít legyőzni az ember önmagába zárkózását, az önzést, a gyönyör hajszolását, és segít megnyílni a másik felé, a kölcsönös segítségre, önmaga elajándékozására. <br><br>
A lelkiismeret a házasság egysége és fölbonthatatlansága tekintetében a régi törvény pedagógiája alatt nőtt fel. A pátriárkák és a királyok többnejűségét még nem kifejezetten utasították el. Mindazonáltal a Mózesnek adott törvény már arra felé irányult, hogy a nőt megvédje a férfi önkényuralmától, bár az Úr szava szerint a törvény még nyomokban hordozza a férfi "szívének keménységét", ami miatt Mózes megengedte az asszony eltaszítását. <br><br>
A próféták, akik Istennek Izraellel kötött szövetségét a kizárólagos és hűséges házastársi szeretet képében szemlélték, előkészítették a választott nép lelkiismeretét a házasság egysége és fölbonthatatlansága mélyebb megértésére. Ruth és Tóbiás könyve megindító tanúság a házasság nagyraértékelése és a házastársak hűsége és gyöngédsége mellett. "A hagyomány az Énekek énekében mindig az emberi szerelem nagyszerű kifejezését látta, amennyiben ez tükröződése Isten szeretetének; annak a szeretetnek, ami "erős, mint a halál" és "vizek árja nem oltja ki" (8,6--7). <br><br>

<strong>HÁZASSÁG AZ ÚRBAN </strong><br><br>
Az Isten és az Ő népe, Izrael közötti házassági szövetség előkészítette azt az új és örök szövetséget, melyben Isten Fia -- megtestesülésében és életének föláldozásában -- valamiképpen az egész általa üdvözített emberi nemet magához kötötte, így készítve elő "a Bárány menyegzőjét". <br><br>
Nyilvános élete kezdetén Jézus -- Anyja kérésére -- első csodáját egy menyegzős ünnepen cselekedte. Az Egyház nagy jelentőséget tulajdonít Jézus részvételének a kánai menyegzőn, mert bizonyítékot lát benne arra, hogy a házasság jó, és annak meghirdetését, hogy a házasság ezentúl Krisztus jelenlétének hatékony jele lesz. <br><br>
Jézus igehirdetésében félreérthetetlenül tanította a férfi és a nő egyesülésének eredeti értelmét, úgy, amint azt a Teremtő kezdettől akarta: a Mózes által adott engedmény az asszony elbocsátására vonatkozólag a szív keménységének tett engedmény volt; a férfi és a nő házassági egysége fölbonthatatlan -- maga Isten kötötte össze: "Amit Isten egybekötött, ember szét ne válassza" (Mt 19,6). <br><br>
A házassági kötelék fölbonthatatlanságának egyértelmű hangsúlyozása zavart kelthetett és teljesíthetetlen követelménynek tűnhetett. Jézus azonban nem elviselhetetlen, nagyon nehéz, Mózes törvényénél is nehezebb terhet rakott a házastársak vállára. Ő, aki azért jött, hogy a teremtés bűn által megzavart eredeti rendjét helyreállítsa, kegyelmet is ad ahhoz, hogy a házasságot Isten országának új módján lehessen élni. Ha a házastársak Krisztust követik, megtagadják önmagukat és fölveszik keresztjüket, "föl tudják fogni" a házasság eredeti értelmét, és Krisztus segítségével meg is tudják élni. A keresztény házasság e kegyelme Krisztus keresztjének gyümölcse, mely az egész keresztény élet forrása. <br><br>
Pál apostol ezt teszi érthetővé, amikor azt mondja: "Férfiak, szeressétek feleségteket, ahogy Krisztus is szerette az Egyházat, és föláldozta magát érte, hogy megszentelje" (Ef 5,25--26). És rögtön hozzáteszi: "Ezért az ember elhagyja atyját és anyját, feleségéhez ragaszkodik, és ketten egy testben lesznek. Nagy titok ez, én Krisztusra és az Egyházra vonatkoztatom." (Ef 5,31--32) <br><br>
Az egész keresztény élet magán viseli Krisztus és az Egyház jegyesi szeretetének jegyét. Már a keresztség, a belépés Isten népébe, menyegzői misztérium; mintegy menyegzői fürdő, mely megelőzi a menyegzői lakomát, az Eucharisztiát. A keresztény házasság a maga részéről hatékony jellé válik, Krisztus és az Egyház szövetségének szakramentumává. Mivel ennek kegyelmét jelzi és közvetíti, a keresztények közötti házasság az Újszövetség igazi szentsége. <br><br>

<strong>A MENNYEK ORSZÁGÁÉRT VÁLLALT SZÜZESSÉG </strong><br><br>
Krisztus az egész keresztény élet középpontja. A vele való kapcsolat megelőz minden más, családi vagy társadalmi kapcsolatot. Az Egyház kezdete óta voltak férfiak és nők, akik lemondtak a házasság nagy javáról azért, hogy kövessék a Bárányt, bárhova megy, az Úr dolgaival törődjenek, neki akarjanak tetszeni, és elébe menjenek az érkező vőlegénynek. Maga Krisztus meghívott egyeseket, hogy abban az életformában kövessék Őt, melyet Ő maga élt eléjük: <br><br>
"Van, aki azért képtelen a házasságra, mert úgy született. Van, akit az emberek tettek a házasságra alkalmatlanná. Végül van, aki a mennyek országáért önként mond le a házasságról. Aki föl tudja fogni, az fogja föl!" (Mt 19,12) <br><br>
A mennyek országáért vállalt szüzesség a keresztségi kegyelem kibontakozása, a Krisztussal való kapcsolat elsődlegességének és az ő visszatérésére való éber várakozásnak hatalmas jele, olyan jel, mely arra is emlékeztet, hogy a házasság ehhez a világhoz tartozik, mely elmúlik. <br><br>
Mindkettő -- a házasság szentsége és az Isten országáért vállalt szüzesség -- magától az Úrtól származik. Ő ad értelmet nekik és ajándékozza meg a nélkülözhetetlen kegyelemmel, hogy úgy lehessen megélni őket, ahogy az Ő akaratának megfelel. A mennyek országáért vállalt szüzesség nagyrabecsülése és a házasság keresztény értelme nem választható el egymástól; kölcsönösen támogatják egymást: <br><br>
"Aki a házasságot kárhoztatja, az megtépázza a szüzesség dicsőségét is; (...) aki dicséri csodálatosabbá teszi a szüzességet. Mert ami egy rosszabbal összehasonlítva tűnik jónak, aligha különösebben jó; ami azonban az általánosan jónak tartottnál jobb, az kiemelkedően jó." <br><br>

<strong>A házasságkötés szertartása </strong><br><br>
A latin szertartásban két katolikus fél házasságkötése többnyire szentmisében történik, amiatt hogy minden szentség kapcsolatban áll Krisztus húsvéti misztériumával. Az Eucharisztiában emlékezünk az új Szövetségre, melyben Krisztus örökre egyesült az Egyházzal, szeretett jegyesével, melyért odaadta magát. Ezért jó, ha a jegyesek a kölcsönös odaadásra kimondott igenjüket azzal pecsételik meg, hogy egyesülnek Krisztus Egyháza iránti odaadásával, ami az eucharisztikus áldozatban jelenik meg, és magukhoz veszik az Eucharisztiát, hogy a Krisztus ugyanazon testével és ugyanazon vérével való egyesülés által Krisztusban "egy testet" alkossanak. <br><br>
"A házasság kiszolgáltatásának mint megszentelő szentségi cselekménynek, mely a liturgiához, az egyházi cselekmények csúcsához és a megszentelő erő forrásához (az Eucharisztiához) kapcsolódik, önmagában érvényesnek, méltónak és gyümölcsözőnek kell lennie." A jegyeseknek a házasságkötésre tehát föl kell készülniük szentgyónással. <br><br>
A latin hagyomány szerint maguk a jegyesek mint Krisztus kegyelmének közvetítői szolgáltatják ki egymásnak a házasság szentségét, amikor az Egyház színe előtt kinyilvánítják házasságkötési szándékukat. A keleti egyházak hagyományaiban a papok vagy püspökök tanúi a jegyesek kölcsönös konszenzus-cseréjének, de áldásuk szükséges a szentség érvényességéhez. <br><br>
A különböző liturgiák gazdagok áldó és epiklézis jellegű imádságokban, melyek Istentől kegyelmet és áldást kérnek az új házaspárra, főként az új asszonyra. E szentség epiklézisében a házastársak úgy fogadják a Szentlelket, mint a Krisztus és az Egyház közötti szeretet közösségét. Ő a szövetségük pecsétje, szerelmük állandóan áradó forrása, az erő, mely megújítja hűségüket. <br><br>

<strong>A házassági beleegyezés </strong><br><br>
A házassági szövetséget egy férfi és egy nő köti, akik meg vannak keresztelve és szabadok a házasságkötésre, és szabadon nyilvánítják ki beleegyezésüket. A "szabad állapot" azt jelenti: <br><br>
<ul>
    <li >nem állnak kényszer alatt; </li>
    <li >nem akadályozza őket sem atermészettörvény, sem egyházi törvény. </li>
</ul>
Az Egyház a beleegyezés cseréjét a jegyesek között a házasságkötés nélkülözhetetlen elemének tekinti. A "házasság" a beleegyezés kölcsönös kinyilvánítása által "jön létre". Ha a beleegyezés hiányzik, a házasság nem jön létre. <br><br>
A beleegyezés "szabad, személyes cselekedet, melyben a házastársak kölcsönösen ajándékozzák és elfogadják egymást": "Feleségül veszlek." (...) "Feleségül megyek hozzád." Ez a beleegyezés, mely egymáshoz köti a jegyeseket, azáltal teljesedik be, hogy a kettő "egy test lesz". <br><br>
A házassági beleegyezésnek mindkét fél akarati aktusának kell lennie, és mentesnek kell lennie a külső kényszertől vagy súlyos megfélemlítéstől. A beleegyezést semmiféle emberi hatalom nem pótolhatja. Ha e szabadság hiányzik, a házasság érvénytelen. <br><br>
Emiatt (vagy más, a házasságot semmissé tevő v. tiltó akadályok miatt) az Egyház, miután az ügyet az illetékes egyházi bíróság megvizsgálta, kinyilváníthatja a "házasság semmisségét", azaz hogy a házasság soha nem létezett. Ebben az esetben a felek szabadok házasságkötésre, de a korábbi együttélésből származó természetes kötelezettségeknek eleget kell tenniük. <br><br>
Az eskető pap vagy diákonus az Egyház nevében veszi ki a beleegyezést a jegyesektől és adja az Egyház áldását. Az Egyház hivatalos szolgájának jelenléte és a tanúk azt teszik láthatóvá, hogy a házasság egyházi életforma. <br><br>
Ezért rendes körülmények között az Egyház egyházi formát követel híveitől a házasságkötéshez. E rendelkezésnek több indoka van: <br><br>
<ul>
    <li >a szentségi házasság liturgikus cselekmény, illő tehát, hogy az Egyház nyilvános liturgiájának keretében történjen; </li>
    <li >a házasságkötés egyházi életállapotba vezet be, jogokat és kötelességeket teremt az Egyházban a házastársak között és a gyermekek felé; </li>
    <li >mivel a házasság az Egyházban életállapot, a házasság megkötése felől bizonyossággal kell rendelkezni (ezért kötelező a tanúk jelenléte); </li>
    <li >a beleegyezés nyilvános jellege védi az egyszer kimondott "igen"-t és segíti hűséges megtartását. </li>
</ul>
Hogy a házastársak beleegyezése szabad és felelős cselekedet legyen, és hogy a házasságkötésnek meglegyenek erős és tartós emberi és keresztény alapjai, rendkívül fontos a fölkészülés a házasságra. <br><br>

<strong>A szülők és családok példája és nevelése a legjobb előkészítés. </strong><br><br>
A lelkipásztorok és a keresztény közösség mint "Isten családja" a házasság és a család emberi és keresztény értékeinek továbbadásában pótolhatatlan szerepet játszik, annál is inkább, mert korunkban számos fiatal megéli a családok szétesését, melyek e feladatuknak már nem tudnak megfelelni. <br><br>
"A fiatalokat alkalmas módon és idejekorán, elsősorban éppen a családon belül, föl kell világosítani a házastársi szerelem méltóságáról, feladatáról és megéléséről, hogy a tisztaság szeretetében nevelkedve megfelelő életkorban és erényes jegyesség után köthessenek házasságot." <br><br>

<strong>VEGYES HÁZASSÁG ÉS VALLÁSKÜLÖNBSÉG </strong><br><br>
Több régióban a vegyes házasság (katolikusok és megkeresztelt nem katolikus fél között) elég gyakran előfordul. Különös figyelmet igényel mind a házastársak, mind a lelkipásztorok részéről; a valláskülönbséggel kötött házasság (katolikus és meg nem keresztelt fél között) esetén még nagyobb körültekintésre van szükség. <br><br>
A hitvallásbeli különbség a házastársak között nem jelent leküzdhetetlen házassági akadályt, ha képesek a közösségbe behozni azt, amit mindegyikük a maga közösségében kapott, és képesek kölcsönösen megtanulni egymástól, hogy miként élnek Krisztus iránti hűségben. De nem szabad figyelmen kívül hagyni a vegyes házasságok nehézségeit. Ezek abból erednek, hogy a keresztények elkülönülése még fennáll. A házastársakat az a veszély fenyegeti, hogy saját házukban tapasztalják meg tragikus módon a keresztények elkülönülését. A valláskülönbség e nehézségeket még súlyosbíthatja. A hitbeli különbségek és magáról a házasságról vallott különböző fölfogások, sőt a különböző vallási lelkületek is, feszültségek forrásává válhatnak a házasságban, főként a gyermekek nevelésében. És így megjelenhet a kísértés: a vallási közömbösség. <br><br>
A latin Egyházban érvényes jog szerint a vegyes házasság megengedettségéhez egyházi hatóság kifejezett engedélyére van szükség. Valláskülönbség esetében a házasság érvényességéhez ezen akadály alóli kifejezett fölmentés szükséges. Ez az engedély vagy fölmentés feltételezi, hogy mindkét fél ismeri és nem zárja ki a házasság lényeges céljait és sajátosságait; ezen felül a katolikus fél vállalja a kötelezettséget -- amit a nem katolikus fél is tudomásul vesz --, hogy megőrzi hitét és gondoskodik a gyermekek keresztségéről és neveléséről a katolikus Egyházban. <br><br>
Az ökumenikus párbeszédnek köszönhetően számos vidéken az érintett keresztény közösségek meg tudták szervezni a vegyes házasságok közös lelkipásztori gondozását. Ennek feladata támogatni a házastársakat, hogy sajátos állapotukban a hit világosságában éljenek. E lelkipásztori gondozás segítse a feleket a feszültségek feloldásában, melyek az egymás és az egyházi közösségek iránti kötelességek között fölléphetnek. Támogatnia kell annak kibontakozását, ami a házastársak hitében közös, és a tiszteletet az iránt, ami szétválasztja őket. <br><br>
A valláskülönbség esetén a katolikus félre különleges feladat hárul, "mert a hitetlen férj megszentelődik az asszonyban, és a hitetlen asszony megszentelődik a testvérben" (1Kor 7,14). A keresztény házasfél és az Egyház számára nagy öröm, ha e "megszentelődés" elvezet a másik fél szabad keresztény hitre téréséhez. Az őszinte házastársi szeretet, a családi erények alázatos és türelmes gyakorlása és a kitartó imádság a nem keresztény felet előkészíthetik a megtérés kegyelmének elfogadására. <br><br>

<strong>A házasság szentségének hatásai </strong><br><br>
"Érvényes házasságból a házastársak között természeténél fogva örökös és kizárólagos kötelék származik, ezenfelül a keresztény házasságban a felek az állapotukkal járó feladatokhoz és méltósághoz külön szentségben kapnak erőt, és mintegy fölszenteltetnek." <br><br>

<strong>A HÁZASSÁGI KÖTELÉK </strong><br><br>
A beleegyezést, mely által a házastársak ajándékozzák és elfogadják egymást, maga Isten pecsételi meg. E szövetségből "Isten rendeléséből szilárd intézmény keletkezik a társadalom színe előtt is". A házastársak közötti szövetség beépül az Isten és az emberek közötti szövetségbe: "Az igazi házastársi szerelem fölvétetik az isteni szeretetbe". <br><br>
A házasság kötelékét tehát maga Isten köti össze, így a megkeresztelt felek között megkötött és bevégzett házasság soha nem bontható föl. E kötelék, mely a házastársak szabad emberi cselekedetéből és a házasság elhálásából származik, visszavonhatatlan valóság és olyan szövetség, amelyért Isten hűsége kezeskedik. Az Egyháznak nem áll hatalmában az isteni bölcsesség e rendelkezése ellen állást foglalni. <br><br>

<strong>A HÁZASSÁG SZENTSÉGÉNEK KEGYELME </strong><br><br>
"A keresztény házastársaknak életük állapotában és rendjében saját ajándékuk van Isten népén belül". A házasság szentségének e sajátos kegyelme arra van rendelve, hogy tökéletesítse szeretetüket és erősítse fölbonthatatlan egységüket. E kegyelemmel "az életszentségre segítik egymást a házaséletben, valamint a gyermekek elfogadásában és nevelésében". <br><br>
E kegyelem forrása Krisztus. "Miként ugyanis egykor a szeretet és a hűség szövetségével Isten a népe elé sietett, úgy most az emberek Üdvözítője és az Egyház Vőlegénye a házasság szentsége által elébe jön a keresztény hitvestársaknak." Velük marad és erőt ad nekik, hogy fölvegyék keresztjüket és így kövessék Őt, bukásaik után fölkeljenek, bocsássanak meg egymásnak, "egymás terhét hordozzák", legyenek "egymásnak alárendelve Krisztus iránti tiszteletből" (Ef 5,21), valamint kölcsönösen szeressék egymást természetfölötti, gyengéd és termékeny szeretettel. Szeretetük és családi életük örömeiben már a Bárány menyegzős lakomájának előízét kapják: <br><br>
"Hogyan vázolhatnám annak a házasságnak a boldogságát, melyet az Egyház egyesít, az áldozat erősít, az áldás megpecsétel, angyalok hirdetnek és az Atya érvényesnek tekint? (...) Micsoda iga: két hívő egy reménnyel, egy vággyal, egy életformával, egy szolgálatban! Mindketten testvérek, mindketten szolgatársak; semmi különbség sem testben, sem lélekben, valóban ketten egy testben vannak. Ahol egy a test, ott egy a lélek is." <br><br>

<strong>A házastársi szeretet értékei és követelményei </strong><br><br>
"A házastársi szeretet olyan egyetemességet hoz magával, amelyben a személy minden alkotóeleme helyet kap -- a test és az ösztön igényei, az érzékek és az érzelmek erői, a lélek és az akarat vágyai --, s e szeretet arra a legszemélyesebb egyesülésre irányul, amely a testi egyesülésen túl nem mást, mint egy szívet és egy lelket hoz létre. Igényli azonban e végső, kölcsönös odaadás fölbonthatatlanságát és hűségét, valamint a termékenységre való nyitottságot. Egyszóval minden természetes házastársi szeretet közös tulajdonságairól beszélünk, de olyan új tartalommal, amely e szerelmet nemcsak megtisztítja és megerősíti, hanem olyan magasságba emeli, ahol sajátosan keresztény értékek megnyilvánulása lesz." <br><br>

<strong>A HÁZASSÁG EGYSÉGE ÉS FÖLBONTHATATLANSÁGA </strong><br><br>
A házastársak szeretete természeténél fogva megköveteli egész életüket átfogó személyes közösségük egységét és fölbonthatatlanságát: "Már többé nem két test, hanem csak egy" (Mt 19,6). "Arra hivatottak, hogy állandóan növekedjenek közösségükben a házassági ígéret iránti mindennapos hűség, valamint a teljes és kölcsönös önátadás által." Ez az emberi közösség megerősödik, megtisztul és tökéletesedik a Jézus Krisztussal való közösségben, amit a házasság szentsége ajándékoz. A közös hitélet és az Eucharisztia közös vétele által elmélyül. <br><br>
"Mind a férfi, mind a nő kölcsönös és teljes szeretetben elismerendő egyenlő személyi méltósága is nyilvánvalóvá teszi a házasságnak az Úrtól megerősített egységét." A poligámia ellentétes ezzel az egyenlő méltósággal és a házastársi szeretettel, mely egyetlen és kizárólagos. <br><br>

<strong>A HÁZASTÁRSI SZERETET HŰSÉGE </strong><br><br>
A házastársi szeretet természeténél fogva a házastársak sérthetetlen hűségét követeli. Ez következik abból a kölcsönös odaadásból, melyben kölcsönösen egymásnak adják magukat. A szeretet végleges akar lenni. Nem lehet "egy új döntésig tartó". "Ez a bensőséges egység mint két személy kölcsönös ajándékozása és a gyermekek java megkívánja a házastársak teljes hűségét, és sürgeti fölbonthatatlan egységüket." <br><br>
E hűség legmélyebb alapja Istennek a szövetségéhez és Krisztusnak az Ő Egyházához való hűségében rejlik. A házasság szentsége által válnak a házastársak képessé arra, hogy e hűséget megjelenítsék és bizonyítsák. A szentség által a házasság fölbonthatatlansága új és mélyebb értelmet nyer. <br><br>
Nehéznek, sőt lehetetlennek tűnhet egész életen át egy emberi személyhez kötődni. Ugyanakkor nagyon fontos hirdetni az örömhírt: Isten végleges és visszavonhatatlan szeretettel szeret bennünket, és a házastársak ebből a szeretetből részesülnek, ez a szeretet hordozza és támogatja őket, és lehetővé teszi, hogy hűségükkel Isten hűséges szeretetének tanúi legyenek. A házastársak, akik Isten kegyelmével teszik ezt a tanúságot gyakran igen nehéz körülmények között, megérdemlik az egyházi közösség hálás elismerését és támogatását. <br><br>
Vannak olyan helyzetek, amikor a házassági együttélés nagyon különböző okok miatt gyakorlatilag lehetetlenné válik. Ilyen esetekben az Egyház megengedi a házastársak fizikai különválását (ágytól, asztaltól való elválás), azt, hogy többé ne éljenek együtt. A külön élő házastársak házassága azonban Isten előtt továbbra is érvényes marad; nem szabadok új házasság megkötésére. Az ilyen nehéz helyzetben a legjobb megoldás, ha lehetséges, a kibékülés. A keresztény közösségnek segítenie kell ezeket az embereket, hogy ebben a helyzetben is keresztények maradjanak, hűségesek a fölbonthatatlan házassági kötelékhez. <br><br>
Napjainkban számos országban sok katolikus él, akik miután a polgári törvények szerint váláshoz folyamodnak, új polgári házasságot kötnek. Az Egyház Jézus Krisztus szava ("Aki elbocsátja feleségét és mást vesz el, házasságtörést követ el ellene. Ha pedig a feleség hagyja el férjét és máshoz megy, házasságot tör." [Mk 10,11--12]) iránti hűsége miatt vallja, hogy nem ismerheti el ezt az új együttélést érvényesnek, ha az első házasság érvényes volt. Amennyiben elvált házasok polgárilag újraházasodtak, olyan helyzetbe kerültek, mely objektív módon áthágja Isten törvényét. Éppen ezért amíg e helyzet fönnáll, nem áldozhatnak. Ugyanezen oknál fogva bizonyos egyházi feladatokat sem vállalhatnak. A szentgyónásban történő kiengesztelődés csak azokat illeti, akik bánják, hogy a Krisztushoz való hűség és szövetség jelét megtörték, és kötelezik magukat, hogy teljes önmegtartóztatásban élnek. <br><br>
Az ilyen helyzetben élő keresztények iránt -- akik gyakran őrzik a hitet és keresztény módon szeretnék nevelni gyermekeiket -- a papoknak és az egész közösségnek figyelmesnek kell lenniük, hogy ne érezzék magukat kizárva az Egyházból, melynek életében mint megkereszteltek részt vehetnek és részt is kell venniük. <br><br>
"Buzdítsák őket arra, hogy hallgassák Isten igéjét, vegyenek részt a szentmisén, imádkozzanak állhatatosan, gyakorolják a szeretet cselekedeteit, működjenek együtt az igazságosság megvalósításáért, a gyermekeket keresztény hitben neveljék, éljen bennük a bűnbánat lelkülete, és rendszeresen tartsanak bűnbánatot, hogy így napról napra kiesdjék Isten kegyelmét." <br><br>

<strong>A TERMÉKENYSÉGRE NYITOTT LELKÜLET </strong><br><br>
"A házasság intézménye és a házastársi szerelem természetszerűleg a gyermek nemzésére és nevelésére irányul, és ebben teljesedik be": <br><br>
"A gyermek a házasság legnagyobb ajándéka, és a szülők számára a legnagyobb kincs. Isten, aki így szólt: ’Nem jó az embernek egyedül lennie’ (Ter 2,18), és aki ‘kezdettől férfinak és nőnek teremtette az embert’ (Mt 19,4), különleges részt akarva adni neki a saját teremtő tevékenységéből, megáldotta a férfit és a nőt: ‘Legyetek termékenyek, szaporodjatok’ (Ter 1,28). Következésképpen a házastársi szerelem helyes gyakorlása és a belőle fakadó egész családi élet -- a házasság egyéb céljainak háttérbe szorítása nélkül -- arra irányul, hogy a házastársak bátran legyenek készek együttműködni a Teremtő és a Megváltó szeretetével, aki általuk gyarapítja és gazdagítja a családját." <br><br>
A házastársi szeretet termékenysége kiterjed az erkölcsi, lelki és természetfölötti élet gyümölcseire, melyeket a szülők nevelés útján adnak át gyermekeiknek. A szülők gyermekeik első és legfontosabb nevelői. Ebben az értelemben a házasság és a család alapvető feladata az élet szolgálata. <br><br>
Azok a házastársak, akiket Isten nem ajándékozott meg gyermekáldással, emberi és keresztény értelemben teljes házastársi életet élhetnek. Házasságuk a szeretet, az elfogadás és az áldozatosság termékenységétől válhat ragyogóvá. <br><br>

<strong>A családegyház </strong><br><br>
Krisztus József és Mária szent családjának ölén akart e világra jönni és felnövekedni. Az Egyház nem más, mint "Isten családja". Kezdettől fogva az Egyház magvát gyakran azok alkották, akik "házuk népével" együtt lettek hívőkké. Amikor megtértek, azt akarták, hogy "egész házuk" is elnyerje az üdvösséget. Ezek a hívővé vált családok voltak a keresztény élet szigetei egy hitetlen világban. <br><br>
Ma egy olyan világban, mely gyakran távol áll a hittől, sőt ellenséges vele szemben, a hívő családok mint a hit élő és sugárzó tűzhelyei rendkívül fontosak. Ezért nevezi a II. Vatikáni Zsinat a családot ősi kifejezéssel: Ecclesia domestica, `családi egyháznak'. A család ölén "a szülők legyenek gyermekeik első hithirdetői szavukkal és példájukkal, és ápolják mindegyikük sajátos hivatását, s különös gonddal a szent hivatásokat". <br><br>
A családban kiemelekdő módon gyakorolják a családapa, a családanya, a gyermekek és valamennyi családtag keresztségi papságát "a szentségek vételében, az imádságban, a hálaadásban, a szent élet tanúságtételében, az önmegtagadásban és a tevékeny szeretetben". A családi otthon tehát a keresztény élet első iskolája és "az érlelődő emberiesség iskolája". Itt tanulja meg az ember a kitartó munkát, ismeri meg a munka örömét, a testvéri szeretetet, a nagylelkű, ismételt megbocsátást, és mindenekelőtt Isten szolgálatát az imádságban és az élet elajándékozásában. <br><br>
Gondolnunk kell még azokra az emberekre is, akik konkrét körülményeik miatt -- melyekben kénytelenek élni, gyakran akaratuk ellenére -- különösen közel állnak Jézus szívéhez, és ezért megérdemlik az Egyház megbecsülését és gondoskodását, különösen a lelkipásztorok részéről: a nem házasságban élő emberek sokaságára. Sokan közülük emberi család nélkül maradnak, gyakran szegénységük miatt. Vannak, akik ezt az élethelyzetet az evangéliumi boldogságok szellemében, Istent és a felebarátot példás módon szolgálva élik meg. Mindannyian találjanak nyitott ajtóra a "családegyházaknál" és annál a nagy családnál, ami az Egyház. "Senki nincs család nélkül ezen a világon: az Egyház mindannyiunk otthona és családja, különösen azoké, akik ‘fáradoznak és az élet terheit hordozzák’ (Mt 11,28)." <br><br>