<h2>Keresztség</h2>

A szent keresztség az egész keresztény élet alapja, a lelki élet ajtaja (vitae spiritualis ianua) és kapu a többi szentségekhez. A keresztség által megszabadulunk a bűntől, és mint Isten fiai születtünk újjá, Krisztus tagjai leszünk, betestesülünk az Egyházba és részeseivé váltunk az Egyház küldetésének.<br><br>

<strong>KRISZTUS KERESZTSÉGE </strong><br><br>
Az Ószövetség minden előképe Jézus Krisztusban beteljesedett. Ő a nyilvános életét az után kezdte meg, hogy Keresztelő Szent Jánossal megkereszteltette magát a Jordánban, és föltámadása után ezt a küldetést adta az Apostoloknak: "Elmenvén tehát, tanítsatok minden nemzetet megkeresztelvén őket az Atya és a Fiú és a Szentlélek nevében, és tanítván őket megtartani mindazt, amit parancsoltam nektek" (Mt 28,19-20).<br><br>
A mi Urunk önként vetette alá magát János keresztségének, ami a bűnösöknek volt szánva, hogy beteljesítse a teljes igazságot. Jézusnak ez a gesztusa "kiüresítésének" megnyilvánulása. A Lélek, aki az első teremtés vizei fölött lebegett, ekkor az új teremtésre utalva leszáll Krisztusra, és az Atya Jézust "szeretett Fiának" nyilvánítja.<br><br>
Krisztus a maga húsvétjában minden ember számára megnyitotta a keresztség forrásait. Valójában már korábban úgy beszélt szenvedéséről, melyet Jeruzsálemben kellett elszenvednie, mint "keresztségről", mellyel meg kell keresztelkednie. A vér és a víz, ami a megfeszített Jézus megnyitott oldalából folyt ki, a keresztség és az Eucharisztia, az új élet szentségeinek előképei: ettől kezdve lehetséges "vízből és Szentlélekből" születni az Isten országába való bemenetelre (Jn 3,5).<br><br>


<strong>A KERESZTSÉG AZ EGYHÁZBAN </strong><br><br>
Az Egyház Pünkösd napjától kezdve ünnepelte és kiszolgáltatta a szent keresztséget. Szent Péter így beszélt a sokasághoz, melyet prédikációja a szíve mélyén érintett meg: "Tartsatok bűnbánatot és keresztelkedjék meg mindegyiktek Jézus Krisztus nevében bűneitek bocsánatára, és megkapjátok a Szentlélek ajándékát" (ApCsel 2,38). Az Apostol és munkatársai a keresztséget mindazoknak fölajánlják, akik hisznek Jézusban: zsidóknak, istenfélőknek, pogányoknak.<br><br>
A keresztség mindig a hithez kötötten jelenik meg: "Higgy az Úr Jézusban, és üdvözülsz te és a házad népe!" -- mondja Szent Pál börtönőrének Filippiben. Az elbeszélés így folytatódik: "azonnal megkeresztelkedett hozzátartozóival együtt" (ApCsel 16,31--33).<br><br>
Szent Pál apostol szerint a hívő ember a keresztség révén közösségre lép Krisztus halálával; vele együtt eltemetik és vele együtt föltámad:<br><br>
"Vagy nem tudjátok, hogy akik Krisztus Jézusban megkeresztelkedtünk, az ő halálában keresztelkedtünk meg? A keresztségben ugyanis eltemetkeztünk vele együtt a halálba, hogy miként Krisztus az Atya dicsőségéből föltámadt a halálból, úgy mi is új életre keljünk" (Róm 6,3-4).<br><br>


<strong>A KERESZTÉNY BEAVATÁS </strong><br><br>
Az Apostolok korától kezdve kereszténnyé egy fokozatos út és beavatás által váltak az emberek. Ezt az utat gyorsabban vagy lassan lehet végigjárni. Néhány lényeges elemet azonban mindig magában foglal: az igehirdetést, az Evangélium megtérésre vonzó elfogadását, a hitvallást, a keresztséget, a Szentlélek kiáradását és az eucharisztikus közösséghez járulást.<br><br>
Ez a beavatás a századok folyamán a körülményeknek megfelelően sokat változott. Az Egyház első századaiban a keresztény beavatás hosszadalmassá vált, hosszú katekumenátusi idő és az előkészület útját liturgikusan jelző előkészítő szertartások vezettek végül a keresztény beavatás szentségeinek ünnepléséhez.<br><br>
Amikor a gyermekkeresztség lett a keresztség szentségének általános formája, az ünnep egyetlen cselekménnyé vált, mely a keresztény beavatást megelőző fokozatokat nagyon lerövidítve foglalja magában. Természetének megfelelően a gyermekkeresztség keresztség utáni katekumenátust igényel. Nem csupán a keresztséget követő oktatás szükségességéről van szó, hanem a keresztség kegyelmének kibontakoztatásáról a személy fejlődésében. Itt van a hitoktatás sajátos helye.<br><br>
A II. Vatikáni Zsinat a latin Egyház számára visszaállította a "felnőttek többlépcsős katekumenátusát", melynek szertartása az Ordo initiationis christianae adultorum (1972) c. kiadványban található. A zsinat egyébként megengedte, hogy "a missziós területeken az egyes népeknél szokásos beavatási szertartások közül a keresztény hagyomány mellé azokat is bevegyék, amelyek összeegyeztethetők a keresztény szertartással".<br><br>
Manapság minden latin és keleti szertartásban a felnőttek keresztény beavatása a katekumenátusba való belépésükkel kezdődik, és csúcspontját a keresztség, a bérmálás és az Eucharisztia három szentségének egyszerre történő ünneplésében éri el. A keleti szertartásokban a gyermekek keresztény beavatása a keresztséggel kezdődik, és azonnal követi a bérmálás és az elsőáldozás. Ezzel szemben a római szertartásban a keresztség után évekig tartó hitoktatást követően kapják a bérmálást és az Eucharisztiát, mely keresztény beavatásuk csúcspontja.<br><br>

<strong>A KERESZTSÉG KISZOLGÁLTATÁSA </strong><br><br>
A kereszt jele a szertartás kezdetén Krisztus pecsétjét jelzi azon, aki hamarosan hozzá fog tartozni, és a megváltás kegyelmét jelzi, melyet Krisztus a keresztje által szerzett nekünk.<br><br>
Isten Igéjének hirdetése a jelölteknek és az összegyűlteknek megvilágítja a kinyilatkoztatott igazságot, és fölkelti a hit válaszát, ami nem választható el a keresztségtől. A keresztség egész különleges módon "a hit szentsége", mert szentségi ajtó a hit életébe.<br><br>
Mivel a keresztség szabadulást jelent a bűntől és bujtogatójától, az ördögtől, a jelölt fölött egy (vagy több) ördögűzést végeznek. Megkenik a keresztelendők olajával, vagy a keresztelő ráteszi a kezét, ő maga pedig kifejezetten ellene mond a Sátánnak. Így fölkészülve megvallhatja az Egyház hitét, melyre a keresztség által "rábízzák".<br><br>
A keresztvizet egy lélekhívó imádsággal (epiklézissel) a keresztelés szertartásában vagy húsvét vigíliáján szentelik meg. Az Egyház kéri Istentől, hogy Fia által a Szentlélek ereje szálljon le erre a vízre, hogy akik benne megkeresztelkednek, "vízből és Lélekből" szülessenek meg (Jn 3,5).<br><br>
Ezután következik a szentség lényegi szertartása: a tulajdonképpeni keresztelés, mely a Krisztus húsvéti misztériumához való hasonulással jelzi és létrehozza a bűnnek való meghalást és a Szentháromság életébe való bemenetelt. A keresztelés legkifejezőbb formája a keresztvízbe történő háromszoros alámerítés. De már az őskeresztény kortól kiszolgáltatható a keresztség a keresztelendő fejének háromszori, vízzel történő leöntésével.<br><br>
A latin Egyházban e háromszoros leöntést a keresztelő e szavai kísérik: "X., én megkeresztellek téged az Atya, és a Fiú, és a Szentlélek nevében."<br><br>
A megkenés a szent krizmával, a püspök által megszentelt jó illatú olajjal az újonnan megkeresztelt számára a Szentlélek ajándékát jelenti. Kereszténnyé, azaz a Szentlélektől "fölkentté" vált, tagja lett Krisztusnak, aki fölkent Pap, Próféta és Király.<br><br>
A keleti egyházak liturgiájában a keresztség utáni megkenés a krizmáció (bérmálás) szentsége. A római liturgiában előre jelzi azt a szent krizmával való fölkenést, melyet majd a püspök fog kiszolgáltatni: a bérmálás szentségét, mely a keresztségi fölkenést mintegy "megerősíti" és tökéletesíti.<br><br>
A fehér ruha szimbolikusan jelzi, hogy a megkeresztelt Krisztust öltötte magára, Krisztussal együtt föltámadott. A húsvéti gyertyáról meggyújtott keresztelési gyertya azt jelenti, hogy Krisztus megvilágosította a megkereszteltet. Krisztusban a megkereszteltek "a világ világossága" (Mt 5,14). Az újonnan megkeresztelt az egyszülött Fiúban most már Isten gyermeke.<br><br>
Elmondhatja Isten gyermekeinek imádságát: a Miatyánkot.<br><br>

Az első áldozás. Az új keresztényt, miután Isten gyermeke lett és menyegzői ruhába öltözött, bebocsátják a "Bárány menyegzői lakomájára", és megkapja az új élet eledelét, Krisztus testét és vérét. A keleti egyházak elevenen őrzik a keresztény beavatás egységét azáltal, hogy a szentáldozást minden újonnan megkereszteltnek és megbérmáltnak, még a csecsemőknek is kiszolgáltatják, emlékezvén az Úr szavára: "Engedjétek hozzám jönni a kisdedeket, ne akadályozzátok őket!" (Mk 10,14). A latin Egyház a szentáldozáshoz járulást azoknak tartja fönn, akik elérik az értelem használatának korát, de a keresztség Eucharisztiára nyitottságát azzal fejezi ki, hogy az újonnan megkeresztelt csecsemőt a Miatyánk elimádkozására az oltárhoz viszi.<br><br>
A keresztelés szertartását ünnepélyes áldás zárja be. Újszülött keresztelésekor az anya megáldásának különleges jelentősége van.<br><br>


<strong>Ki veheti föl a keresztséget? </strong><br><br>
"A keresztség fölvételére alkalmasak mindazok, de csak azok, akik még nincsenek megkeresztelve."<br><br>

<strong>A FELNŐTTEK KERESZTSÉGE </strong><br><br>
A felnőttkeresztség az Egyház kezdetei óta ott a leggyakoribb, ahol az evangélium hirdetése újkeletű. Ilyenkor nagyon fontos szerepe van a katekumenátusnak (a keresztségre való előkészületnek), melynek mint a hitbe és a keresztény életbe való bevezetésnek elő kell készítenie az embert Isten ajándékának fogadására a keresztségben, a bérmálásban és az Eucharisztiában.<br><br>
A katekumenátus azaz a katekumenok képzésének célja az, hogy lehetővé tegye számukra, hogy válaszolva az isteni kezdeményezésre, és valamilyen egyházi közösséggel egységben megérleljék megtérésüket és hitüket. Az "egész keresztény életet" átfogó oktatásról van tehát szó, "mellyel a tanítványok kapcsolatba kerülnek Krisztussal, a Mesterükkel. A katekumenokat tehát megfelelő módon be kell vezetni az üdvösség misztériumába; és az evangéliumi erkölcsök gyakorlásával és meghatározott időközökben egymást követő szertartásokkal vezessék be őket Isten népe hívő, liturgikus életébe és szeretetgyakorlataiba."<br><br>
A katekumenok "már kapcsolatban állnak az Egyházzal, már Krisztus házanépe, s nemritkán már a hit, a remény és a szeretet életét élik".<br><br>
<strong>A GYERMEKEK KERESZTSÉGE </strong><br><br>
Mivel bukott természettel és az áteredő bűntől megszeplősítve születtek, a kisgyermekek is rászorulnak az új születésre a keresztségben, hogy kiszabaduljanak a sötétség hatalmából és átvitessenek Isten gyermekei szabadságának országába, ahová minden ember meghívást kap. A gyermekkeresztségben különösen is világosan látható az üdvösség kegyelmének teljes ingyenessége. Az Egyház és a szülők megtagadnák a gyermektől az Isten gyermekévé válás fölbecsülhetetlen kegyelmét, ha nem hamarosan a születés után gondoskodnának a keresztelésről.<br><br>
A keresztény szülők ismerjék el, hogy ez a szokás megfelel feladatuknak, hogy az Isten által rájuk bízott életet támogassák.<br><br>
Az Egyház ősi hagyománya, hogy kisgyermekeket keresztel. A 2. századtól erre kifejezett bizonyítékok vannak, de valószínű, hogy már az apostoli igehirdetés kezdetén, amikor egész "házak" megkeresztelkedtek, a gyermekeket is megkeresztelték.<br><br>
<strong>HIT ÉS KERESZTSÉG </strong><br><br>
A keresztség a hit szentsége. A hitnek szüksége van a hívők közösségére. Minden hívő csak az Egyház hitében tud hinni. A hitnek azonban, ami a keresztséghez szükséges, nem kell tökéletesnek és érettnek lennie; elég a csíra, amelynek ki kell bontakoznia. A keresztelendőtől vagy a keresztszülőjétől megkérdezik: "Mit kérsz Isten Egyházától?" És ő felel: "A hitet!"<br><br>
A hitnek minden megkereszteltben, akár gyermek, akár felnőtt, a keresztség után növekednie kell. Ezért az Egyház minden évben a húsvéti vigíliában megújítja a keresztségi fogadalmakat. A keresztségi előkészület ugyanis csak az új élet küszöbéhez vezet el. A keresztség a Krisztusban való új élet forrása, melyből az egész keresztény élet fakad.<br><br>
Ahhoz, hogy a keresztségi kegyelem kibontakozhassék, nagyon fontos a szülők segítsége. Ebben szerepe van a keresztapáknak és keresztanyáknak, akiknek jó hívőknek kell lenniük, alkalmasnak és fölkészültnek arra, hogy az újonnan megkeresztelt kisgyermeket vagy felnőttet kísérjék a keresztény élet útján. Feladatuk igazi egyházi szolgálat, officium. A keresztségi kegyelem megőrzéséért és kibontakozásáért az egész egyházi közösség is felelős.<br><br>


<strong>Ki keresztelhet? </strong><br><br>
A keresztség rendes kiszolgáltatója a püspök és a pap, valamint a latin Egyházban a diákonus is. "Szükség esetén bárki, még a meg nem keresztelt ember is keresztelhet a szentháromságos keresztelési formulát alkalmazva." A megkívánt szándék azonban az, hogy azt akarja tenni, amit az Egyház a kereszteléskor tesz. E lehetőség alapját az Egyház Isten mindenkire vonatkozó üdvözítő akaratában és abban látja, hogy a keresztség feltétlenül szükséges az üdvösséghez.<br><br>

<strong>A keresztség szükségessége </strong><br><br>
Maga az Úr mondja, hogy a keresztség szükséges az üdvösséghez. Ezért adta tanítványainak a feladatot, hogy hirdessék az evangéliumot és kereszteljenek meg minden népet. A keresztség szükséges az üdvösséghez azoknak az embereknek, akiknek hirdették az evangéliumot és lehetőségük van arra, hogy kérjék a szentséget. Az Egyház a keresztségen kívül nem ismer más olyan eszközt, amellyel biztosítani lehet az örök boldogságra eljutást; ezért tiltja, hogy elhanyagolják a küldetést, melyet az Úrtól kapott arra, hogy akik csak megkeresztelhetők, azokat hozzásegítse a "vízből és Lélekből való újjászületésre". Isten az üdvösséget a keresztség szentségéhez kötötte, de Ő maga nincs a szentségeihez kötve.<br><br>
Az Egyház a kezdettől fogva szilárdan meg van győződve arról, hogy azok az emberek, akik a hitért halnak meg anélkül, hogy meg lennének keresztelve, a Krisztusért és a Krisztussal elszenvedett halálukkal megkeresztelkednek. E vérkeresztség, miként a vágykeresztség is, meghozza a keresztség gyümölcseit, anélkül hogy szentség lenne.<br><br>
A katekumenoknak, akik a keresztség előtt halnak meg, a keresztség kifejezett vágya, a bűneik fölötti bánat és a szeretet biztosítja azt az üdvösséget, amit nem tudtak a szentség által fogadni.<br><br>
"Mivel ugyanis Krisztus mindenkiért meghalt, s minden ember végső hivatása azonos, tudniillik isteni hivatás, vallanunk kell, hogy a Szentlélek mindenkinek fölkínálja a lehetőséget, hogy -- csak Isten előtt ismert módon -- csatlakozzon e húsvéti misztériumhoz." Minden ember, aki Krisztus evangéliumának és az ő Egyházának ismerete nélkül keresi az igazságot és teszi Isten akaratát úgy, ahogyan azt ismeri, üdvözülhet. Föltételezhetjük, hogy az ilyen emberek kifejezetten kívánták volna a keresztséget, ha annak szükséges voltáról tudomást szereztek volna.<br><br>
Ami a keresztség nélkül meghalt gyermekeket illeti, az Egyház csak Isten irgalmasságára tudja őket bízni, amint ezt meg is teszi a megfelelő temetési szertartásban. A minden ember üdvösségét akaró Isten végtelen irgalmassága és Jézus gyöngédsége a gyermekek iránt, mely azt mondatta vele: "Engedjétek hozzám a kisdedeket, ne akadályozzátok őket" (Mk 10,14), följogosít bennünket a reményre, hogy a keresztség nélkül meghalt gyermekek számára is van út az üdvösségre. Az Egyház nyomatékosan kéri a szülőket, ne akadályozzák a gyermekeket abban, hogy a szent keresztség ajándéka által Krisztushoz jöjjenek.<br><br>

<strong>A keresztségi kegyelem </strong><br><br>
A keresztség különböző hatásait a szentségi szertartás látható elemei jelzik. A vízbe való alámerítés szimbolikusan utal a halálra és a tisztulásra, ugyanakkor a megújulásra és újjászületésre is. A két fő hatás tehát a bűnöktől való megtisztulás és a Szentlélekben való új születés.<br><br>

<strong>A BŰNÖK BOCSÁNATÁRA ... </strong><br><br>
A keresztség által az összes bűnök eltöröltetnek, az áteredő bűn és minden személyes bűn, illetve a bűnökért járó összes büntetések. Azokban, akik újjászülettek, nem marad semmi, ami akadályozhatná őket az Isten országába való belépésben; sem Ádám bűne, sem a személyes bűnök, sem a bűn következményei, melyek közül a legsúlyosabb az Istentől való elszakadás.<br><br>
A megkeresztelt emberben mégis megmaradnak a bűnnek ideigtartó bizonyos következményei, mint a szenvedés, a betegség, a halál, az élettel együttjáró gyöngeségek, például jellemhibák stb., valamint a bűnre való hajlandóság, amit a hagyomány concupiscentiának (`bűnös vágy') vagy képszerűen fomes peccatinak (`a bűn taplójának') nevez. Mivel a concupiscentia a harc érdekében maradt meg, azoknak, akik nem egyeznek bele és Jézus Krisztus kegyelmével férfiasan ellenállnak, nem tud ártani. „A versenyző is csak akkor nyeri el a babérkoszorút, ha szabályszerűen küzd” (2Tim 2,5)<br><br>

<strong>ÚJ TEREMTMÉNY </strong><br><br>
A keresztség nem csupán megtisztít minden bűntől, hanem az újonnan megkereszteltet "új teremtménnyé" teszi , Isten fogadott fiává; aki "az isteni természet részese", Krisztus tagja és "társörökös" Vele és a "Szentlélek temploma" lett.<br><br>
A legszentebb Szentháromság a megkereszteltnek a megszentelő kegyelmet, a megigazulás kegyelmét adja:<br><br>
<ul>
    <li>ami az isteni erények által képessé teszi arra, hogy Istenben higgyen, Benne reméljen és Őt szeresse; </li>
    <li>a Szentlélek ajándékai által lehetővé teszi számára, hogy a Szentlélek irányítása alatt éljen és cselekedjék; </li>
    <li>az erkölcsi erények által képessé teszi arra, hogy a jóban növekedjék. </li>
</ul>
Így a keresztény ember természetfölötti életének egész organizmusa a szent keresztségben gyökerezik.<br><br>

<strong>AZ EGYHÁZBA, KRISZTUS TESTÉBE ÉPÜLVE </strong><br><br>
A keresztség Krisztus testének tagjaivá tesz bennünket. "Emiatt (...) tagjai vagyunk egymásnak" (Ef 4,25). A keresztség beépít az Egyházba. A keresztkútból születik Isten egyedülálló újszövetségi népe, mely a nemzetek, kultúrák, népek és nemek természetes és emberi határait fölülmúlja: "Mi ugyanis mindnyájan egy Lélekben egy testté lettünk a keresztséggel" (1Kor 12,13).<br><br>
A megkereszteltek "élő kövekké" lesznek, hogy "lelki házzá" és "szent papsággá" épüljenek (1Pt 2,5). A keresztség által részesednek Krisztus papságában, prófétai és királyi küldetésében. "Választott nemzetség, királyi papság, szent nemzet, tulajdonul kiválasztott nép, hogy annak dicsőségét hirdessék, aki a sötétségből meghívta (őket) csodálatos világosságára" (1Pt 2,9). A keresztség részt ad a hívők általános papságában.<br><br>
A megkeresztelt ember, mivel az Egyház tagjává lett, már nem önmagáé, hanem ahhoz tartozik, aki érte meghalt és föltámadott. Arra kap meghívást, hogy az Egyház közösségében rendelje alá önmagát másoknak, nekik szolgáljon, s az Egyház elöljárói iránt "engedelmes és tanulékony" legyen, tisztelje és szeresse őket. Miként a keresztség felelősségek és kötelezettségek forrása, úgy a megkeresztelt embernek jogai is vannak az Egyházban: a szentségek vételéhez, az Isten igéjével való táplálkozáshoz és ahhoz, hogy az Egyház lelki segítséggel támogassa.<br><br>
A megkeresztelteknek, "miután Isten fiaivá újjászülettek, a hitet, melyet Istentől az Egyház által kaptak, az emberek előtt meg kell vallaniuk", és részt kell venniük Isten népének apostoli és missziós tevékenységében.<br><br>

<strong>A KERESZTÉNYEK EGYSÉGÉNEK SZENTSÉGI KÖTELÉKE </strong><br><br>
A keresztség a közösség alapja az összes keresztény között, azok tekintetében is, akik még nincsenek teljes közösségben a katolikus Egyházzal: "Akik hisznek Krisztusban és szabályszerűen részesültek a keresztség szentségében, már bizonyos -- jóllehet nem tökéletes -- közösségbe kerültek a katolikus Egyházzal. (...) Mindazonáltal akik a keresztségben megigazultak a hitből, Krisztus testének lettek tagjai, jogosan ékesíti tehát őket a keresztény név, s a katolikus Egyház gyermekei méltán ismerik el őket testvéreiknek az Úrban."<br><br>

<strong>ELTÖRÖLHETETLEN LELKI PECSÉT ... </strong><br><br>
A megkeresztelt ember, mivel a keresztség által Krisztus tagjává vált, hasonlóvá vált Krisztushoz. A keresztség a keresztényt eltörölhetetlen lelki pecséttel (characterrel) jelöli meg, ami annak jele, hogy Krisztushoz tartozik. E jelet semmiféle bűn ki nem törölheti, még akkor sem, ha a bűn megakadályozza, hogy a keresztség az üdvösség gyümölcseit teremje. Az egyszer s mindenkorra kiszolgáltatott keresztséget nem lehet megismételni.<br><br>
A keresztség révén az Egyházba beépült hívők szentségi karaktert kaptak, mely a keresztény vallásos kultuszra szenteli őket. A keresztségi pecsét a keresztényeket alkalmassá teszi és kötelezi egyrészt arra, hogy Istennek szolgáljanak az Egyház szent liturgiájában való eleven részvétellel, másrészt keresztségi papságuk gyakorlására a szent és a szeretetben tevékeny élet tanúságtételével.<br><br>
